package main; import __vidar "vidar_runtime"

import "core:fmt"

// Closure types look like proc types, but values carry captured state.
Counter :: struct {
	inc: __vidar.Closure(proc(__vidar.Env) -> int),
	get: __vidar.Closure(proc(__vidar.Env) -> int),
}

make_counter :: proc(start: int) -> Counter {
	// State that outlives this frame goes on the heap explicitly; both closures share the pointer.
	count := new_clone(start)
	return Counter{
		inc = __closure_0(count),
		get = __closure_1(count),
	}
}

make_adder :: proc(n: int) -> __vidar.Closure(proc(__vidar.Env, int) -> int) {
	return __closure_2(n)
}

compose :: proc(f, g: __vidar.Closure(proc(__vidar.Env, int) -> int)) -> __vidar.Closure(proc(__vidar.Env, int) -> int) {
	// a closure can't hold a copy of another one: keep them on the heap and capture the pointers
	fp, gp := new_clone(f), new_clone(g)
	return __closure_3(fp, gp)
}

apply :: proc(f: __vidar.Closure(proc(__vidar.Env, int) -> int), xs: []int) -> [dynamic]int { __f_call := f.call;
	out: [dynamic]int
	for x in xs do append(&out, __f_call(f.env, x))
	return out
}

Op :: __vidar.Closure(proc(__vidar.Env, int, int) -> (int, bool))

main :: proc() {
	// [x] captures by value: later changes to `step` are not seen.
	step := 5
	add_step := __closure_4(step)
	step = 100
	fmt.println("by value:", add_step.call(add_step.env, 1))

	// [&x] captures by reference: the closure sees and changes the variable.
	hits := 0
	hit := __closure_5(&hits)
	hit.call(hit.env); hit.call(hit.env); hit.call(hit.env)
	fmt.println("by reference:", hits)

	// Closures can outlive the frame that created them.
	c := make_counter(10)
	c.inc.call(c.inc.env)
	c.inc.call(c.inc.env)
	fmt.println("counter:", c.get.call(c.get.env))

	// proc[] has no captures, but is still a closure value.
	double := __vidar.Closure(proc(__vidar.Env, int) -> int){call = proc(__env_raw: __vidar.Env, x: int) -> int { return x * 2 }}
	fmt.println("compose:", __call_closure_0(compose(double, add_step), 3))
	fmt.println("curried:", __call_closure_0(make_adder(40), 2))
	fmt.println("apply:", apply(double, {1, 2, 3})[:])

	// Each loop iteration captures its own copy of `i`.
	adders: [dynamic]__vidar.Closure(proc(__vidar.Env, int) -> int)
	for i in 0..<3 do append(&adders, __closure_6(i))
	for f in adders do fmt.print(f.call(f.env, 1), "")
	fmt.println()

	// A closure type alias with multiple results.
	safe_div: Op = __vidar.Closure(proc(__vidar.Env, int, int) -> (int, bool)){call = proc(__env_raw: __vidar.Env, a, b: int) -> (int, bool) {
		if b == 0 do return 0, false
		return a / b, true
	}}
	q, ok := safe_div.call(safe_div.env, 7, 2)
	_, ok2 := safe_div.call(safe_div.env, 1, 0)
	fmt.println("safe_div:", q, ok, ok2)

	// Nested closures: the inner one re-captures what the outer captured.
	total := 0
	outer := __closure_8(&total)
	outer.call(outer.env, 3)
	outer.call(outer.env, 4)
	fmt.println("nested:", total)
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env) -> int) {
	__Caps :: struct {
		count: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:15: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env) -> int){
		call = proc(__env_raw: __vidar.Env) -> int { __env := transmute(__Env)__env_raw; __env.count^ += 1; return __env.count^ },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_1 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env) -> int) {
	__Caps :: struct {
		count: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:16: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env) -> int){
		call = proc(__env_raw: __vidar.Env) -> int { __env := transmute(__Env)__env_raw; return __env.count^ },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_2 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int) -> int) {
	__Caps :: struct {
		n: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:21: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int) -> int){
		call = proc(__env_raw: __vidar.Env, x: int) -> int { __env := transmute(__Env)__env_raw; return x + __env.n },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_3 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(__vidar.Env, int) -> int) {
	__Caps :: struct {
		fp: T0,
		gp: T1,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:27: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int) -> int){
		call = proc(__env_raw: __vidar.Env, x: int) -> int { __env := transmute(__Env)__env_raw; return __call_closure_0(__env.gp^, __call_closure_0(__env.fp^, x)) },
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1}},
	}
}

__closure_4 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int) -> int) {
	__Caps :: struct {
		step: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:41: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int) -> int){
		call = proc(__env_raw: __vidar.Env, x: int) -> int { __env := transmute(__Env)__env_raw; return x + __env.step },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_5 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		hits: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:47: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw; __env.hits^ += 1 },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_6 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int) -> int) {
	__Caps :: struct {
		i: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:65: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int) -> int){
		call = proc(__env_raw: __vidar.Env, x: int) -> int { __env := transmute(__Env)__env_raw; return x + __env.i * 10 },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_7 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		total: T0,
		n: T1,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:81: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw; __env.total^ += __env.n },
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1}},
	}
}

__closure_8 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int)) {
	__Caps :: struct {
		total: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:80: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int)){
		call = proc(__env_raw: __vidar.Env, n: int) { __env := transmute(__Env)__env_raw;
		bump := __closure_7(__env.total, n)
		bump.call(bump.env)
		bump.call(bump.env)
	},
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__call_closure_0 :: #force_inline proc(c: __vidar.Closure(proc(__vidar.Env, int) -> int), p0: int) -> int {
	return c.call(c.env, p0)
}
