package main; import __vidar "vidar_runtime"

import "core:fmt"
import "core:strings"

Color :: enum { Red, Green, Blue }

Inner :: struct { a: int, s: string }

Empty :: struct {}

Node :: struct {
	name: string,
	children: []Node,
}

Outer :: struct {
	name: string,
	r: rune,
	f: f64,
	g: f32,
	b: bool,
	c: Color,
	in_: Inner,
	arr: [3]int,
	sl: []string,
	dy: [dynamic]Inner,
	u: u8,
	i: i64,
	e: Empty,
	anon: struct { x, y: int },
	colors: [2]Color,
	none: [0]int,
}

// not generated: a pointer field; fmt prints it
Mapped :: struct { p: ^int, n: int }

main :: proc() {
	dy: [dynamic]Inner
	defer delete(dy)
	append(&dy, Inner{1, "q\"x\n"}, Inner{})
	// slices point at named arrays: a slice literal inside a struct literal doesn't outlive its statement
	names := [2]string{"a", "b"}
	o := Outer{name = "rock", r = 'a', f = 1.5, g = 0.1, b = true, c = .Green, in_ = {2, "z"}, arr = {1, 2, 3}, sl = names[:], dy = dy, u = 200, i = -5, anon = {3, 4}, colors = {.Blue, .Red}}
	deep := [1]Node{{"deep", nil}}
	kids := [2]Node{{"leaf", nil}, {"mid", deep[:]}}
	tree := Node{"root", kids[:]}
	colors := [2]Color{.Red, Color(9)}

	// every way a value reaches %v, compared with fmt's own output: fmt called through a proc value,
	// which -opt leaves alone
	tp := fmt.tprint
	tpf := fmt.tprintf
	check :: proc(got, want: string) { __fmt_0(got == want ? "same" : "DIFFERENT", got) }
	check(__fmt_1(o), tp(o))
	check(__fmt_1(o), tpf("%v", o))
	check(__fmt_2(o), tpf("%#v", o))
	check(__fmt_3(tree), tp(tree))
	check(__fmt_4(tree), tpf("%#v", tree))
	check(__fmt_5(Color.Blue, Color(7), colors[:]), tp(Color.Blue, Color(7), colors[:]))
	check(__fmt_6(dy[:], [2]Inner{}, Empty{}), tp(dy[:], [2]Inner{}, Empty{}))
	check(__fmt_7(dy, [0]Inner{}, Empty{}), tpf("%#v|%#v|%#v", dy, [0]Inner{}, Empty{}))
	check(__fmt_8(Mapped{n = 1}), tp(Mapped{n = 1}))

	// the byte counts fmt returns, and a builder sink
	n := __fmt_9(o)
	pl := fmt.println
	m := pl(o)
	__fmt_0(n == m, n)
	b := strings.builder_make()
	defer strings.builder_destroy(&b)
	__fmt_10(&b, tree)
	fmt.println(strings.to_string(b))
}

// ---- generated by vidar ----

// fmt.println
__fmt_0 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.tprint
__fmt_1 :: proc(a0: $T0) -> string {
	b := __vidar.builder(context.temp_allocator)
	when T0 == Outer { __print_main_Outer(__vidar.sb_writer(&b), a0) } else { __vidar.sb_spec(&b, a0, "%v") }
	return __vidar.sb_to_string(&b)
}

// fmt.tprintf "%#v"
__fmt_2 :: proc(a0: $T0) -> string {
	b := __vidar.builder(context.temp_allocator)
	when T0 == Outer { __printh_main_Outer(__vidar.sb_writer(&b), a0, 0) } else { __vidar.sb_spec(&b, a0, "%#v") }
	return __vidar.sb_to_string(&b)
}

// fmt.tprint
__fmt_3 :: proc(a0: $T0) -> string {
	b := __vidar.builder(context.temp_allocator)
	when T0 == Node { __print_main_Node(__vidar.sb_writer(&b), a0) } else { __vidar.sb_spec(&b, a0, "%v") }
	return __vidar.sb_to_string(&b)
}

// fmt.tprintf "%#v"
__fmt_4 :: proc(a0: $T0) -> string {
	b := __vidar.builder(context.temp_allocator)
	when T0 == Node { __printh_main_Node(__vidar.sb_writer(&b), a0, 0) } else { __vidar.sb_spec(&b, a0, "%#v") }
	return __vidar.sb_to_string(&b)
}

// fmt.tprint
__fmt_5 :: proc(a0: $T0, a1: $T1, a2: $T2) -> string {
	b := __vidar.builder(context.temp_allocator)
	__vidar.sb_v(&b, a0)
	__vidar.sb_str(&b, " ")
	when T1 == Color { __print_main_Color(__vidar.sb_writer(&b), a1) } else { __vidar.sb_spec(&b, a1, "%v") }
	__vidar.sb_str(&b, " ")
	when T2 == [2]Color { __print_arr2_main_Color(__vidar.sb_writer(&b), a2) } else { __vidar.sb_spec(&b, a2, "%v") }
	return __vidar.sb_to_string(&b)
}

// fmt.tprint
__fmt_6 :: proc(a0: $T0, a1: $T1, a2: $T2) -> string {
	b := __vidar.builder(context.temp_allocator)
	when T0 == [dynamic]Inner { __print_dyn_main_Inner(__vidar.sb_writer(&b), a0) } else { __vidar.sb_spec(&b, a0, "%v") }
	__vidar.sb_str(&b, " ")
	when T1 == [2]Inner { __print_arr2_main_Inner(__vidar.sb_writer(&b), a1) } else { __vidar.sb_spec(&b, a1, "%v") }
	__vidar.sb_str(&b, " ")
	when T2 == Empty { __print_main_Empty(__vidar.sb_writer(&b), a2) } else { __vidar.sb_spec(&b, a2, "%v") }
	return __vidar.sb_to_string(&b)
}

// fmt.tprintf "%#v|%#v|%#v"
__fmt_7 :: proc(a0: $T0, a1: $T1, a2: $T2) -> string {
	b := __vidar.builder(context.temp_allocator)
	when T0 == [dynamic]Inner { __printh_dyn_main_Inner(__vidar.sb_writer(&b), a0, 0) } else { __vidar.sb_spec(&b, a0, "%#v") }
	__vidar.sb_str(&b, "|")
	when T1 == [0]Inner { __printh_arr0_main_Inner(__vidar.sb_writer(&b), a1, 0) } else { __vidar.sb_spec(&b, a1, "%#v") }
	__vidar.sb_str(&b, "|")
	when T2 == Empty { __printh_main_Empty(__vidar.sb_writer(&b), a2, 0) } else { __vidar.sb_spec(&b, a2, "%#v") }
	return __vidar.sb_to_string(&b)
}

// fmt.tprint
__fmt_8 :: proc(a0: $T0) -> string {
	b := __vidar.builder(context.temp_allocator)
	__vidar.sb_v(&b, a0)
	return __vidar.sb_to_string(&b)
}

// fmt.println
__fmt_9 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	when T0 == Outer { n += __print_main_Outer(w, a0) } else { n += __vidar.w_spec(w, a0, "%v") }
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.sbprintf "<%v>"
__fmt_10 :: proc(b: ^__vidar.Builder, a0: $T0) -> string {
	__vidar.sb_str(b, "<")
	when T0 == Node { __print_main_Node(__vidar.sb_writer(b), a0) } else { __vidar.sb_spec(b, a0, "%v") }
	__vidar.sb_str(b, ">")
	return __vidar.sb_to_string(b)
}

// fmt's %v for the types printed here, written out
@(private="file")
__print_main_Outer :: proc(w: __vidar.Writer, x: Outer) -> (n: int) {
	n += __vidar.w_str(w, "Outer{")
	n += __vidar.w_str(w, "name = ")
	n += __vidar.w_quoted(w, x.name)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "r = ")
	n += __vidar.w_v(w, x.r)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "f = ")
	n += __vidar.w_float(w, x.f)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "g = ")
	n += __vidar.w_float(w, x.g)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "b = ")
	n += __vidar.w_v(w, x.b)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "c = ")
	n += __print_main_Color_q(w, x.c)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "in_ = ")
	n += __print_main_Inner(w, x.in_)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "arr = ")
	n += __print_arr3_int(w, x.arr)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "sl = ")
	n += __print_sl_string(w, x.sl)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "dy = ")
	n += __print_dyn_main_Inner(w, x.dy)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "u = ")
	n += __vidar.w_v(w, x.u)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "i = ")
	n += __vidar.w_v(w, x.i)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "e = ")
	n += __print_main_Empty(w, x.e)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "anon = ")
	n += __vidar.w_str(w, "{")
	n += __vidar.w_str(w, "x = ")
	n += __vidar.w_v(w, x.anon.x)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "y = ")
	n += __vidar.w_v(w, x.anon.y)
	n += __vidar.w_str(w, "}")
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "colors = ")
	n += __print_arr2_main_Color(w, x.colors)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "none = ")
	n += __print_arr0_int(w, x.none)
	n += __vidar.w_str(w, "}")
	return
}

@(private="file")
__print_main_Color_q :: proc(w: __vidar.Writer, x: Color) -> (n: int) {
	switch x {
	case .Red: n += __vidar.w_str(w, "\"Red\"")
	case .Green: n += __vidar.w_str(w, "\"Green\"")
	case .Blue: n += __vidar.w_str(w, "\"Blue\"")
	case: n += __vidar.w_spec(w, x, "%v")
	}
	return
}

@(private="file")
__print_main_Inner :: proc(w: __vidar.Writer, x: Inner) -> (n: int) {
	n += __vidar.w_str(w, "Inner{")
	n += __vidar.w_str(w, "a = ")
	n += __vidar.w_v(w, x.a)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "s = ")
	n += __vidar.w_quoted(w, x.s)
	n += __vidar.w_str(w, "}")
	return
}

@(private="file")
__print_arr3_int :: proc(w: __vidar.Writer, x: [3]int) -> (n: int) {
	n += __vidar.w_str(w, "[")
	for e, i in x {
		if i > 0 do n += __vidar.w_str(w, ", ")
		n += __vidar.w_v(w, e)
	}
	n += __vidar.w_str(w, "]")
	return
}

@(private="file")
__print_sl_string :: proc(w: __vidar.Writer, x: []string) -> (n: int) {
	if raw_data(x) == nil && len(x) > 0 {
		__vidar.w_str(w, "nil")
		return
	}
	n += __vidar.w_str(w, "[")
	for e, i in x {
		if i > 0 do n += __vidar.w_str(w, ", ")
		n += __vidar.w_quoted(w, e)
	}
	n += __vidar.w_str(w, "]")
	return
}

@(private="file")
__print_dyn_main_Inner :: proc(w: __vidar.Writer, x: [dynamic]Inner) -> (n: int) {
	if raw_data(x) == nil && len(x) > 0 {
		__vidar.w_str(w, "nil")
		return
	}
	n += __vidar.w_str(w, "[")
	for e, i in x {
		if i > 0 do n += __vidar.w_str(w, ", ")
		n += __print_main_Inner(w, e)
	}
	n += __vidar.w_str(w, "]")
	return
}

@(private="file")
__print_main_Empty :: proc(w: __vidar.Writer, x: Empty) -> (n: int) {
	n += __vidar.w_str(w, "Empty{")
	n += __vidar.w_str(w, "}")
	return
}

@(private="file")
__print_arr2_main_Color :: proc(w: __vidar.Writer, x: [2]Color) -> (n: int) {
	n += __vidar.w_str(w, "[")
	for e, i in x {
		if i > 0 do n += __vidar.w_str(w, ", ")
		n += __print_main_Color_q(w, e)
	}
	n += __vidar.w_str(w, "]")
	return
}

@(private="file")
__print_arr0_int :: proc(w: __vidar.Writer, x: [0]int) -> (n: int) {
	n += __vidar.w_str(w, "[")
	for e, i in x {
		if i > 0 do n += __vidar.w_str(w, ", ")
		n += __vidar.w_v(w, e)
	}
	n += __vidar.w_str(w, "]")
	return
}

@(private="file")
__printh_main_Outer :: proc(w: __vidar.Writer, x: Outer, indent: int) -> (n: int) {
	n += __vidar.w_str(w, "Outer{")
	n += __vidar.w_str(w, "\n")
	n += __vidar.w_tabs(w, indent + 1)
	n += __vidar.w_str(w, "name = ")
	n += __vidar.w_quoted(w, x.name)
	n += __vidar.w_str(w, ",\n")
	n += __vidar.w_tabs(w, indent + 1)
	n += __vidar.w_str(w, "r = ")
	n += __vidar.w_v(w, x.r)
	n += __vidar.w_str(w, ",\n")
	n += __vidar.w_tabs(w, indent + 1)
	n += __vidar.w_str(w, "f = ")
	n += __vidar.w_float(w, x.f)
	n += __vidar.w_str(w, ",\n")
	n += __vidar.w_tabs(w, indent + 1)
	n += __vidar.w_str(w, "g = ")
	n += __vidar.w_float(w, x.g)
	n += __vidar.w_str(w, ",\n")
	n += __vidar.w_tabs(w, indent + 1)
	n += __vidar.w_str(w, "b = ")
	n += __vidar.w_v(w, x.b)
	n += __vidar.w_str(w, ",\n")
	n += __vidar.w_tabs(w, indent + 1)
	n += __vidar.w_str(w, "c = ")
	n += __print_main_Color_q(w, x.c)
	n += __vidar.w_str(w, ",\n")
	n += __vidar.w_tabs(w, indent + 1)
	n += __vidar.w_str(w, "in_ = ")
	n += __printh_main_Inner(w, x.in_, indent + 1)
	n += __vidar.w_str(w, ",\n")
	n += __vidar.w_tabs(w, indent + 1)
	n += __vidar.w_str(w, "arr = ")
	n += __printh_arr3_int(w, x.arr, indent + 1)
	n += __vidar.w_str(w, ",\n")
	n += __vidar.w_tabs(w, indent + 1)
	n += __vidar.w_str(w, "sl = ")
	n += __printh_sl_string(w, x.sl, indent + 1)
	n += __vidar.w_str(w, ",\n")
	n += __vidar.w_tabs(w, indent + 1)
	n += __vidar.w_str(w, "dy = ")
	n += __printh_dyn_main_Inner(w, x.dy, indent + 1)
	n += __vidar.w_str(w, ",\n")
	n += __vidar.w_tabs(w, indent + 1)
	n += __vidar.w_str(w, "u = ")
	n += __vidar.w_v(w, x.u)
	n += __vidar.w_str(w, ",\n")
	n += __vidar.w_tabs(w, indent + 1)
	n += __vidar.w_str(w, "i = ")
	n += __vidar.w_v(w, x.i)
	n += __vidar.w_str(w, ",\n")
	n += __vidar.w_tabs(w, indent + 1)
	n += __vidar.w_str(w, "e = ")
	n += __printh_main_Empty(w, x.e, indent + 1)
	n += __vidar.w_str(w, ",\n")
	n += __vidar.w_tabs(w, indent + 1)
	n += __vidar.w_str(w, "anon = ")
	n += __vidar.w_str(w, "{")
	n += __vidar.w_str(w, "\n")
	n += __vidar.w_tabs(w, indent + 1 + 1)
	n += __vidar.w_str(w, "x = ")
	n += __vidar.w_v(w, x.anon.x)
	n += __vidar.w_str(w, ",\n")
	n += __vidar.w_tabs(w, indent + 1 + 1)
	n += __vidar.w_str(w, "y = ")
	n += __vidar.w_v(w, x.anon.y)
	n += __vidar.w_str(w, ",\n")
	n += __vidar.w_tabs(w, indent + 1)
	n += __vidar.w_str(w, "}")
	n += __vidar.w_str(w, ",\n")
	n += __vidar.w_tabs(w, indent + 1)
	n += __vidar.w_str(w, "colors = ")
	n += __printh_arr2_main_Color(w, x.colors, indent + 1)
	n += __vidar.w_str(w, ",\n")
	n += __vidar.w_tabs(w, indent + 1)
	n += __vidar.w_str(w, "none = ")
	n += __printh_arr0_int(w, x.none, indent + 1)
	n += __vidar.w_str(w, ",\n")
	n += __vidar.w_tabs(w, indent)
	n += __vidar.w_str(w, "}")
	return
}

@(private="file")
__printh_main_Inner :: proc(w: __vidar.Writer, x: Inner, indent: int) -> (n: int) {
	n += __vidar.w_str(w, "Inner{")
	n += __vidar.w_str(w, "\n")
	n += __vidar.w_tabs(w, indent + 1)
	n += __vidar.w_str(w, "a = ")
	n += __vidar.w_v(w, x.a)
	n += __vidar.w_str(w, ",\n")
	n += __vidar.w_tabs(w, indent + 1)
	n += __vidar.w_str(w, "s = ")
	n += __vidar.w_quoted(w, x.s)
	n += __vidar.w_str(w, ",\n")
	n += __vidar.w_tabs(w, indent)
	n += __vidar.w_str(w, "}")
	return
}

@(private="file")
__printh_arr3_int :: proc(w: __vidar.Writer, x: [3]int, indent: int) -> (n: int) {
	n += __vidar.w_str(w, "[")
	if len(x) > 0 {
		n += __vidar.w_str(w, "\n")
		for e in x {
			n += __vidar.w_tabs(w, indent + 1)
			n += __vidar.w_v(w, e)
			n += __vidar.w_str(w, ",\n")
		}
		n += __vidar.w_tabs(w, indent)
	}
	n += __vidar.w_str(w, "]")
	return
}

@(private="file")
__printh_sl_string :: proc(w: __vidar.Writer, x: []string, indent: int) -> (n: int) {
	if raw_data(x) == nil && len(x) > 0 {
		__vidar.w_str(w, "nil")
		return
	}
	n += __vidar.w_str(w, "[")
	if len(x) > 0 {
		n += __vidar.w_str(w, "\n")
		for e in x {
			n += __vidar.w_tabs(w, indent + 1)
			n += __vidar.w_quoted(w, e)
			n += __vidar.w_str(w, ",\n")
		}
		n += __vidar.w_tabs(w, indent)
	}
	n += __vidar.w_str(w, "]")
	return
}

@(private="file")
__printh_dyn_main_Inner :: proc(w: __vidar.Writer, x: [dynamic]Inner, indent: int) -> (n: int) {
	if raw_data(x) == nil && len(x) > 0 {
		__vidar.w_str(w, "nil")
		return
	}
	n += __vidar.w_str(w, "[")
	if len(x) > 0 {
		n += __vidar.w_str(w, "\n")
		for e in x {
			n += __vidar.w_tabs(w, indent + 1)
			n += __printh_main_Inner(w, e, indent + 1)
			n += __vidar.w_str(w, ",\n")
		}
		n += __vidar.w_tabs(w, indent)
	}
	n += __vidar.w_str(w, "]")
	return
}

@(private="file")
__printh_main_Empty :: proc(w: __vidar.Writer, x: Empty, indent: int) -> (n: int) {
	n += __vidar.w_str(w, "Empty{")
	n += __vidar.w_str(w, "}")
	return
}

@(private="file")
__printh_arr2_main_Color :: proc(w: __vidar.Writer, x: [2]Color, indent: int) -> (n: int) {
	n += __vidar.w_str(w, "[")
	if len(x) > 0 {
		n += __vidar.w_str(w, "\n")
		for e in x {
			n += __vidar.w_tabs(w, indent + 1)
			n += __print_main_Color_q(w, e)
			n += __vidar.w_str(w, ",\n")
		}
		n += __vidar.w_tabs(w, indent)
	}
	n += __vidar.w_str(w, "]")
	return
}

@(private="file")
__printh_arr0_int :: proc(w: __vidar.Writer, x: [0]int, indent: int) -> (n: int) {
	n += __vidar.w_str(w, "[")
	if len(x) > 0 {
		n += __vidar.w_str(w, "\n")
		for e in x {
			n += __vidar.w_tabs(w, indent + 1)
			n += __vidar.w_v(w, e)
			n += __vidar.w_str(w, ",\n")
		}
		n += __vidar.w_tabs(w, indent)
	}
	n += __vidar.w_str(w, "]")
	return
}

@(private="file")
__print_main_Node :: proc(w: __vidar.Writer, x: Node) -> (n: int) {
	n += __vidar.w_str(w, "Node{")
	n += __vidar.w_str(w, "name = ")
	n += __vidar.w_quoted(w, x.name)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "children = ")
	n += __print_sl_main_Node(w, x.children)
	n += __vidar.w_str(w, "}")
	return
}

@(private="file")
__print_sl_main_Node :: proc(w: __vidar.Writer, x: []Node) -> (n: int) {
	if raw_data(x) == nil && len(x) > 0 {
		__vidar.w_str(w, "nil")
		return
	}
	n += __vidar.w_str(w, "[")
	for e, i in x {
		if i > 0 do n += __vidar.w_str(w, ", ")
		n += __print_main_Node(w, e)
	}
	n += __vidar.w_str(w, "]")
	return
}

@(private="file")
__printh_main_Node :: proc(w: __vidar.Writer, x: Node, indent: int) -> (n: int) {
	n += __vidar.w_str(w, "Node{")
	n += __vidar.w_str(w, "\n")
	n += __vidar.w_tabs(w, indent + 1)
	n += __vidar.w_str(w, "name = ")
	n += __vidar.w_quoted(w, x.name)
	n += __vidar.w_str(w, ",\n")
	n += __vidar.w_tabs(w, indent + 1)
	n += __vidar.w_str(w, "children = ")
	n += __printh_sl_main_Node(w, x.children, indent + 1)
	n += __vidar.w_str(w, ",\n")
	n += __vidar.w_tabs(w, indent)
	n += __vidar.w_str(w, "}")
	return
}

@(private="file")
__printh_sl_main_Node :: proc(w: __vidar.Writer, x: []Node, indent: int) -> (n: int) {
	if raw_data(x) == nil && len(x) > 0 {
		__vidar.w_str(w, "nil")
		return
	}
	n += __vidar.w_str(w, "[")
	if len(x) > 0 {
		n += __vidar.w_str(w, "\n")
		for e in x {
			n += __vidar.w_tabs(w, indent + 1)
			n += __printh_main_Node(w, e, indent + 1)
			n += __vidar.w_str(w, ",\n")
		}
		n += __vidar.w_tabs(w, indent)
	}
	n += __vidar.w_str(w, "]")
	return
}

@(private="file")
__print_main_Color :: proc(w: __vidar.Writer, x: Color) -> (n: int) {
	switch x {
	case .Red: n += __vidar.w_str(w, "Red")
	case .Green: n += __vidar.w_str(w, "Green")
	case .Blue: n += __vidar.w_str(w, "Blue")
	case: n += __vidar.w_spec(w, x, "%v")
	}
	return
}

@(private="file")
__print_arr2_main_Inner :: proc(w: __vidar.Writer, x: [2]Inner) -> (n: int) {
	n += __vidar.w_str(w, "[")
	for e, i in x {
		if i > 0 do n += __vidar.w_str(w, ", ")
		n += __print_main_Inner(w, e)
	}
	n += __vidar.w_str(w, "]")
	return
}

@(private="file")
__printh_arr0_main_Inner :: proc(w: __vidar.Writer, x: [0]Inner, indent: int) -> (n: int) {
	n += __vidar.w_str(w, "[")
	if len(x) > 0 {
		n += __vidar.w_str(w, "\n")
		for e in x {
			n += __vidar.w_tabs(w, indent + 1)
			n += __printh_main_Inner(w, e, indent + 1)
			n += __vidar.w_str(w, ",\n")
		}
		n += __vidar.w_tabs(w, indent)
	}
	n += __vidar.w_str(w, "]")
	return
}
