package main; import __vidar "vidar_runtime"

import "core:fmt"
import "core:net"
import sched "vidar_sched"

// Operations that finish at once, or on a worker thread, must resume their goroutine
// even while another goroutine is still waiting on the network.
main :: proc() {
	listener, _ := sched.listen_tcp({net.IP4_Loopback, 0})
	accepted := sched.make_chan(net.TCP_Socket, 1)
	sched.go(__closure_0(listener, accepted))
	sched.yield()

	f, err := sched.open("/etc/hosts")
	fmt.println("open:", err)
	sched.close(f)

	ran := new_clone(false)
	sched.blocking(__closure_1(ran))
	fmt.println("blocking:", ran^)

	udp, _ := sched.udp_socket()
	sched.bind(udp, {net.IP4_Loopback, 0})
	to, _ := net.bound_endpoint(udp)
	n, serr := sched.send_to(udp, transmute([]byte)string("ping"), to)
	fmt.println("send_to:", n, serr)

	endpoint, _ := net.bound_endpoint(listener)
	client, _ := sched.dial(endpoint)
	server_side := sched.recv(accepted)
	hosts, _ := sched.open("/etc/hosts")
	sent, ferr := sched.send_file(server_side, hosts)
	fmt.println("send_file:", sent > 0, ferr)
	sched.close(hosts)
	sched.close(client)
	sched.close(server_side)
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(rawptr)) {
	__Env :: struct {
		listener: T0,
		accepted: T1,
	}
	return __vidar.Closure(proc(rawptr)){
		call = proc(__env_raw: rawptr) { __env := cast(^__Env)__env_raw;
		for {
			conn, _, err := sched.accept(__env.listener)
			if err != nil do return
			sched.send(__env.accepted, conn)
		}
	},
		env = new_clone(__Env{__c0, __c1}),
	}
}

__closure_1 :: proc(__c0: $T0) -> __vidar.Closure(proc(rawptr)) {
	__Env :: struct {
		ran: T0,
	}
	return __vidar.Closure(proc(rawptr)){
		call = proc(__env_raw: rawptr) { __env := cast(^__Env)__env_raw; __env.ran^ = true },
		env = new_clone(__Env{__c0}),
	}
}
