package main; import __vidar "vidar_runtime"

import "core:fmt"

Token :: enum { Ident, If, Else, For, In, Return, Proc, Struct, Enum, Switch, Case, Defer }

// 11 keywords: a perfect hash, then one compare
keyword :: proc(word: string) -> Token {
	switch __strswitch_0(word) {
	case 0:
		return .If
	case 1:
		return .Else
	case 2, 3:
		// two strings, one case
		return .For if word == "for" else .In
	case 4:
		return .Return
	case 5:
		return .Proc
	case 6:
		return .Struct
	case 7:
		return .Enum
	case 8:
		return .Switch
	case 9:
		return .Case
	case 10:
		return .Defer
	}
	return .Ident
}

// fallthrough, a default case in the middle, an init statement, and strings that share a length and bytes
kind :: proc(s: string) -> string {
	out := "?"
	switch t := s; __strswitch_1(t) {
	case 0:
		out = "aa"
		fallthrough
	case 1:
		out = out == "aa" ? "aa+ab" : "ab"
	case:
		out = "other"
	case 2, 3, 4, 5, 6, 7, 8, 9:
		out = __fmt_0(t)
	}
	return out
}

// same length, first, middle and last bytes: the cheap hash can't tell them apart, so FNV-1a it is
twins :: proc(s: string) -> int {
	switch __strswitch_2(s) {
	case 0: return 1
	case 1: return 2
	case 2: return 3
	case 3: return 4
	case 4: return 5
	case 5: return 6
	case 6: return 7
	case 7: return 8
	}
	return 0
}

// opted out

plain_twins :: proc(s: string) -> int {
	switch s {
	case "a1": return 1
	case "a2": return 2
	case "a3": return 3
	case "a4": return 4
	case "a5": return 5
	case "a6": return 6
	case "a7": return 7
	case "a8": return 8
	}
	return 0
}

// fewer than 8 strings: compared one after another
small :: proc(s: string) -> int {
	switch s {
	case "x": return 1
	case "y": return 2
	}
	return 0
}

main :: proc() {
	for w in ([]string{"if", "else", "for", "in", "return", "proc", "struct", "enum", "switch", "case", "defer", "iff", "", "x", "procs", "els"}) {
		__fmt_1(keyword(w))
	}
	__fmt_2()
	for s in ([]string{"aa", "ab", "ba", "bb", "ca", "cb", "a", "", "aaa", "é", "zz", "b"}) do __fmt_3(kind(s))
	__fmt_2()
	__fmt_4(small("y"), small("z"))
	__fmt_5(plain_twins("a7"))
	__fmt_6(twins("axbxa"), twins("asbsa"), twins("atbta"), twins("arbra"))
}

// ---- generated by vidar ----

// switch on 11 strings: a perfect hash, then one compare
@(rodata) __strswitch_0_slots := [16]i8{4, 3, 8, -1, -1, 1, 2, 0, 7, -1, 10, 6, -1, 5, -1, 9}
@(rodata) __strswitch_0_keys := [11]string{"if", "else", "for", "in", "return", "proc", "struct", "enum", "switch", "case", "defer"}
__strswitch_0 :: #force_inline proc "contextless" (s: string) -> int {
	x := u32(len(s))
	if len(s) > 0 {
		x = x * 31 + u32(s[0])
		x = x * 31 + u32(s[len(s) >> 1])
		x = x * 31 + u32(s[len(s) - 1])
	}
	h := (x * 2157344959) >> 28
	#no_bounds_check i := int(__strswitch_0_slots[h])
	#no_bounds_check if i >= 0 && __strswitch_0_keys[i] == s do return i
	return -1
}

// switch on 10 strings: a perfect hash, then one compare
@(rodata) __strswitch_1_slots := [16]i8{7, -1, -1, 6, -1, 2, 5, 9, 1, 8, -1, -1, 4, -1, 0, 3}
@(rodata) __strswitch_1_keys := [10]string{"aa", "ab", "ba", "bb", "ca", "cb", "a", "", "aaa", "é"}
__strswitch_1 :: #force_inline proc "contextless" (s: string) -> int {
	x := u32(len(s))
	if len(s) > 0 {
		x = x * 31 + u32(s[0])
		x = x * 31 + u32(s[len(s) >> 1])
		x = x * 31 + u32(s[len(s) - 1])
	}
	h := (x * 82423799) >> 28
	#no_bounds_check i := int(__strswitch_1_slots[h])
	#no_bounds_check if i >= 0 && __strswitch_1_keys[i] == s do return i
	return -1
}

// fmt.tprintf "short %q"
__fmt_0 :: proc(a0: $T0) -> string {
	b := __vidar.builder(context.temp_allocator)
	__vidar.sb_str(&b, "short ")
	__vidar.sb_spec(&b, a0, "%q")
	return __vidar.sb_to_string(&b)
}

// switch on 8 strings: a perfect hash, then one compare
@(rodata) __strswitch_2_slots := [8]i8{5, 7, 6, 1, 2, 4, 3, 0}
@(rodata) __strswitch_2_keys := [8]string{"axbxa", "aybya", "azbza", "awbwa", "avbva", "aubua", "atbta", "asbsa"}
__strswitch_2 :: #force_inline proc "contextless" (s: string) -> int {
	x: u32 = 2384245308
	for c in transmute([]u8)s do x = (x ~ u32(c)) * 16777619
	h := (x * 0x9e3779b1) >> 29
	#no_bounds_check i := int(__strswitch_2_slots[h])
	#no_bounds_check if i >= 0 && __strswitch_2_keys[i] == s do return i
	return -1
}

// fmt.print
__fmt_1 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	when T0 == Token { n += __print_main_Token(w, a0) } else { n += __vidar.w_spec(w, a0, "%v") }
	n += __vidar.w_str(w, " ")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_2 :: proc() -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.print
__fmt_3 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " | ")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_4 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_5 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_6 :: proc(a0: $T0, a1: $T1, a2: $T2, a3: $T3) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a2)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a3)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt's %v for the types printed here, written out
@(private="file")
__print_main_Token :: proc(w: __vidar.Writer, x: Token) -> (n: int) {
	switch x {
	case .Ident: n += __vidar.w_str(w, "Ident")
	case .If: n += __vidar.w_str(w, "If")
	case .Else: n += __vidar.w_str(w, "Else")
	case .For: n += __vidar.w_str(w, "For")
	case .In: n += __vidar.w_str(w, "In")
	case .Return: n += __vidar.w_str(w, "Return")
	case .Proc: n += __vidar.w_str(w, "Proc")
	case .Struct: n += __vidar.w_str(w, "Struct")
	case .Enum: n += __vidar.w_str(w, "Enum")
	case .Switch: n += __vidar.w_str(w, "Switch")
	case .Case: n += __vidar.w_str(w, "Case")
	case .Defer: n += __vidar.w_str(w, "Defer")
	case: n += __vidar.w_spec(w, x, "%v")
	}
	return
}
