package main; import __vidar "vidar_runtime"

import "core:fmt"

Grid :: struct { cells: []int }

sum :: proc(a: []int) -> (total: int) {
	// proven: a is a parameter, i stays below len(a)
	for i in 0..<len(a) do #no_bounds_check total += a[i]
	for x, i in a {
		#no_bounds_check if a[i] != x do panic("mismatch")
	}
	for i := 0; i < len(a); i += 1 {
		#no_bounds_check total += a[i] * 2
	}
	return
}

dot :: proc(a, b: []int) -> (d: int) {
	// b[i] is not proven: only len(a) bounds i
	for i in 0..<len(a) {
		d += a[i] * b[i]
	}
	return
}

nested :: proc(rows: [][]int) -> (n: int) {
	for row, r in rows {
		for j in 0..<len(row) {
			n += row[j] + rows[r][0]
		}
	}
	return
}

grows :: proc() -> int {
	// not proven: the array is appended to, through &list
	list: [dynamic]int
	append(&list, 1, 2, 3)
	t := 0
	for i in 0..<len(list) do t += list[i]
	return t
}

reassigned :: proc(a: []int) -> int {
	// not proven: s changes inside the loop
	s := a
	t := 0
	for i in 0..<len(s) {
		t += s[i]
		s = a[:1]
	}
	return t
}

scratch :: proc(n: int) -> int {
	// three allocations freed together: one block
	xs, ys, __p := __vidar.make_group3(int, f32, Grid, n, n * 2, 1); p := &__p[0]
	/* ys: allocated together with xs */
	/* p: allocated together with xs */
	defer free(raw_data(xs))
	/* delete(ys): freed together with xs */
	/* free(p): freed together with xs */
	for i in 0..<len(xs) do #no_bounds_check xs[i] = i
	for i in 0..<len(ys) do #no_bounds_check ys[i] = f32(i) / 2
	p.cells = xs
	return sum(p.cells) + int(ys[len(ys) - 1])
}

kept_apart :: proc(n: int) -> int {
	// a is freed by a delete of its own, not a defer: not grouped
	a := make([]int, n)
	b := make([]int, n)
	defer delete(b)
	a[0] = 1
	b[0] = 2
	t := a[0] + b[0]
	delete(a)
	return t
}

main :: proc() {
	nums := []int{3, 1, 4, 1, 5}
	__fmt_0(sum(nums), dot(nums, nums), nested({{1, 2}, {3, 4}}), grows(), reassigned(nums))
	__fmt_1(scratch(4), kept_apart(3))
}

// ---- generated by vidar ----

// fmt.println
__fmt_0 :: proc(a0: $T0, a1: $T1, a2: $T2, a3: $T3, a4: $T4) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a2)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a3)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a4)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_1 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}
