package main; import __vidar "vidar_runtime"

import "core:fmt"
import sched "vidar_sched"

// Goroutines that park and yield all the time, with uneven work, so that at
// -define:VIDAR_THREADS=N idle threads take goroutines that have already run. Each one keeps
// temp-allocated strings and locals across its parks, which must survive the move.

work :: proc(id, rounds: int, mu: ^sched.Mutex, count: ^int, ping: sched.Chan(int)) -> int {
	acc := 0
	for i in 0..<rounds {
		label := fmt.tprintf("job %d round %d", id, i)
		x := id * 7919 + i
		for _ in 0..<(id % 5 + 1) * 200 do x = (x * 1103515245 + 12345) & 0x7fffffff
		sched.yield()
		sched.lock(mu)
		count^ += 1
		sched.unlock(mu)
		if i % 16 == 0 {
			sched.send(ping, id)
			sched.recv(ping)
		}
		want := fmt.tprintf("job %d round %d", id, i)
		if label != want do fmt.println("lost a temp string:", label, want)
		acc = (acc + x % 1000) % 1_000_007
	}
	return acc
}

main :: proc() {
	jobs := 24
	mu: sched.Mutex
	count := 0
	results := sched.make_chan(int, jobs)
	ping := sched.make_chan(int, 1)
	for id in 0..<jobs {
		rounds := 400 if id % 4 == 0 else 60
		sched.go(__closure_0(id, rounds, &mu, &count, ping, results))
	}
	total := 0
	for _ in 0..<jobs do total += sched.recv(results)
	fmt.println("total:", total)
	fmt.println("count:", count)
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0, __c1: $T1, __c2: $T2, __c3: $T3, __c4: $T4, __c5: $T5) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		id: T0,
		rounds: T1,
		mu: T2,
		count: T3,
		ping: T4,
		results: T5,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:39: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw; sched.send(__env.results, work(__env.id, __env.rounds, &__env.mu^, &__env.count^, __env.ping)) },
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1, __c2, __c3, __c4, __c5}},
	}
}
