package main; import __vidar "vidar_runtime"

import "core:fmt"

Kind :: enum { Small, Big }

LIMIT :: 100

// constants passed to it make a copy where they are compile-time parameters

scale :: proc(x: int, factor: int, kind: Kind, clamp := true) -> int {
	r := x * factor
	if kind == .Big do r *= 10
	if clamp && r > LIMIT do r = LIMIT
	return r
}

@(private)
repeat :: #force_inline proc(s: string, n: int) -> (out: string) {
	for _ in 0..<n do out = fmt.tprintf("%s%s", out, s)
	return
}

// a table of all 256 results, computed by vidar

popcount :: #force_inline proc(b: u8) -> int { return __popcount_table[b] }






yes_no :: #force_inline proc(b: bool) -> string { return __yes_no_table[1 if b else 0] }

// enums are filled in once at startup

kind_name :: #force_inline proc(k: Kind) -> string { return __kind_name_table[k] }







main :: proc() {
	f := 3
	fmt.println(scale__x_factor_kind(4, 2, .Small), scale__x_factor_kind(4, 2, Kind.Big), scale__kind(f, f, .Small, false), scale__factor_kind(f, 7, .Big, false))
	fmt.println(repeat__s_n("ab", 3), repeat__s("-", f))
	fmt.println(popcount(0), popcount(7), popcount(255), popcount(u8(f)))
	fmt.println(yes_no(true), yes_no(f > 5), kind_name(.Big), kind_name(Kind.Small))
}

// ---- generated by vidar ----

// scale with x, factor, kind known at compile time
scale__x_factor_kind :: proc($x: int, $factor: int, $kind: Kind, clamp := true) -> int {
	r := x * factor
	if kind == .Big do r *= 10
	if clamp && r > LIMIT do r = LIMIT
	return r
}

// scale with kind known at compile time
scale__kind :: proc(x: int, factor: int, $kind: Kind, clamp := true) -> int {
	r := x * factor
	if kind == .Big do r *= 10
	if clamp && r > LIMIT do r = LIMIT
	return r
}

// scale with factor, kind known at compile time
scale__factor_kind :: proc(x: int, $factor: int, $kind: Kind, clamp := true) -> int {
	r := x * factor
	if kind == .Big do r *= 10
	if clamp && r > LIMIT do r = LIMIT
	return r
}

// repeat with s, n known at compile time
repeat__s_n :: #force_inline proc($s: string, $n: int) -> (out: string) {
	for _ in 0..<n do out = fmt.tprintf("%s%s", out, s)
	return
}

// repeat with s known at compile time
repeat__s :: #force_inline proc($s: string, n: int) -> (out: string) {
	for _ in 0..<n do out = fmt.tprintf("%s%s", out, s)
	return
}

// popcount(x) for every x, computed by vidar
@(rodata)
__popcount_table := [256]int{
	0, 1, 1, 2, 1, 2, 2, 3,
	1, 2, 2, 3, 2, 3, 3, 4,
	1, 2, 2, 3, 2, 3, 3, 4,
	2, 3, 3, 4, 3, 4, 4, 5,
	1, 2, 2, 3, 2, 3, 3, 4,
	2, 3, 3, 4, 3, 4, 4, 5,
	2, 3, 3, 4, 3, 4, 4, 5,
	3, 4, 4, 5, 4, 5, 5, 6,
	1, 2, 2, 3, 2, 3, 3, 4,
	2, 3, 3, 4, 3, 4, 4, 5,
	2, 3, 3, 4, 3, 4, 4, 5,
	3, 4, 4, 5, 4, 5, 5, 6,
	2, 3, 3, 4, 3, 4, 4, 5,
	3, 4, 4, 5, 4, 5, 5, 6,
	3, 4, 4, 5, 4, 5, 5, 6,
	4, 5, 5, 6, 5, 6, 6, 7,
	1, 2, 2, 3, 2, 3, 3, 4,
	2, 3, 3, 4, 3, 4, 4, 5,
	2, 3, 3, 4, 3, 4, 4, 5,
	3, 4, 4, 5, 4, 5, 5, 6,
	2, 3, 3, 4, 3, 4, 4, 5,
	3, 4, 4, 5, 4, 5, 5, 6,
	3, 4, 4, 5, 4, 5, 5, 6,
	4, 5, 5, 6, 5, 6, 6, 7,
	2, 3, 3, 4, 3, 4, 4, 5,
	3, 4, 4, 5, 4, 5, 5, 6,
	3, 4, 4, 5, 4, 5, 5, 6,
	4, 5, 5, 6, 5, 6, 6, 7,
	3, 4, 4, 5, 4, 5, 5, 6,
	4, 5, 5, 6, 5, 6, 6, 7,
	4, 5, 5, 6, 5, 6, 6, 7,
	5, 6, 6, 7, 6, 7, 7, 8,
}

// yes_no(x) for every x, computed by vidar
@(rodata)
__yes_no_table := [2]string{
	"no", "yes",
}

__kind_name_table: [Kind]string

__kind_name_compute :: proc(k: Kind) -> string {
	switch k {
	case .Small: return "small"
	case .Big: return "big"
	}
	return "?"
}

// kind_name(x) for every x, computed once at startup
@(init)
__kind_name_fill :: proc "contextless" () {
	context = __vidar.default_context()
	for x in Kind do __kind_name_table[x] = __kind_name_compute(x)
}
