package main; import __vidar "vidar_runtime"

import "core:fmt"

Handler :: __vidar.Closure(proc(__vidar.Env, string) -> bool)

Button :: struct {
	label:    string,
	on_click: Handler,
}

handlers: [dynamic]Handler

register :: proc(h: Handler) { append(&handlers, h) }

make_filter :: proc(prefix: string) -> Handler {
	return __closure_0(prefix)
}

main :: proc() {
	clicks := 0
	b := Button{label = "ok", on_click = __closure_1(&clicks)}
	b.on_click.call(b.on_click.env, "a")
	b.on_click.call(b.on_click.env, "b")
	fmt.println(b.label, "clicks:", clicks)

	register(make_filter("x"))
	register(make_filter("y"))
	for h, i in handlers {
		fmt.println(i, h.call(h.env, "xylophone"))
	}
	// the callee is a call result: goes through a generated call helper
	fmt.println(__call_closure_0(make_filter("z"), "zebra"))
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, string) -> bool) {
	__Caps :: struct {
		prefix: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:17: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, string) -> bool){
		call = proc(__env_raw: __vidar.Env, msg: string) -> bool { __env := transmute(__Env)__env_raw; return len(msg) > 0 && msg[0] == __env.prefix[0] },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_1 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, string) -> bool) {
	__Caps :: struct {
		clicks: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:22: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, string) -> bool){
		call = proc(__env_raw: __vidar.Env, msg: string) -> bool { __env := transmute(__Env)__env_raw; __env.clicks^ += 1; return true },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__call_closure_0 :: #force_inline proc(c: __vidar.Closure(proc(__vidar.Env, string) -> bool), p0: string) -> bool {
	return c.call(c.env, p0)
}
