package main; import __vidar "vidar_runtime"

import "core:fmt"

Handler :: __vidar.Closure(proc(rawptr, string) -> bool)

Button :: struct {
	label:    string,
	on_click: Handler,
}

handlers: [dynamic]Handler

register :: proc(h: Handler) { append(&handlers, h) }

make_filter :: proc(prefix: string) -> Handler {
	return __closure_0(prefix)
}

main :: proc() {
	clicks := new_clone(0)
	b := Button{label = "ok", on_click = __closure_1(clicks)}
	b.on_click.call(b.on_click.env, "a")
	b.on_click.call(b.on_click.env, "b")
	fmt.println(b.label, "clicks:", clicks^)

	register(make_filter("x"))
	register(make_filter("y"))
	for h, i in handlers {
		fmt.println(i, h.call(h.env, "xylophone"))
	}
	// the callee is a call result: goes through a generated call helper
	fmt.println(__call_closure_0(make_filter("z"), "zebra"))
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0) -> __vidar.Closure(proc(rawptr, string) -> bool) {
	__Env :: struct {
		prefix: T0,
	}
	return __vidar.Closure(proc(rawptr, string) -> bool){
		call = proc(__env_raw: rawptr, msg: string) -> bool { __env := cast(^__Env)__env_raw; return len(msg) > 0 && msg[0] == __env.prefix[0] },
		env = new_clone(__Env{__c0}),
	}
}

__closure_1 :: proc(__c0: $T0) -> __vidar.Closure(proc(rawptr, string) -> bool) {
	__Env :: struct {
		clicks: T0,
	}
	return __vidar.Closure(proc(rawptr, string) -> bool){
		call = proc(__env_raw: rawptr, msg: string) -> bool { __env := cast(^__Env)__env_raw; __env.clicks^ += 1; return true },
		env = new_clone(__Env{__c0}),
	}
}

__call_closure_0 :: #force_inline proc(c: __vidar.Closure(proc(rawptr, string) -> bool), p0: string) -> bool {
	return c.call(c.env, p0)
}
