package geo

import "core:math"

Vec :: struct { x, y: f64 }

Shape :: struct { data: rawptr, __vtable: ^__Shape_VTable }

length :: proc{__Shape_length, vec_length}
scale  :: proc{__Shape_scale, vec_scale}

vec_length :: proc(v: ^Vec) -> f64 { return math.sqrt(v.x * v.x + v.y * v.y) }
vec_scale  :: proc(v: ^Vec, k: f64) { v.x *= k; v.y *= k }

// ---- generated by vidar ----

__Shape_VTable :: struct {
	length: proc(self: Shape) -> f64,
	scale: proc(self: Shape, k: f64),
}

__Shape_length :: proc(s: Shape) -> f64 { return s.__vtable.length(s) }

__Shape_scale :: proc(s: Shape, k: f64) { s.__vtable.scale(s, k) }

__Shape_identity :: #force_inline proc(v: Shape) -> Shape { return v }

__Shape_from :: proc{__Shape_from_Vec, __Shape_identity}

@(rodata)
__Shape_vtable_Vec := __Shape_VTable{
	length = proc(self: Shape) -> f64 { return vec_length((^Vec)(self.data)) },
	scale = proc(self: Shape, k: f64) { vec_scale((^Vec)(self.data), k) },
}

__Shape_from_Vec :: proc(p: ^Vec) -> Shape { return {data = p, __vtable = &__Shape_vtable_Vec} }
