// Generated by vidar: runtime support shared by all packages.
package vidar_runtime

import "base:intrinsics"
import "base:runtime"
import "core:fmt"
import "core:sync"
import "core:time"

// a closure: a proc plus its captured environment
Closure :: struct($P: typeid) {
	call: P,
	env:  rawptr,
}

// scoped!: a block's own temp allocator
Temp_Arena :: runtime.Default_Temp_Allocator

temp_arena_begin :: proc(arena: ^Temp_Arena, backing: runtime.Allocator) -> runtime.Allocator {
	runtime.default_temp_allocator_init(arena, 64 * runtime.Kilobyte, backing)
	return runtime.default_temp_allocator(arena)
}

temp_arena_end :: proc(arena: ^Temp_Arena) {
	runtime.default_temp_allocator_destroy(arena)
}

// built-in macros: with_allocator!, locked!, timed!, dbg!, check!, todo!, unimplemented!, format!
lock :: proc(m: ^$T) { sync.lock(m) }
unlock :: proc(m: ^$T) { sync.unlock(m) }

timer_start :: proc() -> time.Tick { return time.tick_now() }

timer_report :: proc(label, site: string, start: time.Tick) {
	fmt.eprintf("[timed] %s: %v\n", label if label != "" else site, time.tick_since(start))
}

dbg :: proc(value: $T, text, site: string) -> T {
	fmt.eprintf("[%s] %s = %v\n", site, text, value)
	return value
}

check_failed :: proc(text: string, message: string, loc := #caller_location) -> ! {
	panic(fmt.tprintf("check failed: %s%s", text, message != "" ? fmt.tprintf(" (%s)", message) : ""), loc)
}

check_failed_cmp :: proc(text: string, message: string, lhs_text: string, lhs: $A, rhs_text: string, rhs: $B, loc := #caller_location) -> ! {
	msg := fmt.tprintf("check failed: %s%s", text, message != "" ? fmt.tprintf(" (%s)", message) : "")
	if lhs_text != "" do msg = fmt.tprintf("%s\n\t%s = %v", msg, lhs_text, lhs)
	if rhs_text != "" do msg = fmt.tprintf("%s\n\t%s = %v", msg, rhs_text, rhs)
	panic(msg, loc)
}

not_done :: proc(what: string, message: string, loc := #caller_location) -> ! {
	panic(message != "" ? fmt.tprintf("%s: %s", what, message) : what, loc)
}

tprintf :: proc(format: string, args: ..any) -> string { return fmt.tprintf(format, ..args) }

// whether a result signals failure: false for an ok-bool, otherwise anything but the zero/nil value
failed :: #force_inline proc(e: $T) -> bool {
	when T == bool {
		return !e
	} else when intrinsics.type_is_union(T) || intrinsics.type_is_pointer(T) {
		return e != nil
	} else {
		zero: T
		return e != zero
	}
}

// `catch unreachable`: the error was not supposed to happen
unexpected :: proc(e: $T, loc := #caller_location) -> ! {
	when T == bool {
		panic("unexpected failure", loc)
	} else {
		panic(fmt.tprintf("unexpected error: %v", e), loc)
	}
}
