package main; import __vidar "vidar_runtime"

import "core:fmt"
import "core:strings"

Store :: struct { data: rawptr, __vtable: ^__Store_VTable }

get  :: proc{__Store_get, mem_get, log_get}
put  :: proc{__Store_put, mem_put, log_put}
keys :: proc{__Store_keys, mem_keys, log_keys}
tag  :: proc{__Store_tag, mem_tag, log_tag}

Mem :: struct { data: map[string]string }
Log :: struct { inner: Store, lines: [dynamic]string }

mem_get :: proc(m: ^Mem, key: string) -> (string, bool) { v, ok := m.data[key]; return v, ok }
mem_put :: proc(m: ^Mem, key, value: string) { m.data[key] = value }
mem_keys :: proc(m: ^Mem) -> []string {
	out: [dynamic]string
	for k in m.data do append(&out, k)
	return out[:]
}
mem_tag :: proc(m: ^Mem, parts: ..string) -> string { return strings.join(parts, "/") }



// a decorator: wraps any Store and records the calls
log_get :: proc(l: ^Log, key: string) -> (string, bool) {
	append(&l.lines, fmt.tprintf("get %s", key))
	return get(l.inner, key)
}
log_put :: proc(l: ^Log, key, value: string) {
	append(&l.lines, fmt.tprintf("put %s", key))
	put(l.inner, key, value)
}
log_keys :: proc(l: ^Log) -> []string { return keys(l.inner) }
log_tag :: proc(l: ^Log, parts: ..string) -> string { return fmt.tprintf("log:%s", tag(l.inner, ..parts)) }



fill :: proc(s: Store) {
	put(s, "a", "1")
	put(s, "b", "2")
}

main :: proc() {
	mem := Mem{}
	log := Log{inner = __Store_from(&mem)}
	fill(__Store_from(&log))

	v, ok := get(log.inner, "a")
	fmt.println(v, ok)
	_, missing := get(__Store_from(&log), "zzz")
	fmt.println("missing:", !missing)
	fmt.println(log.lines[:])
	fmt.println(len(keys(__Store_from(&mem))), tag(__Store_from(&log), "x", "y", "z"))

	// static calls, including variadic and multiple results
	w, found := get(&mem, "b")
	fmt.println("static:", w, found, tag(&mem, "p", "q"))

	// interfaces captured by closures
	s: Store = __Store_from(&mem)
	reader := __closure_0(s)
	fmt.println("via closure:", reader.call(reader.env, "b"))

	// zero value: no data, no vtable
	empty: Store
	fmt.println("empty is nil:", empty.__vtable == nil)
}

// ---- generated by vidar ----

__Store_VTable :: struct {
	get: proc(self: Store, key: string) -> (string, bool),
	put: proc(self: Store, key, value: string),
	keys: proc(self: Store) -> []string,
	tag: proc(self: Store, parts: ..string) -> string,
}

__Store_get :: proc(s: Store, key: string) -> (string, bool) {
	if s.__vtable == &__Store_vtable_Mem { return mem_get(auto_cast s.data, key) }
	if s.__vtable == &__Store_vtable_Log { return log_get(auto_cast s.data, key) }
	return s.__vtable.get(s, key)
}

__Store_put :: proc(s: Store, key, value: string) {
	if s.__vtable == &__Store_vtable_Mem { mem_put(auto_cast s.data, key, value); return }
	if s.__vtable == &__Store_vtable_Log { log_put(auto_cast s.data, key, value); return }
	s.__vtable.put(s, key, value)
}

__Store_keys :: proc(s: Store) -> []string {
	if s.__vtable == &__Store_vtable_Mem { return mem_keys(auto_cast s.data) }
	if s.__vtable == &__Store_vtable_Log { return log_keys(auto_cast s.data) }
	return s.__vtable.keys(s)
}

__Store_tag :: proc(s: Store, parts: ..string) -> string {
	if s.__vtable == &__Store_vtable_Mem { return mem_tag(auto_cast s.data, ..parts) }
	if s.__vtable == &__Store_vtable_Log { return log_tag(auto_cast s.data, ..parts) }
	return s.__vtable.tag(s, ..parts)
}

__Store_identity :: #force_inline proc(v: Store) -> Store { return v }

__Store_from :: proc{__Store_from_Mem, __Store_from_Log, __Store_identity}

@(rodata)
__Store_vtable_Mem := __Store_VTable{
	get = proc(self: Store, key: string) -> (string, bool) { return mem_get((^Mem)(self.data), key) },
	put = proc(self: Store, key, value: string) { mem_put((^Mem)(self.data), key, value) },
	keys = proc(self: Store) -> []string { return mem_keys((^Mem)(self.data)) },
	tag = proc(self: Store, parts: ..string) -> string { return mem_tag((^Mem)(self.data), ..parts) },
}

__Store_from_Mem :: proc(p: ^Mem) -> Store { return {data = p, __vtable = &__Store_vtable_Mem} }

@(rodata)
__Store_vtable_Log := __Store_VTable{
	get = proc(self: Store, key: string) -> (string, bool) { return log_get((^Log)(self.data), key) },
	put = proc(self: Store, key, value: string) { log_put((^Log)(self.data), key, value) },
	keys = proc(self: Store) -> []string { return log_keys((^Log)(self.data)) },
	tag = proc(self: Store, parts: ..string) -> string { return log_tag((^Log)(self.data), ..parts) },
}

__Store_from_Log :: proc(p: ^Log) -> Store { return {data = p, __vtable = &__Store_vtable_Log} }

__closure_0 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, string) -> string) {
	__Caps :: struct {
		s: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:64: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, string) -> string){
		call = proc(__env_raw: __vidar.Env, key: string) -> string { __env := transmute(__Env)__env_raw; val, _ := get(__env.s, key); return val },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}
