package main; import __vidar "vidar_runtime"

import "core:fmt"

// a bound that isn't len(a): one check before the loop, none inside
scale :: proc(a: []int, n: int) -> (total: int) {
	__vidar.bounds_upto(n, 0, len(a)); for i in 0..<n {
		#no_bounds_check a[i] *= 2
		#no_bounds_check total += a[i]
	}
	return
}

// lockstep: b is indexed by a's index
dot :: proc(a, b: []f64) -> (sum: f64) {
	__vidar.bounds_upto(len(a), 0, len(b)); for x, i in a do #no_bounds_check sum += x * b[i]
	return
}

// two arrays, one bound
add_into :: proc(dst, src: []int, n: int) {
	__vidar.bounds_upto(n, 2, len(dst), len(src)); for i in 2..<n do #no_bounds_check dst[i] = src[i] + 1
}

// constant offsets the range already proves
diffs :: proc(src: []int, out: []int) {
	__vidar.bounds_upto(len(src) - 1, 0, len(out)); for i in 0..<len(src) - 1 do #no_bounds_check out[i] = src[i + 1] - src[i]
}

back :: proc(src: []int) -> (total: int) {
	for i in 2..<len(src) do #no_bounds_check total += src[i] - src[i - 2]
	return
}

// not hoisted: an early exit, or an index under an `if`
first_negative :: proc(a: []int, n: int) -> int {
	for i in 0..<n {
		if a[i] < 0 do return i
	}
	return -1
}

guarded :: proc(a: []int, n: int) -> (total: int) {
	for i in 0..<n {
		if i % 2 == 0 do total += a[i]
	}
	return
}

main :: proc() {
	a := []int{1, 2, 3, 4, 5, 6}
	__fmt_0(scale__n(a, 4), a)
	__fmt_1(dot({1, 2, 3}, {4, 5, 6, 7}))
	__dst_buf: [6]int; dst := __dst_buf[:]
	/* delete(dst): dst is on the stack */
	add_into(dst, a, 6)
	__fmt_2(dst)
	__out_buf: [5]int; out := __out_buf[:]
	/* delete(out): out is on the stack */
	diffs(a, out)
	__fmt_3(out, back(a))
	__fmt_4(first_negative({3, -1, 2}, 10), guarded(a, 6))
	// a loop that runs zero times checks nothing
	// a constant 0 bound: no copy where n is compile-time (Odin rejects `0..<0`)
	__fmt_1(scale(a, 0))
	__fmt_1(nested(a, 3, 2))
	__fmt_4(runes("ab", {1, 2}), fixed({1, 2, 3, 4}, {1, 1, 1, 1}))
}

// a string's index is a byte offset: no check before the loop; a fixed array gets one
runes :: proc(s: string, b: []int) -> (n: int) {
	for r, i in s do n += int(r) * b[i]
	return
}

fixed :: proc(a: [4]int, b: []int) -> (n: int) {
	__vidar.bounds_upto(len(a), 0, len(b)); for x, i in a do #no_bounds_check n += x * b[i]
	return
}

// a loop that is the body of a `do`, and a labeled one: the check still goes right before the loop
nested :: proc(a: []int, n, reps: int) -> (total: int) {
	for _ in 0..<reps { __vidar.bounds_upto(n, 0, len(a)); for i in 0..<n do #no_bounds_check total += a[i] }
	if reps > 0 { __vidar.bounds_upto(n, 0, len(a)); for i in 0..<n do #no_bounds_check total += a[i] }
	outer: for i in 0..<n {
		total += a[i]
		for j in 0..<n do if j > i do continue outer
	}
	return
}

// ---- generated by vidar ----

// scale with n known at compile time
scale__n :: proc(a: []int, $n: int) -> (total: int) {
	for i in 0..<n {
		a[i] *= 2
		total += a[i]
	}
	return
}

// fmt.println
__fmt_0 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	when T1 == []int { n += __print_sl_int(w, a1) } else { n += __vidar.w_spec(w, a1, "%v") }
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_1 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_2 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	when T0 == []int { n += __print_sl_int(w, a0) } else { n += __vidar.w_spec(w, a0, "%v") }
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_3 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	when T0 == []int { n += __print_sl_int(w, a0) } else { n += __vidar.w_spec(w, a0, "%v") }
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_4 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt's %v for the types printed here, written out
@(private="file")
__print_sl_int :: proc(w: __vidar.Writer, x: []int) -> (n: int) {
	if raw_data(x) == nil && len(x) > 0 {
		__vidar.w_str(w, "nil")
		return
	}
	n += __vidar.w_str(w, "[")
	for e, i in x {
		if i > 0 do n += __vidar.w_str(w, ", ")
		n += __vidar.w_v(w, e)
	}
	n += __vidar.w_str(w, "]")
	return
}
