package main

import "core:fmt"
import geo "geo"

Foo :: struct { n: int }

Counter :: struct { data: rawptr, __vtable: ^__Counter_VTable }

bump :: proc{__Counter_bump, foo_bump}
get  :: proc{__Counter_get, foo_get}

foo_bump :: proc(f: ^Foo, by: int) -> int { f.n += by; return f.n }
foo_get  :: proc(f: ^Foo) -> int { return f.n }



Holder :: struct { foo: Foo, all: [2]Foo }

main :: proc() {
	// a method called with a pointer to a concrete type: a static call, no vtable
	foo := Foo{1}
	fmt.println(bump(&foo, 2), get(&foo))

	// through a pointer, a field, an index and a dereference
	p := &foo
	bump(p, 10)
	h := Holder{foo = {100}, all = {{7}, {8}}}
	bump(&h.foo, 1)
	bump(&h.all[1], 1)
	fmt.println(get(p), get(&h.foo), get(&h.all[1]), get(&p^))

	// on an interface value, the same call dispatches through the vtable
	c: Counter = __Counter_from(&foo)
	fmt.println(bump(c, 1), foo.n)

	// interfaces, methods and impls from another package
	v := geo.Vec{3, 4}
	fmt.println(geo.length(&v))
	geo.scale(&v, 2)
	fmt.println(v)
	s: geo.Shape = geo.__Shape_from(&v)
	fmt.println(geo.length(s))
}

// ---- generated by vidar ----

__Counter_VTable :: struct {
	bump: proc(self: Counter, by: int) -> int,
	get: proc(self: Counter) -> int,
}

__Counter_bump :: proc(c: Counter, by: int) -> int { return c.__vtable.bump(c, by) }

__Counter_get :: proc(c: Counter) -> int { return c.__vtable.get(c) }

__Counter_identity :: #force_inline proc(v: Counter) -> Counter { return v }

__Counter_from :: proc{__Counter_from_Foo, __Counter_identity}

@(rodata)
__Counter_vtable_Foo := __Counter_VTable{
	bump = proc(self: Counter, by: int) -> int { return foo_bump((^Foo)(self.data), by) },
	get = proc(self: Counter) -> int { return foo_get((^Foo)(self.data)) },
}

__Counter_from_Foo :: proc(p: ^Foo) -> Counter { return {data = p, __vtable = &__Counter_vtable_Foo} }
