package main; import __vidar "vidar_runtime"

import "core:fmt"

Point :: struct { x, y: int }

// every way a variable can be declared, captured by reference
main :: proc() {
	a := 1                       // short declaration
	b: int = 2                   // typed with value
	c: [dynamic]int              // typed without value
	p := Point{1, 2}             // struct value
	d, e := 4, 5                 // multi-declaration, only `e` captured

	touch := __closure_0(&a, &b, &c, &p, &e)
	touch.call(touch.env)
	touch.call(touch.env)
	fmt.println(a, b, c[:], p, d, e)

	// a parameter captured by reference is copied into a stack local at proc entry
	acc := proc(start: int) -> int { start := start;
		add := __closure_1(&start)
		add.call(add.env, 5)
		add.call(add.env, 6)
		return start
	}
	fmt.println("acc:", acc(100))

	// a closure that outlives its frame needs state the coder puts on the heap
	make := proc() -> __vidar.Closure(proc(__vidar.Env) -> int) {
		total := new(int)
		return __closure_2(total)
	}
	counter := make()
	counter.call(counter.env)
	fmt.println("counter:", counter.call(counter.env))
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0, __c1: $T1, __c2: $T2, __c3: $T3, __c4: $T4) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		a: T0,
		b: T1,
		c: T2,
		p: T3,
		e: T4,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:15: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw;
		__env.a^ *= 10
		__env.b^ *= 10
		append(&__env.c^, 7)
		__env.p^.x += 100
		__env.e^ += 1
	},
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1, __c2, __c3, __c4}},
	}
}

__closure_1 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int)) {
	__Caps :: struct {
		start: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:28: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int)){
		call = proc(__env_raw: __vidar.Env, k: int) { __env := transmute(__Env)__env_raw; __env.start^ += k },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_2 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env) -> int) {
	__Caps :: struct {
		total: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:38: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env) -> int){
		call = proc(__env_raw: __vidar.Env) -> int { __env := transmute(__Env)__env_raw; __env.total^ += 1; return __env.total^ },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}
