package main; import __vidar "vidar_runtime"

import "core:fmt"
import "core:net"
import sched "vidar_sched"

ROUNDS :: 2000

// sched_pending_io's scenario, many times in one process: operations that finish at once,
// or on a worker thread, while another goroutine waits on the network. A lost wakeup or a
// busy loop shows up here as a hang, which the test runner times out.
round :: proc() -> (ok: bool) {
	listener, _ := sched.listen_tcp({net.IP4_Loopback, 0})
	accepted := sched.make_chan(net.TCP_Socket, 1)
	defer sched.close(accepted)
	sched.go(__closure_0(listener, accepted))
	sched.yield()

	f, err := sched.open("/etc/hosts")
	if err != nil do return
	sched.close(f)

	ran := false
	sched.blocking(__closure_1(&ran))
	if !ran do return

	udp, _ := sched.udp_socket()
	sched.bind(udp, {net.IP4_Loopback, 0})
	to, _ := net.bound_endpoint(udp)
	n, serr := sched.send_to(udp, transmute([]byte)string("ping"), to)
	sched.close(udp)
	if n != 4 || serr != nil do return

	endpoint, _ := net.bound_endpoint(listener)
	client, _ := sched.dial(endpoint)
	server_side := sched.recv(accepted)
	hosts, _ := sched.open("/etc/hosts")
	sent, ferr := sched.send_file(server_side, hosts)
	sched.close(hosts)
	sched.close(client)
	sched.close(server_side)
	sched.close(listener)
	return sent > 0 && ferr == nil
}

main :: proc() {
	passed := 0
	for _ in 0..<ROUNDS do if round() do passed += 1
	fmt.println(passed, "of", ROUNDS, "rounds")
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		listener: T0,
		accepted: T1,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:16: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw;
		conn, _, err := sched.accept(__env.listener)
		if err == nil do sched.send(__env.accepted, conn)
	},
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1}},
	}
}

__closure_1 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		ran: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:27: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw; __env.ran^ = true },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}
