package main; import __vidar "vidar_runtime"

import "core:fmt"

// Closure bodies using the enclosing proc's constants and types. Ones that
// depend on nothing local move to file scope with the body.

Shape :: enum { Circle, Square }

each :: proc(xs: []int, f: __vidar.Closure(proc(__vidar.Env, int))) { __f_call := f.call; for x in xs do __f_call(f.env, x) }

main :: proc() {
	SCALE :: __Local_0
	LIMIT :: __Local_1
	RATE : f32 : 1.5
	Vec :: __Local_2
	Kind :: __Local_3
	Pair :: __Local_4
	clamp :: __Local_5

	offset := 10
	scale := __closure_0(offset)
	fmt.println(scale.call(scale.env, Vec{1, 2}), scale.call(scale.env, Vec{5, 5}))

	classify := __closure_1(offset)
	p := classify.call(classify.env, Vec{1, 1})
	fmt.println(p.kind, p.shape, classify.call(classify.env, Vec{3, 0}).kind)

	// a nested closure, and one with no captures
	total := 0
	add := __closure_3(&total)
	add.call(add.env, 1); add.call(add.env, 2)
	half := __vidar.Closure(proc(__vidar.Env) -> f32){call = proc(__env_raw: __vidar.Env) -> f32 { return RATE / 2 }}
	fmt.println(total, half.call(half.env), f32(SCALE) * RATE)

	// with -opt, a copy of each calls the body directly; it uses the lifted names too
	sum := 0
	each([]int{1, 2, 3}, __closure_4(&sum))
	fmt.println(sum)

	// a constant that would change meaning at file scope stays where it is: the helper goes in main
	WHERE :: (#procedure)
	buf: [4]int
	__closure_5 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int)) {
		__Caps :: struct {
			buf: T0,
		}
		#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:50: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
		__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
		return __vidar.Closure(proc(__vidar.Env, int)){
			call = proc(__env_raw: __vidar.Env, x: int) { __env := transmute(__Env)__env_raw; for i in 0..<len(__env.buf^) do __env.buf^[i] = x + i * __Local_0; fmt.println(WHERE) },
			env = transmute(__vidar.Env)__Env{__caps = {__c0}},
		}
	}
	fill := __closure_5(&buf)
	fill.call(fill.env, 7)
	fmt.println(buf)
}

// ---- generated by vidar ----

// SCALE, from line 13, used by a closure body
__Local_0 :: 3

// LIMIT, from line 14, used by a closure body
__Local_1 :: __Local_0 * 4

// Vec, from line 16, used by a closure body
__Local_2 :: struct { x, y: int }

// Kind, from line 17, used by a closure body
__Local_3 :: enum { Small, Big }

// Pair, from line 18, used by a closure body
__Local_4 :: struct { v: __Local_2, kind: __Local_3, shape: Shape }

// clamp, from line 19, used by a closure body
__Local_5 :: proc(x: int) -> int { return min(x, __Local_1) }

__closure_0 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, __Local_2) -> int) {
	__Caps :: struct {
		offset: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:22: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, __Local_2) -> int){
		call = proc(__env_raw: __vidar.Env, v: __Local_2) -> int { __env := transmute(__Env)__env_raw; return __Local_5(v.x * __Local_0 + v.y + __env.offset) },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_1 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, __Local_2) -> __Local_4) {
	__Caps :: struct {
		offset: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:25: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, __Local_2) -> __Local_4){
		call = proc(__env_raw: __vidar.Env, v: __Local_2) -> __Local_4 { __env := transmute(__Env)__env_raw;
		k := __Local_3.Big if v.x + __env.offset > __Local_1 else __Local_3.Small
		return __Local_4{v, k, .Square}
	},
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_2 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env) -> int) {
	__Caps :: struct {
		n: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:35: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env) -> int){
		call = proc(__env_raw: __vidar.Env) -> int { __env := transmute(__Env)__env_raw; return __env.n * __Local_0 * 2 },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_3 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int)) {
	__Caps :: struct {
		total: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:34: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int)){
		call = proc(__env_raw: __vidar.Env, n: int) { __env := transmute(__Env)__env_raw;
		twice := __closure_2(n)
		__env.total^ += twice.call(twice.env)
	},
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_4 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int)) {
	__Caps :: struct {
		sum: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:44: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int)){
		call = proc(__env_raw: __vidar.Env, x: int) { __env := transmute(__Env)__env_raw; __env.sum^ += __Local_5(x * __Local_1) },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}
