package main

import "core:fmt"

// An interface method is a proc group: called with a pointer to a concrete type it is a
// static call to that type's proc, called with an interface value it goes through the vtable.

Container :: struct { data: rawptr, __vtable: ^__Container_VTable }

push :: proc{__Container_push, stack_push}
size :: proc{__Container_size, stack_size}

// A cleanup interface is declared like any other.
Destroy :: struct { data: rawptr, __vtable: ^__Destroy_VTable }

destroy :: proc{__Destroy_destroy, stack_destroy}

Stack :: struct { items: [dynamic]int }

stack_push :: proc(s: ^Stack, x: int) { append(&s.items, x) }
stack_size :: proc(s: ^Stack) -> int  { return len(s.items) }

stack_destroy :: proc(s: ^Stack) {
	fmt.println("destroying stack of", len(s.items))
	delete(s.items)
}




Pair :: struct { left, right: Stack }

main :: proc() {
	a: Stack
	defer destroy(&a)
	push(&a, 1)
	push(&a, 2)
	fmt.println("value:", size(&a))

	// through a pointer, a field, an index and a dereference
	p := &a
	push(p, 3)
	pair: Pair
	push(&pair.left, 10)
	stacks: [2]Stack
	push(&stacks[1], 20)
	fmt.println("pointer:", size(p), "field:", size(&pair.left), "index:", size(&stacks[1]), "deref:", size(&p^))

	// the implementation stays an ordinary proc
	stack_push(&a, 5)

	// on an interface value, the same call dispatches through the vtable
	c: Container = __Container_from(&a)
	push(c, 4)
	fmt.println("interface:", size(c), size(&a))

	// interface values of different types can be cleaned up together
	trash: [dynamic]Destroy
	append(&trash, __Destroy_from(&pair.left), __Destroy_from(&stacks[1]))
	for d in trash do destroy(d)
	delete(trash)
}

// ---- generated by vidar ----

__Container_VTable :: struct {
	push: proc(self: Container, x: int),
	size: proc(self: Container) -> int,
}

__Container_push :: proc(c: Container, x: int) { c.__vtable.push(c, x) }

__Container_size :: proc(c: Container) -> int { return c.__vtable.size(c) }

__Container_identity :: #force_inline proc(v: Container) -> Container { return v }

__Container_from :: proc{__Container_from_Stack, __Container_identity}

__Destroy_VTable :: struct {
	destroy: proc(self: Destroy),
}

__Destroy_destroy :: proc(d: Destroy) { d.__vtable.destroy(d) }

__Destroy_identity :: #force_inline proc(v: Destroy) -> Destroy { return v }

__Destroy_from :: proc{__Destroy_from_Stack, __Destroy_identity}

@(rodata)
__Container_vtable_Stack := __Container_VTable{
	push = proc(self: Container, x: int) { stack_push((^Stack)(self.data), x) },
	size = proc(self: Container) -> int { return stack_size((^Stack)(self.data)) },
}

__Container_from_Stack :: proc(p: ^Stack) -> Container { return {data = p, __vtable = &__Container_vtable_Stack} }

@(rodata)
__Destroy_vtable_Stack := __Destroy_VTable{
	destroy = proc(self: Destroy) { stack_destroy((^Stack)(self.data)) },
}

__Destroy_from_Stack :: proc(p: ^Stack) -> Destroy { return {data = p, __vtable = &__Destroy_vtable_Stack} }
