package main; import __vidar "vidar_runtime"

import "core:fmt"

main :: proc() {
	// each iteration's `i` is a fresh variable: by-value captures see 0, 1, 2
	values: [dynamic]__vidar.Closure(proc(rawptr) -> int)
	for i in 0..<3 {
		append(&values, __closure_0(i))
	}
	for f in values do fmt.print(f.call(f.env), "")
	fmt.println()

	// by-reference capture of a range variable refers to that iteration's copy
	for x in ([]int{10, 20, 30}) { x := x;
		inc := __closure_1(&x)
		inc.call(inc.env)
		inc.call(inc.env)
		fmt.print(x, "")
	}
	fmt.println()

	// one shared counter captured by reference from inside a while-style loop
	n := 0
	bump := __closure_2(&n)
	for n < 7 do bump.call(bump.env)
	fmt.println("n:", n)

	// C-style loop variable captured by reference is shared by all closures
	shared: [dynamic]__vidar.Closure(proc(rawptr) -> int)
	for j := 0; j < 3; j += 1 {
		append(&shared, __closure_3(&j))
	}
	for f in shared do fmt.print(f.call(f.env), "")
	fmt.println()
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0) -> __vidar.Closure(proc(rawptr) -> int) {
	__Env :: struct {
		i: T0,
	}
	return __vidar.Closure(proc(rawptr) -> int){
		call = proc(__env_raw: rawptr) -> int { __env := cast(^__Env)__env_raw; return __env.i },
		env = new_clone(__Env{__c0}),
	}
}

__closure_1 :: proc(__c0: $T0) -> __vidar.Closure(proc(rawptr)) {
	__Env :: struct {
		x: T0,
	}
	return __vidar.Closure(proc(rawptr)){
		call = proc(__env_raw: rawptr) { __env := cast(^__Env)__env_raw; __env.x^ += 1 },
		env = new_clone(__Env{__c0}),
	}
}

__closure_2 :: proc(__c0: $T0) -> __vidar.Closure(proc(rawptr)) {
	__Env :: struct {
		n: T0,
	}
	return __vidar.Closure(proc(rawptr)){
		call = proc(__env_raw: rawptr) { __env := cast(^__Env)__env_raw; __env.n^ += 2 },
		env = new_clone(__Env{__c0}),
	}
}

__closure_3 :: proc(__c0: $T0) -> __vidar.Closure(proc(rawptr) -> int) {
	__Env :: struct {
		j: T0,
	}
	return __vidar.Closure(proc(rawptr) -> int){
		call = proc(__env_raw: rawptr) -> int { __env := cast(^__Env)__env_raw; return __env.j^ },
		env = new_clone(__Env{__c0}),
	}
}
