package main; import __vidar "vidar_runtime"

import "core:encoding/json"
import "core:fmt"

Color :: enum { Red, Green, Blue }
Level :: enum u8 { Low = 1, High = 200 }

Point :: struct { x, y: f32 }

Item :: struct {
	id: int,
	name: string `json:"title"`,
	note: string `json:"note,omitempty"`,
	tags: []string `json:"tags,omitempty"`,
	secret: string `json:"-"`,
	count: int `json:",omitempty"`,
	color: Color,
	level: Level,
	ok: bool,
	r: rune,
	at: Point,
	path: [dynamic]Point,
	grid: [2][2]i8,
	big: u64,
	ratio: f64,
	text: string `fmt:"-" json:"body"`,
	inner: struct { a: int, b: string },
}

// not generated: a map field; encoding/json writes it
Tagged :: struct { m: map[string]int, n: int }

main :: proc() {
	path: [dynamic]Point
	defer delete(path)
	append(&path, Point{1, 2.5}, Point{-0.0, 1e21})
	tags := [2]string{"new", "q\"<&>\né"}
	items := [2]Item{
		{id = 1, name = "first", tags = tags[:], secret = "hidden", count = 0, color = .Blue, level = .High, ok = true, r = 'é', at = {0.1, 3}, path = path, grid = {{1, -2}, {3, 4}}, big = 18446744073709551615, ratio = 1.0 / 3.0, text = "t\tab", inner = {7, "in"}},
		{id = 2, name = "", note = "has a note", r = '"', level = Level(7)},
	}
	m := json.marshal
	check :: proc(got, want: []byte, gerr, werr: json.Marshal_Error) {
		__fmt_0(string(got) == string(want) && gerr == werr ? "same" : "DIFFERENT", string(got))
	}
	for it in items {
		got, gerr := __json_marshal_main_Item(it)
		want, werr := m(it)
		check(got, want, gerr, werr)
		delete(got)
		delete(want)
	}
	got, gerr := __json_marshal_arr2_main_Item(items[:])
	want, werr := m(items[:])
	check(got, want, gerr, werr)
	delete(got)
	delete(want)
	got2, gerr2 := json.marshal(Color.Green)
	want2, werr2 := m(Color.Green)
	check(got2, want2, gerr2, werr2)
	delete(got2)
	delete(want2)
	tm: Tagged
	got3, gerr3 := json.marshal(tm)
	want3, werr3 := m(tm)
	check(got3, want3, gerr3, werr3)
	delete(got3)
	delete(want3)
}

// ---- generated by vidar ----

// fmt.println
__fmt_0 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

@(private="file")
// json.marshal of Item, written out: encoding/json's bytes
__json_marshal_main_Item :: proc(x: $T, allocator := context.allocator) -> (data: []byte, err: json.Marshal_Error) {
	when T == Item {
		b := __vidar.builder(allocator)
		__jsonw_main_Item(__vidar.sb_writer(&b), x)
		return b.buf[:], nil
	} else {
		return json.marshal(x, allocator = allocator)
	}
}

@(private="file")
__jsonw_main_Item :: proc(w: __vidar.Writer, x: Item) {
	__vidar.w_str(w, "{")
	first := true
	{
		if !first do __vidar.w_str(w, ",")
		first = false
		__vidar.w_str(w, "\"id\":")
		__vidar.w_d(w, x.id)
	}
	{
		if !first do __vidar.w_str(w, ",")
		first = false
		__vidar.w_str(w, "\"title\":")
		__vidar.w_json_str(w, x.name)
	}
	if len(x.note) != 0 {
		if !first do __vidar.w_str(w, ",")
		first = false
		__vidar.w_str(w, "\"note\":")
		__vidar.w_json_str(w, x.note)
	}
	if len(x.tags) != 0 {
		if !first do __vidar.w_str(w, ",")
		first = false
		__vidar.w_str(w, "\"tags\":")
		__jsonw_sl_string(w, x.tags)
	}
	{
		if !first do __vidar.w_str(w, ",")
		first = false
		__vidar.w_str(w, "\"count\":")
		__vidar.w_d(w, x.count)
	}
	{
		if !first do __vidar.w_str(w, ",")
		first = false
		__vidar.w_str(w, "\"color\":")
		__vidar.w_d(w, i64(x.color))
	}
	{
		if !first do __vidar.w_str(w, ",")
		first = false
		__vidar.w_str(w, "\"level\":")
		__vidar.w_d(w, u64(x.level))
	}
	{
		if !first do __vidar.w_str(w, ",")
		first = false
		__vidar.w_str(w, "\"ok\":")
		__vidar.w_t(w, x.ok)
	}
	{
		if !first do __vidar.w_str(w, ",")
		first = false
		__vidar.w_str(w, "\"r\":")
		__vidar.w_json_rune(w, x.r)
	}
	{
		if !first do __vidar.w_str(w, ",")
		first = false
		__vidar.w_str(w, "\"at\":")
		__jsonw_main_Point(w, x.at)
	}
	{
		if !first do __vidar.w_str(w, ",")
		first = false
		__vidar.w_str(w, "\"path\":")
		__jsonw_dyn_main_Point(w, x.path)
	}
	{
		if !first do __vidar.w_str(w, ",")
		first = false
		__vidar.w_str(w, "\"grid\":")
		__jsonw_arr2_arr2_i8(w, x.grid)
	}
	{
		if !first do __vidar.w_str(w, ",")
		first = false
		__vidar.w_str(w, "\"big\":")
		__vidar.w_d(w, x.big)
	}
	{
		if !first do __vidar.w_str(w, ",")
		first = false
		__vidar.w_str(w, "\"ratio\":")
		__vidar.w_json_float(w, x.ratio)
	}
	{
		if !first do __vidar.w_str(w, ",")
		first = false
		__vidar.w_str(w, "\"body\":")
		__vidar.w_json_str(w, x.text)
	}
	{
		if !first do __vidar.w_str(w, ",")
		first = false
		__vidar.w_str(w, "\"inner\":")
		__vidar.w_str(w, "{")
		__vidar.w_str(w, "\"a\":")
		__vidar.w_d(w, x.inner.a)
		__vidar.w_str(w, ",\"b\":")
		__vidar.w_json_str(w, x.inner.b)
		__vidar.w_str(w, "}")
	}
	__vidar.w_str(w, "}")
}

@(private="file")
__jsonw_sl_string :: proc(w: __vidar.Writer, x: []string) {
	__vidar.w_str(w, "[")
	for e, i in x {
		if i > 0 do __vidar.w_str(w, ",")
		__vidar.w_json_str(w, e)
	}
	__vidar.w_str(w, "]")
}

@(private="file")
__jsonw_main_Point :: proc(w: __vidar.Writer, x: Point) {
	__vidar.w_str(w, "{")
	__vidar.w_str(w, "\"x\":")
	__vidar.w_json_float(w, x.x)
	__vidar.w_str(w, ",\"y\":")
	__vidar.w_json_float(w, x.y)
	__vidar.w_str(w, "}")
}

@(private="file")
__jsonw_dyn_main_Point :: proc(w: __vidar.Writer, x: [dynamic]Point) {
	__vidar.w_str(w, "[")
	for e, i in x {
		if i > 0 do __vidar.w_str(w, ",")
		__jsonw_main_Point(w, e)
	}
	__vidar.w_str(w, "]")
}

@(private="file")
__jsonw_arr2_arr2_i8 :: proc(w: __vidar.Writer, x: [2][2]i8) {
	__vidar.w_str(w, "[")
	for e, i in x {
		if i > 0 do __vidar.w_str(w, ",")
		__jsonw_arr2_i8(w, e)
	}
	__vidar.w_str(w, "]")
}

@(private="file")
__jsonw_arr2_i8 :: proc(w: __vidar.Writer, x: [2]i8) {
	__vidar.w_str(w, "[")
	for e, i in x {
		if i > 0 do __vidar.w_str(w, ",")
		__vidar.w_d(w, e)
	}
	__vidar.w_str(w, "]")
}

@(private="file")
// json.marshal of [2]Item, written out: encoding/json's bytes
__json_marshal_arr2_main_Item :: proc(x: $T, allocator := context.allocator) -> (data: []byte, err: json.Marshal_Error) {
	when T == [2]Item {
		b := __vidar.builder(allocator)
		__jsonw_arr2_main_Item(__vidar.sb_writer(&b), x)
		return b.buf[:], nil
	} else {
		return json.marshal(x, allocator = allocator)
	}
}

@(private="file")
__jsonw_arr2_main_Item :: proc(w: __vidar.Writer, x: [2]Item) {
	__vidar.w_str(w, "[")
	for e, i in x {
		if i > 0 do __vidar.w_str(w, ",")
		__jsonw_main_Item(w, e)
	}
	__vidar.w_str(w, "]")
}
