package game_ui; import __vidar "../vidar_runtime"

import "core:fmt"

import util "../util"

// game imports ui, and ui imports game: a cycle plain Odin rejects.
// vidar merges the two into one Odin package and keeps their names apart.

game__Entity :: struct { data: rawptr, __vtable: ^__game__Entity_VTable }

game__name :: proc{__game__Entity_name, game__sprite_name, ui__button_name}
game__draw :: proc{__game__Entity_draw, game__sprite_draw, ui__button_draw}

game__Error :: enum { None, Empty_Label, Too_Many }

game__World :: struct {
	entities: [dynamic]game__Entity,
	frame:    int,
	on_frame: [dynamic]__vidar.Closure(proc(rawptr, int)),
}

game__Sprite :: struct { label: string }

game__sprite_name :: proc(s: ^game__Sprite) -> string { return s.label }
game__sprite_draw :: proc(s: ^game__Sprite) -> string { return fmt.tprintf("<%s>", s.label) }



// log :: proc!(msg: Expr(string)) -> Stmt — comptime, game.vidar:30

game__make_world :: proc() -> game__World {
	w: game__World
	append(&w.entities, ui__make_button("start"))
	return w
}

game__spawn :: proc(w: ^game__World, label: string) -> game__Error {
	if label == "" do return .Empty_Label
	if len(w.entities) >= 3 do return .Too_Many
	append(&w.entities, __game__Entity_from(new_clone(game__Sprite{label})))
	// log!(fmt.tprintf("spawned %s", label)) — game.vidar:44
	if false { __macro_typecheck: string = fmt.tprintf("spawned %s", label); _ = __macro_typecheck }
	fmt.println("[game]", fmt.tprintf("spawned %s", label))
	return .None
}

game__run :: proc(w: ^game__World, frames: int) -> string {
	ticks := 0
	append(&w.on_frame, __closure_0(&ticks))
	append(&w.on_frame, util.every(2, __vidar.Closure(proc(rawptr, int)){call = proc(__env_raw: rawptr, frame: int) { fmt.println("[game] even frame", frame) }, env = nil}))
	for _ in 0..<frames {
		w.frame += 1
		for cb in w.on_frame do cb.call(cb.env, w.frame)
	}
	return fmt.tprintf("%d ticks, screen: %s", ticks, ui__render(w))
}

// ---- generated by vidar ----

__game__Entity_VTable :: struct {
	name: proc(self: game__Entity) -> string,
	draw: proc(self: game__Entity) -> string,
}

__game__Entity_name :: proc(e: game__Entity) -> string {
	if e.__vtable == &__game__Entity_vtable_game_Sprite { return game__sprite_name(auto_cast e.data) }
	if e.__vtable == &__game__Entity_vtable_ui_Button { return ui__button_name(auto_cast e.data) }
	return e.__vtable.name(e)
}

__game__Entity_draw :: proc(e: game__Entity) -> string {
	if e.__vtable == &__game__Entity_vtable_game_Sprite { return game__sprite_draw(auto_cast e.data) }
	if e.__vtable == &__game__Entity_vtable_ui_Button { return ui__button_draw(auto_cast e.data) }
	return e.__vtable.draw(e)
}

__game__Entity_identity :: #force_inline proc(v: game__Entity) -> game__Entity { return v }

__game__Entity_from :: proc{__game__Entity_from_game_Sprite, __game__Entity_from_ui_Button, __game__Entity_identity}

@(rodata)
__game__Entity_vtable_game_Sprite := __game__Entity_VTable{
	name = proc(self: game__Entity) -> string { return game__sprite_name((^game__Sprite)(self.data)) },
	draw = proc(self: game__Entity) -> string { return game__sprite_draw((^game__Sprite)(self.data)) },
}

__game__Entity_from_game_Sprite :: proc(p: ^game__Sprite) -> game__Entity { return {data = p, __vtable = &__game__Entity_vtable_game_Sprite} }

__closure_0 :: proc(__c0: $T0) -> __vidar.Closure(proc(rawptr, int)) {
	__Env :: struct {
		ticks: T0,
	}
	return __vidar.Closure(proc(rawptr, int)){
		call = proc(__env_raw: rawptr, frame: int) { __env := cast(^__Env)__env_raw; __env.ticks^ += 1 },
		env = new_clone(__Env{__c0}),
	}
}
