package game_ui

import "core:fmt"
import "core:strings"


ui__Button :: struct { text: string }

// Implementing game's interface from ui works because both are in the same cycle.
ui__button_name :: proc(b: ^ui__Button) -> string { return b.text }
ui__button_draw :: proc(b: ^ui__Button) -> string { return fmt.tprintf("[%s]", b.text) }



ui__make_button :: proc(text: string) -> game__Entity {
	return __game__Entity_from(new_clone(ui__Button{text = text}))
}

ui__render :: proc(w: ^game__World) -> string {
	parts: [dynamic]string
	for e in w.entities do append(&parts, game__draw(e))
	// game.log!(...) — ui.vidar:22
	if false { __macro_typecheck: string = fmt.tprintf("rendered %d entities at frame %d", len(w.entities), w.frame); _ = __macro_typecheck }
	fmt.println("[game]", fmt.tprintf("rendered %d entities at frame %d", len(w.entities), w.frame))
	return strings.join(parts[:], " ")
}

// ---- generated by vidar ----

@(rodata)
__game__Entity_vtable_ui_Button := __game__Entity_VTable{
	name = proc(self: game__Entity) -> string { return ui__button_name((^ui__Button)(self.data)) },
	draw = proc(self: game__Entity) -> string { return ui__button_draw((^ui__Button)(self.data)) },
}

__game__Entity_from_ui_Button :: proc(p: ^ui__Button) -> game__Entity { return {data = p, __vtable = &__game__Entity_vtable_ui_Button} }
