package right; import __vidar "../vidar_runtime"

import b "../base"

make :: proc() -> b.Op {
	inner := b.adder(100)
	return __closure_0(inner)
}

name :: proc() -> string { return "right/" + b.NAME }

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0) -> __vidar.Closure(proc(rawptr, int) -> int) {
	__Env :: struct {
		inner: T0,
	}
	return __vidar.Closure(proc(rawptr, int) -> int){
		call = proc(__env_raw: rawptr, x: int) -> int { __env := cast(^__Env)__env_raw; return __env.inner.call(__env.inner.env, x) * 2 },
		env = new_clone(__Env{__c0}),
	}
}
