package right; import __vidar "../vidar_runtime"

import b "../base"

make :: proc() -> b.Op {
	inner := new_clone(b.adder(100))
	return __closure_0(inner)
}

name :: proc() -> string { return "right/" + b.NAME }

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int) -> int) {
	__Caps :: struct {
		inner: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at right.vidar:7: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int) -> int){
		call = proc(__env_raw: __vidar.Env, x: int) -> int { __env := transmute(__Env)__env_raw; return __call_closure_0(__env.inner^, x) * 2 },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__call_closure_0 :: #force_inline proc(c: __vidar.Closure(proc(__vidar.Env, int) -> int), p0: int) -> int {
	return c.call(c.env, p0)
}
