package model_view



// observers are implemented in view, which imports model back
model__Observer :: struct { data: rawptr, __vtable: ^__model__Observer_VTable }

model__changed :: proc{__model__Observer_changed, view__label_changed}

model__Store :: struct {
	value:     int,
	observers: [dynamic]model__Observer,
	log:       [dynamic]string,
}

model__new_store :: proc() -> model__Store {
	s: model__Store
	append(&s.observers, view__label("first"), view__label("second"))
	return s
}

// ---- generated by vidar ----

__model__Observer_VTable :: struct {
	changed: proc(self: model__Observer, value: int) -> string,
}

__model__Observer_changed :: proc(o: model__Observer, value: int) -> string {
	if o.__vtable == &__model__Observer_vtable_view_Label { return view__label_changed(auto_cast o.data, value) }
	return o.__vtable.changed(o, value)
}

__model__Observer_identity :: #force_inline proc(v: model__Observer) -> model__Observer { return v }

__model__Observer_from :: proc{__model__Observer_from_view_Label, __model__Observer_identity}
