package model_view

import "core:fmt"


view__Label :: struct { name: string }

view__label_changed :: proc(l: ^view__Label, value: int) -> string { return fmt.tprintf("%s saw %d", l.name, value) }



view__label :: proc(name: string) -> model__Observer { return __model__Observer_from(new_clone(view__Label{name})) }

// ---- generated by vidar ----

@(rodata)
__model__Observer_vtable_view_Label := __model__Observer_VTable{
	changed = proc(self: model__Observer, value: int) -> string { return view__label_changed((^view__Label)(self.data), value) },
}

__model__Observer_from_view_Label :: proc(p: ^view__Label) -> model__Observer { return {data = p, __vtable = &__model__Observer_vtable_view_Label} }
