package main; import __vidar "vidar_runtime"

import "core:fmt"

counter := 0
SHIFT :: 3

// loops over integers only: -opt makes it a table
collatz :: #force_inline proc(b: u8) -> int { return __collatz_table[b] }









// a default case written first still runs last
bucket :: #force_inline proc(b: u8) -> u8 { return __bucket_table[b] }












parity :: #force_inline proc(x: i8) -> bool { return __parity_table[int(x) + 128] }

odd :: proc(n: int) -> bool {
	m := n
	for m >= 2 || m <= -2 do m -= 2 if m > 0 else -2
	return m != 0
}

// too cheap to beat a load
twice :: proc(b: u8) -> u8 { return b * 2 }

// reads a variable
noisy :: proc(b: u8) -> int {
	total := 0
	for i in 0..<int(b) do total += counter
	return total
}

// floats aren't run at compile time exactly as compiled
halves :: proc(b: u8) -> int {
	f := f32(b)
	for f > 1 do f /= 3
	return int(f * 100)
}


kept :: proc(b: u8) -> int {
	n := 0
	for i in 0..<int(b) do n += i
	return n
}

// radius bounds the loop and calls pass two constants: a copy for each
blur :: proc(xs: []int, radius: int) -> int {
	s := 0
	for i in radius..<len(xs) - radius do for k in -radius..=radius do s += xs[i + k]
	return s
}

// every call passes the same constant: left to LLVM
sum_to :: proc(n: int) -> int {
	s := 0
	for i in 0..<n do s += i
	return s
}

// the divisor is a constant inside a loop

div_all :: proc(xs: []int, d: int) -> int {
	s := 0
	for x in xs do s += x / d
	return s
}

step :: proc(xs: []int, d: int) -> int {
	s := 0
	for x in xs do s += x / d
	return s
}

main :: proc() {
	counter = 2
	r := 2
	xs := []int{5, 1, 4, 1, 5, 9, 2, 6, 5, 3}
	__fmt_0(collatz(0), collatz(26), collatz(255))
	__fmt_0(bucket(3), bucket(7), bucket(200))
	__fmt_1(parity(-7), parity(12), twice(200), noisy(3), halves(200), kept(10))
	__fmt_0(blur__radius(xs, 1), blur__radius(xs, 2), blur(xs, r))
	__fmt_2(sum_to(10), sum_to(10))
	__fmt_3(div_all(xs, 2), div_all(xs, 3), step__d(xs, 2), step__d(xs, 3))
}

// ---- generated by vidar ----

// collatz(x) for every x, computed by vidar
@(rodata)
__collatz_table := [256]int{
	0, 1, 7, 2, 5, 8, 16, 3,
	19, 6, 14, 9, 9, 17, 17, 4,
	12, 20, 20, 7, 7, 15, 15, 10,
	23, 10, 111, 18, 18, 18, 106, 5,
	26, 13, 13, 21, 21, 21, 34, 8,
	109, 8, 29, 16, 16, 16, 104, 11,
	24, 24, 24, 11, 11, 112, 112, 19,
	32, 19, 32, 19, 19, 107, 107, 6,
	27, 27, 27, 14, 14, 14, 102, 22,
	115, 22, 14, 22, 22, 35, 35, 9,
	22, 110, 110, 9, 9, 30, 30, 17,
	30, 17, 92, 17, 17, 105, 105, 12,
	118, 25, 25, 25, 25, 25, 87, 12,
	38, 12, 100, 113, 113, 113, 69, 20,
	12, 33, 33, 20, 20, 33, 33, 20,
	95, 20, 46, 108, 108, 108, 46, 7,
	121, 28, 28, 28, 28, 28, 41, 15,
	90, 15, 41, 15, 15, 103, 103, 23,
	116, 116, 116, 23, 23, 15, 15, 23,
	36, 23, 85, 36, 36, 36, 54, 10,
	98, 23, 23, 111, 111, 111, 67, 10,
	49, 10, 124, 31, 31, 31, 80, 18,
	31, 31, 31, 18, 18, 93, 93, 18,
	44, 18, 44, 106, 106, 106, 44, 13,
	119, 119, 119, 26, 26, 26, 119, 26,
	18, 26, 39, 26, 26, 88, 88, 13,
	39, 39, 39, 13, 13, 101, 101, 114,
	26, 114, 52, 114, 114, 70, 70, 21,
	52, 13, 13, 34, 34, 34, 127, 21,
	83, 21, 127, 34, 34, 34, 52, 21,
	21, 96, 96, 21, 21, 47, 47, 109,
	47, 109, 65, 109, 109, 47, 47, 8,
}

// bucket(x) for every x, computed by vidar
@(rodata)
__bucket_table := [256]u8{
	0, 9, 18, 20, 32, 41, 50, 52,
	64, 73, 82, 84, 96, 105, 114, 116,
	128, 137, 146, 148, 160, 169, 178, 180,
	192, 201, 210, 212, 224, 233, 242, 244,
	0, 9, 18, 20, 32, 41, 50, 52,
	64, 73, 82, 84, 96, 105, 114, 116,
	128, 137, 146, 148, 160, 169, 178, 180,
	192, 201, 210, 212, 224, 233, 242, 244,
	0, 9, 18, 20, 32, 41, 50, 52,
	64, 73, 82, 84, 96, 105, 114, 116,
	128, 137, 146, 148, 160, 169, 178, 180,
	192, 201, 210, 212, 224, 233, 242, 244,
	0, 9, 18, 20, 32, 41, 50, 52,
	64, 73, 82, 84, 96, 105, 114, 116,
	128, 137, 146, 148, 160, 169, 178, 180,
	192, 201, 210, 212, 224, 233, 242, 244,
	0, 9, 18, 20, 32, 41, 50, 52,
	64, 73, 82, 84, 96, 105, 114, 116,
	128, 137, 146, 148, 160, 169, 178, 180,
	192, 201, 210, 212, 224, 233, 242, 244,
	0, 9, 18, 20, 32, 41, 50, 52,
	64, 73, 82, 84, 96, 105, 114, 116,
	128, 137, 146, 148, 160, 169, 178, 180,
	192, 201, 210, 212, 224, 233, 242, 244,
	0, 9, 18, 20, 32, 41, 50, 52,
	64, 73, 82, 84, 96, 105, 114, 116,
	128, 137, 146, 148, 160, 169, 178, 180,
	192, 201, 210, 212, 224, 233, 242, 244,
	0, 9, 18, 20, 32, 41, 50, 52,
	64, 73, 82, 84, 96, 105, 114, 116,
	128, 137, 146, 148, 160, 169, 178, 180,
	192, 201, 210, 212, 224, 233, 242, 244,
}

// parity(x) for every x, computed by vidar
@(rodata)
__parity_table := [256]bool{
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
	false, true, false, true, false, true, false, true,
}

// blur with radius known at compile time
blur__radius :: proc(xs: []int, $radius: int) -> int {
	s := 0
	for i in radius..<len(xs) - radius do for k in -radius..=radius do s += xs[i + k]
	return s
}

// step with d known at compile time
step__d :: proc(xs: []int, $d: int) -> int {
	s := 0
	for x in xs do s += x / d
	return s
}

// fmt.println
__fmt_0 :: proc(a0: $T0, a1: $T1, a2: $T2) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a2)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_1 :: proc(a0: $T0, a1: $T1, a2: $T2, a3: $T3, a4: $T4, a5: $T5) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a2)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a3)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a4)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a5)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_2 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_3 :: proc(a0: $T0, a1: $T1, a2: $T2, a3: $T3) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a2)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a3)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}
