package main; import __vidar "vidar_runtime"

import "core:fmt"
import "core:strings"

// `x := { name = value, ... }` declares a struct type on the spot. The field
// types are inferred from the values; untyped constants take their default types.

Word :: struct { text: string, count: int }

// A written-out anonymous struct type is the same type as a matching literal.
print_range :: proc(r: struct { lo: int, hi: int }) {
	fmt.printf("range %d..%d\n", r.lo, r.hi)
}

main :: proc() {
	text := "the slime and the wizard and the slime"

	// group related locals without declaring a named type
	
		__anon1_words := 0;
		__anon1_longest := "";
		__anon1_first := Word{}; stats := struct { words: type_of(__anon1_words), longest: type_of(__anon1_longest), first: type_of(__anon1_first) }{words = __anon1_words, longest = __anon1_longest, first = __anon1_first}

	for w in strings.fields(text, context.temp_allocator) {
		stats.words += 1
		if len(w) > len(stats.longest) do stats.longest = w
		if stats.first.text == "" do stats.first = {w, 1}
	}
	fmt.println(stats)

	// nesting, and fields of any type: here a closure that captures the record by reference
	__anon2_size_w := 800; __anon2_size_h := 600; __anon2_title := "vidar"; __anon2_resized := 0; window := struct { size: struct { w: type_of(__anon2_size_w), h: type_of(__anon2_size_h) }, title: type_of(__anon2_title), resized: type_of(__anon2_resized) }{size = {w = __anon2_size_w, h = __anon2_size_h}, title = __anon2_title, resized = __anon2_resized}
	resize := __closure_0(&window)
	resize.call(resize.env, 1024, 768)
	fmt.println(window.title, window.size.w, "x", window.size.h, "resized", window.resized, "time(s)")

	// literals with the same field names and types have the same type
	__anon3_lo := 0; __anon3_hi := 10; bounds := struct { lo: type_of(__anon3_lo), hi: type_of(__anon3_hi) }{lo = __anon3_lo, hi = __anon3_hi}
	__anon4_lo := 2; __anon4_hi := 8; clamped := struct { lo: type_of(__anon4_lo), hi: type_of(__anon4_hi) }{lo = __anon4_lo, hi = __anon4_hi}
	bounds = clamped
	print_range(bounds)

	// %T shows the generated type
	fmt.printf("%T\n", window)
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int, int)) {
	__Caps :: struct {
		window: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:34: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int, int)){
		call = proc(__env_raw: __vidar.Env, w, h: int) { __env := transmute(__Env)__env_raw;
		__env.window^.size = {w, h}
		__env.window^.resized += 1
	},
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}
