package main; import __vidar "vidar_runtime"

import "core:fmt"

Animal :: struct { data: rawptr, __vtable: ^__Animal_VTable }

speak  :: proc{__Animal_speak, dog_speak, bird_speak}
rename :: proc{__Animal_rename, dog_rename, bird_rename}
legs   :: proc{__Animal_legs, dog_legs, bird_legs}

Dog :: struct { name: string }
Bird :: struct { name: string, can_fly: bool }

dog_speak :: proc(d: ^Dog) -> string { return fmt.tprintf("%s: woof", d.name) }
dog_rename :: proc(d: ^Dog, name: string) { d.name = name }
dog_legs :: proc(d: ^Dog) -> int { return 4 }

bird_speak :: proc(b: ^Bird) -> string { return fmt.tprintf("%s: tweet", b.name) }
bird_rename :: proc(b: ^Bird, name: string) { b.name = name }
bird_legs :: proc(b: ^Bird) -> int { return 2 }









// interfaces in struct fields, parameters and return values
Zoo :: struct { star: Animal, all: [dynamic]Animal }

pick :: proc(z: ^Zoo, i: int) -> Animal { return z.all[i] }

count_legs :: proc(animals: ..Animal) -> (n: int) {
	for a in animals do n += legs(a)
	return
}

main :: proc() {
	rex := Dog{"rex"}
	tweety := Bird{"tweety", true}
	z := Zoo{star = __Animal_from(&rex)}
	append(&z.all, __Animal_from(&rex), __Animal_from(&tweety))

	rename(z.star, "max")
	fmt.println(rex.name, "/", speak(z.all[0]))

	for a in z.all do fmt.println(speak(a))
	fmt.println("legs:", count_legs(..z.all[:]))
	fmt.println("picked:", speak(pick(&z, 1)))

	// the same function value works for any Animal
	shout := __vidar.Closure(proc(rawptr, Animal) -> string){call = proc(__env_raw: rawptr, a: Animal) -> string { return speak(a) }, env = nil}
	fmt.println(shout.call(shout.env, z.star), shout.call(shout.env, __Animal_from(&rex)))

	// static calls on concrete values
	fmt.println("static:", speak(&tweety), legs(&rex))
}

// ---- generated by vidar ----

__Animal_VTable :: struct {
	speak: proc(self: Animal) -> string,
	rename: proc(self: Animal, name: string),
	legs: proc(self: Animal) -> int,
}

__Animal_speak :: proc(a: Animal) -> string {
	if a.__vtable == &__Animal_vtable_Dog { return dog_speak(auto_cast a.data) }
	if a.__vtable == &__Animal_vtable_Bird { return bird_speak(auto_cast a.data) }
	return a.__vtable.speak(a)
}

__Animal_rename :: proc(a: Animal, name: string) {
	if a.__vtable == &__Animal_vtable_Dog { dog_rename(auto_cast a.data, name); return }
	if a.__vtable == &__Animal_vtable_Bird { bird_rename(auto_cast a.data, name); return }
	a.__vtable.rename(a, name)
}

__Animal_legs :: proc(a: Animal) -> int {
	if a.__vtable == &__Animal_vtable_Dog { return dog_legs(auto_cast a.data) }
	if a.__vtable == &__Animal_vtable_Bird { return bird_legs(auto_cast a.data) }
	return a.__vtable.legs(a)
}

__Animal_identity :: #force_inline proc(v: Animal) -> Animal { return v }

__Animal_from :: proc{__Animal_from_Dog, __Animal_from_Bird, __Animal_identity}

@(rodata)
__Animal_vtable_Dog := __Animal_VTable{
	speak = proc(self: Animal) -> string { return dog_speak((^Dog)(self.data)) },
	rename = proc(self: Animal, name: string) { dog_rename((^Dog)(self.data), name) },
	legs = proc(self: Animal) -> int { return dog_legs((^Dog)(self.data)) },
}

__Animal_from_Dog :: proc(p: ^Dog) -> Animal { return {data = p, __vtable = &__Animal_vtable_Dog} }

@(rodata)
__Animal_vtable_Bird := __Animal_VTable{
	speak = proc(self: Animal) -> string { return bird_speak((^Bird)(self.data)) },
	rename = proc(self: Animal, name: string) { bird_rename((^Bird)(self.data), name) },
	legs = proc(self: Animal) -> int { return bird_legs((^Bird)(self.data)) },
}

__Animal_from_Bird :: proc(p: ^Bird) -> Animal { return {data = p, __vtable = &__Animal_vtable_Bird} }
