package main; import __vidar "vidar_runtime"

import "core:fmt"
import sched "vidar_sched"

// `&x` closures passed to procs that don't let them escape: none of these is an error

run :: proc(f: __vidar.Closure(proc(__vidar.Env) -> int)) -> int { __f_call := f.call; return __f_call(f.env) }
twice :: proc(f: __vidar.Closure(proc(__vidar.Env) -> int)) -> int { return run(f) + run(f) }
id :: proc(f: __vidar.Closure(proc(__vidar.Env) -> int)) -> __vidar.Closure(proc(__vidar.Env) -> int) { return f }

count :: proc() -> int {
	n := 0
	inc := __closure_0(&n)
	// through two procs that only call it
	a := twice(inc)
	// returned by `id`, but only called here
	b := __call_closure_0(id(inc))
	g := id(inc)
	c := g.call(g.env)
	// a proc constant local to this one
	thrice :: proc(f: __vidar.Closure(proc(__vidar.Env) -> int)) -> int { __f_call := f.call; return __f_call(f.env) + __f_call(f.env) + __f_call(f.env) }
	d := thrice(inc)
	return a * 1000 + b * 100 + c * 10 + d
}

main :: proc() {
	fmt.println(count())
	// main's frame lasts until the program exits, so its goroutines may hold &x
	total := 0
	wg: sched.Wait_Group
	sched.add(&wg, 3)
	for i in 1..=3 do sched.go(__closure_1(i, &total, &wg))
	sched.wait(&wg)
	fmt.println(total)
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env) -> int) {
	__Caps :: struct {
		n: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:14: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env) -> int){
		call = proc(__env_raw: __vidar.Env) -> int { __env := transmute(__Env)__env_raw; __env.n^ += 1; return __env.n^ },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_1 :: proc(__c0: $T0, __c1: $T1, __c2: $T2) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		i: T0,
		total: T1,
		wg: T2,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:33: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw;
		__env.total^ += __env.i
		sched.done(&__env.wg^)
	},
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1, __c2}},
	}
}

__call_closure_0 :: #force_inline proc(c: __vidar.Closure(proc(__vidar.Env) -> int)) -> int {
	return c.call(c.env)
}
