package main; import __vidar "vidar_runtime"

import "core:fmt"

Particle :: struct {
	x, y, vx, vy: f32,
	id:           int,
	alive:        bool,
}

Pair :: struct { a, b: int }

// loops here touch only some of the 6 fields: -opt makes these #soa
converted :: proc() {
	ps := make(#soa[dynamic]Particle)
	defer delete(ps)
	reserve(&ps, len(ps) + 10)
	for i in 0..<10 do append(&ps, Particle{vx = f32(i), vy = 1, id = i, alive = i % 3 != 0})
	reserve(&ps, 16)
	for _ in 0..<3 {
		for &p in ps {
			p.x += p.vx
			p.y += p.vy
		}
	}
	first := ps[0]
	ps[1] = first
	ps[2].alive = ps[2].id > 1 && ps[0] == first
	sum: f32
	alive := 0
	for p, i in ps {
		sum += p.x + p.y
		if p.alive do alive += i
	}
	__fmt_0(len(ps), cap(ps) >= 16, sum, alive, ps[3])

	grid: #soa[8]Particle
	for &g, i in grid do g.vx = f32(i) * 0.5
	for i in 0..<len(grid) do #no_bounds_check grid[i].x += grid[i].vx
	__fmt_1(grid[7].x, grid[3])

	__buf_buf: #soa[5]Particle; buf := __buf_buf[:]
	/* delete(buf): buf is on the stack */
	for i := 0; i < len(buf); i += 1 do #no_bounds_check buf[i].id = i * i
	total := 0
	for b in buf do total += b.id
	__fmt_2(total, buf[4])
	clear(&ps)
	__fmt_3(len(ps))

	typed: #soa[dynamic]Particle = make(#soa[dynamic]Particle, 0, 4)
	defer delete(typed)
	reserve(&typed, len(typed) + 4)
	for i in 0..<4 do append(&typed, Particle{x = f32(i), id = i})
	for &p in typed do p.x *= 3
	__fmt_4(len(typed), typed[3].x, typed[1])

	typed_slice: #soa[]Particle = make(#soa[]Particle, 2)
	defer delete(typed_slice)
	for &p in typed_slice do p.y += 1
	__fmt_5(typed_slice[1].y)
}

sum_x :: proc(ps: []Particle) -> (s: f32) {
	for p in ps do s += p.x
	return
}

make_some :: proc() -> [dynamic]Particle {
	out: [dynamic]Particle
	reserve(&out, len(out) + 3)
	for i in 0..<3 do append(&out, Particle{x = f32(i)})
	for &p in out do p.x *= 2
	return out
}

// each of these keeps its layout, and -opt-report says why
kept :: proc() {
	sliced := make([]Particle, 4)
	defer delete(sliced)
	for &p in sliced do p.x = 1
	__fmt_6(sum_x(sliced[:]))

	passed := make([]Particle, 4)
	defer delete(passed)
	for &p in passed do p.x = 2
	__fmt_7(sum_x(passed))

	addressed: [4]Particle
	for i in 0..<len(addressed) do #no_bounds_check addressed[i].x = f32(i)
	q := &addressed[2]
	q.x = 9
	__fmt_8(addressed[2].x)

	pairs: [4]Pair
	for &p, i in pairs do p.a = i
	__fmt_9(pairs[3])

	whole: [dynamic]Particle
	defer delete(whole)
	append(&whole, Particle{id = 7})
	for p in whole do __fmt_10(p)

	captured: [dynamic]Particle
	defer delete(captured)
	append(&captured, Particle{id = 1})
	for &p in captured do p.y = 3
	count := __closure_0(&captured)
	__fmt_11(count.call(count.env))

	by_ref := make([dynamic]Particle)
	defer delete(by_ref)
	append(&by_ref, Particle{x = 5})
	for &p in by_ref {
		p.x += 1
		copy := p
		__fmt_12(copy.x)
	}

	returned: [dynamic]Particle = make_some()
	defer delete(returned)
	__fmt_13(returned[2].x)

	reassigned: [dynamic]Particle
	reserve(&reassigned, len(reassigned) + 2)
	for i in 0..<2 do append(&reassigned, Particle{id = i})
	for &p in reassigned do p.id += 1
	delete(reassigned)
	reassigned = make([dynamic]Particle)
	__fmt_14(len(reassigned))
	delete(reassigned)
}

main :: proc() {
	converted()
	kept()
}

// ---- generated by vidar ----

// fmt.println
__fmt_0 :: proc(a0: $T0, a1: $T1, a2: $T2, a3: $T3, a4: $T4) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "dynamic: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a2)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a3)
	n += __vidar.w_str(w, " ")
	when T4 == Particle { n += __print_main_Particle(w, a4) } else { n += __vidar.w_spec(w, a4, "%v") }
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_1 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "fixed: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	when T1 == Particle { n += __print_main_Particle(w, a1) } else { n += __vidar.w_spec(w, a1, "%v") }
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_2 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "slice: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	when T1 == Particle { n += __print_main_Particle(w, a1) } else { n += __vidar.w_spec(w, a1, "%v") }
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_3 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "cleared: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_4 :: proc(a0: $T0, a1: $T1, a2: $T2) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "typed: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, " ")
	when T2 == Particle { n += __print_main_Particle(w, a2) } else { n += __vidar.w_spec(w, a2, "%v") }
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_5 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "typed slice: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_6 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "sliced: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_7 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "passed: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_8 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "addressed: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_9 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "narrow: ")
	when T0 == Pair { n += __print_main_Pair(w, a0) } else { n += __vidar.w_spec(w, a0, "%v") }
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_10 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "whole: ")
	when T0 == Particle { n += __print_main_Particle(w, a0) } else { n += __vidar.w_spec(w, a0, "%v") }
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

__closure_0 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env) -> int) {
	__Caps :: struct {
		captured: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:105: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env) -> int){
		call = proc(__env_raw: __vidar.Env) -> int { __env := transmute(__Env)__env_raw; return len(__env.captured^) },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

// fmt.println
__fmt_11 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "captured: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_12 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "by_ref: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_13 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "returned: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_14 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "reassigned: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt's %v for the types printed here, written out
__print_main_Particle :: proc(w: __vidar.Writer, x: Particle) -> (n: int) {
	n += __vidar.w_str(w, "Particle{")
	n += __vidar.w_str(w, "x = ")
	n += __vidar.w_float(w, x.x)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "y = ")
	n += __vidar.w_float(w, x.y)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "vx = ")
	n += __vidar.w_float(w, x.vx)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "vy = ")
	n += __vidar.w_float(w, x.vy)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "id = ")
	n += __vidar.w_v(w, x.id)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "alive = ")
	n += __vidar.w_v(w, x.alive)
	n += __vidar.w_str(w, "}")
	return
}

__print_main_Pair :: proc(w: __vidar.Writer, x: Pair) -> (n: int) {
	n += __vidar.w_str(w, "Pair{")
	n += __vidar.w_str(w, "a = ")
	n += __vidar.w_v(w, x.a)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "b = ")
	n += __vidar.w_v(w, x.b)
	n += __vidar.w_str(w, "}")
	return
}
