package main; import __vidar "vidar_runtime"

import "core:fmt"
import "core:net"
import "core:time"
import sched "vidar_sched"

main :: proc() {
	start := time.tick_now()

	// a goroutine ticking while another blocks a worker thread for 100ms
	ticks := 0
	stop := false
	sched.go(__closure_0(&ticks, &stop))
	sched.blocking(__vidar.Closure(proc(__vidar.Env)){call = proc(__env_raw: __vidar.Env) { time.sleep(100 * time.Millisecond) }})
	stop = true
	fmt.println("ticked while blocked:", ticks >= 10)

	// files
	path := "/tmp/vidar-sched-test.txt"
	err := sched.write_entire_file(path, transmute([]byte)string("hello from a goroutine\n"))
	fmt.println("write:", err)
	data, rerr := sched.read_entire_file(path)
	fmt.print("read:", rerr, string(data))
	f, oerr := sched.open(path)
	kind, size, _ := sched.stat(f)
	buf: [5]byte
	n, _ := sched.read_at(f, 6, buf[:])
	fmt.println("stat:", oerr, kind, size, "read_at:", string(buf[:n]))
	sched.close(f)

	// many file reads in parallel goroutines
	done := sched.make_chan(int, 50)
	for i in 0..<50 do sched.go(__closure_1(path, done))
	total := 0
	for _ in 0..<50 do total += sched.recv(done)
	fmt.println("parallel reads:", total == 50 * 23)

	// DNS on a worker
	ep4, _, derr := sched.resolve("localhost:80")
	fmt.println("resolve:", derr, ep4)

	// UDP echo
	server, _ := sched.udp_socket()
	sched.bind(server, {net.IP4_Loopback, 0})
	addr, _ := net.bound_endpoint(server)
	sched.go(__closure_2(server))
	client, _ := sched.udp_socket()
	sched.send_to(client, transmute([]byte)string("ping"), addr)
	b: [64]byte
	m, _, _ := sched.recv_from(client, b[:])
	fmt.println("udp:", string(b[:m]))

	// mutex held across a sleep: goroutines take turns without blocking the thread
	mu: sched.Mutex
	order := sched.make_chan(int, 3)
	for i in 0..<3 do sched.go(__closure_3(i, &mu, order))
	fmt.println("mutex order:", sched.recv(order), sched.recv(order), sched.recv(order))

	// after() as a select timeout
	never := sched.make_chan(int)
	switch sched.select(sched.on_recv(never), sched.on_recv(sched.after(10 * time.Millisecond))) {
	case 1: fmt.println("after fired")
	}
	fmt.println("total under 1s:", time.tick_since(start) < time.Second)
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		ticks: T0,
		stop: T1,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:14: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw;
		for !__env.stop^ {
			sched.sleep(5 * time.Millisecond)
			__env.ticks^ += 1
		}
	},
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1}},
	}
}

__closure_1 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		path: T0,
		done: T1,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:39: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw;
		d, _ := sched.read_entire_file(__env.path)
		sched.send(__env.done, len(d))
	},
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1}},
	}
}

__closure_2 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		server: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:55: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw;
		b: [64]byte
		n, from, _ := sched.recv_from(__env.server, b[:])
		sched.send_to(__env.server, b[:n], from)
	},
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_3 :: proc(__c0: $T0, __c1: $T1, __c2: $T2) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		i: T0,
		mu: T1,
		order: T2,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:69: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw;
		sched.lock(&__env.mu^)
		defer sched.unlock(&__env.mu^)
		sched.sleep(5 * time.Millisecond)
		sched.send(__env.order, __env.i)
	},
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1, __c2}},
	}
}
