package main; import __vidar "vidar_runtime"; import __str "core:strings"

import "core:fmt"
import iter "iter"

main :: proc() {
	xs := []int{1, 2, 3, 4}
	total := 0
	each__closure0(xs, &total)
	__fmt_0(total)

	stats: iter.Stats
	k := 10
	__fmt_1(sum_by__closure1(xs, &stats, k), stats.calls)

	seen := 0
	iter.doubled(xs, __closure_0(&seen))
	__fmt_2(seen)

	moved := 0
	iter.shifted(xs, __closure_1(&moved))
	__fmt_3(moved)

	limit := 2
	__fmt_4(visit__closure2(xs, limit))

	got := 0
	scaled(xs, __closure_2(&got))
	__fmt_5(got)
}

// ---- generated by vidar ----

// fmt.println
__fmt_0 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "each: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_1 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "sum_by: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

__closure_0 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int)) {
	__Caps :: struct {
		seen: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:17: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int)){
		call = proc(__env_raw: __vidar.Env, x: int) { __env := transmute(__Env)__env_raw; __env.seen^ += x },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

// fmt.println
__fmt_2 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "doubled: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

__closure_1 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int)) {
	__Caps :: struct {
		moved: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:21: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int)){
		call = proc(__env_raw: __vidar.Env, x: int) { __env := transmute(__Env)__env_raw; __env.moved^ += x },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

// fmt.println
__fmt_3 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "shifted: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_4 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "visit: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

__closure_2 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int)) {
	__Caps :: struct {
		got: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:28: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int)){
		call = proc(__env_raw: __vidar.Env, x: int) { __env := transmute(__Env)__env_raw; __env.got^ += x },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

// fmt.println
__fmt_5 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "scaled: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

__each__closure0_f_Env :: struct($__T0: typeid) {
	total: __T0,
}

__each__closure0_f :: proc(__env: ^__each__closure0_f_Env($__T0), x: int) { __env.total^ += x }

// each with the closure from line 9 called directly
each__closure0 :: proc(xs: []int, __f_c0: $__f_T0) { __f_env := __each__closure0_f_Env(__f_T0){__f_c0};
	for x in xs do __each__closure0_f(&__f_env, x)
}

__sum_by__closure1_f_Env :: struct($__T0: typeid) {
	k: __T0,
}

__sum_by__closure1_f :: proc(__env: ^__sum_by__closure1_f_Env($__T0), x: int) -> int { return x * __env.k }

// fmt.println
__fmt_6 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "sum_by: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " values\n")
	__vidar.w_flush(w)
	return
}

// sum_by with the closure from line 14 called directly
sum_by__closure1 :: proc(xs: []int, s: ^iter.Stats, __f_c0: $__f_T0) -> int { __f_env := __sum_by__closure1_f_Env(__f_T0){__f_c0};
	total := 0
	for x in xs {
		total += __sum_by__closure1_f(&__f_env, x)
		iter.bump(s)
	}
	if __str.has_prefix("iter", "it") do __fmt_6(len(xs))
	return total
}

__visit__closure2_f_Env :: struct($__T0: typeid) {
	limit: __T0,
}

__visit__closure2_f :: proc(__env: ^__visit__closure2_f_Env($__T0), x: int) -> bool { return x > __env.limit }

// visit with the closure from line 25 called directly
visit__closure2 :: proc(xs: []int, __f_c0: $__f_T0) -> int { __f_env := __visit__closure2_f_Env(__f_T0){__f_c0};
	n := 0
	for x in xs do if __visit__closure2_f(&__f_env, x) do n += 1
	b := __str.builder_make()
	defer __str.builder_destroy(&b)
	__str.write_string(&b, "visit")
	fmt.println(__str.to_string(b), n)
	return n
}
