package main; import __vidar "vidar_runtime"

import "core:fmt"

// -opt with generic impls and polymorphic or grouped bound procs

Counter :: struct { data: rawptr, __vtable: ^__Counter_VTable }
bump :: proc{__Counter_bump, cell_bump, tally_bump}
get  :: proc{__Counter_get, cell_get, tally_get}

Cell :: struct($T: typeid) { n: T }
Tally :: struct { hits: [4]int }

cell_bump :: proc(c: ^Cell($T), by: int) { c.n += T(by) }
cell_get  :: proc(c: ^Cell($T)) -> int { return int(c.n) }
tally_bump :: proc(t: ^Tally, by: int) { t.hits[0] += by }
tally_get  :: proc(t: ^Tally) -> int { return t.hits[0] }




// followed into the generic impl's procs too: nothing allocates

bump_all :: proc(cs: []Counter, by: int) -> (sum: int) { when __vidar.NO_ALLOC_CHECKS { context.allocator = __vidar.panic_allocator(); context.temp_allocator = context.allocator };
	for c in cs {
		bump(c, by)
		sum += get(c)
	}
	return
}

// not inline: Cell(T) is parametric, so the array keeps interface values
cells :: proc() -> int {
	list: [dynamic]Counter
	defer {
		for c in list do free(c.data)
		delete(list)
	}
	append(&list, __Counter_from(new_clone(Cell(int){1})), __Counter_from(new_clone(Cell(f32){2})), __Counter_from(new_clone(Tally{})))
	for c in list do bump(c, 3)
	total := 0
	for c in list do total += get(c)
	return total
}

// plain types bound to a polymorphic proc and to a proc group: still inline, and devirtualized
Sized :: struct { data: rawptr, __vtable: ^__Sized_VTable }
size   :: proc{__Sized_size, __Sized_size_Small, __Sized_size_Large}
weight :: proc{__Sized_weight, small_weight, large_weight}

Small :: struct { a: u8 }
Large :: struct { a, b, c: i64 }

byte_size :: proc(x: ^$T) -> int { return size_of(T) }
small_weight :: proc(s: ^Small, scale: int) -> int { return int(s.a) * scale }
large_weight :: proc(l: ^Large, scale: int) -> int { return int(l.a + l.b + l.c) * scale }
weights :: proc{small_weight, large_weight}




sizes :: proc() -> int {
	list: [dynamic]__Sized_Value
	defer delete(list)
	append(&list, Small{3}, Large{1, 2, 3})
	total := 0
	for &s in list do total += __Sized_v_size(&s) * 100 + __Sized_v_weight(&s, 2)
	return total
}

main :: proc() {
	a := Cell(int){10}
	b := Cell(u8){20}
	t := Tally{}
	cs := []Counter{__Counter_from(&a), __Counter_from(&b), __Counter_from(&t)}
	__fmt_0(bump_all(cs, 1), bump_all(cs, 2))
	__fmt_1(a.n, b.n, t.hits[0])
	__fmt_0(cells(), sizes())
	s: Sized = __Sized_from(&Large{4, 5, 6})
	__fmt_2(size(s), weight(s, 3), size(&Small{}), weight(&Small{7}, 1))
}

// ---- generated by vidar ----

__Counter_VTable :: struct {
	bump: proc(self: Counter, by: int),
	get: proc(self: Counter) -> int,
}

__Counter_bump :: proc(c: Counter, by: int) {
	if c.__vtable == &__Counter_vtable_Tally { tally_bump(auto_cast c.data, by); return }
	c.__vtable.bump(c, by)
}

__Counter_get :: proc(c: Counter) -> int {
	if c.__vtable == &__Counter_vtable_Tally { return tally_get(auto_cast c.data) }
	return c.__vtable.get(c)
}

__Counter_identity :: #force_inline proc(v: Counter) -> Counter { return v }

__Counter_from :: proc{__Counter_from_Cell_T, __Counter_from_Tally, __Counter_identity}

__Counter_from_Cell_T :: proc(p: ^Cell($T)) -> Counter {
	@(static, rodata) vt := __Counter_VTable{
		bump = proc(self: Counter, by: int) { cell_bump((^Cell(T))(self.data), by) },
		get = proc(self: Counter) -> int { return cell_get((^Cell(T))(self.data)) },
	}
	return {data = p, __vtable = &vt}
}

@(rodata)
__Counter_vtable_Tally := __Counter_VTable{
	bump = proc(self: Counter, by: int) { tally_bump((^Tally)(self.data), by) },
	get = proc(self: Counter) -> int { return tally_get((^Tally)(self.data)) },
}

__Counter_from_Tally :: proc(p: ^Tally) -> Counter { return {data = p, __vtable = &__Counter_vtable_Tally} }

__Sized_VTable :: struct {
	size: proc(self: Sized) -> int,
	weight: proc(self: Sized, scale: int) -> int,
}

__Sized_size :: proc(s: Sized) -> int {
	if s.__vtable == &__Sized_vtable_Small { return __Sized_size_Small(auto_cast s.data) }
	if s.__vtable == &__Sized_vtable_Large { return __Sized_size_Large(auto_cast s.data) }
	return s.__vtable.size(s)
}

__Sized_weight :: proc(s: Sized, scale: int) -> int {
	if s.__vtable == &__Sized_vtable_Small { return small_weight(auto_cast s.data, scale) }
	if s.__vtable == &__Sized_vtable_Large { return large_weight(auto_cast s.data, scale) }
	return s.__vtable.weight(s, scale)
}

__Sized_identity :: #force_inline proc(v: Sized) -> Sized { return v }

__Sized_from :: proc{__Sized_from_Small, __Sized_from_Large, __Sized_identity}

__Sized_size_Small :: #force_inline proc(__self: ^Small) -> int { return byte_size(__self) }

@(rodata)
__Sized_vtable_Small := __Sized_VTable{
	size = proc(self: Sized) -> int { return __Sized_size_Small((^Small)(self.data)) },
	weight = proc(self: Sized, scale: int) -> int { return small_weight((^Small)(self.data), scale) },
}

__Sized_from_Small :: proc(p: ^Small) -> Sized { return {data = p, __vtable = &__Sized_vtable_Small} }

__Sized_size_Large :: #force_inline proc(__self: ^Large) -> int { return byte_size(__self) }

@(rodata)
__Sized_vtable_Large := __Sized_VTable{
	size = proc(self: Sized) -> int { return __Sized_size_Large((^Large)(self.data)) },
	weight = proc(self: Sized, scale: int) -> int { return large_weight((^Large)(self.data), scale) },
}

__Sized_from_Large :: proc(p: ^Large) -> Sized { return {data = p, __vtable = &__Sized_vtable_Large} }

// Sized values stored inline
__Sized_Value :: union { Small, Large }

__Sized_v_size :: #force_inline proc(self: ^__Sized_Value) -> int {
	switch &v in self^ {
	case Small: return byte_size(&v)
	case Large: return byte_size(&v)
	case: unreachable()
	}
	unreachable()
}

__Sized_v_weight :: #force_inline proc(self: ^__Sized_Value, scale: int) -> int {
	switch &v in self^ {
	case Small: return small_weight(&v, scale)
	case Large: return large_weight(&v, scale)
	case: unreachable()
	}
	unreachable()
}

// fmt.println
__fmt_0 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_1 :: proc(a0: $T0, a1: $T1, a2: $T2) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a2)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_2 :: proc(a0: $T0, a1: $T1, a2: $T2, a3: $T3) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a2)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a3)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}
