package main; import __vidar "vidar_runtime"

import "core:fmt"
import "core:io"
import "core:strings"

Color :: enum { Red, Green }
Meters :: distinct int
Point :: struct { x, y: int }

main :: proc() {
	hp, max_hp := 7, 10
	name := "slime"
	big: u64 = 18446744073709551615
	small: i8 = -128
	b: u8 = 200
	r: rune = 'é'
	ok := true
	f := 2.5
	m: Meters = 42
	huge: i128 = -170141183460469231731687303715884105728

	// written directly: strings, bools, runes and integers
	__fmt_0(name, hp, max_hp)
	__fmt_1(big, small, b, r, ok, -hp)
	__fmt_2(255, small, big, ok, r)
	__fmt_3()
	__fmt_4(name, hp, ok, r)
	__fmt_5(hp)
	__fmt_6()

	// through fmt for the one value: widths, floats, enums, structs, distinct and big types
	__fmt_7(hp, name, f, Color.Green, Point{1, 2}, m, huge, f)
	__fmt_8(name, name, f, 255, 8, 5, Color.Red)

	// escapes and braces
	__fmt_9()
	__fmt_10()
	__fmt_6()

	sb := strings.builder_make()
	__fmt_11(&sb, name, hp)
	__fmt_12(&sb, max_hp)
	__fmt_13(&sb, true)
	s := __fmt_14(&sb)
	__fmt_15(s)
	__fmt_16(__fmt_17(hp), __fmt_18(name))
	__fmt_16(__fmt_19(hp), __fmt_20())
	a := __fmt_21(hp, max_hp)
	__fmt_22(a, __fmt_23(ok), __fmt_24())
	delete(a)

	wb := strings.builder_make()
	w := strings.to_writer(&wb)
	n := __fmt_25(w, hp, name)
	__fmt_26(w, n)
	__fmt_27(w, 4096)
	__fmt_28(w)
	fmt.println(strings.to_string(wb))
	count := __fmt_29()
	__fmt_30(count)
	__fmt_31(hp)

	// left alone: fmt does something a fixed proc doesn't
	format := "%d dynamic\n"
	fmt.printf(format, hp)
	fmt.printf("%[1]d %[1]d indexed\n", hp)
	fmt.printf("%*d star\n", 5, hp)
	fmt.printf("{} {0} braces\n", hp)
	fmt.printf("%d %d missing\n", hp)
	fmt.printf("%d extra\n", hp, hp)
	fmt.println("nil:", nil)
	fmt.println("sep", hp, sep = "-")
	args := []any{1, "two"}
	fmt.println(..args)
	_ = io.Error.None
}

// ---- generated by vidar ----

// fmt.printf "%s [%d/%d]\n"
__fmt_0 :: proc(a0: $T0, a1: $T1, a2: $T2) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_s(w, a0)
	n += __vidar.w_str(w, " [")
	n += __vidar.w_d(w, a1)
	n += __vidar.w_str(w, "/")
	n += __vidar.w_d(w, a2)
	n += __vidar.w_str(w, "]\n")
	__vidar.w_flush(w)
	return
}

// fmt.printf "%v %v %v %v %v %v\n"
__fmt_1 :: proc(a0: $T0, a1: $T1, a2: $T2, a3: $T3, a4: $T4, a5: $T5) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a2)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a3)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a4)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a5)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.printf "%x %x %x %t %c\n"
__fmt_2 :: proc(a0: $T0, a1: $T1, a2: $T2, a3: $T3, a4: $T4) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_x(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_x(w, a1)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_x(w, a2)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_t(w, a3)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_c(w, a4)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.printfln "literals: %s %d %v %v"
__fmt_3 :: proc() -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "literals: inline 12 too 0\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_4 :: proc(a0: $T0, a1: $T1, a2: $T2, a3: $T3) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "println: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a2)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a3)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.print
__fmt_5 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "print: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " \n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_6 :: proc() -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.printf "[%5d] [%-6s] [%.2f] [%v] [%v] [%v] [%v] [%08.3f]\n"
__fmt_7 :: proc(a0: $T0, a1: $T1, a2: $T2, a3: $T3, a4: $T4, a5: $T5, a6: $T6, a7: $T7) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "[")
	n += __vidar.w_spec(w, a0, "%5d")
	n += __vidar.w_str(w, "] [")
	n += __vidar.w_spec(w, a1, "%-6s")
	n += __vidar.w_str(w, "] [")
	n += __vidar.w_spec(w, a2, "%.2f")
	n += __vidar.w_str(w, "] [")
	n += __vidar.w_v(w, a3)
	n += __vidar.w_str(w, "] [")
	n += __vidar.w_v(w, a4)
	n += __vidar.w_str(w, "] [")
	n += __vidar.w_v(w, a5)
	n += __vidar.w_str(w, "] [")
	n += __vidar.w_v(w, a6)
	n += __vidar.w_str(w, "] [")
	n += __vidar.w_spec(w, a7, "%08.3f")
	n += __vidar.w_str(w, "]\n")
	__vidar.w_flush(w)
	return
}

// fmt.printf "%q %w %e %X %o %b %d\n"
__fmt_8 :: proc(a0: $T0, a1: $T1, a2: $T2, a3: $T3, a4: $T4, a5: $T5, a6: $T6) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_spec(w, a0, "%q")
	n += __vidar.w_str(w, " ")
	n += __vidar.w_spec(w, a1, "%w")
	n += __vidar.w_str(w, " ")
	n += __vidar.w_spec(w, a2, "%e")
	n += __vidar.w_str(w, " ")
	n += __vidar.w_spec(w, a3, "%X")
	n += __vidar.w_str(w, " ")
	n += __vidar.w_spec(w, a4, "%o")
	n += __vidar.w_str(w, " ")
	n += __vidar.w_spec(w, a5, "%b")
	n += __vidar.w_str(w, " ")
	n += __vidar.w_d(w, a6)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.printf "tab\there \"quoted\" 100%% {{x}} }} } ünï\n"
__fmt_9 :: proc() -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "tab\there \"quoted\" 100% {x} } } ünï\n")
	__vidar.w_flush(w)
	return
}

// fmt.printf `raw %s\n`
__fmt_10 :: proc() -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "raw string\\n")
	__vidar.w_flush(w)
	return
}

// fmt.sbprintf "%s:%d"
__fmt_11 :: proc(b: ^__vidar.Builder, a0: $T0, a1: $T1) -> string {
	__vidar.sb_s(b, a0)
	__vidar.sb_str(b, ":")
	__vidar.sb_d(b, a1)
	return __vidar.sb_to_string(b)
}

// fmt.sbprintfln " +%v"
__fmt_12 :: proc(b: ^__vidar.Builder, a0: $T0) -> string {
	__vidar.sb_str(b, " +")
	__vidar.sb_v(b, a0)
	__vidar.sb_str(b, "\n")
	return __vidar.sb_to_string(b)
}

// fmt.sbprint
__fmt_13 :: proc(b: ^__vidar.Builder, a0: $T0) -> string {
	__vidar.sb_str(b, "a 1 ")
	__vidar.sb_v(b, a0)
	return __vidar.sb_to_string(b)
}

// fmt.sbprintln
__fmt_14 :: proc(b: ^__vidar.Builder) -> string {
	__vidar.sb_str(b, " end\n")
	return __vidar.sb_to_string(b)
}

// fmt.print
__fmt_15 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	__vidar.w_flush(w)
	return
}

// fmt.print
__fmt_16 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	__vidar.w_flush(w)
	return
}

// fmt.tprintf "tprintf %d|"
__fmt_17 :: proc(a0: $T0) -> string {
	b := __vidar.builder(context.temp_allocator)
	__vidar.sb_str(&b, "tprintf ")
	__vidar.sb_d(&b, a0)
	__vidar.sb_str(&b, "|")
	return __vidar.sb_to_string(&b)
}

// fmt.tprintfln "tprintfln %s"
__fmt_18 :: proc(a0: $T0) -> string {
	b := __vidar.builder(context.temp_allocator)
	__vidar.sb_str(&b, "tprintfln ")
	__vidar.sb_s(&b, a0)
	__vidar.sb_str(&b, "\n")
	return __vidar.sb_to_string(&b)
}

// fmt.tprint
__fmt_19 :: proc(a0: $T0) -> string {
	b := __vidar.builder(context.temp_allocator)
	__vidar.sb_str(&b, "tprint ")
	__vidar.sb_v(&b, a0)
	return __vidar.sb_to_string(&b)
}

// fmt.tprintln
__fmt_20 :: proc() -> string {
	b := __vidar.builder(context.temp_allocator)
	__vidar.sb_str(&b, " tprintln\n")
	return __vidar.sb_to_string(&b)
}

// fmt.aprintf "aprintf %v/%v"
__fmt_21 :: proc(a0: $T0, a1: $T1) -> string {
	b := __vidar.builder(context.allocator)
	__vidar.sb_str(&b, "aprintf ")
	__vidar.sb_v(&b, a0)
	__vidar.sb_str(&b, "/")
	__vidar.sb_v(&b, a1)
	return __vidar.sb_to_string(&b)
}

// fmt.println
__fmt_22 :: proc(a0: $T0, a1: $T1, a2: $T2) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a2)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.aprintln
__fmt_23 :: proc(a0: $T0) -> string {
	b := __vidar.builder(context.allocator)
	__vidar.sb_str(&b, "aprintln ")
	__vidar.sb_v(&b, a0)
	__vidar.sb_str(&b, "\n")
	return __vidar.sb_to_string(&b)
}

// fmt.aprint
__fmt_24 :: proc() -> string {
	b := __vidar.builder(context.allocator)
	__vidar.sb_str(&b, "aprint")
	return __vidar.sb_to_string(&b)
}

// fmt.wprintf "wprintf %d %s"
__fmt_25 :: proc(w: __vidar.Writer, a0: $T0, a1: $T1) -> (n: int) {
	n += __vidar.w_str(w, "wprintf ")
	n += __vidar.w_d(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_s(w, a1)
	__vidar.w_flush(w)
	return
}

// fmt.wprintln
__fmt_26 :: proc(w: __vidar.Writer, a0: $T0) -> (n: int) {
	n += __vidar.w_str(w, " wprintln ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.wprintfln "wprintfln %x"
__fmt_27 :: proc(w: __vidar.Writer, a0: $T0) -> (n: int) {
	n += __vidar.w_str(w, "wprintfln ")
	n += __vidar.w_x(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.wprint
__fmt_28 :: proc(w: __vidar.Writer) -> (n: int) {
	n += __vidar.w_str(w, "wprint")
	__vidar.w_flush(w)
	return
}

// fmt.printf "%d bytes\n"
__fmt_29 :: proc() -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "12345 bytes\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_30 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "printf returned ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.eprintf "to stderr %d\n"
__fmt_31 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], true)
	n += __vidar.w_str(w, "to stderr ")
	n += __vidar.w_d(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}
