package main

import "core:fmt"

Named :: struct { data: rawptr, __vtable: ^__Named_VTable }
Shape :: struct { data: rawptr, __vtable: ^__Shape_VTable }

label :: proc{__Named_label, __Shape_label, circle_label, __Shape_label_Square, __Shape_label_Box_T, __Shape_label_Pair_int_f64}
area  :: proc{__Shape_area, circle_area, square_area, box_area, pair_area}
scale :: proc{__Shape_scale, circle_scale, square_scale, box_scale, pair_scale}

Circle :: struct { r: f64 }
Square :: struct { side: f64 }
Box :: struct($T: typeid) { w, h: T }
Pair :: struct($A: typeid, $B: typeid) { a: A, b: B }

circle_area :: proc(c: ^Circle) -> f64 { return 3 * c.r * c.r }
square_area :: proc(s: ^Square) -> f64 { return s.side * s.side }
circle_scale :: proc(c: ^Circle, k: f64) { c.r *= k }
square_scale :: proc(s: ^Square, k: f64) { s.side *= k }

// proc groups: each impl binds the member that takes its type
areas  :: proc{circle_area, square_area}
scales :: proc{circle_scale, square_scale}

// a polymorphic proc: instantiated for each type it is bound for
type_label :: proc(x: ^$T) -> string { return fmt.tprint(typeid_of(T)) }
circle_label :: proc(c: ^Circle) -> string { return fmt.tprintf("circle r=%v", c.r) }
// for Circle, the exact ^Circle wins over ^$T; Square only fits ^$T
labels :: proc{circle_label, type_label}

// a generic impl: one for every Box(T)
box_area  :: proc(b: ^Box($T)) -> f64 { return f64(b.w) * f64(b.h) }
box_scale :: proc(b: ^Box($T), k: f64) { b.w = T(f64(b.w) * k); b.h = T(f64(b.h) * k) }

// an impl for one instance of a parametric type
pair_area  :: proc(p: ^Pair(int, f64)) -> f64 { return f64(p.a) * p.b }
pair_scale :: proc(p: ^Pair(int, f64), k: f64) { p.b *= k }






// generic code converting to the interface: a vtable for each instance it is called with
total :: proc(xs: []$T) -> (sum: f64) {
	for &x in xs {
		s: Shape = __Shape_from(&x)
		sum += area(s)
	}
	return
}

main :: proc() {
	c := Circle{1}
	sq := Square{2}
	bi := Box(int){2, 3}
	bf := Box(f32){0.5, 4}
	p := Pair(int, f64){3, 1.5}

	shapes: [dynamic]Shape
	defer delete(shapes)
	append(&shapes, __Shape_from(&c), __Shape_from(&sq), __Shape_from(&bi), __Shape_from(&bf), __Shape_from(&p))
	for s in shapes do fmt.println(label(s), area(s))
	for s in shapes do scale(s, 2)
	for s in shapes do fmt.printf("%s: %.2f\n", label(s), area(s))

	// static calls go to the bound proc, no vtable
	fmt.println("static:", area(&bi), label(&sq), label(&c), area(&p))

	// a base interface, implied by the generic impl too
	n: Named = __Named_from(&bf)
	fmt.println("named:", label(n), label(__Shape_as_Named(shapes[2])))

	fmt.println("total:", total([]Box(int){{1, 2}, {3, 4}}), total([]Box(f64){{0.5, 0.5}}), total([]Square{{1}, {2}}))
}

// ---- generated by vidar ----

__Named_VTable :: struct {
	label: proc(self: Named) -> string,
}

__Named_label :: proc(n: Named) -> string {
	if n.__vtable == &__Shape_vtable_Circle.__Named || n.__vtable == &__Named_vtable_Circle { return circle_label(auto_cast n.data) }
	if n.__vtable == &__Shape_vtable_Square.__Named || n.__vtable == &__Named_vtable_Square { return __Shape_label_Square(auto_cast n.data) }
	if n.__vtable == &__Shape_vtable_Pair_int_f64.__Named || n.__vtable == &__Named_vtable_Pair_int_f64 { return __Shape_label_Pair_int_f64(auto_cast n.data) }
	return n.__vtable.label(n)
}

__Named_identity :: #force_inline proc(v: Named) -> Named { return v }

__Named_from :: proc{__Named_from_Circle, __Named_from_Square, __Named_from_Box_T, __Named_from_Pair_int_f64, __Named_identity}

__Shape_VTable :: struct {
	__Named: __Named_VTable,
	area: proc(self: Shape) -> f64,
	scale: proc(self: Shape, k: f64),
}

__Shape_area :: proc(s: Shape) -> f64 {
	if s.__vtable == &__Shape_vtable_Circle { return circle_area(auto_cast s.data) }
	if s.__vtable == &__Shape_vtable_Square { return square_area(auto_cast s.data) }
	if s.__vtable == &__Shape_vtable_Pair_int_f64 { return pair_area(auto_cast s.data) }
	return s.__vtable.area(s)
}

__Shape_scale :: proc(s: Shape, k: f64) {
	if s.__vtable == &__Shape_vtable_Circle { circle_scale(auto_cast s.data, k); return }
	if s.__vtable == &__Shape_vtable_Square { square_scale(auto_cast s.data, k); return }
	if s.__vtable == &__Shape_vtable_Pair_int_f64 { pair_scale(auto_cast s.data, k); return }
	s.__vtable.scale(s, k)
}

__Shape_label :: proc(self: Shape) -> string {
	if self.__vtable == &__Shape_vtable_Circle { return circle_label(auto_cast self.data) }
	if self.__vtable == &__Shape_vtable_Square { return __Shape_label_Square(auto_cast self.data) }
	if self.__vtable == &__Shape_vtable_Pair_int_f64 { return __Shape_label_Pair_int_f64(auto_cast self.data) }
	return self.__vtable.__Named.label(__Shape_as_Named(self))
}

__Shape_as_Named :: #force_inline proc(v: Shape) -> Named { return {data = v.data, __vtable = &v.__vtable.__Named} }

__Shape_identity :: #force_inline proc(v: Shape) -> Shape { return v }

__Shape_from :: proc{__Shape_from_Circle, __Shape_from_Square, __Shape_from_Box_T, __Shape_from_Pair_int_f64, __Shape_identity}

@(rodata)
__Shape_vtable_Circle := __Shape_VTable{
	__Named = {
		label = proc(self: Named) -> string { return circle_label((^Circle)(self.data)) },
	},
	area = proc(self: Shape) -> f64 { return circle_area((^Circle)(self.data)) },
	scale = proc(self: Shape, k: f64) { circle_scale((^Circle)(self.data), k) },
}

__Shape_from_Circle :: proc(p: ^Circle) -> Shape { return {data = p, __vtable = &__Shape_vtable_Circle} }

@(rodata)
__Named_vtable_Circle := __Named_VTable{
	label = proc(self: Named) -> string { return circle_label((^Circle)(self.data)) },
}

__Named_from_Circle :: proc(p: ^Circle) -> Named { return {data = p, __vtable = &__Named_vtable_Circle} }

__Shape_label_Square :: #force_inline proc(__self: ^Square) -> string { return type_label(__self) }

@(rodata)
__Shape_vtable_Square := __Shape_VTable{
	__Named = {
		label = proc(self: Named) -> string { return __Shape_label_Square((^Square)(self.data)) },
	},
	area = proc(self: Shape) -> f64 { return square_area((^Square)(self.data)) },
	scale = proc(self: Shape, k: f64) { square_scale((^Square)(self.data), k) },
}

__Shape_from_Square :: proc(p: ^Square) -> Shape { return {data = p, __vtable = &__Shape_vtable_Square} }

@(rodata)
__Named_vtable_Square := __Named_VTable{
	label = proc(self: Named) -> string { return __Shape_label_Square((^Square)(self.data)) },
}

__Named_from_Square :: proc(p: ^Square) -> Named { return {data = p, __vtable = &__Named_vtable_Square} }

__Shape_label_Box_T :: #force_inline proc(__self: ^Box($T)) -> string { return type_label(__self) }

__Shape_from_Box_T :: proc(p: ^Box($T)) -> Shape {
	@(static, rodata) vt := __Shape_VTable{
		__Named = {
			label = proc(self: Named) -> string { return __Shape_label_Box_T((^Box(T))(self.data)) },
		},
		area = proc(self: Shape) -> f64 { return box_area((^Box(T))(self.data)) },
		scale = proc(self: Shape, k: f64) { box_scale((^Box(T))(self.data), k) },
	}
	return {data = p, __vtable = &vt}
}

__Named_from_Box_T :: proc(p: ^Box($T)) -> Named {
	@(static, rodata) vt := __Named_VTable{
		label = proc(self: Named) -> string { return __Shape_label_Box_T((^Box(T))(self.data)) },
	}
	return {data = p, __vtable = &vt}
}

__Shape_label_Pair_int_f64 :: #force_inline proc(__self: ^Pair(int, f64)) -> string { return type_label(__self) }

@(rodata)
__Shape_vtable_Pair_int_f64 := __Shape_VTable{
	__Named = {
		label = proc(self: Named) -> string { return __Shape_label_Pair_int_f64((^Pair(int, f64))(self.data)) },
	},
	area = proc(self: Shape) -> f64 { return pair_area((^Pair(int, f64))(self.data)) },
	scale = proc(self: Shape, k: f64) { pair_scale((^Pair(int, f64))(self.data), k) },
}

__Shape_from_Pair_int_f64 :: proc(p: ^Pair(int, f64)) -> Shape { return {data = p, __vtable = &__Shape_vtable_Pair_int_f64} }

@(rodata)
__Named_vtable_Pair_int_f64 := __Named_VTable{
	label = proc(self: Named) -> string { return __Shape_label_Pair_int_f64((^Pair(int, f64))(self.data)) },
}

__Named_from_Pair_int_f64 :: proc(p: ^Pair(int, f64)) -> Named { return {data = p, __vtable = &__Named_vtable_Pair_int_f64} }
