package main; import __vidar "vidar_runtime"

import "core:fmt"

Shape :: struct { data: rawptr, __vtable: ^__Shape_VTable }
area :: proc{__Shape_area, circle_area, rect_area}
grow :: proc{__Shape_grow, circle_grow, rect_grow}

Circle :: struct { r: f64 }
Rect :: struct { w, h: f64 }

circle_area :: proc(c: ^Circle) -> f64 { return 3 * c.r * c.r }
circle_grow :: proc(c: ^Circle, k: f64) { c.r += k }
rect_area :: proc(r: ^Rect) -> f64 { return r.w * r.h }
rect_grow :: proc(r: ^Rect, k: f64) { r.w += k; r.h += k }




// held inline: grow changes the elements in place, as it changed the clones before
inline :: proc() -> f64 {
	list: [dynamic]__Shape_Value
	defer delete(list)
	append(&list, Circle{1}, Rect{2, 3})
	append(&list, Circle{2})
	for &s in list do __Shape_v_grow(&s, 1)
	for &s, i in list do if i > 0 do __Shape_v_grow(&s, 0.5)
	total := 0.0
	for &s in list do total += __Shape_v_area(&s)
	__Shape_v_grow(&list[0], 10)
	return total + __Shape_v_area(&list[0]) + f64(len(list))
}

// not inline: a value converted twice shares its data, which a copy wouldn't
shared :: proc() -> f64 {
	c := new_clone(Circle{1})
	list: [dynamic]Shape
	defer delete(list)
	append(&list, __Shape_from(c), __Shape_from(c))
	for s in list do grow(s, 1)
	return area(list[0]) + area(list[1])
}

// not inline: an element is kept outside the array
kept :: proc() -> f64 {
	list: [dynamic]Shape
	defer delete(list)
	append(&list, __Shape_from(new_clone(Circle{1})))
	first: Shape
	for s in list do first = s
	grow(first, 1)
	return area(list[0])
}

// not inline: appending while looping over it
grows :: proc() -> int {
	list: [dynamic]Shape
	defer delete(list)
	append(&list, __Shape_from(new_clone(Rect{1, 1})))
	for s in list do if area(s) < 2 do append(&list, __Shape_from(new_clone(Rect{2, 2})))
	return len(list)
}

main :: proc() {
	__fmt_0(inline(), shared(), kept(), grows())
}

// ---- generated by vidar ----

__Shape_VTable :: struct {
	area: proc(self: Shape) -> f64,
	grow: proc(self: Shape, k: f64),
}

__Shape_area :: proc(s: Shape) -> f64 {
	if s.__vtable == &__Shape_vtable_Circle { return circle_area(auto_cast s.data) }
	if s.__vtable == &__Shape_vtable_Rect { return rect_area(auto_cast s.data) }
	return s.__vtable.area(s)
}

__Shape_grow :: proc(s: Shape, k: f64) {
	if s.__vtable == &__Shape_vtable_Circle { circle_grow(auto_cast s.data, k); return }
	if s.__vtable == &__Shape_vtable_Rect { rect_grow(auto_cast s.data, k); return }
	s.__vtable.grow(s, k)
}

__Shape_identity :: #force_inline proc(v: Shape) -> Shape { return v }

__Shape_from :: proc{__Shape_from_Circle, __Shape_from_Rect, __Shape_identity}

@(rodata)
__Shape_vtable_Circle := __Shape_VTable{
	area = proc(self: Shape) -> f64 { return circle_area((^Circle)(self.data)) },
	grow = proc(self: Shape, k: f64) { circle_grow((^Circle)(self.data), k) },
}

__Shape_from_Circle :: proc(p: ^Circle) -> Shape { return {data = p, __vtable = &__Shape_vtable_Circle} }

@(rodata)
__Shape_vtable_Rect := __Shape_VTable{
	area = proc(self: Shape) -> f64 { return rect_area((^Rect)(self.data)) },
	grow = proc(self: Shape, k: f64) { rect_grow((^Rect)(self.data), k) },
}

__Shape_from_Rect :: proc(p: ^Rect) -> Shape { return {data = p, __vtable = &__Shape_vtable_Rect} }

// Shape values stored inline
__Shape_Value :: union { Circle, Rect }

__Shape_v_grow :: #force_inline proc(self: ^__Shape_Value, k: f64) {
	switch &v in self^ {
	case Circle: circle_grow(&v, k)
	case Rect: rect_grow(&v, k)
	case: unreachable()
	}
}

__Shape_v_area :: #force_inline proc(self: ^__Shape_Value) -> f64 {
	switch &v in self^ {
	case Circle: return circle_area(&v)
	case Rect: return rect_area(&v)
	case: unreachable()
	}
	unreachable()
}

// fmt.println
__fmt_0 :: proc(a0: $T0, a1: $T1, a2: $T2, a3: $T3) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a2)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a3)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}
