package shapes

Shape :: struct { data: rawptr, __vtable: ^__Shape_VTable }
area :: proc{__Shape_area}

total :: proc(list: []Shape) -> (sum: f64) {
	for s in list do sum += area(s)
	return
}

// ---- generated by vidar ----

__Shape_VTable :: struct {
	area: proc(self: Shape) -> f64,
}

__Shape_area :: proc(s: Shape) -> f64 { return s.__vtable.area(s) }

__Shape_identity :: #force_inline proc(v: Shape) -> Shape { return v }

__Shape_from :: proc{__Shape_identity}
