package shapes

// Extended from another package, so a Shape can hold types this package doesn't know: a vtable.
Shape :: struct { data: rawptr, __vtable: ^__Shape_VTable }
area :: proc{__Shape_area, __Polygon_area, square_area}

// Only extended here: a union over its implementations.
Polygon :: struct { data: rawptr, __vtable: ^__Polygon_VTable }
sides :: proc{__Polygon_sides, square_sides}

Square :: struct { side: f64 }

square_area  :: proc(s: ^Square) -> f64 { return s.side * s.side }
square_sides :: proc(s: ^Square) -> int { return 4 }



total :: proc(list: []Shape) -> (sum: f64) {
	for s in list do sum += area(s)
	return
}

as_shape :: proc(p: Polygon) -> Shape { return __Polygon_as_Shape(p) }

// ---- generated by vidar ----

__Shape_VTable :: struct {
	area: proc(self: Shape) -> f64,
}

__Shape_area :: proc(s: Shape) -> f64 {
	if s.__vtable == &__Polygon_vtable_Square.__Shape || s.__vtable == &__Shape_vtable_Square { return square_area(auto_cast s.data) }
	return s.__vtable.area(s)
}

__Shape_identity :: #force_inline proc(v: Shape) -> Shape { return v }

__Shape_from :: proc{__Shape_from_Square, __Shape_identity}

__Polygon_VTable :: struct {
	__Shape: __Shape_VTable,
	sides: proc(self: Polygon) -> int,
}

__Polygon_sides :: proc(p: Polygon) -> int {
	if p.__vtable == &__Polygon_vtable_Square { return square_sides(auto_cast p.data) }
	return p.__vtable.sides(p)
}

__Polygon_area :: proc(self: Polygon) -> f64 {
	if self.__vtable == &__Polygon_vtable_Square { return square_area(auto_cast self.data) }
	return self.__vtable.__Shape.area(__Polygon_as_Shape(self))
}

__Polygon_as_Shape :: #force_inline proc(v: Polygon) -> Shape { return {data = v.data, __vtable = &v.__vtable.__Shape} }

__Polygon_identity :: #force_inline proc(v: Polygon) -> Polygon { return v }

__Polygon_from :: proc{__Polygon_from_Square, __Polygon_identity}

@(rodata)
__Polygon_vtable_Square := __Polygon_VTable{
	__Shape = {
		area = proc(self: Shape) -> f64 { return square_area((^Square)(self.data)) },
	},
	sides = proc(self: Polygon) -> int { return square_sides((^Square)(self.data)) },
}

__Polygon_from_Square :: proc(p: ^Square) -> Polygon { return {data = p, __vtable = &__Polygon_vtable_Square} }

@(rodata)
__Shape_vtable_Square := __Shape_VTable{
	area = proc(self: Shape) -> f64 { return square_area((^Square)(self.data)) },
}

__Shape_from_Square :: proc(p: ^Square) -> Shape { return {data = p, __vtable = &__Shape_vtable_Square} }
