package main; import __vidar "vidar_runtime"

import "core:fmt"

main :: proc() {
	total := new_clone(0)
	outer := __closure_1(total)
	outer.call(outer.env, 1)
	outer.call(outer.env, 2)
	fmt.println("total:", total^)

	base := 100
	make := __closure_3(base)
	f := make.call(make.env, 3)
	fmt.println("f(2):", f.call(f.env, 2))
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(rawptr)) {
	__Env :: struct {
		total: T0,
		n: T1,
	}
	return __vidar.Closure(proc(rawptr)){
		call = proc(__env_raw: rawptr) { __env := cast(^__Env)__env_raw; __env.total^ += __env.n },
		env = new_clone(__Env{__c0, __c1}),
	}
}

__closure_1 :: proc(__c0: $T0) -> __vidar.Closure(proc(rawptr, int)) {
	__Env :: struct {
		total: T0,
	}
	return __vidar.Closure(proc(rawptr, int)){
		call = proc(__env_raw: rawptr, n: int) { __env := cast(^__Env)__env_raw;
		// re-capture: by-ref of a by-ref capture, by-value of a param
		inner := __closure_0(__env.total, n)
		inner.call(inner.env)
		inner.call(inner.env)
	},
		env = new_clone(__Env{__c0}),
	}
}

__closure_2 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(rawptr, int) -> int) {
	__Env :: struct {
		base: T0,
		k: T1,
	}
	return __vidar.Closure(proc(rawptr, int) -> int){
		call = proc(__env_raw: rawptr, x: int) -> int { __env := cast(^__Env)__env_raw; return __env.base + __env.k * x },
		env = new_clone(__Env{__c0, __c1}),
	}
}

__closure_3 :: proc(__c0: $T0) -> __vidar.Closure(proc(rawptr, int) -> __vidar.Closure(proc(rawptr, int) -> int)) {
	__Env :: struct {
		base: T0,
	}
	return __vidar.Closure(proc(rawptr, int) -> __vidar.Closure(proc(rawptr, int) -> int)){
		call = proc(__env_raw: rawptr, k: int) -> __vidar.Closure(proc(rawptr, int) -> int) { __env := cast(^__Env)__env_raw;
		return __closure_2(__env.base, k)
	},
		env = new_clone(__Env{__c0}),
	}
}
