package main; import __vidar "vidar_runtime"

import "core:fmt"

main :: proc() {
	total := 0
	outer := __closure_1(&total)
	outer.call(outer.env, 1)
	outer.call(outer.env, 2)
	fmt.println("total:", total)

	base := 100
	make := __closure_3(base)
	f := make.call(make.env, 3)
	fmt.println("f(2):", f.call(f.env, 2))
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		total: T0,
		n: T1,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:9: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw; __env.total^ += __env.n },
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1}},
	}
}

__closure_1 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int)) {
	__Caps :: struct {
		total: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:7: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int)){
		call = proc(__env_raw: __vidar.Env, n: int) { __env := transmute(__Env)__env_raw;
		// re-capture: by-ref of a by-ref capture, by-value of a param
		inner := __closure_0(__env.total, n)
		inner.call(inner.env)
		inner.call(inner.env)
	},
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_2 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(__vidar.Env, int) -> int) {
	__Caps :: struct {
		base: T0,
		k: T1,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:19: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int) -> int){
		call = proc(__env_raw: __vidar.Env, x: int) -> int { __env := transmute(__Env)__env_raw; return __env.base + __env.k * x },
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1}},
	}
}

__closure_3 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int) -> __vidar.Closure(proc(__vidar.Env, int) -> int)) {
	__Caps :: struct {
		base: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:18: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int) -> __vidar.Closure(proc(__vidar.Env, int) -> int)){
		call = proc(__env_raw: __vidar.Env, k: int) -> __vidar.Closure(proc(__vidar.Env, int) -> int) { __env := transmute(__Env)__env_raw;
		return __closure_2(__env.base, k)
	},
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}
