package main; import __vidar "vidar_runtime"

import "core:fmt"
import "core:encoding/json"

P :: struct { x: int, name: string }

main :: proc() {
	b, _ := __json_marshal_main_P(P{1, "a"})
	__fmt_0(string(b))
	__fmt_1(P{1, "a"})
	other()
}

// ---- generated by vidar ----

// fmt.println
__fmt_0 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.printfln "%v"
__fmt_1 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	when T0 == P { n += __print_main_P(w, a0) } else { n += __vidar.w_spec(w, a0, "%v") }
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt's %v for the types printed here, written out
@(private="file")
__print_main_P :: proc(w: __vidar.Writer, x: P) -> (n: int) {
	n += __vidar.w_str(w, "P{")
	n += __vidar.w_str(w, "x = ")
	n += __vidar.w_v(w, x.x)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "name = ")
	n += __vidar.w_quoted(w, x.name)
	n += __vidar.w_str(w, "}")
	return
}

@(private="file")
// json.marshal of P, written out: encoding/json's bytes
__json_marshal_main_P :: proc(x: $T, allocator := context.allocator) -> (data: []byte, err: json.Marshal_Error) {
	when T == P {
		b := __vidar.builder(allocator)
		__jsonw_main_P(__vidar.sb_writer(&b), x)
		return b.buf[:], nil
	} else {
		return json.marshal(x, allocator = allocator)
	}
}

@(private="file")
__jsonw_main_P :: proc(w: __vidar.Writer, x: P) {
	__vidar.w_str(w, "{")
	__vidar.w_str(w, "\"x\":")
	__vidar.w_d(w, x.x)
	__vidar.w_str(w, ",\"name\":")
	__vidar.w_json_str(w, x.name)
	__vidar.w_str(w, "}")
}
