package main; import __vidar "vidar_runtime"

import "core:fmt"
import "core:encoding/json"

// the same generated json writer and %v printer as a.vidar: each file gets its own copy
other :: proc() {
	b, _ := __json_marshal_main_P(P{2, "b"})
	__fmt_0(string(b))
	__fmt_1(P{2, "b"})
}

// ---- generated by vidar ----

// fmt's %v for the types printed here, written out
@(private="file")
__print_main_P :: proc(w: __vidar.Writer, x: P) -> (n: int) {
	n += __vidar.w_str(w, "P{")
	n += __vidar.w_str(w, "x = ")
	n += __vidar.w_v(w, x.x)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "name = ")
	n += __vidar.w_quoted(w, x.name)
	n += __vidar.w_str(w, "}")
	return
}

@(private="file")
// json.marshal of P, written out: encoding/json's bytes
__json_marshal_main_P :: proc(x: $T, allocator := context.allocator) -> (data: []byte, err: json.Marshal_Error) {
	when T == P {
		b := __vidar.builder(allocator)
		__jsonw_main_P(__vidar.sb_writer(&b), x)
		return b.buf[:], nil
	} else {
		return json.marshal(x, allocator = allocator)
	}
}

@(private="file")
__jsonw_main_P :: proc(w: __vidar.Writer, x: P) {
	__vidar.w_str(w, "{")
	__vidar.w_str(w, "\"x\":")
	__vidar.w_d(w, x.x)
	__vidar.w_str(w, ",\"name\":")
	__vidar.w_json_str(w, x.name)
	__vidar.w_str(w, "}")
}
