package main; import __vidar "vidar_runtime"; import __vidar_intrinsics "base:intrinsics"

import "core:fmt"
import "core:net"
import "core:time"
import sched "vidar_runtime"

Color :: enum { Red, Green, Blue }

paint :: proc(id: int, scale: f64, c: Color, out: sched.Chan(string), wg: ^sched.Wait_Group) {
	defer sched.done(wg)
	sched.sleep(time.Duration(10 * (3 - id)) * time.Millisecond)
	__vidar.chan_send(out, fmt.aprintf("worker %d: %v x%.1f", id, c, scale))
}

producer :: proc(n: int, out: sched.Chan(int)) {
	for i in 0..<n {
		__vidar.chan_send(out, i * i)
	}
	sched.close(out)
}

echo_server :: proc(listener: net.TCP_Socket) {
	for {
		client, _, err := sched.accept(listener)
		if err != nil do return
		{ __go1_f := __closure_0(client); __vidar.go(__go_1(__go1_f)) }








	}
}

main :: proc() {
	// workers finish in reverse order of their sleeps; untyped args take the parameter types
	results := sched.make_chan(string, 3)
	wg: sched.Wait_Group
	for i in 0..<3 {
		sched.add(&wg)
		{ __go2_0: __vidar_intrinsics.type_proc_parameter_type(type_of(paint), 0) = i; __go2_1: __vidar_intrinsics.type_proc_parameter_type(type_of(paint), 1) = 2; __go2_2: __vidar_intrinsics.type_proc_parameter_type(type_of(paint), 2) = .Blue; __go2_3: __vidar_intrinsics.type_proc_parameter_type(type_of(paint), 3) = results; __go2_4: __vidar_intrinsics.type_proc_parameter_type(type_of(paint), 4) = &wg; __vidar.go(__go_2(__go2_0, __go2_1, __go2_2, __go2_3, __go2_4)) }
	}
	sched.wait(&wg)
	for _ in 0..<3 do fmt.println(__vidar.chan_recv(results))

	// range over a channel until it's closed
	squares := sched.make_chan(int)
	{ __go3_0: __vidar_intrinsics.type_proc_parameter_type(type_of(producer), 0) = 5; __go3_1: __vidar_intrinsics.type_proc_parameter_type(type_of(producer), 1) = squares; __vidar.go(__go_3(__go3_0, __go3_1)) }
	total := 0
	for {
		v, ok := __vidar.chan_recv(squares)
		if !ok do break
		total += v
	}
	fmt.println("sum of squares:", total)

	// closures capture by value; each goroutine gets its own copy of i
	done := sched.make_chan(int, 10)
	for i in 0..<10 { { __go4_f := __closure_1(i, done); __vidar.go(__go_4(__go4_f)) } }
	sum := 0
	for _ in 0..<10 do sum += __vidar.chan_recv(done)
	fmt.println("closure sum:", sum)

	// select with a timeout
	slow := sched.make_chan(string)
	timeout := sched.make_chan(bool, 1)
	{ __go5_f := __closure_2(slow); __vidar.go(__go_5(__go5_f)) }
	{ __go6_f := __closure_3(timeout); __vidar.go(__go_6(__go6_f)) }
	{ __sel1_c0 := slow; __sel1_0 := __vidar.chan_zero(__sel1_c0); __sel1_c1 := timeout; __sel1_1 := __vidar.chan_zero(__sel1_c1); __sel1 := []__vidar.Select_Case{__vidar.recv_case(__sel1_c0, &__sel1_0), __vidar.recv_case(__sel1_c1, &__sel1_1)}; __sel1_idx, __sel1_ok := __vidar.select_raw(__sel1, false); _ = __sel1_ok; switch __sel1_idx {
	case 0: msg := __sel1_0;
		fmt.println(msg)
	case 1:
		fmt.println("timed out")
	}}

	// non-blocking select
	empty := sched.make_chan(int)
	{ __sel2_c0 := empty; __sel2_0 := __vidar.chan_zero(__sel2_c0); __sel2 := []__vidar.Select_Case{__vidar.recv_case(__sel2_c0, &__sel2_0)}; __sel2_idx, __sel2_ok := __vidar.select_raw(__sel2, true); _ = __sel2_ok; switch __sel2_idx {
	case 0: v := __sel2_0;
		fmt.println("got", v)
	case:
		fmt.println("nothing ready")
	}}

	// TCP echo over the event loop
	listener, err := sched.listen_tcp({net.IP4_Loopback, 0})
	if err != nil {
		fmt.println("listen failed:", err)
		return
	}
	endpoint, _ := net.bound_endpoint(listener)
	{ __go7_0: __vidar_intrinsics.type_proc_parameter_type(type_of(echo_server), 0) = listener; __vidar.go(__go_7(__go7_0)) }
	replies := sched.make_chan(string)
	for k in 0..<3 {
		{ __go8_f := __closure_4(k, endpoint, replies); __vidar.go(__go_8(__go8_f)) }












	}
	got: [3]string
	for &r in got do r = __vidar.chan_recv(replies)
	fmt.println("echoed", len(got), "messages")
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0) -> __vidar.Closure(proc(rawptr)) {
	__Env :: struct {
		client: T0,
	}
	return __vidar.Closure(proc(rawptr)){
		call = proc(__env_raw: rawptr) { __env := cast(^__Env)__env_raw;
			buf: [256]byte
			for {
				n, rerr := sched.recv(__env.client, buf[:])
				if rerr != nil || n == 0 do break
				sched.send(__env.client, buf[:n])
			}
			sched.close(__env.client)
		},
		env = new_clone(__Env{__c0}),
	}
}

__go_1 :: proc(__c0: $T0) -> __vidar.Task {
	__Go_Env :: struct {
		c0: T0,
	}
	return {
		call = proc(__env_raw: rawptr) {
			__genv := cast(^__Go_Env)__env_raw
			__genv.c0.call(__genv.c0.env)
			free(__genv)
		},
		env = new_clone(__Go_Env{__c0}),
	}
}

__go_2 :: proc(__c0: $T0, __c1: $T1, __c2: $T2, __c3: $T3, __c4: $T4) -> __vidar.Task {
	__Go_Env :: struct {
		c0: T0,
		c1: T1,
		c2: T2,
		c3: T3,
		c4: T4,
	}
	return {
		call = proc(__env_raw: rawptr) {
			__genv := cast(^__Go_Env)__env_raw
			paint(__genv.c0, __genv.c1, __genv.c2, __genv.c3, __genv.c4)
			free(__genv)
		},
		env = new_clone(__Go_Env{__c0, __c1, __c2, __c3, __c4}),
	}
}

__go_3 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Task {
	__Go_Env :: struct {
		c0: T0,
		c1: T1,
	}
	return {
		call = proc(__env_raw: rawptr) {
			__genv := cast(^__Go_Env)__env_raw
			producer(__genv.c0, __genv.c1)
			free(__genv)
		},
		env = new_clone(__Go_Env{__c0, __c1}),
	}
}

__closure_1 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(rawptr)) {
	__Env :: struct {
		i: T0,
		done: T1,
	}
	return __vidar.Closure(proc(rawptr)){
		call = proc(__env_raw: rawptr) { __env := cast(^__Env)__env_raw; __vidar.chan_send(__env.done, __env.i) },
		env = new_clone(__Env{__c0, __c1}),
	}
}

__go_4 :: proc(__c0: $T0) -> __vidar.Task {
	__Go_Env :: struct {
		c0: T0,
	}
	return {
		call = proc(__env_raw: rawptr) {
			__genv := cast(^__Go_Env)__env_raw
			__genv.c0.call(__genv.c0.env)
			free(__genv)
		},
		env = new_clone(__Go_Env{__c0}),
	}
}

__closure_2 :: proc(__c0: $T0) -> __vidar.Closure(proc(rawptr)) {
	__Env :: struct {
		slow: T0,
	}
	return __vidar.Closure(proc(rawptr)){
		call = proc(__env_raw: rawptr) { __env := cast(^__Env)__env_raw; sched.sleep(50 * time.Millisecond); __vidar.chan_send(__env.slow, "too late") },
		env = new_clone(__Env{__c0}),
	}
}

__go_5 :: proc(__c0: $T0) -> __vidar.Task {
	__Go_Env :: struct {
		c0: T0,
	}
	return {
		call = proc(__env_raw: rawptr) {
			__genv := cast(^__Go_Env)__env_raw
			__genv.c0.call(__genv.c0.env)
			free(__genv)
		},
		env = new_clone(__Go_Env{__c0}),
	}
}

__closure_3 :: proc(__c0: $T0) -> __vidar.Closure(proc(rawptr)) {
	__Env :: struct {
		timeout: T0,
	}
	return __vidar.Closure(proc(rawptr)){
		call = proc(__env_raw: rawptr) { __env := cast(^__Env)__env_raw; sched.sleep(10 * time.Millisecond); __vidar.chan_send(__env.timeout, true) },
		env = new_clone(__Env{__c0}),
	}
}

__go_6 :: proc(__c0: $T0) -> __vidar.Task {
	__Go_Env :: struct {
		c0: T0,
	}
	return {
		call = proc(__env_raw: rawptr) {
			__genv := cast(^__Go_Env)__env_raw
			__genv.c0.call(__genv.c0.env)
			free(__genv)
		},
		env = new_clone(__Go_Env{__c0}),
	}
}

__go_7 :: proc(__c0: $T0) -> __vidar.Task {
	__Go_Env :: struct {
		c0: T0,
	}
	return {
		call = proc(__env_raw: rawptr) {
			__genv := cast(^__Go_Env)__env_raw
			echo_server(__genv.c0)
			free(__genv)
		},
		env = new_clone(__Go_Env{__c0}),
	}
}

__closure_4 :: proc(__c0: $T0, __c1: $T1, __c2: $T2) -> __vidar.Closure(proc(rawptr)) {
	__Env :: struct {
		k: T0,
		endpoint: T1,
		replies: T2,
	}
	return __vidar.Closure(proc(rawptr)){
		call = proc(__env_raw: rawptr) { __env := cast(^__Env)__env_raw;
			conn, derr := sched.dial(__env.endpoint)
			if derr != nil {
				__vidar.chan_send(__env.replies, fmt.aprint("dial failed:", derr))
				return
			}
			msg := fmt.aprintf("ping %d", __env.k)
			sched.send(conn, transmute([]byte)msg)
			buf: [64]byte
			n, _ := sched.recv(conn, buf[:])
			sched.close(conn)
			__vidar.chan_send(__env.replies, string(buf[:n]))
		},
		env = new_clone(__Env{__c0, __c1, __c2}),
	}
}

__go_8 :: proc(__c0: $T0) -> __vidar.Task {
	__Go_Env :: struct {
		c0: T0,
	}
	return {
		call = proc(__env_raw: rawptr) {
			__genv := cast(^__Go_Env)__env_raw
			__genv.c0.call(__genv.c0.env)
			free(__genv)
		},
		env = new_clone(__Go_Env{__c0}),
	}
}
