package main; import __vidar "vidar_runtime"

import "core:fmt"
import "core:net"
import "core:time"
import sched "vidar_sched"

Color :: enum { Red, Green, Blue }

paint :: proc(id: int, scale: f64, c: Color, out: sched.Chan(string), wg: ^sched.Wait_Group) {
	defer sched.done(wg)
	sched.sleep(time.Duration(10 * (3 - id)) * time.Millisecond)
	sched.send(out, fmt.aprintf("worker %d: %v x%.1f", id, c, scale))
}

producer :: proc(n: int, out: sched.Chan(int)) {
	for i in 0..<n do sched.send(out, i * i)
	sched.close(out)
}

echo_server :: proc(listener: net.TCP_Socket) {
	for {
		client, _, err := sched.accept(listener)
		if err != nil do return
		sched.go(__closure_0(client))
	}
}

main :: proc() {
	// workers finish in reverse order of their sleeps
	results := sched.make_chan(string, 3)
	wg: sched.Wait_Group
	for i in 0..<3 {
		sched.add(&wg)
		sched.go(__closure_1(i, results, &wg))
	}
	sched.wait(&wg)
	for _ in 0..<3 do fmt.println(sched.recv(results))

	// receive until the channel is closed
	squares := sched.make_chan(int)
	sched.go(__closure_2(squares))
	total := 0
	for {
		v, ok := sched.recv(squares)
		if !ok do break
		total += v
	}
	fmt.println("sum of squares:", total)

	// captures are copies, so each goroutine gets its own i
	done := sched.make_chan(int, 10)
	for i in 0..<10 do sched.go(__closure_3(i, done))
	sum := 0
	for _ in 0..<10 do sum += sched.recv(done)
	fmt.println("closure sum:", sum)

	// select with a timeout
	slow := sched.make_chan(string)
	timeout := sched.make_chan(bool, 1)
	sched.go(__closure_4(slow))
	sched.go(__closure_5(timeout))
	msg: string
	switch sched.select(sched.on_recv(slow, &msg), sched.on_recv(timeout)) {
	case 0: fmt.println(msg)
	case 1: fmt.println("timed out")
	}

	// non-blocking select, and a closed channel
	empty := sched.make_chan(int)
	closed := sched.make_chan(int)
	sched.close(closed)
	got: bool
	switch sched.try_select(sched.on_recv(empty)) {
	case -1: fmt.println("nothing ready")
	}
	switch sched.select(sched.on_recv(empty), sched.on_recv(closed, ok = &got)) {
	case 1: fmt.println("closed channel, ok =", got)
	}

	// TCP echo over the event loop
	listener, err := sched.listen_tcp({net.IP4_Loopback, 0})
	if err != nil {
		fmt.println("listen failed:", err)
		return
	}
	endpoint, _ := net.bound_endpoint(listener)
	sched.go(__closure_6(listener))
	replies := sched.make_chan(string)
	for k in 0..<3 {
		sched.go(__closure_7(k, endpoint, replies))
	}
	echoed: [3]string
	for &r in echoed do r = sched.recv(replies)
	fmt.println("echoed", len(echoed), "messages")
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		client: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:25: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw;
			buf: [256]byte
			for {
				n, rerr := sched.recv(__env.client, buf[:])
				if rerr != nil || n == 0 do break
				sched.send(__env.client, buf[:n])
			}
			sched.close(__env.client)
		},
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_1 :: proc(__c0: $T0, __c1: $T1, __c2: $T2) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		i: T0,
		results: T1,
		wg: T2,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:43: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw; paint(__env.i, 2, .Blue, __env.results, &__env.wg^) },
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1, __c2}},
	}
}

__closure_2 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		squares: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:50: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw; producer(5, __env.squares) },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_3 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		i: T0,
		done: T1,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:61: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw; sched.send(__env.done, __env.i) },
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1}},
	}
}

__closure_4 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		slow: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:69: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw; sched.sleep(50 * time.Millisecond); sched.send(__env.slow, "too late") },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_5 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		timeout: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:70: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw; sched.sleep(10 * time.Millisecond); sched.send(__env.timeout, true) },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_6 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		listener: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:96: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw; echo_server(__env.listener) },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_7 :: proc(__c0: $T0, __c1: $T1, __c2: $T2) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		k: T0,
		endpoint: T1,
		replies: T2,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:99: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw;
			conn, derr := sched.dial(__env.endpoint)
			if derr != nil {
				sched.send(__env.replies, fmt.aprint("dial failed:", derr))
				return
			}
			msg := fmt.aprintf("ping %d", __env.k)
			sched.send(conn, transmute([]byte)msg)
			buf: [64]byte
			n, _ := sched.recv(conn, buf[:])
			sched.close(conn)
			sched.send(__env.replies, string(buf[:n]))
		},
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1, __c2}},
	}
}
