package main

import "core:fmt"

Named :: struct { data: rawptr, __vtable: ^__Named_VTable }
name :: proc{__Named_name, box_name}

Sized :: struct { data: rawptr, __vtable: ^__Sized_VTable }
size :: proc{__Sized_size, box_size}

// Extends two interfaces and adds a method of its own.
Item :: struct { data: rawptr, __vtable: ^__Item_VTable }
describe :: proc{__Item_describe, box_describe}

// Diamond: both bases extend Named.
Labeled :: struct { data: rawptr, __vtable: ^__Labeled_VTable }
label :: proc{__Labeled_label, box_label}

Product :: struct { data: rawptr, __vtable: ^__Product_VTable }

Box :: struct { w, h: int }

box_name     :: proc(b: ^Box) -> string { return "box" }
box_size     :: proc(b: ^Box) -> int    { return b.w * b.h }
box_describe :: proc(b: ^Box) -> string { return fmt.tprintf("%dx%d", b.w, b.h) }
box_label    :: proc(b: ^Box) -> string { return "BOX" }

// Also implements Named, Sized, Item and Labeled.


print_named :: proc(n: Named) { fmt.println("named:", name(n)) }

total :: proc(items: []Sized) -> (sum: int) {
	for s in items do sum += size(s)
	return
}

main :: proc() {
	b := Box{2, 3}
	fmt.println("static:", name(&b), size(&b), describe(&b), label(&b))

	p: Product = __Product_from(&b)
	fmt.println("dynamic:", name(__Product_as_Named(p)), size(__Product_as_Sized(p)), describe(__Product_as_Item(p)), label(__Product_as_Labeled(p)))

	i: Item = __Product_as_Item(p)
	print_named(__Item_as_Named(i))
	print_named(__Product_as_Named(p))
	print_named(__Named_from(&b))
	print_named(__Product_as_Named(p))

	l := __Labeled_from(&b)
	fmt.println("labeled:", label(l), name(__Labeled_as_Named(l)))

	sized: [dynamic]Sized
	append(&sized, __Item_as_Sized(i), __Product_as_Sized(p), __Sized_from(&b))
	fmt.println("total:", total(sized[:]))
}

// ---- generated by vidar ----

__Named_VTable :: struct {
	name: proc(self: Named) -> string,
}

__Named_name :: proc(n: Named) -> string { return n.__vtable.name(n) }

__Named_identity :: #force_inline proc(v: Named) -> Named { return v }

__Named_from :: proc{__Named_from_Box, __Named_identity}

__Sized_VTable :: struct {
	size: proc(self: Sized) -> int,
}

__Sized_size :: proc(s: Sized) -> int { return s.__vtable.size(s) }

__Sized_identity :: #force_inline proc(v: Sized) -> Sized { return v }

__Sized_from :: proc{__Sized_from_Box, __Sized_identity}

__Item_VTable :: struct {
	__Named: __Named_VTable,
	__Sized: __Sized_VTable,
	describe: proc(self: Item) -> string,
}

__Item_describe :: proc(i: Item) -> string { return i.__vtable.describe(i) }

__Item_as_Named :: #force_inline proc(v: Item) -> Named { return {data = v.data, __vtable = &v.__vtable.__Named} }

__Item_as_Sized :: #force_inline proc(v: Item) -> Sized { return {data = v.data, __vtable = &v.__vtable.__Sized} }

__Item_identity :: #force_inline proc(v: Item) -> Item { return v }

__Item_from :: proc{__Item_from_Box, __Item_identity}

__Labeled_VTable :: struct {
	__Named: __Named_VTable,
	label: proc(self: Labeled) -> string,
}

__Labeled_label :: proc(l: Labeled) -> string { return l.__vtable.label(l) }

__Labeled_as_Named :: #force_inline proc(v: Labeled) -> Named { return {data = v.data, __vtable = &v.__vtable.__Named} }

__Labeled_identity :: #force_inline proc(v: Labeled) -> Labeled { return v }

__Labeled_from :: proc{__Labeled_from_Box, __Labeled_identity}

__Product_VTable :: struct {
	__Item: __Item_VTable,
	__Labeled: __Labeled_VTable,
}

__Product_as_Item :: #force_inline proc(v: Product) -> Item { return {data = v.data, __vtable = &v.__vtable.__Item} }

__Product_as_Named :: #force_inline proc(v: Product) -> Named { return {data = v.data, __vtable = &v.__vtable.__Item.__Named} }

__Product_as_Sized :: #force_inline proc(v: Product) -> Sized { return {data = v.data, __vtable = &v.__vtable.__Item.__Sized} }

__Product_as_Labeled :: #force_inline proc(v: Product) -> Labeled { return {data = v.data, __vtable = &v.__vtable.__Labeled} }

__Product_identity :: #force_inline proc(v: Product) -> Product { return v }

__Product_from :: proc{__Product_from_Box, __Product_identity}

@(rodata)
__Product_vtable_Box := __Product_VTable{
	__Item = {
		__Named = {
			name = proc(self: Named) -> string { return box_name((^Box)(self.data)) },
		},
		__Sized = {
			size = proc(self: Sized) -> int { return box_size((^Box)(self.data)) },
		},
		describe = proc(self: Item) -> string { return box_describe((^Box)(self.data)) },
	},
	__Labeled = {
		__Named = {
			name = proc(self: Named) -> string { return box_name((^Box)(self.data)) },
		},
		label = proc(self: Labeled) -> string { return box_label((^Box)(self.data)) },
	},
}

__Product_from_Box :: proc(p: ^Box) -> Product { return {data = p, __vtable = &__Product_vtable_Box} }

@(rodata)
__Item_vtable_Box := __Item_VTable{
	__Named = {
		name = proc(self: Named) -> string { return box_name((^Box)(self.data)) },
	},
	__Sized = {
		size = proc(self: Sized) -> int { return box_size((^Box)(self.data)) },
	},
	describe = proc(self: Item) -> string { return box_describe((^Box)(self.data)) },
}

__Item_from_Box :: proc(p: ^Box) -> Item { return {data = p, __vtable = &__Item_vtable_Box} }

@(rodata)
__Named_vtable_Box := __Named_VTable{
	name = proc(self: Named) -> string { return box_name((^Box)(self.data)) },
}

__Named_from_Box :: proc(p: ^Box) -> Named { return {data = p, __vtable = &__Named_vtable_Box} }

@(rodata)
__Sized_vtable_Box := __Sized_VTable{
	size = proc(self: Sized) -> int { return box_size((^Box)(self.data)) },
}

__Sized_from_Box :: proc(p: ^Box) -> Sized { return {data = p, __vtable = &__Sized_vtable_Box} }

@(rodata)
__Labeled_vtable_Box := __Labeled_VTable{
	__Named = {
		name = proc(self: Named) -> string { return box_name((^Box)(self.data)) },
	},
	label = proc(self: Labeled) -> string { return box_label((^Box)(self.data)) },
}

__Labeled_from_Box :: proc(p: ^Box) -> Labeled { return {data = p, __vtable = &__Labeled_vtable_Box} }
