package main; import __vidar "vidar_runtime"

import "core:fmt"
import sched "vidar_sched"

Point :: struct { x, y: int }

make_adder :: proc(k: int) -> __vidar.Closure(proc(__vidar.Env, int) -> int) {
	return __closure_0(k)
}

main :: proc() {
	// captures are copied into the closure value, so a returned closure keeps them
	add := make_adder(10)
	fmt.println(add.call(add.env, 1))

	// each closure made in a loop has its own copy
	prints: [dynamic]__vidar.Closure(proc(__vidar.Env) -> int)
	defer delete(prints)
	for i in 0..<3 do append(&prints, __closure_1(i))
	for f in prints do fmt.print(f.call(f.env), "")
	fmt.println()

	// copying a closure copies its captures; a pointer capture is shared
	p := Point{1, 2}
	hits := 0
	show := __closure_2(p, &hits)
	p.x = 100
	copy := show
	fmt.println(show.call(show.env), copy.call(copy.env), hits, p.x)

	// writes through a captured pointer reach the original
	q := new_clone(Point{3, 4})
	defer free(q)
	shift := __closure_3(q)
	shift.call(shift.env, 5)
	fmt.println(q.x)

	// a closure holding another closure keeps a pointer to it
	inner := make_adder(1)
	outer := __closure_4(&inner)
	fmt.println(outer.call(outer.env, 4))

	// goroutines get their captures by value too
	done := sched.make_chan(int, 3)
	for id in 0..<3 do sched.go(__closure_5(id, done))
	sum := 0
	for _ in 0..<3 do sum += sched.recv(done)
	fmt.println("goroutines:", sum)

	fmt.println("closure size:", size_of(add))
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int) -> int) {
	__Caps :: struct {
		k: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:9: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int) -> int){
		call = proc(__env_raw: __vidar.Env, x: int) -> int { __env := transmute(__Env)__env_raw; return x + __env.k },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_1 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env) -> int) {
	__Caps :: struct {
		i: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:20: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env) -> int){
		call = proc(__env_raw: __vidar.Env) -> int { __env := transmute(__Env)__env_raw; return __env.i * 10 },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_2 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(__vidar.Env) -> int) {
	__Caps :: struct {
		p: T0,
		hits: T1,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:27: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env) -> int){
		call = proc(__env_raw: __vidar.Env) -> int { __env := transmute(__Env)__env_raw; __env.hits^ += 1; return __env.p.x + __env.p.y },
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1}},
	}
}

__closure_3 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int)) {
	__Caps :: struct {
		q: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:35: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int)){
		call = proc(__env_raw: __vidar.Env, d: int) { __env := transmute(__Env)__env_raw; __env.q.x += d },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_4 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int) -> int) {
	__Caps :: struct {
		inner: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:41: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int) -> int){
		call = proc(__env_raw: __vidar.Env, x: int) -> int { __env := transmute(__Env)__env_raw; return __env.inner^.call(__env.inner^.env, x) * 2 },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_5 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		id: T0,
		done: T1,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:46: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw; sched.send(__env.done, __env.id * __env.id) },
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1}},
	}
}
