package main; import __vidar "vidar_runtime"

import "core:fmt"
import "core:slice"
import sched "vidar_sched"

N :: 16

sum :: proc(xs: []int) -> (total: int) {
	for x in xs do total += x
	return
}

// keeps what it is given: a caller's buffer can't go on the stack
Keeper :: struct { kept: []int }
keep :: proc(k: ^Keeper, xs: []int) { k.kept = xs }

first :: proc(xs: []int) -> []int { return xs }

// opted out

heap_only :: proc() -> int {
	xs := make([]int, 8)
	defer delete(xs)
	xs[7] = 9
	return xs[7]
}

// a goroutine runs this: 8 KB is over the 4 KB limit for goroutine stacks
worker :: proc(done: sched.Chan(int)) {
	buf := make([]int, 1024)
	defer delete(buf)
	buf[1023] = 5
	__small_buf: [64]int; small := __small_buf[:]
	/* delete(small): small is on the stack */
	small[0] = 1
	sched.send(done, buf[1023] + small[0])
}

main :: proc() {
	// constant size, indexed, passed to procs that don't keep it: on the stack
	__a_buf: [N]int; a := __a_buf[:]
	/* delete(a): a is on the stack */
	for i in 0..<len(a) do #no_bounds_check a[i] = N - i
	slice.sort(a)
	__fmt_0(sum(a), a[0], a[N - 1])

	// a constant expression
	__b_buf: [N * 2 + 1]f64; b := __b_buf[:]
	/* delete(b): b is on the stack */
	b[3] = 1.5
	__fmt_1(len(b), b[3])

	// not constant: stays on the heap
	n := 8
	c := make([]int, n)
	defer delete(c)
	__fmt_2(len(c))

	// kept by the callee
	k: Keeper
	d := make([]int, 4)
	defer delete(d)
	keep(&k, d)
	__fmt_2(len(k.kept))

	// returned through a callee
	e := make([]int, 4)
	defer delete(e)
	__fmt_2(len(first(e)))

	// sliced
	f := make([]int, 4)
	defer delete(f)
	g := f[1:]
	__fmt_2(len(g))

	// too big: 100 000 ints
	h := make([]int, 100_000)
	defer delete(h)
	h[99_999] = 7
	__fmt_2(h[99_999])

	__fmt_2(heap_only())

	done := sched.make_chan(int, 1)
	sched.go(__closure_0(done))
	fmt.println(sched.recv(done))

	// a stack buffer in a loop is a fresh, zeroed one each time
	for round in 0..<3 {
		__r_buf: [4]int; r := __r_buf[:]
		/* delete(r): r is on the stack */
		r[round] += round + 1
		__fmt_3(r)
	}
}

// ---- generated by vidar ----

// fmt.println
__fmt_0 :: proc(a0: $T0, a1: $T1, a2: $T2) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a2)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_1 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_2 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

__closure_0 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		done: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:87: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw; worker(__env.done) },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

// fmt.println
__fmt_3 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	when T0 == []int { n += __print_sl_int(w, a0) } else { n += __vidar.w_spec(w, a0, "%v") }
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt's %v for the types printed here, written out
__print_sl_int :: proc(w: __vidar.Writer, x: []int) -> (n: int) {
	if raw_data(x) == nil && len(x) > 0 {
		__vidar.w_str(w, "nil")
		return
	}
	n += __vidar.w_str(w, "[")
	for e, i in x {
		if i > 0 do n += __vidar.w_str(w, ", ")
		n += __vidar.w_v(w, e)
	}
	n += __vidar.w_str(w, "]")
	return
}
