package util; import __vidar "../vidar_runtime"

// Not part of the cycle, so it stays its own Odin package.
// Closures still cross the package boundary: they share one runtime type.
every :: proc(n: int, f: __vidar.Closure(proc(__vidar.Env, int))) -> __vidar.Closure(proc(__vidar.Env, int)) {
	fp := new_clone(f)
	return __closure_0(n, fp)
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(__vidar.Env, int)) {
	__Caps :: struct {
		n: T0,
		fp: T1,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at util.vidar:7: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int)){
		call = proc(__env_raw: __vidar.Env, frame: int) { __env := transmute(__Env)__env_raw; if frame % __env.n == 0 do __call_closure_0(__env.fp^, frame) },
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1}},
	}
}

__call_closure_0 :: #force_inline proc(c: __vidar.Closure(proc(__vidar.Env, int)), p0: int) {
	c.call(c.env, p0)
}
