package util; import __vidar "../vidar_runtime"

// Not part of the cycle, so it stays its own Odin package.
// Closures still cross the package boundary: they share one runtime type.
every :: proc(n: int, f: __vidar.Closure(proc(rawptr, int))) -> __vidar.Closure(proc(rawptr, int)) {
	return __closure_0(n, f)
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(rawptr, int)) {
	__Env :: struct {
		n: T0,
		f: T1,
	}
	return __vidar.Closure(proc(rawptr, int)){
		call = proc(__env_raw: rawptr, frame: int) { __env := cast(^__Env)__env_raw; if frame % __env.n == 0 do __env.f.call(__env.f.env, frame) },
		env = new_clone(__Env{__c0, __c1}),
	}
}
