package main; import __vidar "vidar_runtime"

import "core:fmt"
import "core:math"

// An interface lists its methods. Each method is declared at the top level without a body,
// taking the interface first; calling it on an interface value dispatches through the vtable.
Shape :: struct { data: rawptr, __vtable: ^__Shape_VTable }

area  :: proc{__Shape_area, circle_area, rect_area}
name  :: proc{__Shape_name, circle_name, rect_name}
scale :: proc{__Shape_scale, circle_scale, rect_scale}

Circle :: struct { r: f64 }
Rect   :: struct { w, h: f64 }

// Implementations are ordinary procs taking a pointer to the type first.
circle_area  :: proc(c: ^Circle) -> f64    { return math.PI * c.r * c.r }
circle_name  :: proc(c: ^Circle) -> string { return "circle" }
circle_scale :: proc(c: ^Circle, k: f64)   { c.r *= k }

rect_area  :: proc(r: ^Rect) -> f64    { return r.w * r.h }
rect_name  :: proc(r: ^Rect) -> string { return "rect" }
rect_scale :: proc(r: ^Rect, k: f64)   { r.w *= k; r.h *= k }

// An impl binds each method to a proc.








// One type can implement several interfaces; implementations may use closures.
Writer :: struct { data: rawptr, __vtable: ^__Writer_VTable }

write :: proc{__Writer_write, log_write}

Log :: struct { lines: [dynamic]string, bytes: int }

log_write :: proc(l: ^Log, s: string) -> int {
	count := __closure_0(l)
	count.call(count.env, len(s))
	append(&l.lines, s)
	return len(s)
}



total_area :: proc(shapes: []Shape) -> (sum: f64) {
	for s in shapes do sum += area(s)
	return
}

biggest :: proc(a, b: Shape) -> Shape {
	return a if area(a) >= area(b) else b
}

describe :: proc(s: Shape) -> string {
	return fmt.tprintf("%s(%.2f)", name(s), area(s))
}

unit_square :: proc() -> Shape {
	return __Shape_from(new_clone(Rect{1, 1}))
}

Scene :: struct {
	hero:  Shape,
	label: string,
}

main :: proc() {
	c := Circle{1}
	r := Rect{2, 3}

	// Called on the concrete type, a method is a plain static call (no vtable).
	fmt.printf("circle area: %.2f\n", area(&c))

	// A pointer converts implicitly: the interface refers to `c` itself.
	s: Shape = __Shape_from(&c)
	scale(s, 2)
	fmt.println("c.r after scale through interface:", c.r)

	// Interfaces always hold a pointer; new_clone makes an owned heap copy explicitly.
	shapes: [dynamic]Shape
	append(&shapes, __Shape_from(&c), __Shape_from(&r), __Shape_from(new_clone(Rect{0.5, 4})))
	for sh in shapes do fmt.println(describe(sh))
	fmt.printf("total: %.2f\n", total_area(shapes[:]))

	// Arguments convert implicitly; Shape(...) converts explicitly.
	fmt.println("biggest:", name(biggest(__Shape_from(&r), __Shape_from(&c))))

	// So do named struct-literal fields and `return` values.
	scene := Scene{hero = __Shape_from(&r), label = "intro"}
	fmt.println("scene:", scene.label, describe(scene.hero), describe(unit_square()))

	log: Log
	w: Writer = __Writer_from(&log)
	write(w, "hello ")
	write(&log, "vidar")
	fmt.println("log:", log.lines[:], log.bytes, "bytes")
}

// ---- generated by vidar ----

__Shape_VTable :: struct {
	area: proc(self: Shape) -> f64,
	name: proc(self: Shape) -> string,
	scale: proc(self: Shape, k: f64),
}

__Shape_area :: proc(s: Shape) -> f64 {
	if s.__vtable == &__Shape_vtable_Circle { return circle_area(auto_cast s.data) }
	if s.__vtable == &__Shape_vtable_Rect { return rect_area(auto_cast s.data) }
	return s.__vtable.area(s)
}

__Shape_name :: proc(s: Shape) -> string {
	if s.__vtable == &__Shape_vtable_Circle { return circle_name(auto_cast s.data) }
	if s.__vtable == &__Shape_vtable_Rect { return rect_name(auto_cast s.data) }
	return s.__vtable.name(s)
}

__Shape_scale :: proc(s: Shape, k: f64) {
	if s.__vtable == &__Shape_vtable_Circle { circle_scale(auto_cast s.data, k); return }
	if s.__vtable == &__Shape_vtable_Rect { rect_scale(auto_cast s.data, k); return }
	s.__vtable.scale(s, k)
}

__Shape_identity :: #force_inline proc(v: Shape) -> Shape { return v }

__Shape_from :: proc{__Shape_from_Circle, __Shape_from_Rect, __Shape_identity}

@(rodata)
__Shape_vtable_Circle := __Shape_VTable{
	area = proc(self: Shape) -> f64 { return circle_area((^Circle)(self.data)) },
	name = proc(self: Shape) -> string { return circle_name((^Circle)(self.data)) },
	scale = proc(self: Shape, k: f64) { circle_scale((^Circle)(self.data), k) },
}

__Shape_from_Circle :: proc(p: ^Circle) -> Shape { return {data = p, __vtable = &__Shape_vtable_Circle} }

@(rodata)
__Shape_vtable_Rect := __Shape_VTable{
	area = proc(self: Shape) -> f64 { return rect_area((^Rect)(self.data)) },
	name = proc(self: Shape) -> string { return rect_name((^Rect)(self.data)) },
	scale = proc(self: Shape, k: f64) { rect_scale((^Rect)(self.data), k) },
}

__Shape_from_Rect :: proc(p: ^Rect) -> Shape { return {data = p, __vtable = &__Shape_vtable_Rect} }

__Writer_VTable :: struct {
	write: proc(self: Writer, s: string) -> int,
}

__Writer_write :: proc(w: Writer, s: string) -> int {
	if w.__vtable == &__Writer_vtable_Log { return log_write(auto_cast w.data, s) }
	return w.__vtable.write(w, s)
}

__Writer_identity :: #force_inline proc(v: Writer) -> Writer { return v }

__Writer_from :: proc{__Writer_from_Log, __Writer_identity}

__closure_0 :: proc(__c0: $T0) -> __vidar.Closure(proc(rawptr, int)) {
	__Env :: struct {
		l: T0,
	}
	return __vidar.Closure(proc(rawptr, int)){
		call = proc(__env_raw: rawptr, n: int) { __env := cast(^__Env)__env_raw; __env.l.bytes += n },
		env = new_clone(__Env{__c0}),
	}
}

@(rodata)
__Writer_vtable_Log := __Writer_VTable{
	write = proc(self: Writer, s: string) -> int { return log_write((^Log)(self.data), s) },
}

__Writer_from_Log :: proc(p: ^Log) -> Writer { return {data = p, __vtable = &__Writer_vtable_Log} }
