package main

import "core:fmt"

// Anonymous struct literals outside `:=` declarations in procs: globals,
// if/for/switch initializers, and arguments whose parameter type is inferred.

LIMIT :: 3

config := struct { name: type_of(__anon_typed("slime")), size: type_of(__anon_typed(LIMIT * 2)), scale: type_of(__anon_typed(1.5)), origin: struct { x: type_of(__anon_typed(0)), y: type_of(__anon_typed(-1)) } }{name = "slime", size = LIMIT * 2, scale = 1.5, origin = {x = 0, y = -1}}
banner := struct { text: type_of(__anon_typed("http://x // not a comment")), width: type_of(__anon_typed(40)) }{text = "http://x // not a comment", width = 40}

describe :: proc(v: $T) -> string { return fmt.tprintf("%v", v) }

show :: proc(label: string, values: ..any) {
	fmt.print(label)
	for v in values do fmt.print("", v)
	fmt.println()
}

call_f :: proc(v: $T) -> int { return v.f(v.k) }

hp_of :: proc(v: struct { name: string, hp: int }) -> int { return v.hp }

calls := 0
next :: proc() -> int { calls += 1; return calls }

main :: proc() {
	config.size += 1
	fmt.println(config, config.origin.y, banner.text)

	// initializers: evaluated once, scoped to the statement
	if p := (struct { hp: type_of(__anon_typed(next())), name: type_of(__anon_typed("a")) }{hp = next(), name = "a"}); p.hp > 0 {
		fmt.println(p.name, p.hp, calls)
	}
	for c := (struct { i: type_of(__anon_typed(0)), step: type_of(__anon_typed(2)) }{i = 0, step = 2}); c.i < 6; c.i += c.step {
		fmt.print(c.i, "")
	}
	fmt.println()
	switch s := (struct { kind: type_of(__anon_typed('b')), n: type_of(__anon_typed(next())) }{kind = 'b', n = next()}); s.kind {
	case 'a': fmt.println("a")
	case 'b': fmt.println("b", s.n)
	}

	// arguments to $T, ..any and fmt's print procs
	fmt.println(describe(struct { a: type_of(__anon_typed(1)), b: type_of(__anon_typed("two")) }{a = 1, b = "two"}))
	show("show:", struct { x: type_of(__anon_typed(1.5)) }{x = 1.5}, 7, struct { y: type_of(__anon_typed(true)), z: struct { w: type_of(__anon_typed('w')) } }{y = true, z = {w = 'w'}})
	fmt.println(struct { hp: type_of(__anon_typed(10)), name: type_of(__anon_typed("hero")) }{hp = 10, name = "hero"}, struct { calls: type_of(__anon_typed(next())) }{calls = next()})
	fmt.println(call_f(struct { k: type_of(__anon_typed(LIMIT)), f: proc(x: int) -> int }{k = LIMIT, f = proc(x: int) -> int { return x * 10 }}))
	fmt.printf("%v %v\n", struct { q: type_of(__anon_typed(1)) }{q = 1}, struct { r: type_of(__anon_typed(2)), s: type_of(__anon_typed("s")) }{r = 2, s = "s"})

	// a parameter with a type keeps Odin's meaning
	fmt.println(hp_of({ name = "typed", hp = 5 }))
	fmt.println(calls)
}

// ---- generated by vidar ----

// the default type of an untyped constant, for anonymous struct fields
@(private = "file")
__anon_typed :: #force_inline proc "contextless" (x: $T) -> T { return x }
