package main

import "core:fmt"

Shape :: struct { data: rawptr, __vtable: ^__Shape_VTable }
area  :: proc{__Shape_area, circle_area, rect_area, dot_area}
scale :: proc{__Shape_scale, circle_scale, rect_scale, dot_scale}
name  :: proc{__Shape_name, circle_name, rect_name, dot_name}

Circle :: struct { r: f64 }
Rect   :: struct { w, h: f64 }
Dot    :: struct {}

circle_area  :: proc(c: ^Circle) -> f64 { return 3 * c.r * c.r }
circle_scale :: proc(c: ^Circle, k: f64) { c.r *= k }
circle_name  :: proc(c: ^Circle) -> string { return "circle" }
rect_area    :: proc(r: ^Rect) -> f64 { return r.w * r.h }
rect_scale   :: proc(r: ^Rect, k: f64) { r.w *= k; r.h *= k }
rect_name    :: proc(r: ^Rect) -> string { return "rect" }
dot_area     :: proc(d: ^Dot) -> f64 { return 0 }
dot_scale    :: proc(d: ^Dot, k: f64) {}
dot_name     :: proc(d: ^Dot) -> string { return "dot" }





Scene :: struct {
	shapes: __Shape_Pool,
}

describe :: proc(s: Shape) -> string { return fmt.tprintf("%s %.1f", name(s), area(s)) }

total :: proc(p: ^__Shape_Pool) -> (sum: f64) {
	for &__s in p.Circle { s := &__s; sum += area(s) }
	for &__s in p.Rect { s := &__s; sum += area(s) }
	for &__s in p.Dot { s := &__s; sum += area(s) }
	return
}

make_scene :: proc() -> ^Scene {
	sc := new(Scene)
	c := Circle{1}
	append(&sc.shapes.Rect, Rect{2, 3}); append(&sc.shapes.Circle, Circle{2}, c); append(&sc.shapes.Rect, Rect{1, 1})
	append(&sc.shapes.Dot, Dot{})
	return sc
}

main :: proc() {
	sc := make_scene()
	fmt.println("len:", __Shape_Pool_len(sc.shapes), "total:", total(&sc.shapes))

	// each type's values are visited together, in insertion order within a type
	for &__s in sc.shapes.Circle { s := &__s;
		fmt.println(describe(__Shape_from(s)))
	}
	for &__s in sc.shapes.Rect { s := &__s;
		fmt.println(describe(__Shape_from(s)))
	}
	for &__s in sc.shapes.Dot { s := &__s;
		fmt.println(describe(__Shape_from(s)))
	}

	// a pointer to the element: methods that change it change the pool
	for &__s in sc.shapes.Circle { s := &__s; scale(s, 2) }
	for &__s in sc.shapes.Rect { s := &__s; scale(s, 2) }
	for &__s in sc.shapes.Dot { s := &__s; scale(s, 2) }
	fmt.println("scaled total:", total(&sc.shapes))

	// break leaves the whole loop, continue goes on with the next value
	found := ""
	__pool3: { for &__s in sc.shapes.Circle { s := &__s;
		if area(s) < 10 do continue
		found = name(s)
		break __pool3
	}
	for &__s in sc.shapes.Rect { s := &__s;
		if area(s) < 10 do continue
		found = name(s)
		break __pool3
	}
	for &__s in sc.shapes.Dot { s := &__s;
		if area(s) < 10 do continue
		found = name(s)
		break __pool3
	} }
	fmt.println("first big:", found)

	outer: { outer__Circle: for &__s in sc.shapes.Circle { s := &__s;
		fmt.println("visiting", name(s))
		for i in 0..<3 {
			if i == 1 do continue outer__Circle
			if name(s) == "rect" do break outer
		}
		fmt.println("visited", name(s))
	}
	outer__Rect: for &__s in sc.shapes.Rect { s := &__s;
		fmt.println("visiting", name(s))
		for i in 0..<3 {
			if i == 1 do continue outer__Rect
			if name(s) == "rect" do break outer
		}
		fmt.println("visited", name(s))
	}
	outer__Dot: for &__s in sc.shapes.Dot { s := &__s;
		fmt.println("visiting", name(s))
		for i in 0..<3 {
			if i == 1 do continue outer__Dot
			if name(s) == "rect" do break outer
		}
		fmt.println("visited", name(s))
	} }

	// stored as the interface, it converts like any pointer to an implementation
	list: [dynamic]Shape
	for &__s in sc.shapes.Circle { s := &__s;
		if name(s) != "dot" do append(&list, __Shape_from(s))
	}
	for &__s in sc.shapes.Rect { s := &__s;
		if name(s) != "dot" do append(&list, __Shape_from(s))
	}
	for &__s in sc.shapes.Dot { s := &__s;
		if name(s) != "dot" do append(&list, __Shape_from(s))
	}
	fmt.println("as interfaces:", len(list), describe(list[0]))

	__Shape_Pool_clear(&sc.shapes)
	fmt.println("cleared:", __Shape_Pool_len(sc.shapes))
	__Shape_Pool_delete(sc.shapes)
}

// ---- generated by vidar ----

__Shape_VTable :: struct {
	area: proc(self: Shape) -> f64,
	scale: proc(self: Shape, k: f64),
	name: proc(self: Shape) -> string,
}

__Shape_area :: proc(s: Shape) -> f64 {
	if s.__vtable == &__Shape_vtable_Circle { return circle_area(auto_cast s.data) }
	if s.__vtable == &__Shape_vtable_Rect { return rect_area(auto_cast s.data) }
	if s.__vtable == &__Shape_vtable_Dot { return dot_area(auto_cast s.data) }
	return s.__vtable.area(s)
}

__Shape_scale :: proc(s: Shape, k: f64) {
	if s.__vtable == &__Shape_vtable_Circle { circle_scale(auto_cast s.data, k); return }
	if s.__vtable == &__Shape_vtable_Rect { rect_scale(auto_cast s.data, k); return }
	if s.__vtable == &__Shape_vtable_Dot { dot_scale(auto_cast s.data, k); return }
	s.__vtable.scale(s, k)
}

__Shape_name :: proc(s: Shape) -> string {
	if s.__vtable == &__Shape_vtable_Circle { return circle_name(auto_cast s.data) }
	if s.__vtable == &__Shape_vtable_Rect { return rect_name(auto_cast s.data) }
	if s.__vtable == &__Shape_vtable_Dot { return dot_name(auto_cast s.data) }
	return s.__vtable.name(s)
}

__Shape_identity :: #force_inline proc(v: Shape) -> Shape { return v }

__Shape_from :: proc{__Shape_from_Circle, __Shape_from_Rect, __Shape_from_Dot, __Shape_identity}

__Shape_Pool :: struct {
	Circle: [dynamic]Circle,
	Rect: [dynamic]Rect,
	Dot: [dynamic]Dot,
}

__Shape_Pool_len :: #force_inline proc(p: __Shape_Pool) -> int { return len(p.Circle) + len(p.Rect) + len(p.Dot) }

__Shape_Pool_clear :: proc(p: ^__Shape_Pool) { clear(&p.Circle); clear(&p.Rect); clear(&p.Dot) }

__Shape_Pool_delete :: proc(p: __Shape_Pool) { delete(p.Circle); delete(p.Rect); delete(p.Dot) }

@(rodata)
__Shape_vtable_Circle := __Shape_VTable{
	area = proc(self: Shape) -> f64 { return circle_area((^Circle)(self.data)) },
	scale = proc(self: Shape, k: f64) { circle_scale((^Circle)(self.data), k) },
	name = proc(self: Shape) -> string { return circle_name((^Circle)(self.data)) },
}

__Shape_from_Circle :: proc(p: ^Circle) -> Shape { return {data = p, __vtable = &__Shape_vtable_Circle} }

@(rodata)
__Shape_vtable_Rect := __Shape_VTable{
	area = proc(self: Shape) -> f64 { return rect_area((^Rect)(self.data)) },
	scale = proc(self: Shape, k: f64) { rect_scale((^Rect)(self.data), k) },
	name = proc(self: Shape) -> string { return rect_name((^Rect)(self.data)) },
}

__Shape_from_Rect :: proc(p: ^Rect) -> Shape { return {data = p, __vtable = &__Shape_vtable_Rect} }

@(rodata)
__Shape_vtable_Dot := __Shape_VTable{
	area = proc(self: Shape) -> f64 { return dot_area((^Dot)(self.data)) },
	scale = proc(self: Shape, k: f64) { dot_scale((^Dot)(self.data), k) },
	name = proc(self: Shape) -> string { return dot_name((^Dot)(self.data)) },
}

__Shape_from_Dot :: proc(p: ^Dot) -> Shape { return {data = p, __vtable = &__Shape_vtable_Dot} }
