package main; import __vidar "vidar_runtime"

import "core:fmt"
import "core:strconv"

Parser :: __vidar.Closure(proc(__vidar.Env, string) -> (int, bool))

parsers: map[string]Parser

make_checked :: proc(limit: int) -> Parser {
	return __closure_0(limit)
}

pick :: proc(name: string) -> Parser { return parsers[name] }

main :: proc() {
	parsers["small"] = make_checked(10)
	parsers["big"] = make_checked(1000)

	// closure stored in a map, called through an index expression
	v, ok := parsers["small"].call(parsers["small"].env, "7")
	fmt.println(v, ok)
	v, ok = parsers["small"].call(parsers["small"].env, "70")
	fmt.println(v, ok)

	// the callee is a call result, so a generated call helper evaluates it once
	w, ok2 := __call_closure_0(pick("big"), "700")
	fmt.println(w, ok2)

	// variadic closure parameters pass through
	sum := __vidar.Closure(proc(__vidar.Env, ..int) -> int){call = proc(__env_raw: __vidar.Env, xs: ..int) -> int {
		t := 0
		for x in xs do t += x
		return t
	}}
	fmt.println("sum:", sum.call(sum.env, 1, 2, 3, 4))
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, string) -> (int, bool)) {
	__Caps :: struct {
		limit: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:11: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, string) -> (int, bool)){
		call = proc(__env_raw: __vidar.Env, s: string) -> (value: int, ok: bool) { __env := transmute(__Env)__env_raw;
		v, parsed := strconv.parse_int(s)
		if !parsed || v > __env.limit do return 0, false
		return v, true
	},
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__call_closure_0 :: #force_inline proc(c: __vidar.Closure(proc(__vidar.Env, string) -> (int, bool)), p0: string) -> (int, bool) {
	return c.call(c.env, p0)
}
