package main; import __vidar "vidar_runtime"

import "core:fmt"

// called twice: one read of f.call on entry serves both
twice :: proc(x: int, f: __vidar.Closure(proc(__vidar.Env, int) -> int)) -> int { __f_call := f.call; return __f_call(f.env, __f_call(f.env, x)) }

// called in a loop, and passed on unchanged
sum_map :: proc(xs: []int, f: __vidar.Closure(proc(__vidar.Env, int) -> int)) -> (total: int) { __f_call := f.call;
	for x in xs do total += __f_call(f.env, x)
	total += twice(0, f)
	return
}

// captured by reference: f is a local copy then, and calls read it as it is
swap_and_call :: proc(f: __vidar.Closure(proc(__vidar.Env, int) -> int), g: __vidar.Closure(proc(__vidar.Env, int) -> int)) -> int { f := f; g := g;
	reset := __closure_0(&f, &g)
	a := f.call(f.env, 1)
	reset.call(reset.env)
	return a * 100 + f.call(f.env, 1)
}

// called from a nested closure, through a by-reference capture
compose_sum :: proc(xs: []int, f, g: __vidar.Closure(proc(__vidar.Env, int) -> int)) -> int { f := f; g := g;
	both := __closure_1(&f, &g)
	return sum_map(xs, both)
}

// a closure literal's own closure parameter

apply_with :: proc(xs: []int, f: __vidar.Closure(proc(__vidar.Env, int) -> int)) -> int {
	run := __vidar.Closure(proc(__vidar.Env, []int, __vidar.Closure(proc(__vidar.Env, int) -> int)) -> int){call = proc(__env_raw: __vidar.Env, ys: []int, h: __vidar.Closure(proc(__vidar.Env, int) -> int)) -> (n: int) { __h_call := h.call;
		for y in ys do n += __h_call(h.env, y)
		return
	}}
	return run.call(run.env, xs, f)
}

main :: proc() {
	k := 3
	add := __closure_2(k)
	dbl := __vidar.Closure(proc(__vidar.Env, int) -> int){call = proc(__env_raw: __vidar.Env, x: int) -> int { return x * 2 }}
	xs := []int{1, 2, 3}
	fmt.println(twice(1, add), twice(1, dbl))
	fmt.println(sum_map(xs, add), sum_map(xs, dbl))
	fmt.println(swap_and_call(add, dbl))
	fmt.println(compose_sum(xs, add, dbl), apply_with(xs, add))
	// a literal passed straight in
	fmt.println(sum_map(xs, __closure_3(k)))
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		f: T0,
		g: T1,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:17: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw; __env.f^ = __env.g^ },
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1}},
	}
}

__closure_1 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(__vidar.Env, int) -> int) {
	__Caps :: struct {
		f: T0,
		g: T1,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:25: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int) -> int){
		call = proc(__env_raw: __vidar.Env, x: int) -> int { __env := transmute(__Env)__env_raw; return __env.g^.call(__env.g^.env, __env.f^.call(__env.f^.env, x)) },
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1}},
	}
}

__closure_2 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int) -> int) {
	__Caps :: struct {
		k: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:41: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int) -> int){
		call = proc(__env_raw: __vidar.Env, x: int) -> int { __env := transmute(__Env)__env_raw; return x + __env.k },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_3 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int) -> int) {
	__Caps :: struct {
		k: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:49: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int) -> int){
		call = proc(__env_raw: __vidar.Env, x: int) -> int { __env := transmute(__Env)__env_raw; return x * __env.k },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}
