package main; import __vidar "vidar_runtime"

import "core:fmt"

Point :: struct { x, y: f32 }

hp_of :: proc(v: struct { name: string, hp: int }) -> int { return v.hp }

describe :: proc(v: $T) -> string { return fmt.tprintf("%v", v) }

main :: proc() {
	// untyped constants take their default types
	__anon1_b := 5; __anon1_s := "x"; __anon1_r := 'r'; __anon1_f := 1.5; __anon1_ok := true; a := struct { b: type_of(__anon1_b), s: type_of(__anon1_s), r: type_of(__anon1_r), f: type_of(__anon1_f), ok: type_of(__anon1_ok) }{b = __anon1_b, s = __anon1_s, r = __anon1_r, f = __anon1_f, ok = __anon1_ok}
	fmt.println(a)
	fmt.printf("%T\n", a)

	// multi-line, and interchangeable with a written-out anonymous struct type
	
		__anon2_name := "slime";
		__anon2_hp := 10; hero := struct { name: type_of(__anon2_name), hp: type_of(__anon2_hp) }{name = __anon2_name, hp = __anon2_hp}

	hero.hp += 1
	fmt.println(hp_of(hero), describe(hero))

	// nested literals, typed values, closures, pointers
	k := 3
	add := __closure_0(k)
	__anon3_pos_x := 1.5; __anon3_pos_y := -2; __anon3_at := Point{1, 2}; __anon3_tags := []string{"a"}; __anon3_f := add; __anon3_p := &k; __anon3_big := k > 2; cfg := struct { pos: struct { x: type_of(__anon3_pos_x), y: type_of(__anon3_pos_y) }, at: type_of(__anon3_at), tags: type_of(__anon3_tags), f: type_of(__anon3_f), p: type_of(__anon3_p), big: type_of(__anon3_big) }{pos = {x = __anon3_pos_x, y = __anon3_pos_y}, at = __anon3_at, tags = __anon3_tags, f = __anon3_f, p = __anon3_p, big = __anon3_big}
	cfg.pos.x += 1
	fmt.println(cfg.pos, cfg.at, cfg.tags, cfg.f.call(cfg.f.env, 1), cfg.p^, cfg.big)

	// captured by reference like any other local
	__anon4_calls := 0; __anon4_last := ""; stats := struct { calls: type_of(__anon4_calls), last: type_of(__anon4_last) }{calls = __anon4_calls, last = __anon4_last}
	record := __closure_1(&stats)
	record.call(record.env, "x")
	record.call(record.env, "y")
	fmt.println(stats)

	// same field names and types: same type
	__anon5_v := 1; __anon6_v := 2; l, r := struct { v: type_of(__anon5_v) }{v = __anon5_v}, struct { v: type_of(__anon6_v) }{v = __anon6_v}
	l = r
	fmt.println(l)

	// values are evaluated once, in order
	n := 0
	next := __closure_2(&n)
	__anon7_first := next.call(next.env); __anon7_second := next.call(next.env); __anon7_inner_third := next.call(next.env); seq := struct { first: type_of(__anon7_first), second: type_of(__anon7_second), inner: struct { third: type_of(__anon7_inner_third) } }{first = __anon7_first, second = __anon7_second, inner = {third = __anon7_inner_third}}
	fmt.println(seq, n)

	// a typed context keeps Odin's own meaning
	p: Point = { x = 3, y = 4 }
	fmt.println(p, Point{ x = 5 })
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int) -> int) {
	__Caps :: struct {
		k: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:27: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int) -> int){
		call = proc(__env_raw: __vidar.Env, x: int) -> int { __env := transmute(__Env)__env_raw; return x + __env.k },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_1 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, string)) {
	__Caps :: struct {
		stats: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:34: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, string)){
		call = proc(__env_raw: __vidar.Env, s: string) { __env := transmute(__Env)__env_raw; __env.stats^.calls += 1; __env.stats^.last = s },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_2 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env) -> int) {
	__Caps :: struct {
		n: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:46: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env) -> int){
		call = proc(__env_raw: __vidar.Env) -> int { __env := transmute(__Env)__env_raw; __env.n^ += 1; return __env.n^ },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}
