package main; import __vidar "vidar_runtime"

import "core:fmt"

main :: proc() {
	n := new_clone(1)
	by_value := __closure_0(n^)
	by_ref := __closure_1(n)
	n^ = 2
	fmt.println(by_value.call(by_value.env), by_ref.call(by_ref.env))

	// mutating a by-value capture changes only the closure's own copy
	counter := __closure_2(n^)
	fmt.println(counter.call(counter.env), counter.call(counter.env), n^)

	// params can be captured by reference too
	bump := proc(x: int) -> int { x := new_clone(x);
		inc := __closure_3(x)
		inc.call(inc.env)
		return x^
	}
	fmt.println(bump(5))
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0) -> __vidar.Closure(proc(rawptr) -> int) {
	__Env :: struct {
		n: T0,
	}
	return __vidar.Closure(proc(rawptr) -> int){
		call = proc(__env_raw: rawptr) -> int { __env := cast(^__Env)__env_raw; return __env.n },
		env = new_clone(__Env{__c0}),
	}
}

__closure_1 :: proc(__c0: $T0) -> __vidar.Closure(proc(rawptr) -> int) {
	__Env :: struct {
		n: T0,
	}
	return __vidar.Closure(proc(rawptr) -> int){
		call = proc(__env_raw: rawptr) -> int { __env := cast(^__Env)__env_raw; return __env.n^ },
		env = new_clone(__Env{__c0}),
	}
}

__closure_2 :: proc(__c0: $T0) -> __vidar.Closure(proc(rawptr) -> int) {
	__Env :: struct {
		n: T0,
	}
	return __vidar.Closure(proc(rawptr) -> int){
		call = proc(__env_raw: rawptr) -> int { __env := cast(^__Env)__env_raw; __env.n += 1; return __env.n },
		env = new_clone(__Env{__c0}),
	}
}

__closure_3 :: proc(__c0: $T0) -> __vidar.Closure(proc(rawptr)) {
	__Env :: struct {
		x: T0,
	}
	return __vidar.Closure(proc(rawptr)){
		call = proc(__env_raw: rawptr) { __env := cast(^__Env)__env_raw; __env.x^ += 10 },
		env = new_clone(__Env{__c0}),
	}
}
