package main; import __vidar "vidar_runtime"

import "core:fmt"
import sched "vidar_sched"

Handler :: struct {
	run: __vidar.Closure(proc(rawptr, int) -> int),
}

saved: [dynamic]__vidar.Closure(proc(rawptr) -> int)

// @(no_specialize) on these: a copy per closure would skip the env being tested

twice :: proc(f: __vidar.Closure(proc(rawptr, int) -> int), x: int) -> int {
	return f.call(f.env, f.call(f.env, x))
}

// only calls f, and hands it to twice, which only calls it

apply :: proc(f: __vidar.Closure(proc(rawptr, int) -> int), n: int) -> int {
	if n == 0 do return f.call(f.env, 0)
	return twice(f, n) + apply(f, n - 1)
}

keep :: proc(f: __vidar.Closure(proc(rawptr) -> int)) {
	append(&saved, f)
}

wrap :: proc(f: __vidar.Closure(proc(rawptr, int) -> int)) -> Handler {
	return Handler{run = f}
}

make_adder :: proc(k: int) -> __vidar.Closure(proc(rawptr, int) -> int) {
	return __closure_0(k)
}


each :: proc(xs: []int, f: __vidar.Closure(proc(rawptr, int))) {
	for x in xs do f.call(f.env, x)
}

main :: proc() {
	// stack: only called here
	a, b := 3, 4
	add := __closure_1(&__closure_1_Env(type_of(a), type_of(b)){a, b})
	__fmt_0(add.call(add.env, 1), add.call(add.env, 2))

	// stack: passed to procs that only call it
	__fmt_1(apply(__closure_2(&__closure_2_Env(type_of(a)){a}), 2))
	mul := __closure_3(&__closure_3_Env(type_of(a), type_of(b)){a, b})
	__fmt_2(twice(mul, 1))

	// heap: stored by keep, returned in a struct by wrap, returned by make_adder
	for i in 0..<3 {
		keep(__closure_4(i, a))
	}
	for f in saved do __fmt_3(f.call(f.env))
	__fmt_4()
	h := wrap(__closure_5(a, b))
	__fmt_5(h.run.call(h.run.env, 10), __call_closure_0(make_adder(5), 1))

	// heap: appended directly, and assigned to a variable declared outside the loop
	values: [dynamic]__vidar.Closure(proc(rawptr) -> int)
	last: __vidar.Closure(proc(rawptr) -> int)
	reserve(&values, len(values) + 3)
	for i in 0..<3 {
		s := i * i
		append(&values, __closure_6(i, s))
		last = __closure_7(i, s)
	}
	for f in values do __fmt_3(f.call(f.env))
	__fmt_6(last.call(last.env))

	// stack in a loop: a fresh env every iteration, never used after it
	total := 0
	for i in 0..<4 {
		step := i + 1
		inc := __closure_8(&__closure_8_Env(type_of(&total), type_of(step)){&total, step})
		inc.call(inc.env)
		inc.call(inc.env)
	}
	__fmt_7(total)

	// one by-reference capture: the pointer is the env, even when the closure escapes
	count := 0
	tick := __closure_9(&count)
	keep(tick)
	tick.call(tick.env)
	__fmt_8(__call_closure_1(saved[len(saved) - 1]), count)

	// nested: the inner closure runs inside the outer one's call, so both envs are on the stack
	sum := 0
	scale := 2
	each([]int{1, 2, 3}, __closure_11(&__closure_11_Env(type_of(&sum), type_of(scale)){&sum, scale}))
	__fmt_9(sum)

	// nested: the outer closure returns a pointer into its env, so its env stays on the heap
	base := 100
	outer := __closure_13(base)
	g := outer.call(outer.env)
	g.call(g.env)
	__fmt_10(g.call(g.env))

	// heap: handed to a goroutine
	done := false
	msg := "hi"
	sched.go(__closure_14(&done, msg))
	sched.yield()
	__fmt_12(done)
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0) -> __vidar.Closure(proc(rawptr, int) -> int) {
	__Env :: struct {
		k: T0,
	}
	return __vidar.Closure(proc(rawptr, int) -> int){
		call = proc(__env_raw: rawptr, x: int) -> int { __env := cast(^__Env)__env_raw; return x + __env.k },
		env = new_clone(__Env{__c0}),
	}
}

__closure_1_Env :: struct($T0: typeid, $T1: typeid) {
	a: T0,
	b: T1,
}

__closure_1 :: proc(__env_ptr: ^__closure_1_Env($T0, $T1)) -> __vidar.Closure(proc(rawptr, int) -> int) {
	__Env :: __closure_1_Env(T0, T1)
	return __vidar.Closure(proc(rawptr, int) -> int){
		call = proc(__env_raw: rawptr, x: int) -> int { __env := cast(^__Env)__env_raw; return x + __env.a + __env.b },
		env = __env_ptr,
	}
}

// fmt.println
__fmt_0 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "add: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_1 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "apply: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

__closure_2_Env :: struct($T0: typeid) {
	a: T0,
}

__closure_2 :: proc(__env_ptr: ^__closure_2_Env($T0)) -> __vidar.Closure(proc(rawptr, int) -> int) {
	__Env :: __closure_2_Env(T0)
	return __vidar.Closure(proc(rawptr, int) -> int){
		call = proc(__env_raw: rawptr, x: int) -> int { __env := cast(^__Env)__env_raw; return x * __env.a },
		env = __env_ptr,
	}
}

__closure_3_Env :: struct($T0: typeid, $T1: typeid) {
	a: T0,
	b: T1,
}

__closure_3 :: proc(__env_ptr: ^__closure_3_Env($T0, $T1)) -> __vidar.Closure(proc(rawptr, int) -> int) {
	__Env :: __closure_3_Env(T0, T1)
	return __vidar.Closure(proc(rawptr, int) -> int){
		call = proc(__env_raw: rawptr, x: int) -> int { __env := cast(^__Env)__env_raw; return x * __env.a + __env.b },
		env = __env_ptr,
	}
}

// fmt.println
__fmt_2 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "twice: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

__closure_4 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(rawptr) -> int) {
	__Env :: struct {
		i: T0,
		a: T1,
	}
	return __vidar.Closure(proc(rawptr) -> int){
		call = proc(__env_raw: rawptr) -> int { __env := cast(^__Env)__env_raw; return __env.i * 10 + __env.a },
		env = new_clone(__Env{__c0, __c1}),
	}
}

// fmt.print
__fmt_3 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_4 :: proc() -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

__closure_5 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(rawptr, int) -> int) {
	__Env :: struct {
		a: T0,
		b: T1,
	}
	return __vidar.Closure(proc(rawptr, int) -> int){
		call = proc(__env_raw: rawptr, x: int) -> int { __env := cast(^__Env)__env_raw; return x - __env.a - __env.b },
		env = new_clone(__Env{__c0, __c1}),
	}
}

// fmt.println
__fmt_5 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "wrap: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

__closure_6 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(rawptr) -> int) {
	__Env :: struct {
		i: T0,
		s: T1,
	}
	return __vidar.Closure(proc(rawptr) -> int){
		call = proc(__env_raw: rawptr) -> int { __env := cast(^__Env)__env_raw; return __env.i + __env.s },
		env = new_clone(__Env{__c0, __c1}),
	}
}

__closure_7 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(rawptr) -> int) {
	__Env :: struct {
		i: T0,
		s: T1,
	}
	return __vidar.Closure(proc(rawptr) -> int){
		call = proc(__env_raw: rawptr) -> int { __env := cast(^__Env)__env_raw; return __env.i - __env.s },
		env = new_clone(__Env{__c0, __c1}),
	}
}

// fmt.println
__fmt_6 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "last: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

__closure_8_Env :: struct($T0: typeid, $T1: typeid) {
	total: T0,
	step: T1,
}

__closure_8 :: proc(__env_ptr: ^__closure_8_Env($T0, $T1)) -> __vidar.Closure(proc(rawptr)) {
	__Env :: __closure_8_Env(T0, T1)
	return __vidar.Closure(proc(rawptr)){
		call = proc(__env_raw: rawptr) { __env := cast(^__Env)__env_raw; __env.total^ += __env.step },
		env = __env_ptr,
	}
}

// fmt.println
__fmt_7 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "total: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

__closure_9 :: proc(__c0: $T0) -> __vidar.Closure(proc(rawptr) -> int) {
	__Env :: struct {
		count: T0,
	}
	return __vidar.Closure(proc(rawptr) -> int){
		call = proc(__env_raw: rawptr) -> int { __env := __Env{cast(T0)__env_raw}; __env.count^ += 1; return __env.count^ },
		env = rawptr(__c0),
	}
}

// fmt.println
__fmt_8 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "count: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

__closure_10_Env :: struct($T0: typeid, $T1: typeid, $T2: typeid) {
	sum: T0,
	scale: T1,
	x: T2,
}

__closure_10 :: proc(__env_ptr: ^__closure_10_Env($T0, $T1, $T2)) -> __vidar.Closure(proc(rawptr)) {
	__Env :: __closure_10_Env(T0, T1, T2)
	return __vidar.Closure(proc(rawptr)){
		call = proc(__env_raw: rawptr) { __env := cast(^__Env)__env_raw; __env.sum^ += __env.x * __env.scale },
		env = __env_ptr,
	}
}

__closure_11_Env :: struct($T0: typeid, $T1: typeid) {
	sum: T0,
	scale: T1,
}

__closure_11 :: proc(__env_ptr: ^__closure_11_Env($T0, $T1)) -> __vidar.Closure(proc(rawptr, int)) {
	__Env :: __closure_11_Env(T0, T1)
	return __vidar.Closure(proc(rawptr, int)){
		call = proc(__env_raw: rawptr, x: int) { __env := cast(^__Env)__env_raw;
		add := __closure_10(&__closure_10_Env(type_of(__env.sum), type_of(__env.scale), type_of(x)){__env.sum, __env.scale, x})
		add.call(add.env)
	},
		env = __env_ptr,
	}
}

// fmt.println
__fmt_9 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "sum: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

__closure_12 :: proc(__c0: $T0) -> __vidar.Closure(proc(rawptr) -> int) {
	__Env :: struct {
		base: T0,
	}
	return __vidar.Closure(proc(rawptr) -> int){
		call = proc(__env_raw: rawptr) -> int { __env := __Env{cast(T0)__env_raw}; __env.base^ += 1; return __env.base^ },
		env = rawptr(__c0),
	}
}

__closure_13 :: proc(__c0: $T0) -> __vidar.Closure(proc(rawptr) -> __vidar.Closure(proc(rawptr) -> int)) {
	__Env :: struct {
		base: T0,
	}
	return __vidar.Closure(proc(rawptr) -> __vidar.Closure(proc(rawptr) -> int)){
		call = proc(__env_raw: rawptr) -> __vidar.Closure(proc(rawptr) -> int) { __env := cast(^__Env)__env_raw;
		return __closure_12(&__env.base)
	},
		env = new_clone(__Env{__c0}),
	}
}

// fmt.println
__fmt_10 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "outer: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_11 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "go: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

__closure_14 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(rawptr)) {
	__Env :: struct {
		done: T0,
		msg: T1,
	}
	return __vidar.Closure(proc(rawptr)){
		call = proc(__env_raw: rawptr) { __env := cast(^__Env)__env_raw;
		__fmt_11(__env.msg)
		__env.done^ = true
	},
		env = new_clone(__Env{__c0, __c1}),
	}
}

// fmt.println
__fmt_12 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "done: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

__call_closure_0 :: #force_inline proc(c: __vidar.Closure(proc(rawptr, int) -> int), p0: int) -> int {
	return c.call(c.env, p0)
}

__call_closure_1 :: #force_inline proc(c: __vidar.Closure(proc(rawptr) -> int)) -> int {
	return c.call(c.env)
}
