package main; import __vidar "vidar_runtime"

import "core:fmt"

for_each :: proc(xs: []int, f: __vidar.Closure(proc(__vidar.Env, int))) { __f_call := f.call;
	for x in xs do __f_call(f.env, x)
}

fold :: proc(xs: []$T, init: T, f: __vidar.Closure(proc(__vidar.Env, T, T) -> T)) -> T { __f_call := f.call;
	acc := init
	for x in xs do acc = __f_call(f.env, acc, x)
	return acc
}

// two closure parameters, one call each, plus a deferred call
filter_map :: proc(xs: []int, keep: __vidar.Closure(proc(__vidar.Env, int) -> bool), f: __vidar.Closure(proc(__vidar.Env, int) -> int), done: __vidar.Closure(proc(__vidar.Env))) -> (out: [dynamic]int) { __keep_call := keep.call; __f_call := f.call; __done_call := done.call;
	defer __done_call(done.env)
	reserve(&out, len(out) + len(xs))
	for x in xs {
		if __keep_call(keep.env, x) do append(&out, __f_call(f.env, x))
	}
	return
}

// stores its closure: not specialized
Handler :: struct {
	on: __vidar.Closure(proc(__vidar.Env, int) -> int),
}

install :: proc(h: ^Handler, f: __vidar.Closure(proc(__vidar.Env, int) -> int)) {
	h.on = f
}

// passes its closure on: not specialized
apply_twice :: proc(x: int, f: __vidar.Closure(proc(__vidar.Env, int) -> int)) -> int { __f_call := f.call;
	return twice_inner(__f_call(f.env, x), f)
}

twice_inner :: proc(x: int, f: __vidar.Closure(proc(__vidar.Env, int) -> int)) -> int { __f_call := f.call;
	return __f_call(f.env, x)
}


plain_each :: proc(xs: []int, f: __vidar.Closure(proc(__vidar.Env, int))) { __f_call := f.call;
	for x in xs do __f_call(f.env, x)
}

// more calls with closures than copies
times :: proc(n: int, f: __vidar.Closure(proc(__vidar.Env, int))) { __f_call := f.call;
	for i in 0..<n do __f_call(f.env, i)
}


repeat :: proc(n: int, f: __vidar.Closure(proc(__vidar.Env, int) -> int)) -> int { __f_call := f.call;
	s := 0
	for i in 0..<n do s += __f_call(f.env, i)
	return s
}

// passes a closure literal to itself: every copy calls the same one
count_down :: proc(n: int, f: __vidar.Closure(proc(__vidar.Env, int))) { __f_call := f.call;
	__f_call(f.env, n)
	if n > 0 do count_down__closure0(n - 1)
}

main :: proc() {
	xs := []int{1, 2, 3, 4, 5}
	total := 0
	k := 3
	for_each__closure1(xs, &total, k)
	__fmt_0(total)

	// by-reference capture changed by the body
	calls := 0
	for_each__closure2(xs, &calls)
	__fmt_1(calls)

	__fmt_2(fold__closure3(xs, 0))
	scale := 1.5
	__fmt_3(fold__closure4([]f64{1, 2}, 0.5, scale))

	evens := filter_map__closure5(xs, k)
	__fmt_4(evens[:])
	delete(evens)

	h: Handler
	install(&h, __closure_0(k))
	__fmt_5(h.on.call(h.on.env, 1))
	__fmt_6(apply_twice(1, __closure_1(k)))

	n := 0
	plain_each(xs, __closure_2(&n))
	__fmt_7(n)

	// the call inside a closure: its captures come from that closure's environment
	sum := 0
	run := __closure_3(&sum, k)
	run.call(run.env)
	__fmt_8(sum)

	// a closure inside the one passed
	adder := __closure_4(k)
	for_each__closure7(xs[:2], &adder)

	count := 0
	times__closure8(2, &count)
	times__closure9(3, &count)
	times__closure10(4, &count)
	times__closure11(5, &count)
	times(6, __closure_5(&count))
	__fmt_9(count)

	count_down__closure12(2, k)
	__fmt_10(repeat__n_closure13(4, k), repeat__closure14(k))
}

// ---- generated by vidar ----

// fmt.println
__fmt_0 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "for_each: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_1 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "calls outside: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_2 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "fold: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_3 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "fold f64: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_4 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "filter_map: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

__closure_0 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int) -> int) {
	__Caps :: struct {
		k: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:89: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int) -> int){
		call = proc(__env_raw: __vidar.Env, x: int) -> int { __env := transmute(__Env)__env_raw; return x + __env.k },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

// fmt.println
__fmt_5 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "installed: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_6 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "apply_twice: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

__closure_1 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int) -> int) {
	__Caps :: struct {
		k: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:91: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int) -> int){
		call = proc(__env_raw: __vidar.Env, x: int) -> int { __env := transmute(__Env)__env_raw; return x * __env.k },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_2 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int)) {
	__Caps :: struct {
		n: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:94: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int)){
		call = proc(__env_raw: __vidar.Env, x: int) { __env := transmute(__Env)__env_raw; __env.n^ += x },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

// fmt.println
__fmt_7 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "plain: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

__closure_3 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		sum: T0,
		k: T1,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:99: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw;
		for_each__closure6([]int{10, 20}, __env.sum, __env.k)
	},
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1}},
	}
}

// fmt.println
__fmt_8 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "nested: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

__closure_4 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int) -> int) {
	__Caps :: struct {
		k: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:106: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int) -> int){
		call = proc(__env_raw: __vidar.Env, x: int) -> int { __env := transmute(__Env)__env_raw; return x + __env.k },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_5 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int)) {
	__Caps :: struct {
		count: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:117: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int)){
		call = proc(__env_raw: __vidar.Env, i: int) { __env := transmute(__Env)__env_raw; __env.count^ += 10000 },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

// fmt.println
__fmt_9 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "times: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_10 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "repeat: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_11 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "down ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

__count_down__closure0_f :: proc(x: int) { __fmt_11(x) }

// count_down with the closure from line 62 called directly
count_down__closure0 :: proc(n: int) {
	__count_down__closure0_f(n)
	if n > 0 do count_down__closure0(n - 1)
}

__for_each__closure1_f_Env :: struct($__T0, $__T1: typeid) {
	total: __T0,
	k: __T1,
}

__for_each__closure1_f :: proc(__env: ^__for_each__closure1_f_Env($__T0, $__T1), x: int) { __env.total^ += x * __env.k }

// for_each with the closure from line 69 called directly
for_each__closure1 :: proc(xs: []int, __f_c0: $__f_T0, __f_c1: $__f_T1) { __f_env := __for_each__closure1_f_Env(__f_T0, __f_T1){__f_c0, __f_c1};
	for x in xs do __for_each__closure1_f(&__f_env, x)
}

// fmt.println
__fmt_12 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "third call sees ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

__for_each__closure2_f_Env :: struct($__T0: typeid) {
	calls: __T0,
}

__for_each__closure2_f :: proc(__env: ^__for_each__closure2_f_Env($__T0), x: int) {
		__env.calls^ += 1
		if __env.calls^ == len("abc") do __fmt_12(x)
	}

// for_each with the closure from line 74 called directly
for_each__closure2 :: proc(xs: []int, __f_c0: $__f_T0) { __f_env := __for_each__closure2_f_Env(__f_T0){__f_c0};
	for x in xs do __for_each__closure2_f(&__f_env, x)
}

__fold__closure3_f :: proc(a, b: int) -> int { return a + b }

// fold with the closure from line 80 called directly
fold__closure3 :: proc(xs: []$T, init: T) -> T {
	acc := init
	for x in xs do acc = __fold__closure3_f(acc, x)
	return acc
}

__fold__closure4_f_Env :: struct($__T0: typeid) {
	scale: __T0,
}

__fold__closure4_f :: proc(__env: ^__fold__closure4_f_Env($__T0), a, b: f64) -> f64 { return a + b * __env.scale }

// fold with the closure from line 82 called directly
fold__closure4 :: proc(xs: []$T, init: T, __f_c0: $__f_T0) -> T { __f_env := __fold__closure4_f_Env(__f_T0){__f_c0};
	acc := init
	for x in xs do acc = __fold__closure4_f(&__f_env, acc, x)
	return acc
}

__filter_map__closure5_keep :: proc(x: int) -> bool { return x % 2 == 0 }

__filter_map__closure5_f_Env :: struct($__T0: typeid) {
	k: __T0,
}

__filter_map__closure5_f :: proc(__env: ^__filter_map__closure5_f_Env($__T0), x: int) -> int { return x * __env.k }

// fmt.println
__fmt_13 :: proc() -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "filter_map done\n")
	__vidar.w_flush(w)
	return
}

__filter_map__closure5_done :: proc() { __fmt_13() }

// filter_map with the closures from line 84 called directly
filter_map__closure5 :: proc(xs: []int, __f_c0: $__f_T0) -> (out: [dynamic]int) { __f_env := __filter_map__closure5_f_Env(__f_T0){__f_c0};
	defer __filter_map__closure5_done()
	reserve(&out, len(out) + len(xs))
	for x in xs {
		if __filter_map__closure5_keep(x) do append(&out, __filter_map__closure5_f(&__f_env, x))
	}
	return
}

__for_each__closure6_f_Env :: struct($__T0, $__T1: typeid) {
	sum: __T0,
	k: __T1,
}

__for_each__closure6_f :: proc(__env: ^__for_each__closure6_f_Env($__T0, $__T1), x: int) { __env.sum^ += x + __env.k }

// for_each with the closure from line 100 called directly
for_each__closure6 :: proc(xs: []int, __f_c0: $__f_T0, __f_c1: $__f_T1) { __f_env := __for_each__closure6_f_Env(__f_T0, __f_T1){__f_c0, __f_c1};
	for x in xs do __for_each__closure6_f(&__f_env, x)
}

__closure_6 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(__vidar.Env) -> int) {
	__Caps :: struct {
		adder: T0,
		x: T1,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:108: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env) -> int){
		call = proc(__env_raw: __vidar.Env) -> int { __env := transmute(__Env)__env_raw; return __env.adder^.call(__env.adder^.env, __env.x) * 2 },
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1}},
	}
}

// fmt.println
__fmt_14 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "inner: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

__for_each__closure7_f_Env :: struct($__T0: typeid) {
	adder: __T0,
}

__for_each__closure7_f :: proc(__env: ^__for_each__closure7_f_Env($__T0), x: int) {
		inner := __closure_6(__env.adder, x)
		__fmt_14(inner.call(inner.env))
	}

// for_each with the closure from line 107 called directly
for_each__closure7 :: proc(xs: []int, __f_c0: $__f_T0) { __f_env := __for_each__closure7_f_Env(__f_T0){__f_c0};
	for x in xs do __for_each__closure7_f(&__f_env, x)
}

__times__closure8_f_Env :: struct($__T0: typeid) {
	count: __T0,
}

__times__closure8_f :: proc(__env: ^__times__closure8_f_Env($__T0), i: int) { __env.count^ += 1 }

// times with the closure from line 113 called directly
times__closure8 :: proc(n: int, __f_c0: $__f_T0) { __f_env := __times__closure8_f_Env(__f_T0){__f_c0};
	for i in 0..<n do __times__closure8_f(&__f_env, i)
}

__times__closure9_f_Env :: struct($__T0: typeid) {
	count: __T0,
}

__times__closure9_f :: proc(__env: ^__times__closure9_f_Env($__T0), i: int) { __env.count^ += 10 }

// times with the closure from line 114 called directly
times__closure9 :: proc(n: int, __f_c0: $__f_T0) { __f_env := __times__closure9_f_Env(__f_T0){__f_c0};
	for i in 0..<n do __times__closure9_f(&__f_env, i)
}

__times__closure10_f_Env :: struct($__T0: typeid) {
	count: __T0,
}

__times__closure10_f :: proc(__env: ^__times__closure10_f_Env($__T0), i: int) { __env.count^ += 100 }

// times with the closure from line 115 called directly
times__closure10 :: proc(n: int, __f_c0: $__f_T0) { __f_env := __times__closure10_f_Env(__f_T0){__f_c0};
	for i in 0..<n do __times__closure10_f(&__f_env, i)
}

__times__closure11_f_Env :: struct($__T0: typeid) {
	count: __T0,
}

__times__closure11_f :: proc(__env: ^__times__closure11_f_Env($__T0), i: int) { __env.count^ += 1000 }

// times with the closure from line 116 called directly
times__closure11 :: proc(n: int, __f_c0: $__f_T0) { __f_env := __times__closure11_f_Env(__f_T0){__f_c0};
	for i in 0..<n do __times__closure11_f(&__f_env, i)
}

// fmt.println
__fmt_15 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "start ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

__count_down__closure12_f_Env :: struct($__T0: typeid) {
	k: __T0,
}

__count_down__closure12_f :: proc(__env: ^__count_down__closure12_f_Env($__T0), x: int) { __fmt_15(x, __env.k) }

// count_down with the closure from line 120 called directly
count_down__closure12 :: proc(n: int, __f_c0: $__f_T0) { __f_env := __count_down__closure12_f_Env(__f_T0){__f_c0};
	__count_down__closure12_f(&__f_env, n)
	if n > 0 do count_down__closure0(n - 1)
}

__repeat__n_closure13_f_Env :: struct($__T0: typeid) {
	k: __T0,
}

__repeat__n_closure13_f :: proc(__env: ^__repeat__n_closure13_f_Env($__T0), i: int) -> int { return i * __env.k }

// repeat with n known at compile time, the closure from line 121 called directly
repeat__n_closure13 :: proc($n: int, __f_c0: $__f_T0) -> int { __f_env := __repeat__n_closure13_f_Env(__f_T0){__f_c0};
	s := 0
	for i in 0..<n do s += __repeat__n_closure13_f(&__f_env, i)
	return s
}

__repeat__closure14_f :: proc(i: int) -> int { return i }

// repeat with the closure from line 121 called directly
repeat__closure14 :: proc(n: int) -> int {
	s := 0
	for i in 0..<n do s += __repeat__closure14_f(i)
	return s
}
