#!/usr/bin/env node
// Writes docs/reference/*.md from the compiler's own tables. `--check` fails if they are stale.
const fs = require("fs");
const path = require("path");
const { spawnSync } = require("child_process");
const d = require("../dist/lsp/docs.js");

const root = path.join(__dirname, "..");
const outDir = path.join(root, "docs", "reference");
const NOTE = "<!-- Generated by scripts/gen-docs.js from src/lsp/docs.ts. Do not edit. -->";

const entries = (table) => Object.entries(table).sort(([a], [b]) => a.localeCompare(b));
const doc = ([name, v]) => {
  const { sig, text } = typeof v === "string" ? { text: v } : v;
  return `### \`${name}\`\n\n${sig ? "```odin\n" + sig + "\n```\n\n" : ""}${text}\n`;
};
const list = (table) => entries(table).map(([n, t]) => `- \`${n}\`: ${typeof t === "string" ? t : t.text}`).join("\n") + "\n";
const page = (title, intro, body) => `${NOTE}\n\n# ${title}\n\n${intro}\n\n${body}`;

const kw = Object.entries(d.KEYWORD_DOCS);
const split = kw.findIndex(([k]) => k === "closure");
const odinKw = Object.fromEntries(kw.slice(0, split));
const vidarKw = Object.fromEntries(kw.slice(split));

const cli = spawnSync("node", [path.join(root, "dist", "cli.js")], { encoding: "utf8" }).stderr.trimEnd();

const pages = {
  "keywords.md": page(
    "Keywords",
    "Words the language server explains on hover. The first group is Odin's; the second is what Vidar adds. All of Vidar's are contextual: they stay usable as ordinary names.",
    `## Vidar keywords\n\n${entries(vidarKw).map(doc).join("\n")}\n## Odin keywords\n\n${entries(odinKw).map(doc).join("\n")}`,
  ),
  "builtins.md": page(
    "Built-in procs and types",
    "Procs, types, constants and context fields that exist without a declaration.",
    `## Procs\n\n${entries(d.BUILTIN_PROC_DOCS).map(doc).join("\n")}\n## Types\n\n${list(d.BUILTIN_TYPE_DOCS)}\n## Constants\n\n${entries(d.ODIN_CONSTANT_DOCS).map(doc).join("\n")}\n## Context fields\n\n${entries(d.CONTEXT_FIELD_DOCS).map(doc).join("\n")}`,
  ),
  "comptime.md": page(
    "Comptime built-ins",
    "Helpers available inside a comptime proc (`proc!`) and a `comptime! { ... }` block, and what the macro parameter kinds mean. See [Comptime procs](../language/comptime.md).",
    `## Helpers\n\n${entries(d.COMPTIME_BUILTIN_DOCS).map(doc).join("\n")}\n## Parameter and result kinds\n\n${list(d.MACRO_KIND_DOCS)}`,
  ),
  "attributes.md": page(
    "Attributes",
    "Attributes written `@(name)` or `@(name=value)`. The ones marked Vidar control `-opt` and the checks; see [Faster code](../language/optimization.md).",
    `${list(d.ATTRIBUTE_DOCS)}`,
  ),
  "cli.md": page("Command line reference", "The text `vidar` prints when run without arguments. See [Command line](../cli.md) for a guided tour.", "```text\n" + cli + "\n```\n"),
};

let stale = false;
for (const [name, text] of Object.entries(pages)) {
  const file = path.join(outDir, name);
  if (process.argv.includes("--check")) {
    if (!fs.existsSync(file) || fs.readFileSync(file, "utf8") !== text) {
      console.error(`stale: docs/reference/${name}`);
      stale = true;
    }
  } else {
    fs.mkdirSync(outDir, { recursive: true });
    fs.writeFileSync(file, text);
  }
}
if (stale) {
  console.error("run: npm run docs:gen");
  process.exit(1);
}
