#!/usr/bin/env node
// Writes the generated docs pages from the compiler's own sources. `--check` fails if they are stale.
const fs = require("fs");
const path = require("path");
const { spawnSync } = require("child_process");
const d = require("../dist/lsp/docs.js");

const root = path.join(__dirname, "..");
const outDir = path.join(root, "docs", "reference");
const NOTE = "<!-- Generated by scripts/gen-docs.js. Do not edit; run npm run docs:gen. -->";

const entries = (table) => Object.entries(table).sort(([a], [b]) => a.localeCompare(b));
const doc = ([name, v]) => {
  const { sig, text } = typeof v === "string" ? { text: v } : v;
  return `### \`${name}\`\n\n${sig ? "```odin\n" + sig + "\n```\n\n" : ""}${text}\n`;
};
const list = (table) => entries(table).map(([n, t]) => `- \`${n}\`: ${typeof t === "string" ? t : t.text}`).join("\n") + "\n";
const page = (title, intro, body) => `${NOTE}\n\n# ${title}\n\n${intro}\n\n${body}`;

const kw = Object.entries(d.KEYWORD_DOCS);
const split = kw.findIndex(([k]) => k === "closure");
const odinKw = Object.fromEntries(kw.slice(0, split));
const vidarKw = Object.fromEntries(kw.slice(split));

const cli = spawnSync("node", [path.join(root, "dist", "cli.js")], { encoding: "utf8" }).stderr.trimEnd();


const read = (p) => fs.readFileSync(path.join(root, p), "utf8");
const list_ = (dir) => (fs.existsSync(path.join(root, dir)) ? fs.readdirSync(path.join(root, dir)).sort() : []);
const fence = (lang, text) => "```" + lang + "\n" + text.replace(/\s+$/, "") + "\n```\n";
const commentAbove = (lines, i) => {
  const out = [];
  for (let j = i - 1; j >= 0 && /^\/\/ ?/.test(lines[j]); j--) out.unshift(lines[j].replace(/^\/\/ ?/, ""));
  return out;
};

// ---- compile errors, from tests/errors ----
const errorCategory = (name) => {
  const rules = [
    [/^anon_struct/, "Anonymous struct literals"],
    [/^(closure_|capture_)/, "Closures"],
    [/^(catch_|errdefer_|or_return_)/, "Error handling"],
    [/^(memo_|no_alloc|no_table|specialize_|table_)/, "Optimization attributes"],
    [/^(nested_plain_proc|not_captured)/, "Closures"],
    [/^stmt_macro/, "Comptime and macros"],
    [/^(duplicate_global|parse_)/, "Declarations and parsing"],
    [/^(comptime_|macro_|compile_error)/, "Comptime and macros"],
    [/^do_/, "`do!` blocks"],
    [/^(iface_|impl_|bodiless_|pool_)/, "Interfaces"],
    [/^(collection_|missing_|package_|private_)/, "Packages and imports"],
  ];
  return (rules.find(([re]) => re.test(name)) ?? [null, "Other"])[1];
};
const errorCases = [];
for (const f of list_("tests/errors")) {
  if (!f.endsWith(".vidar")) continue;
  const lines = read(`tests/errors/${f}`).split("\n");
  errorCases.push({ name: f.replace(/\.vidar$/, ""), message: lines[0].replace(/^\/\/ error: /, ""), files: [{ file: null, text: lines.slice(1).join("\n") }] });
}
for (const d of list_("tests/errors_pkg")) {
  const dir = `tests/errors_pkg/${d}`;
  const files = [];
  const walk = (rel) => {
    for (const f of list_(`${dir}/${rel}`)) {
      const sub = path.join(rel, f);
      if (fs.statSync(path.join(root, dir, sub)).isDirectory()) walk(sub);
      else if (/\.(vidar|toml)$/.test(f)) files.push(sub);
    }
  };
  walk("");
  const main = read(`${dir}/main.vidar`).split("\n");
  errorCases.push({
    name: d,
    message: main[0].replace(/^\/\/ error: /, ""),
    files: files.map((f) => ({ file: f, text: f === "main.vidar" ? main.slice(1).join("\n") : read(`${dir}/${f}`) })),
  });
}
const byCategory = new Map();
for (const c of errorCases) {
  const cat = errorCategory(c.name);
  if (!byCategory.has(cat)) byCategory.set(cat, []);
  byCategory.get(cat).push(c);
}
const categories = [...byCategory.entries()].sort(([a], [b]) => (a === "Other") - (b === "Other") || a.localeCompare(b));
const errorsToc = categories.map(([cat, cases]) => `- [${cat}](#${cat.toLowerCase().replace(/[^a-z0-9 ]/g, "").trim().replace(/ +/g, "-")}): ${cases.length} errors`).join("\n") + "\n\n";
const errorsBody = errorsToc + [...byCategory.entries()]
  .sort(([a], [b]) => (a === "Other") - (b === "Other") || a.localeCompare(b))
  .map(([cat, cases]) => {
    const items = cases.map((c) => {
      const title = c.name.replace(/_/g, " ");
      const code = c.files.length === 1 && !c.files[0].file ? fence("odin", c.files[0].text) : c.files.map((f) => `\`${f.file}\`:\n\n${fence(f.file.endsWith(".toml") ? "toml" : "odin", f.text)}`).join("\n");
      return `### ${title}\n\nThe message contains:\n\n${fence("text", c.message)}\nThis program fails to compile:\n\n${code}`;
    });
    return `## ${cat}\n\n${items.join("\n")}`;
  })
  .join("\n");

// ---- built-in macros, from src/prelude.vidar ----
const prelude = read("src/prelude.vidar").split("\n");
const macros = [];
prelude.forEach((line, i) => {
  const m = /^(\w+) :: (proc!\(.*\) -> \w+)\s*\{/.exec(line);
  if (m) macros.push({ name: m[1], sig: m[2], doc: commentAbove(prelude, i) });
});
const macrosBody = macros.map((m) => `### \`${m.name}!\`\n\n${fence("odin", `${m.name} :: ${m.sig}`)}\n${fence("text", m.doc.join("\n"))}`).join("\n");

// ---- -define flags, from #config in src ----
const defineRows = [];
for (const file of ["src/sched.ts", "src/emitter.ts"]) {
  const lines = read(file).split("\n");
  lines.forEach((line, i) => {
    const m = /#config\((VIDAR_\w+),\s*(.+?)\)(?=[\s;,]|$)/.exec(line);
    if (m) defineRows.push({ name: m[1], def: m[2], doc: commentAbove(lines, i).join(" "), file });
  });
}
const defineNotes = {
  VIDAR_FILES_ON_WORKERS: "send file operations to worker threads. On by default except on Linux, where io_uring does them; set it to true on Linux to test that path",
  VIDAR_RACE_TABLE: "how many addresses the race check watches (a power of two). It stops adding at 3/4 full",
  VIDAR_STACK_SIZE: "the stack of each goroutine, in bytes, with a guard page below it",
  VIDAR_TRACE_EVENTS: "how many scheduler events each thread keeps for the trace (a power of two)",
  VIDAR_WORKERS: "how many worker threads run `sched.blocking` calls, file operations off Linux, and DNS lookups",
};
for (const r of defineRows) {
  if (!r.doc) r.doc = defineNotes[r.name] ?? "";
  if (!r.doc) throw new Error(`gen-docs: describe ${r.name} in defineNotes`);
}
const esc = (s) => s.replace(/[<>{}]/g, (c) => ({ "<": "&lt;", ">": "&gt;", "{": "&#123;", "}": "&#125;" })[c]);
const definesBody =
  "| Flag | Default | What it does |\n|---|---|---|\n" +
  defineRows
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((r) => `| \`-define:${r.name}=<value>\` | \`${r.def}\` | ${esc(r.doc).replace(/\|/g, "\\|")} |`)
    .join("\n") +
  "\n";

// ---- vidar:sched API, from src/sched.ts ----
const sched = read("src/sched.ts").split("\n");
const schedItems = [];
let priv = false;
sched.forEach((line, i) => {
  if (/^@\(private/.test(line)) { priv = true; return; }
  const m = /^(\w+)\s*::\s*(.*)$/.exec(line);
  const isPriv = priv;
  if (!/^\/\//.test(line) && !/^@\(/.test(line)) priv = false;
  if (!m || isPriv || /^__/.test(m[1]) || /^[A-Z0-9_]+$/.test(m[1]) || m[1] === "Raw_Chan" || /#config/.test(line)) return;
  if (!/^(proc|struct|nbio\.|#force)/.test(m[2])) return;
  schedItems.push({ name: m[1], sig: m[2].replace(/\s*\{.*$/, ""), doc: commentAbove(sched, i).join(" ") });
});
const schedBody = schedItems.map((s) => `### \`${s.name}\`\n\n${fence("odin", `${s.name} :: ${s.sig}`)}${s.doc ? "\n" + s.doc.replace(/[<>{}]/g, (c) => ({ "<": "&lt;", ">": "&gt;", "{": "&#123;", "}": "&#125;" })[c]) + "\n" : ""}`).join("\n");

// ---- generated Odin for the lowering page, from docs/snippets/lowering ----
const lowerOrder = ["closure", "closure_ref", "interface", "error_handling", "do_block", "anon_struct", "macro", "goroutine"];
const lowering = lowerOrder.map((name) => {
  const file = path.join(root, "docs", "snippets", "lowering", `${name}.vidar`);
  const src = fs.readFileSync(file, "utf8").split("\n");
  const meta = (k) => (src.find((l) => l.startsWith(`// ${k}: `)) ?? "").slice(k.length + 5);
  const code = src.filter((l) => !/^\/\/ (title|about): /.test(l)).join("\n");
  const r = spawnSync("node", [path.join(root, "dist", "cli.js"), "emit", file], { encoding: "utf8" });
  if (r.status !== 0) throw new Error(`emit failed for ${name}: ${r.stderr}`);
  const raw = r.stdout.split("\n");
  const cut = raw.findIndex((l) => /^\/\/ ==== (vidar_runtime|vidar_sched)/.test(l));
  const odin = (cut < 0 ? raw : raw.slice(0, cut)).filter((l) => l.trim() && !/^\/\/ ==== .* ====$/.test(l) && !/^\/\/ (title|about): /.test(l));
  return `## ${meta("title")}\n\n${meta("about")}\n\nYou write:\n\n${fence("odin", code)}\nVidar generates:\n\n${fence("odin", odin.join("\n"))}`;
});
const pages = {
  "errors.md": page(
    "Compile errors",
    "Every program here is a test in `tests/errors/` and `tests/errors_pkg/` that must fail to compile. The text under \"The message contains\" is the part of the error that the test checks for, so the full message may add the file, line and a suggested fix. Each is grouped by feature.",
    errorsBody,
  ),
  "macros.md": page(
    "Built-in macro definitions",
    "The macros that come with the language, as written in `src/prelude.vidar`. For how to use them, see [Built-in macros](../language/builtin-macros.md). Names are called with a `!`, for example `scoped!`.",
    macrosBody,
  ),
  "defines.md": page(
    "Build flags (`-define`)",
    "Flags set with `-define:NAME=value` on `vidar run`, `check`, `test` and `build`. They are passed on to `odin`.",
    definesBody,
  ),
  "sched.md": page(
    "`vidar:sched` API",
    "The public procs and types of `import \"vidar:sched\"`, from `src/sched.ts`. For how they behave, see [Goroutines and channels](../language/goroutines.md).",
    schedBody,
  ),
  "keywords.md": page(
    "Keywords",
    "Words the language server explains on hover. The first group is Odin's; the second is what Vidar adds. All of Vidar's are contextual: they stay usable as ordinary names.",
    `## Vidar keywords\n\n${entries(vidarKw).map(doc).join("\n")}\n## Odin keywords\n\n${entries(odinKw).map(doc).join("\n")}`,
  ),
  "builtins.md": page(
    "Built-in procs and types",
    "Procs, types, constants and context fields that exist without a declaration.",
    `## Procs\n\n${entries(d.BUILTIN_PROC_DOCS).map(doc).join("\n")}\n## Types\n\n${list(d.BUILTIN_TYPE_DOCS)}\n## Constants\n\n${entries(d.ODIN_CONSTANT_DOCS).map(doc).join("\n")}\n## Context fields\n\n${entries(d.CONTEXT_FIELD_DOCS).map(doc).join("\n")}`,
  ),
  "comptime.md": page(
    "Comptime built-ins",
    "Helpers available inside a comptime proc (`proc!`) and a `comptime! { ... }` block, and what the macro parameter kinds mean. See [Comptime procs](../language/comptime.md).",
    `## Helpers\n\n${entries(d.COMPTIME_BUILTIN_DOCS).map(doc).join("\n")}\n## Parameter and result kinds\n\n${list(d.MACRO_KIND_DOCS)}`,
  ),
  "attributes.md": page(
    "Attributes",
    "Attributes written `@(name)` or `@(name=value)`. The ones marked Vidar control `-opt` and the checks; see [Faster code](../language/optimization.md).",
    `${list(d.ATTRIBUTE_DOCS)}`,
  ),
  "../internals/lowering.md": page("What Vidar generates","Each new construct, next to the Odin it becomes. These are produced by `vidar emit` from the files in `docs/snippets/lowering/`, so they match the compiler. See [Architecture](architecture.md) for the pipeline.", lowering.join("\n")),
  "cli.md": page("Command line reference", "The text `vidar` prints when run without arguments. See [Command line](../cli.md) for a guided tour.", "```text\n" + cli + "\n```\n"),
};

let stale = false;
for (const [name, text] of Object.entries(pages)) {
  const file = path.join(outDir, name);
  if (process.argv.includes("--check")) {
    if (!fs.existsSync(file) || fs.readFileSync(file, "utf8") !== text) {
      console.error(`stale: docs/reference/${name}`);
      stale = true;
    }
  } else {
    fs.mkdirSync(outDir, { recursive: true });
    fs.writeFileSync(file, text);
  }
}
if (stale) {
  console.error("run: npm run docs:gen");
  process.exit(1);
}
