package main; import __vidar "vidar_runtime"

import "core:fmt"

// `&x` captures that stay inside the frame: none of these is an error

apply :: proc(xs: []int, f: __vidar.Closure(proc(__vidar.Env, int))) { __f_call := f.call; for x in xs do __f_call(f.env, x) }

Totals :: struct { cbs: [dynamic]__vidar.Closure(proc(__vidar.Env, int)) }

sum :: proc(xs: []int) -> int {
	total := 0
	// passed to a call
	apply(xs, __closure_0(&total))
	// held in a local, called here
	add := __closure_1(&total)
	add.call(add.env, 100)
	// appended to a local array, and stored in a local struct, neither returned
	cbs: [dynamic]__vidar.Closure(proc(__vidar.Env, int))
	defer delete(cbs)
	append(&cbs, add)
	t: Totals
	t.cbs = cbs
	for cb in t.cbs do cb.call(cb.env, 1000)
	return total
}

// a pointer from new_clone outlives the frame
counter :: proc() -> __vidar.Closure(proc(__vidar.Env) -> int) {
	n := new_clone(0)
	return __closure_2(n)
}

main :: proc() {
	fmt.println(sum({1, 2, 3}))
	c := counter()
	c.call(c.env)
	fmt.println(c.call(c.env))
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int)) {
	__Caps :: struct {
		total: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:14: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int)){
		call = proc(__env_raw: __vidar.Env, x: int) { __env := transmute(__Env)__env_raw; __env.total^ += x },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_1 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env, int)) {
	__Caps :: struct {
		total: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:16: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, int)){
		call = proc(__env_raw: __vidar.Env, x: int) { __env := transmute(__Env)__env_raw; __env.total^ += x },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_2 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env) -> int) {
	__Caps :: struct {
		n: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:31: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env) -> int){
		call = proc(__env_raw: __vidar.Env) -> int { __env := transmute(__Env)__env_raw; __env.n^ += 1; return __env.n^ },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}
