package main; import __vidar "vidar_runtime"

import "core:fmt"

// u8, f64, u8, f64, bool: 40 bytes as written, 24 with the f64s first
Particle :: struct {
	x: f64,
	y: f64,
	alive: bool,
	kind: u8,
	hot: bool,
}

// already tight: left alone
Tight :: struct { a, b: f64, c: u32, d: u16 }

// printed: fmt shows fields in memory order, so it stays as written
Shown :: struct { a: u8, b: f64, c: u8 }

// measured
Measured :: struct { a: u8, b: f64, c: u8 }

// a map key: its hash follows its bytes
Key :: struct { a: u8, b: i64, c: u8 }

step :: proc(ps: []Particle) -> (sum: f64) {
	for &p in ps {
		if p.alive do p.x += p.y
		sum += p.x * f64(p.kind)
	}
	return
}

main :: proc() {
	ps := make([]Particle, 4)
	defer delete(ps)
	// positional and named literals both keep their meaning
	ps[0] = Particle{alive = true, x = 1.5, kind = 2, y = 0.5, hot = false}
	ps[1] = {alive = true, x = 2, kind = 3, y = 1}
	arr := [2]Particle{{alive = false, x = 9, kind = 1, y = 1, hot = true}, {alive = true, x = 1, kind = 1, y = 1, hot = true}}
	ps[2], ps[3] = arr[0], arr[1]
	__fmt_0(step(ps), ps[0].hot, ps[2].hot, ps[3].x)

	t := Tight{1, 2, 3, 4}
	__fmt_1(t.a + t.b + f64(t.c) + f64(t.d))
	__fmt_2(Shown{1, 2, 3})
	__fmt_1(size_of(Measured) > 0)
	m: map[Key]int
	defer delete(m)
	m[{1, 2, 3}] = 4
	__fmt_1(m[{1, 2, 3}])
}

// ---- generated by vidar ----

// fmt.println
__fmt_0 :: proc(a0: $T0, a1: $T1, a2: $T2, a3: $T3) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a2)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a3)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_1 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_2 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	when T0 == Shown { n += __print_main_Shown(w, a0) } else { n += __vidar.w_spec(w, a0, "%v") }
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt's %v for the types printed here, written out
@(private="file")
__print_main_Shown :: proc(w: __vidar.Writer, x: Shown) -> (n: int) {
	n += __vidar.w_str(w, "Shown{")
	n += __vidar.w_str(w, "a = ")
	n += __vidar.w_v(w, x.a)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "b = ")
	n += __vidar.w_float(w, x.b)
	__vidar.w_str(w, ", ")
	n += __vidar.w_str(w, "c = ")
	n += __vidar.w_v(w, x.c)
	n += __vidar.w_str(w, "}")
	return
}
