package main; import __vidar "vidar_runtime"

import "core:fmt"
import sched "vidar_sched"

// CPU work spread over goroutines, and the sync between them: the same output at any
// -define:VIDAR_THREADS, since every result is combined in an order-independent way.

work :: proc(seed: int) -> int {
	x := seed
	for _ in 0..<200_000 do x = (x * 1103515245 + 12345) & 0x7fffffff
	return x
}

main :: proc() {
	// fan out, fan in
	results := sched.make_chan(int, 4)
	for i in 0..<64 do sched.go(__closure_0(i, results))
	total := 0
	for _ in 0..<64 do total += sched.recv(results)
	fmt.println("fan-out:", total)

	// a counter behind a sched.Mutex, many goroutines, a wait group
	mu: sched.Mutex
	wg: sched.Wait_Group
	count := 0
	sched.add(&wg, 32)
	for _ in 0..<32 do sched.go(__closure_1(&mu, &wg, &count))
	sched.wait(&wg)
	fmt.println("mutex:", count)

	// select over several channels, from several senders, until all are closed
	a := sched.make_chan(int)
	b := sched.make_chan(int, 2)
	sched.go(__closure_2(a))
	sched.go(__closure_3(b))
	sum, open_a, open_b := 0, true, true
	for open_a || open_b {
		x: int
		ok: bool
		switch sched.select(sched.on_recv(a, &x, &ok), sched.on_recv(b, &x, &ok)) {
		case 0: if ok do sum += x
			else do open_a = false
		case 1: if ok do sum += x
			else do open_b = false
		}
		if !open_a do a = {}
		if !open_b do b = {}
	}
	fmt.println("select:", sum)

	// unbuffered ping-pong between two goroutines
	ping := sched.make_chan(int)
	pong := sched.make_chan(int)
	sched.go(__closure_4(ping, pong))
	hits := 0
	for {
		v, ok := sched.recv(ping)
		if !ok do break
		hits += v
		sched.send(pong, v)
	}
	fmt.println("ping-pong:", hits)
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		i: T0,
		results: T1,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:18: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw; sched.send(__env.results, work(__env.i)) },
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1}},
	}
}

__closure_1 :: proc(__c0: $T0, __c1: $T1, __c2: $T2) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		mu: T0,
		wg: T1,
		count: T2,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:28: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw;
		for _ in 0..<1000 {
			sched.lock(&__env.mu^)
			__env.count^ += 1
			sched.unlock(&__env.mu^)
			if __env.count^ % 97 == 0 do sched.yield()
		}
		sched.done(&__env.wg^)
	},
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1, __c2}},
	}
}

__closure_2 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		a: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:43: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw; for i in 1..=100 do sched.send(__env.a, i); sched.close(__env.a) },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_3 :: proc(__c0: $T0) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		b: T0,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:44: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw; for i in 1..=100 do sched.send(__env.b, 1000 * i); sched.close(__env.b) },
		env = transmute(__vidar.Env)__Env{__caps = {__c0}},
	}
}

__closure_4 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(__vidar.Env)) {
	__Caps :: struct {
		ping: T0,
		pong: T1,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at input.vidar:63: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env)){
		call = proc(__env_raw: __vidar.Env) { __env := transmute(__Env)__env_raw; for v in 0..<500 { sched.send(__env.ping, v); _ = sched.recv(__env.pong) } ; sched.close(__env.ping) },
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1}},
	}
}
