package main; import __vidar "vidar_runtime"

import "core:fmt"
import "core:math"
import "core:strings"

Shape :: struct { data: rawptr, __vtable: ^__Shape_VTable }
area :: proc{__Shape_area, circle_area, square_area}

Circle :: struct { r: f64 }
Square :: struct { side: f64 }

circle_area :: proc(c: ^Circle) -> f64 { return 3 * c.r * c.r }
square_area :: proc(s: ^Square) -> f64 { return s.side * s.side }




Vec :: struct { x, y: f64 }

length :: proc { length_vec, length_xy }
length_vec :: proc(v: Vec) -> f64 { return math.sqrt(v.x * v.x + v.y * v.y) }
length_xy :: proc(x, y: f64) -> f64 { return length_vec(Vec{x, y}) }

fib :: proc(n: int) -> int { return n if n < 2 else fib(n - 1) + fib(n - 2) }

// interface calls, proc groups, recursion, core:math and fmt.println: nothing here allocates

summary :: proc(shapes: []Shape, words: []string) -> (total: f64, tagged: int) { when __vidar.NO_ALLOC_CHECKS { context.allocator = __vidar.panic_allocator(); context.temp_allocator = context.allocator };
	double :: proc(x: f64) -> f64 { return 2 * x }
	for s in shapes do total += double(area(s))
	total += length(Vec{3, 4}) + length(6, 8) + f64(fib(10))
	for w in words do if strings.has_prefix(w, "#") do tagged += 1
	buf: [64]byte
	fmt.println(fmt.bprintf(buf[:], "%.1f/%d", total, tagged))
	return
}

// called with a constant, so -opt specializes it; each copy keeps the check

sum_to :: proc(xs: []int, n: int) -> (s: int) { when __vidar.NO_ALLOC_CHECKS { context.allocator = __vidar.panic_allocator(); context.temp_allocator = context.allocator };
	for i in 0..<n do s += xs[i]
	return
}

main :: proc() {
	c := Circle{1}
	sq := Square{2}
	shapes := []Shape{__Shape_from(&c), __Shape_from(&sq)}
	fmt.println(summary(shapes, {"#a", "b", "#c"}))
	xs := []int{1, 2, 3, 4}
	fmt.println(sum_to(xs, 3), sum_to(xs, 4))
}

// ---- generated by vidar ----

__Shape_VTable :: struct {
	area: proc(self: Shape) -> f64,
}

__Shape_area :: proc(s: Shape) -> f64 {
	if s.__vtable == &__Shape_vtable_Circle { return circle_area(auto_cast s.data) }
	if s.__vtable == &__Shape_vtable_Square { return square_area(auto_cast s.data) }
	return s.__vtable.area(s)
}

__Shape_identity :: #force_inline proc(v: Shape) -> Shape { return v }

__Shape_from :: proc{__Shape_from_Circle, __Shape_from_Square, __Shape_identity}

@(rodata)
__Shape_vtable_Circle := __Shape_VTable{
	area = proc(self: Shape) -> f64 { return circle_area((^Circle)(self.data)) },
}

__Shape_from_Circle :: proc(p: ^Circle) -> Shape { return {data = p, __vtable = &__Shape_vtable_Circle} }

@(rodata)
__Shape_vtable_Square := __Shape_VTable{
	area = proc(self: Shape) -> f64 { return square_area((^Square)(self.data)) },
}

__Shape_from_Square :: proc(p: ^Square) -> Shape { return {data = p, __vtable = &__Shape_vtable_Square} }
