import { CompileError, Token } from "./lexer";
import { Block, Expr, File, Node, ProcSig, Stmt, children } from "./ast";
import { posix } from "node:path";
import { A, AnonField, AnonTemp, Analyzer, IfaceMethod, ImplInfo, posOf } from "./analyzer";
import type { CaptureSym, GlobalSym, LocalSym, PackageInfo, PkgSym, Sym, Ty, Unit } from "./scope";

type ProcLit = Extract<Expr, { k: "ProcLit" }>;
type Call = Extract<Expr, { k: "Call" }>;
type InterfaceType = Extract<Expr, { k: "InterfaceType" }>;

/** Shared by every generated package, so closure types are identical across packages. */
export const CLOSURE_RUNTIME = `// Generated by vidar: runtime support shared by all packages.
package vidar_runtime

import "base:intrinsics"
import "base:runtime"
import "core:fmt"
import "core:sync"
import "core:time"

// a closure: a proc plus its captured environment
Closure :: struct($P: typeid) {
	call: P,
	env:  rawptr,
}

// scoped!: a block's own temp allocator
Temp_Arena :: runtime.Default_Temp_Allocator

temp_arena_begin :: proc(arena: ^Temp_Arena, backing: runtime.Allocator) -> runtime.Allocator {
	runtime.default_temp_allocator_init(arena, 64 * runtime.Kilobyte, backing)
	return runtime.default_temp_allocator(arena)
}

temp_arena_end :: proc(arena: ^Temp_Arena) {
	runtime.default_temp_allocator_destroy(arena)
}

// built-in macros: with_allocator!, locked!, timed!, dbg!, check!, todo!, unimplemented!, format!
lock :: proc(m: ^$T) { sync.lock(m) }
unlock :: proc(m: ^$T) { sync.unlock(m) }

timer_start :: proc() -> time.Tick { return time.tick_now() }

timer_report :: proc(label, site: string, start: time.Tick) {
	fmt.eprintf("[timed] %s: %v\\n", label if label != "" else site, time.tick_since(start))
}

dbg :: proc(value: $T, text, site: string) -> T {
	fmt.eprintf("[%s] %s = %v\\n", site, text, value)
	return value
}

check_failed :: proc(text: string, message: string, loc := #caller_location) -> ! {
	panic(fmt.tprintf("check failed: %s%s", text, message != "" ? fmt.tprintf(" (%s)", message) : ""), loc)
}

check_failed_cmp :: proc(text: string, message: string, lhs_text: string, lhs: $A, rhs_text: string, rhs: $B, loc := #caller_location) -> ! {
	msg := fmt.tprintf("check failed: %s%s", text, message != "" ? fmt.tprintf(" (%s)", message) : "")
	if lhs_text != "" do msg = fmt.tprintf("%s\\n\\t%s = %v", msg, lhs_text, lhs)
	if rhs_text != "" do msg = fmt.tprintf("%s\\n\\t%s = %v", msg, rhs_text, rhs)
	panic(msg, loc)
}

not_done :: proc(what: string, message: string, loc := #caller_location) -> ! {
	panic(message != "" ? fmt.tprintf("%s: %s", what, message) : what, loc)
}

tprintf :: proc(format: string, args: ..any) -> string { return fmt.tprintf(format, ..args) }

// whether a result signals failure: false for an ok-bool, otherwise anything but the zero/nil value
failed :: #force_inline proc(e: $T) -> bool {
	when T == bool {
		return !e
	} else when intrinsics.type_is_union(T) || intrinsics.type_is_pointer(T) {
		return e != nil
	} else {
		zero: T
		return e != zero
	}
}

// \`catch unreachable\`: the error was not supposed to happen
unexpected :: proc(e: $T, loc := #caller_location) -> ! {
	when T == bool {
		panic("unexpected failure", loc)
	} else {
		panic(fmt.tprintf("unexpected error: %v", e), loc)
	}
}
`;

const RUNTIME_ALIAS = "__vidar";
const RUNTIME_MARK = "\u0000vidar-runtime\u0000";

export class Emitter {
  usesRuntime = false;
  private fileUsesRuntime = false;
  private helpers: string[] = [];
  private callHelpers = new Map<string, string>();
  private closureCount = 0;
  private callHelperCount = 0;
  private prologue = new Map<Block, string[]>();
  private file!: File;
  private pkg!: PackageInfo;

  constructor(private an: Analyzer, private unit: Unit) {}

  emitFile(f: File, pkg: PackageInfo): string {
    this.file = f;
    this.pkg = pkg;
    this.helpers = [];
    this.callHelpers.clear();
    this.fileUsesRuntime = false;
    const root = { k: "Block", toks: f.toks, start: 0, end: f.toks.length, stmts: f.stmts } as Block;
    let out = f.toks[0].pre + this.generic(root, 0, f.toks.length, f.stmts);
    const runtime = this.fileUsesRuntime ? `; import ${RUNTIME_ALIAS} "${relImport(this.unit.outDir, "vidar_runtime")}"` : "";
    out = out.replace(RUNTIME_MARK, runtime);
    if (this.helpers.length || this.callHelpers.size) {
      out = out.replace(/\s*$/, "\n");
      out += "\n// ---- generated by vidar ----\n\n" + [...this.helpers, ...this.callHelpers.values()].join("\n\n") + "\n";
    }
    return out;
  }

  // ---- generic emission ----

  private generic(n: Node, from = n.start, to = n.end, kidsIn?: Node[]): string {
    const kids = (kidsIn ?? children(n)).filter((c) => c.toks === n.toks && c.end > c.start && c.start >= from && c.end <= to).sort((a, b) => a.start - b.start);
    let out = "";
    let ki = 0;
    for (let i = from; i < to; ) {
      while (ki < kids.length && kids[ki].start < i) ki++;
      const tok = n.toks[i];
      const pre = i === from ? "" : tok.pre;
      if (ki < kids.length && kids[ki].start === i) {
        out += pre + this.withPre(kids[ki]);
        i = kids[ki].end;
        ki++;
      } else {
        const text = this.tok(tok);
        const blanked = text === "" && this.an.tokText.has(tok);
        out += (blanked ? pre.replace(/[^\n]+$/, "") : pre) + text;
        i++;
      }
    }
    return out;
  }

  private tok(t: Token): string {
    return this.an.tokText.get(t) ?? t.text;
  }

  private withPre(n: Node): string {
    const pre: Stmt[] | undefined = A(n)._pre;
    const body = this.emit(n);
    return pre?.length ? pre.map((s) => this.emit(s)).join("; ") + "; " + body : body;
  }

  emit(n: Node): string {
    const iface: GlobalSym | undefined = A(n)._wrapIface;
    let text = this.emitNode(n);
    if (iface) text = `${this.qualify(iface, fromName(iface))}(${text})`;
    const fix: { prefix: string; suffix: string } | undefined = A(n)._fix;
    return fix ? fix.prefix + text + fix.suffix : text;
  }

  private emitNode(n: Node): string {
    switch (n.k) {
      case "Ident": {
        const sym: Sym | undefined = A(n)._sym;
        if (!sym && n.name === RUNTIME_ALIAS) this.fileUsesRuntime = this.usesRuntime = true; // used by built-in macros
        return sym ? this.symRef(sym) : this.generic(n);
      }
      case "Selector": {
        const member: GlobalSym | undefined = A(n)._pkgMember;
        if (!member) return this.generic(n);
        return member.pkg.unit === this.unit ? member.odinName : `${this.generic(n.x)}.${member.odinName}`;
      }
      case "Package":
        return (this.unit.merged ? `package ${this.unit.name}` : this.generic(n)) + RUNTIME_MARK;
      case "Import": {
        const sym: PkgSym | undefined = A(n)._sym;
        const target = sym?.target;
        if (!sym || !target) return this.generic(n);
        if (target.unit === this.unit) return "";
        return `import ${sym.name} "${relImport(this.unit.outDir, target.unit.outDir)}"`;
      }
      case "MacroCall":
        return keepLines(n, this.emit(A(n)._expansion));
      case "ExprStmt": {
        const exp: Block | undefined = A(n)._expansion;
        if (exp) return keepLines(n, this.inline(exp));
        return A(n)._orReturn ? this.orReturn(n) : this.generic(n);
      }
      case "Block":
        return n.inline ? this.inline(n) : this.block(n);
      case "ValueDecl": {
        const temps: AnonTemp[] | undefined = A(n)._anonTemps;
        const hoisted = temps?.map((t, i) => `${t.pre.includes("\n") ? t.pre : i ? " " : ""}${t.name} := ${this.emit(t.value)};`).join("").concat(" ") ?? "";
        const text = hoisted + (A(n)._orReturn ? this.orReturn(n) : this.valueDecl(n));
        return hoisted ? keepLines(n, text) : text;
      }
      case "CompoundLit":
        return A(n)._anon ? this.anonLit(n) : this.generic(n);
      case "Assign":
        return A(n)._orReturn ? this.orReturn(n) : this.generic(n);
      case "Catch":
        return this.catchStmt(n);
      case "ErrDefer":
        this.fileUsesRuntime = this.usesRuntime = true;
        return `defer if ${RUNTIME_ALIAS}.failed(${A(n)._errName}) { ${this.emit(n.stmt)} }`;
      case "ProcLit":
        return A(n)._ifaceMethod ? this.methodGroup(n, A(n)._ifaceMethod) : this.procLit(n);
      case "RangeFor": {
        const syms: LocalSym[] = A(n)._syms ?? [];
        const boxed = syms.filter((s) => s.boxed);
        if (boxed.length) this.prologue.set(n.body, boxed.map((s) => `${s.name} := new_clone(${s.name})`));
        return this.generic(n);
      }
      case "Call": {
        const conv: GlobalSym | undefined = A(n)._ifaceConv;
        if (conv) return `${this.qualify(conv, fromName(conv))}(${n.args.map((a) => this.emit(a)).join(", ")})`;
        return A(n)._closure ? this.closureCall(n) : this.generic(n);
      }
      case "InterfaceType":
        return this.interfaceType(n);
      case "ImplBlock":
        if (A(n)._impl) this.implHelpers(A(n)._impl);
        return this.generic(n, n.start, n.end, []);
      case "ClosureType":
        return this.closureType(n.sig);
      default:
        return this.generic(n);
    }
  }

  private inline(b: Block): string {
    return b.stmts.map((s) => this.withPre(s)).join("; ");
  }

  private block(b: Block): string {
    const lines = this.prologue.get(b);
    if (!lines?.length) return this.generic(b);
    this.prologue.delete(b);
    const next = b.toks[b.start + 1];
    return this.tok(b.toks[b.start]) + " " + lines.join("; ") + ";" + (next.pre || " ") + this.generic(b, b.start + 1);
  }

  private symRef(sym: Sym): string {
    switch (sym.kind) {
      case "global": return sym.odinName;
      case "local": return sym.boxed ? `${sym.name}^` : sym.name;
      case "capture": return sym.byRef ? `__env.${sym.name}^` : `__env.${sym.name}`;
      case "pkg": return sym.name;
    }
  }

  // ---- error handling ----

  /** The left-hand names, the call, and assignments to run after the error check. */
  private failHead(s: Stmt, call: string, errVar: string): { head: string; tail: string } {
    if (s.k === "ValueDecl") return { head: `${[...s.names.map((n) => n.name), errVar].join(", ")} := ${call}`, tail: "" };
    if (s.k === "Assign") {
      const temps = s.lhs.map((_, i) => `${errVar}_v${i}`);
      return { head: `${[...temps, errVar].join(", ")} := ${call}`, tail: `; ${s.lhs.map((l) => this.emit(l)).join(", ")} = ${temps.join(", ")}` };
    }
    const discard: number = A(s)._discard ?? 0;
    return { head: `${[...Array(discard).fill("_"), errVar].join(", ")} := ${call}`, tail: "" };
  }

  /** `x := f() or_return .E` -> `x, e := f(); if failed(e) do return {}, .E` */
  private orReturn(s: Stmt): string {
    const info: { postfix: Extract<Expr, { k: "Postfix" }>; results: number; errVar: string } = A(s)._orReturn;
    this.fileUsesRuntime = this.usesRuntime = true;
    const { head, tail } = this.failHead(s, this.emit(info.postfix.x), info.errVar);
    const values = [...Array(info.results - 1).fill("{}"), this.emit(info.postfix.value!)];
    return `${head}; if ${RUNTIME_ALIAS}.failed(${info.errVar}) do return ${values.join(", ")}${tail}`;
  }

  private catchStmt(s: Extract<Stmt, { k: "Catch" }>): string {
    this.fileUsesRuntime = this.usesRuntime = true;
    const errVar: string = A(s)._errVar;
    const { head, tail } = this.failHead(s.stmt, this.emit(A(s)._value), errVar);
    let handler: string;
    if (s.unreachable || !s.body) handler = `{ ${RUNTIME_ALIAS}.unexpected(${errVar}) }`;
    else {
      const bind = s.errName ? [`${s.errName} := ${errVar}`] : [];
      if (s.body.toks[s.body.start].text === "do") handler = `{ ${[...bind, ...s.body.stmts.map((x) => this.emit(x))].join("; ")} }`;
      else {
        if (bind.length) this.prologue.set(s.body, bind);
        handler = this.emit(s.body);
      }
    }
    return `${head}; if ${RUNTIME_ALIAS}.failed(${errVar}) ${handler}${tail}`;
  }

  /** `name` declared in `owner`'s package, as spelled from the file being emitted. */
  private qualify(owner: GlobalSym, name: string, what = `use interface '${owner.name}'`): string {
    if (owner.pkg.unit === this.unit) return name;
    const scope = this.pkg.fileScopes.get(this.file);
    for (const s of scope?.syms.values() ?? []) if (s.kind === "pkg" && s.target?.unit === owner.pkg.unit) return `${s.name}.${name}`;
    throw new CompileError(`to ${what} here, this file needs to import package '${owner.pkg.name}'`, posOf(this.file.stmts[0] ?? owner.decl));
  }

  // ---- declarations ----

  private valueDecl(s: Extract<Stmt, { k: "ValueDecl" }>): string {
    if (s.values.length && s.values.every((v) => v.k === "ProcLit" && v.comptime)) {
      const lines = s.toks.slice(s.start + 1, s.end).reduce((n, t) => n + (t.pre.match(/\n/g)?.length ?? 0), 0);
      return "\n".repeat(lines);
    }
    const syms: Sym[] = A(s)._syms ?? [];
    if (!syms.some((x) => x.kind === "local" && x.boxed)) return this.generic(s);
    const boxed = (i: number) => (syms[i] as LocalSym).boxed;
    const names = s.names.map((n) => n.name);
    if (!s.type && s.values.length === names.length) {
      return `${names.join(", ")} := ${s.values.map((v, i) => (boxed(i) ? `new_clone(${this.emit(v)})` : this.emit(v))).join(", ")}`;
    }
    if (s.type && s.values.length === 0) {
      const t = this.emit(s.type);
      return names.map((n, i) => (boxed(i) ? `${n} := new(${t})` : `${n}: ${t}`)).join("; ");
    }
    if (s.type && names.length === 1 && s.values.length === 1) {
      return `${names[0]} := new(${this.emit(s.type)}); ${names[0]}^ = ${this.emit(s.values[0])}`;
    }
    throw new CompileError("cannot capture by reference a variable declared from a multi-value expression; declare it separately", posOf(s));
  }

  // ---- anonymous struct literals ----

  /** `{ a = 1 }` -> `struct { a: type_of(__anon1_a) }{a = __anon1_a}`; the values were hoisted into temps. */
  private anonLit(n: Extract<Expr, { k: "CompoundLit" }>): string {
    return `${this.anonType(n)}${this.anonValue(n)}`;
  }

  private anonType(n: Extract<Expr, { k: "CompoundLit" }>): string {
    const fields: AnonField[] = A(n)._anon;
    return `struct { ${fields.map((f) => `${f.name}: ${f.nested ? this.anonType(f.nested) : `type_of(${f.temp})`}`).join(", ")} }`;
  }

  private anonValue(n: Extract<Expr, { k: "CompoundLit" }>): string {
    const fields: AnonField[] = A(n)._anon;
    return `{${fields.map((f) => `${f.name} = ${f.nested ? this.anonValue(f.nested) : f.temp}`).join(", ")}}`;
  }

  // ---- interfaces ----

  private paramList(sig: ProcSig): { decl: string; forward: string[] } {
    const decl: string[] = [];
    const forward: string[] = [];
    sig.params.forEach((p, gi) => {
      const t = p.type ? this.emit(p.type) : "";
      const variadic = p.type?.k === "Spread";
      if (sig.unnamed) {
        decl.push(`p${gi}: ${t}`);
        forward.push(variadic ? `..p${gi}` : `p${gi}`);
      } else {
        decl.push(`${p.names.map((n) => n.name).join(", ")}: ${t}`);
        for (const n of p.names) forward.push(variadic ? `..${n.name}` : n.name);
      }
    });
    return { decl: decl.join(", "), forward };
  }

  /** The interface value: a data pointer plus a vtable; each method is a dispatcher proc. */
  private interfaceType(t: InterfaceType): string {
    const sym: GlobalSym = A(t)._ifaceSym;
    const name = sym.odinName;
    const methods: IfaceMethod[] = A(t)._methods;
    const vtable = methods.map((m) => {
      const { decl } = this.paramList(m.rest);
      return `\t${m.name}: proc(self: ${name}${decl ? ", " + decl : ""})${this.results(m.rest)},\n`;
    });
    const dispatchers = methods.map((m) => {
      const { decl, forward } = this.paramList(m.lit.sig);
      const res = this.results(m.lit.sig);
      return `${dispatcherName(m)} :: proc(${decl})${res} { ${res ? "return " : ""}${forward[0]}.__vtable.${m.name}(${forward.join(", ")}) }`;
    });
    const impls = this.an.impls.filter((i) => i.iface === sym);
    const overloads = [...impls.map((i) => `__${name}_from_${i.key}`), `__${name}_identity`];
    this.helpers.push(
      `__${name}_VTable :: struct {\n${vtable.join("")}}\n\n` +
        dispatchers.join("\n\n") + "\n\n" +
        `__${name}_identity :: #force_inline proc(v: ${name}) -> ${name} { return v }\n\n` +
        `${fromName(sym)} :: proc{${overloads.join(", ")}}`,
    );
    return keepLines(t, `struct { data: rawptr, __vtable: ^__${name}_VTable }`);
  }

  /** `m :: proc(x: I, ...) ---` -> `m :: proc{dispatcher, every bound impl proc}` */
  private methodGroup(lit: ProcLit, m: IfaceMethod): string {
    const procs = this.an.impls.filter((i) => i.iface === m.iface).map((i) => i.methods.get(m.name)!.odinName);
    return keepLines(lit, `proc{${[dispatcherName(m), ...procs].join(", ")}}`);
  }

  private implHelpers(info: ImplInfo): void {
    const name = info.iface.odinName;
    const node = info.iface.decl.values[info.iface.index] as InterfaceType;
    const methods: IfaceMethod[] = A(node)._methods;
    const T = this.emit(info.node.target);
    const thunks = methods.map((m) => {
      const { decl, forward } = this.paramList(m.rest);
      const res = this.results(m.rest);
      const call = `${info.methods.get(m.name)!.odinName}((^${T})(self.data)${forward.map((f) => ", " + f).join("")})`;
      return `\t${m.name} = proc(self: ${name}${decl ? ", " + decl : ""})${res} { ${res ? "return " : ""}${call} },\n`;
    });
    const vt = `__${name}_vtable_${info.key}`;
    this.helpers.push(
      `@(rodata)\n${vt} := __${name}_VTable{\n${thunks.join("")}}\n\n` +
        `__${name}_from_${info.key} :: proc(p: ^${T}) -> ${name} { return {data = p, __vtable = &${vt}} }`,
    );
  }

  // ---- closures ----

  private closureType(sig: ProcSig): string {
    this.usesRuntime = true;
    const params = sig.params.flatMap((p) => {
      if (!p.type) throw new CompileError("closure parameters need explicit types", p.names[0] ? undefined : undefined);
      const t = this.emit(p.type);
      return sig.unnamed ? [t] : p.names.map(() => t);
    });
    this.fileUsesRuntime = true;
    return `${RUNTIME_ALIAS}.Closure(proc(rawptr${params.map((t) => ", " + t).join("")})${this.results(sig)})`;
  }

  private results(sig: ProcSig): string {
    const types = sig.results.flatMap((r) => {
      const t = r.type ? this.emitNode(r.type) : "";
      return sig.resultsUnnamed ? [t] : r.names.map(() => t);
    });
    if (!types.length) return "";
    return types.length === 1 ? ` -> ${types[0]}` : ` -> (${types.join(", ")})`;
  }

  /** Gives unnamed results names so `errdefer` can look at the error result after `return`. */
  private nameResults(p: ProcLit): void {
    const rs = p.sig.results;
    rs.forEach((r, i) => {
      if (!r.type) return;
      const name = i === rs.length - 1 ? "__err" : `__r${i}`;
      const bare = rs.length === 1 && p.toks[r.type.start - 1]?.text === "->";
      A(r.type)._fix = bare ? { prefix: `(${name}: `, suffix: ")" } : { prefix: `${name}: `, suffix: "" };
    });
  }

  private procLit(p: ProcLit): string {
    if (A(p)._nameResults) this.nameResults(p);
    const params: LocalSym[] = A(p)._params ?? [];
    const boxedParams = params.filter((s) => s.boxed).map((s) => `${s.name} := new_clone(${s.name})`);
    if (!p.captures) {
      if (p.body && boxedParams.length) this.prologue.set(p.body, boxedParams);
      return this.generic(p);
    }
    if (!p.body) throw new CompileError("closure literal needs a body", posOf(p));
    const caps: CaptureSym[] = A(p)._captures;
    const sigText = this.closureType(p.sig);
    let paren = p.start;
    while (!(p.toks[paren].kind === "op" && p.toks[paren].text === "]")) paren++;
    paren++;
    const signature = this.generic(p, paren, p.body.start);
    const withEnv = /^\(\s*\)/.test(signature)
      ? signature.replace(/^\(\s*\)/, "(__env_raw: rawptr)")
      : signature.replace(/^\(/, "(__env_raw: rawptr, ");
    this.prologue.set(p.body, [...(caps.length ? ["__env := cast(^__Env)__env_raw"] : []), ...boxedParams]);
    const body = this.emit(p.body);
    const procText = `proc${withEnv} ${body}`;
    if (!caps.length) return `${sigText}{call = ${procText}, env = nil}`;

    const id = this.closureCount++;
    const helper = `__closure_${id}`;
    this.helpers.push(
      `${helper} :: proc(${caps.map((c, i) => `__c${i}: $T${i}`).join(", ")}) -> ${sigText} {\n` +
        `\t__Env :: struct {\n${caps.map((c, i) => `\t\t${c.name}: T${i},\n`).join("")}\t}\n` +
        `\treturn ${sigText}{\n\t\tcall = ${procText},\n` +
        `\t\tenv = new_clone(__Env{${caps.map((_, i) => `__c${i}`).join(", ")}}),\n\t}\n}`,
    );
    return `${helper}(${caps.map((c) => this.captureArg(c)).join(", ")})`;
  }

  /** The value handed to a closure constructor for one capture, as seen at the creation site. */
  private captureArg(c: CaptureSym): string {
    const t = c.target;
    if (t.kind === "local") {
      if (c.byRef) return t.name;
      return t.boxed ? `${t.name}^` : t.name;
    }
    if (c.byRef) return t.byRef ? `__env.${t.name}` : `&__env.${t.name}`;
    return t.byRef ? `__env.${t.name}^` : `__env.${t.name}`;
  }

  private isSimple(e: Expr): boolean {
    switch (e.k) {
      case "Ident": return true;
      case "Selector": return this.isSimple(e.x);
      case "Paren": return this.isSimple(e.x);
      case "Index": return !e.slice && this.isSimple(e.x) && e.indices.every((i) => i && (i.k === "Lit" || i.k === "Ident"));
      default: return false;
    }
  }

  private closureCall(c: Call): string {
    const ty: Extract<Ty, { t: "sig" }> = A(c)._closure;
    const callee = this.emit(c.fn);
    const args = c.args.map((a) => this.emit(a));
    if (this.isSimple(c.fn)) return `${callee}.call(${[`${callee}.env`, ...args].join(", ")})`;
    const sig = this.closureType(ty.sig);
    let name = this.callHelpers.has(sig) ? undefined : `__call_closure_${this.callHelperCount++}`;
    if (name) {
      const params = ty.sig.params.flatMap((p) => (ty.sig.unnamed ? [p.type!] : p.names.map(() => p.type!))).map((t) => this.emit(t));
      const res = this.results(ty.sig);
      this.callHelpers.set(sig,
        `${name} :: #force_inline proc(c: ${sig}${params.map((t, i) => `, p${i}: ${t}`).join("")})${res} {\n` +
          `\t${res ? "return " : ""}c.call(c.env${params.map((_, i) => `, p${i}`).join("")})\n}`);
    } else name = /^(\S+) ::/.exec(this.callHelpers.get(sig)!)![1];
    return `${name}(${[callee, ...args].join(", ")})`;
  }
}

function fromName(iface: GlobalSym): string {
  return `__${iface.odinName}_from`;
}

function dispatcherName(m: IfaceMethod): string {
  return `__${m.iface.odinName}_${m.name}`;
}

function relImport(fromDir: string, toDir: string): string {
  return posix.relative(fromDir || ".", toDir || ".") || ".";
}

/** Pads generated code to the line count of the code it replaces, so later line numbers still match. */
function keepLines(n: Node, text: string): string {
  let lines = 0;
  for (let i = n.start + 1; i < n.end; i++) lines += n.toks[i].pre.split("\n").length - 1;
  const have = text.split("\n").length - 1;
  return have < lines ? text + "\n".repeat(lines - have) : text;
}
