import { CompileError, Token } from "./lexer";
import { Block, Expr, File, Node, ProcSig, Stmt, children } from "./ast";
import { posix } from "node:path";
import { A, AnonField, AnonTemp, Analyzer, IfaceMethod, ImplInfo, SpecInfo, TableInfo, isStmt, nodeText, posOf } from "./analyzer";
import { joinTokens, repeatable } from "./comptime";
import { FmtPiece, decodeString, encodeString, parseFormat } from "./fmtspec";
import { AllocGroup, optimizeProc } from "./optimize";
import type { CaptureSym, GlobalSym, LocalSym, PackageInfo, PkgSym, Sym, Ty, Unit } from "./scope";

type ProcLit = Extract<Expr, { k: "ProcLit" }>;
type Call = Extract<Expr, { k: "Call" }>;
type InterfaceType = Extract<Expr, { k: "InterfaceType" }>;

/** Shared by every generated package, so closure types are identical across packages. */
export const CLOSURE_RUNTIME = `// Generated by vidar: runtime support shared by all packages.
package vidar_runtime

import "base:intrinsics"
import "base:runtime"
import "core:bufio"
import "core:fmt"
import "core:io"
import "core:mem"
import "core:os"
import "core:path/filepath"
import "core:slice"
import "core:strings"
import "core:sync"
import "core:time"

// a closure: a proc plus its captured environment
Closure :: struct($P: typeid) {
	call: P,
	env:  rawptr,
}

// scoped!: a block's own temp allocator
Temp_Arena :: runtime.Default_Temp_Allocator

temp_arena_begin :: proc(arena: ^Temp_Arena, backing: runtime.Allocator) -> runtime.Allocator {
	runtime.default_temp_allocator_init(arena, 64 * runtime.Kilobyte, backing)
	return runtime.default_temp_allocator(arena)
}

temp_arena_end :: proc(arena: ^Temp_Arena) {
	runtime.default_temp_allocator_destroy(arena)
}

// built-in macros: with_allocator!, locked!, timed!, track!, dbg!, check!, todo!, unimplemented!
lock :: proc(m: ^$T) { sync.lock(m) }
unlock :: proc(m: ^$T) { sync.unlock(m) }

timer_start :: proc() -> time.Tick { return time.tick_now() }

timer_report :: proc(label, site: string, start: time.Tick) {
	fmt.eprintf("[timed] %s: %v\\n", label if label != "" else site, time.tick_since(start))
}

// track!: allocations that outlive a block
Tracker :: mem.Tracking_Allocator

// release builds (no -debug) keep the allocator and skip tracking
track_begin :: proc(backing: runtime.Allocator, internals := context.allocator) -> runtime.Allocator {
	when !ODIN_DEBUG {
		return backing
	} else {
		t := new(Tracker, internals)
		mem.tracking_allocator_init(t, backing, internals)
		t.bad_free_callback = track_foreign_free
		return mem.tracking_allocator(t)
	}
}

// a free of memory allocated before the block
track_foreign_free :: proc(t: ^Tracker, memory: rawptr, loc: runtime.Source_Code_Location) {
	runtime.mem_free(memory, t.backing, loc)
}

track_end :: proc(a: runtime.Allocator, label, site: string) {
	when ODIN_DEBUG do track_report(a, label, site)
}

track_report :: proc(a: runtime.Allocator, label, site: string) {
	t := (^Tracker)(a.data)
	name := label if label != "" else site
	sync.mutex_lock(&t.mutex)
	n := len(t.allocation_map)
	if n == 0 {
		fmt.eprintf("[track] %s: nothing escaped\\n", name)
		internals := t.allocation_map.allocator
		mem.tracking_allocator_destroy(t)
		free(t, internals)
		return
	}
	// t stays alive: escaped memory may still be freed through it
	defer sync.mutex_unlock(&t.mutex)
	entries := make([]mem.Tracking_Allocator_Entry, n, t.allocation_map.allocator)
	defer delete(entries, t.allocation_map.allocator)
	i, bytes := 0, 0
	for _, e in t.allocation_map {
		entries[i] = e
		i += 1
		bytes += e.size
	}
	slice.sort_by(entries, proc(x, y: mem.Tracking_Allocator_Entry) -> bool {
		if x.location.file_path != y.location.file_path do return x.location.file_path < y.location.file_path
		return x.location.line < y.location.line
	})
	fmt.eprintf("[track] %s: %d allocation%s escaped (%d bytes)\\n", name, n, "" if n == 1 else "s", bytes)
	for e in entries {
		fmt.eprintf("\\t%d bytes at %s:%d\\n", e.size, filepath.base(e.location.file_path), e.location.line)
	}
}

dbg :: proc(value: $T, text, site: string) -> T {
	fmt.eprintf("[%s] %s = %v\\n", site, text, value)
	return value
}

check_failed :: proc(text: string, message: string, loc := #caller_location) -> ! {
	panic(fmt.tprintf("check failed: %s%s", text, message != "" ? fmt.tprintf(" (%s)", message) : ""), loc)
}

check_failed_cmp :: proc(text: string, message: string, lhs_text: string, lhs: $A, rhs_text: string, rhs: $B, loc := #caller_location) -> ! {
	msg := fmt.tprintf("check failed: %s%s", text, message != "" ? fmt.tprintf(" (%s)", message) : "")
	if lhs_text != "" do msg = fmt.tprintf("%s\\n\\t%s = %v", msg, lhs_text, lhs)
	if rhs_text != "" do msg = fmt.tprintf("%s\\n\\t%s = %v", msg, rhs_text, rhs)
	panic(msg, loc)
}

not_done :: proc(what: string, message: string, loc := #caller_location) -> ! {
	panic(message != "" ? fmt.tprintf("%s: %s", what, message) : what, loc)
}

do_fell_off :: proc(loc := #caller_location) -> ! {
	panic("do!: the block ended without a take", loc)
}

// whether a result signals failure: false for an ok-bool, otherwise anything but the zero/nil value
failed :: #force_inline proc(e: $T) -> bool {
	when T == bool {
		return !e
	} else when intrinsics.type_is_union(T) || intrinsics.type_is_pointer(T) {
		return e != nil
	} else {
		zero: T
		return e != zero
	}
}

// \`catch unreachable\`: the error was not supposed to happen
unexpected :: proc(e: $T, loc := #caller_location) -> ! {
	when T == bool {
		panic("unexpected failure", loc)
	} else {
		panic(fmt.tprintf("unexpected error: %v", e), loc)
	}
}
${fmtRuntime()}
${groupRuntime()}`;

/** -opt: `make_groupN` allocates N zeroed slices in one block, each aligned for its element type. */
function groupRuntime(): string {
  const procs: string[] = [];
  for (let n = 2; n <= 8; n++) {
    const ix = Array.from({ length: n }, (_, i) => i + 1);
    const lines = [
      `\tif ${ix.map((i) => `n${i} < 0`).join(" || ")} do panic("make: negative length", loc)`,
      `\to1 := 0`,
      ...ix.slice(1).map((i) => `\to${i} := mem.align_forward_int(o${i - 1} + size_of(E${i - 1}) * n${i - 1}, align_of(E${i}))`),
      `\tbase, err := mem.alloc(o${n} + size_of(E${n}) * n${n}, max(${ix.map((i) => `align_of(E${i})`).join(", ")}, mem.DEFAULT_ALIGNMENT), allocator, loc)`,
      `\tif err != nil do return`,
      ...ix.map((i) => `\ts${i} = ([^]E${i})(uintptr(base) + uintptr(o${i}))[:n${i}]`),
      `\treturn`,
    ];
    procs.push(
      `make_group${n} :: proc(${ix.map((i) => `$E${i}`).join(", ")}: typeid, ${ix.map((i) => `n${i}`).join(", ")}: int, allocator := context.allocator, loc := #caller_location) -> (${ix.map((i) => `s${i}: []E${i}`).join(", ")}) {\n${lines.join("\n")}\n}`,
    );
  }
  return `\n// -opt: allocations freed together, made together\n${procs.join("\n\n")}\n`;
}

/**
 * -opt: fmt calls with a literal format become a proc per format, writing each piece with these.
 * Common verbs on basic types are written directly; anything else goes through fmt for that one value.
 */
function fmtRuntime(): string {
  const ints = "T == int || T == i8 || T == i16 || T == i32 || T == i64";
  const uints = "T == uint || T == u8 || T == u16 || T == u32 || T == u64";
  type Fast = [cond: string, sb: string, w: string];
  const str: Fast = ["T == string", "strings.write_string(b, x)", "n, _ = io.write_string(w, x)"];
  const bool: Fast = ["T == bool", `strings.write_string(b, "true" if x else "false")`, `n, _ = io.write_string(w, "true" if x else "false")`];
  const rune: Fast = ["T == rune", "strings.write_rune(b, x)", "n, _ = io.write_rune(w, x)"];
  const num = (base: number): Fast[] => [
    [ints, `strings.write_i64(b, i64(x), ${base})`, `n, _ = io.write_i64(w, i64(x), ${base})`],
    [uints, `strings.write_u64(b, u64(x), ${base})`, `n, _ = io.write_u64(w, u64(x), ${base})`],
  ];
  const verbs: Record<string, Fast[]> = { v: [str, bool, rune, ...num(10)], d: num(10), s: [str], x: num(16), t: [bool], c: [rune] };
  const chain = (fast: Fast[], pick: 1 | 2, slow: string) =>
    fast.map(([cond, ...code], i) => `${i ? " else " : "\t"}when ${cond} {\n\t\t${code[pick - 1]}\n\t}`).join("") + ` else {\n\t\t${slow}\n\t}`;
  const procs = Object.entries(verbs).map(([verb, fast]) =>
    `sb_${verb} :: #force_inline proc(b: ^strings.Builder, x: $T) {\n${chain(fast, 1, `fmt.sbprintf(b, "%${verb}", x)`)}\n}\n\n` +
    `w_${verb} :: #force_inline proc(w: io.Writer, x: $T) -> (n: int) {\n${chain(fast, 2, `n = fmt.wprintf(w, "%${verb}", x, flush = false)`)}\n\treturn\n}\n`);
  return `
// @(table) fills its table at startup, before any context exists
default_context :: proc "contextless" () -> runtime.Context { return runtime.default_context() }

// -opt: fmt calls specialized to their format
Builder :: strings.Builder
Writer :: io.Writer
File_Writer :: bufio.Writer

builder :: #force_inline proc(allocator: runtime.Allocator) -> (b: strings.Builder) {
	strings.builder_init(&b, allocator)
	return
}

sb_to_string :: #force_inline proc(b: ^strings.Builder) -> string { return strings.to_string(b^) }

sb_str :: #force_inline proc(b: ^strings.Builder, s: string) { strings.write_string(b, s) }

sb_spec :: proc(b: ^strings.Builder, x: $T, spec: string) { fmt.sbprintf(b, spec, x) }

// what fmt.printf and fmt.eprintf write through
std_writer :: proc(b: ^bufio.Writer, buf: []byte, to_stderr: bool) -> io.Writer {
	bufio.writer_init_with_buf(b, os.to_stream(os.stderr if to_stderr else os.stdout), buf)
	return bufio.writer_to_writer(b)
}

w_str :: #force_inline proc(w: io.Writer, s: string) -> (n: int) {
	n, _ = io.write_string(w, s)
	return
}

w_spec :: proc(w: io.Writer, x: $T, spec: string) -> int { return fmt.wprintf(w, spec, x, flush = false) }

w_flush :: #force_inline proc(w: io.Writer) { io.flush(w) }

${procs.join("\n")}`;
}

const RUNTIME_ALIAS = "__vidar";
const RUNTIME_MARK = "\u0000vidar-runtime\u0000";
/** past this many vtables to test, a dispatcher keeps the plain indirect call */
const MAX_DEVIRTUAL = 8;

// Generated line breaks are written as markers and resolved into a line map once the file is done.
// A real "\n" always comes from the source, so it advances the source line.
const GEN_NL = "\u0001";
const GEN_NL_END = "\u0002";
/** a source line break the output leaves out */
const SKIP_LINE = "\u0003";

/** A generated line break; the next line maps to source `line` (negative when vidar wrote that line). */
function nl(line: number): string {
  return `${GEN_NL}${line}${GEN_NL_END}`;
}

export interface EmittedFile {
  text: string;
  /** source line (1-based) of each output line; negative for lines vidar generated, 0 for helpers */
  lines: number[];
}

/** Code produced by a macro: written out from its syntax tree, one statement per line. */
interface Pretty {
  /** the source line generated lines are attributed to */
  line: number;
  file: string;
  from: number;
  to: number;
}

export class Emitter {
  usesRuntime = false;
  private fileUsesRuntime = false;
  private helpers: string[] = [];
  private callHelpers = new Map<string, string>();
  private closureCount = 0;
  private callHelperCount = 0;
  private prologue = new Map<Block, string[]>();
  private file!: File;
  private pkg!: PackageInfo;
  private pretty: Pretty | null = null;
  /** keeps blocks of generated code on one line */
  private compact = false;
  /** indentation of the statement being emitted */
  private indent = "";
  /** comments naming the macro calls in the statement being emitted */
  private notes: string[] = [];
  /** the statement emitted as part of a statement list, where it may take several lines */
  private listed: Node | null = null;
  private indents = new Map<number, string>();
  /** indentation added to source lines, inside a block vidar wrapped them in */
  private deeper = "";
  /** `break`/`continue` statements retargeted while a pool loop's body is emitted once per type */
  private branchText = new Map<Node, string>();
  private poolLoops = 0;
  /** -opt: specialized fmt procs of this unit, by what they write */
  private fmtProcs = new Map<string, string>();

  constructor(private an: Analyzer, private unit: Unit) {}

  emitFile(f: File, pkg: PackageInfo): EmittedFile {
    this.file = f;
    this.pkg = pkg;
    this.helpers = [];
    this.callHelpers.clear();
    this.fileUsesRuntime = false;
    this.indents.clear();
    for (const t of f.toks) if (t.pre.includes("\n") && !this.indents.has(t.pos.line)) this.indents.set(t.pos.line, t.pre.slice(t.pre.lastIndexOf("\n") + 1));
    const root = { k: "Block", toks: f.toks, start: 0, end: f.toks.length, stmts: f.stmts } as Block;
    let out = f.toks[0].pre + this.generic(root, 0, f.toks.length, f.stmts);
    const runtime = this.fileUsesRuntime ? `; import ${RUNTIME_ALIAS} "${relImport(this.unit.outDir, "vidar_runtime")}"` : "";
    out = out.replace(RUNTIME_MARK, runtime);
    const { text, lines } = resolveLines(out);
    out = text;
    if (this.helpers.length || this.callHelpers.size) {
      out = out.replace(/\s*$/, "\n");
      while (lines.length < out.split("\n").length) lines.push(0);
      out += "\n// ---- generated by vidar ----\n\n" + resolveLines([...this.helpers, ...this.callHelpers.values()].join("\n\n")).text + "\n";
      while (lines.length < out.split("\n").length) lines.push(0);
    }
    return { text: out, lines };
  }

  // ---- generic emission ----

  private generic(n: Node, from = n.start, to = n.end, kidsIn?: Node[]): string {
    const kids = (kidsIn ?? children(n)).filter((c) => c.toks === n.toks && c.end > c.start && c.start >= from && c.end <= to).sort((a, b) => a.start - b.start);
    const list = isList(n);
    let out = "";
    let ki = 0;
    for (let i = from; i < to; ) {
      while (ki < kids.length && kids[ki].start < i) ki++;
      const tok = n.toks[i];
      const pre = i === from ? "" : this.pretty ? squash(tok.pre) : this.ws(tok.pre);
      if (ki < kids.length && kids[ki].start === i) {
        const kid = kids[ki];
        const whole = BARE_PARENTS.has(n.k) && !(n.k === "Call" && n.fn === kid);
        if (kid.k === "MacroCall" && whole) A(kid)._bare = true;
        // generated code parenthesizes spliced expressions; a whole argument or value doesn't need it
        const shown = this.pretty && whole && kid.k === "Paren" ? kid.x : kid;
        out += pre + (list && isStmt(kid) ? this.listStmt(kid as Stmt, this.indentOf(kid)) : this.withPre(shown));
        i = kid.end;
        ki++;
      } else {
        const text = this.tok(tok);
        const blanked = text === "" && this.an.tokText.has(tok);
        out += (blanked ? pre.replace(/[^\n]+$/, "") : pre) + text;
        i++;
      }
    }
    return out;
  }

  private ws(pre: string): string {
    return this.deeper ? pre.replace(/\n(?!\n)/g, "\n" + this.deeper) : pre;
  }

  private tok(t: Token): string {
    return this.an.tokText.get(t) ?? t.text;
  }

  private withPre(n: Node): string {
    const pre: Stmt[] | undefined = A(n)._pre;
    const body = this.emit(n);
    return pre?.length ? pre.map((s) => this.emit(s)).join("; ") + "; " + body : body;
  }

  emit(n: Node): string {
    const iface: GlobalSym | undefined = A(n)._wrapIface;
    let text = this.emitNode(n);
    if (iface) text = `${this.qualify(iface, fromName(iface))}(${text})`;
    const up: { from: GlobalSym; to: GlobalSym } | undefined = A(n)._upcast;
    if (up) text = `${this.qualify(up.from, upcastName(up.from, up.to), `convert '${up.from.name}' to '${up.to.name}'`)}(${text})`;
    const fix: { prefix: string; suffix: string } | undefined = A(n)._fix;
    if (fix) text = fix.prefix + text + fix.suffix;
    // -opt: every index in the statement is proven in bounds
    return A(n)._noBounds ? `#no_bounds_check ${text}` : text;
  }

  private emitNode(n: Node): string {
    switch (n.k) {
      case "Ident": {
        const sym: Sym | undefined = A(n)._sym;
        if (!sym && n.name === RUNTIME_ALIAS) this.fileUsesRuntime = this.usesRuntime = true; // used by built-in macros
        return sym ? this.symRef(sym) : this.generic(n);
      }
      case "Selector": {
        const member: GlobalSym | undefined = A(n)._pkgMember;
        if (!member) return this.generic(n);
        return member.pkg.unit === this.unit ? member.odinName : `${this.generic(n.x)}.${member.odinName}`;
      }
      case "Package":
        return (this.unit.merged ? `package ${this.unit.name}` : this.generic(n)) + RUNTIME_MARK;
      case "Import": {
        const sym: PkgSym | undefined = A(n)._sym;
        const target = sym?.target;
        if (!sym || !target) return this.generic(n);
        if (target.unit === this.unit) return "";
        return `import ${sym.name} "${relImport(this.unit.outDir, target.unit.outDir)}"`;
      }
      case "MacroCall": {
        this.note(n);
        const exp: Expr = A(n)._expansion;
        // parentheses around an expansion that is a whole argument or value are only noise
        const bare = A(n)._bare && exp.k === "Paren" ? exp.x : exp;
        return this.inPretty(n, () => this.emit(bare)) + this.skipLines(n);
      }
      case "ExprStmt": {
        const exp: Block | undefined = A(n)._expansion;
        if (exp) {
          if (n.x.k === "MacroCall") this.note(n.x);
          return this.inPretty(n, () => this.expansion(n, exp)) + this.skipLines(n);
        }
        return A(n)._orReturn ? this.orReturn(n) : this.generic(n);
      }
      case "Block":
        if (n.inline) return this.inline(n);
        if (this.pretty && this.tok(n.toks[n.start]) === "{") return this.compact ? `{ ${n.stmts.map((s) => this.withPre(s)).join("; ")} }` : this.prettyBlock(n);
        if (this.tok(n.toks[n.start]) !== "do") return this.block(n);
        // statements hoisted before the body, or a prologue, must stay under the `do`
        if (n.stmts.some((s) => A(s)._pre?.length) || this.prologue.has(n)) {
          const lines = this.prologue.get(n) ?? [];
          this.prologue.delete(n);
          return `{ ${[...lines, ...n.stmts.map((s) => this.withPre(s))].join("; ")} }`;
        }
        // Odin rejects `do { ... }`, which a statement macro that expands to several statements gives
        return this.block(n).replace(/^do\s+(?=\{)/, "");
      case "Switch":
        return this.pretty ? this.prettySwitch(n) : this.generic(n);
      case "ValueDecl": {
        const temps: AnonTemp[] | undefined = A(n)._anonTemps;
        const hoisted = temps?.map((t, i) => `${t.pre.includes("\n") ? t.pre : i ? " " : ""}${t.name} := ${this.emit(t.value)};`).join("").concat(" ") ?? "";
        if (A(n)._allocGroup) return keepLines(n, this.allocGroup(A(n)._allocGroup));
        const declared: GlobalSym | undefined = A(n)._syms?.[0];
        const table = declared?.kind === "global" ? this.an.tables.get(declared) : undefined;
        if (table) return this.tableDecl(n, declared!, table);
        const spec = declared?.kind === "global" ? this.an.specialized.get(declared) : undefined;
        if (spec) for (const [key, consts] of spec.clones) this.helpers.push(this.specClone(declared!, spec, key, consts));
        if (A(n)._allocGrouped) return `/* ${n.names[0].name}: allocated together with ${A(n)._allocGrouped} */` + this.skipLines(n);
        const text = hoisted + (A(n)._orReturn ? this.orReturn(n) : this.valueDecl(n));
        return hoisted ? keepLines(n, text) : text;
      }
      case "CompoundLit":
        if (A(n)._anon) return this.anonLit(n);
        return this.pretty ? `${n.type ? this.emit(n.type) : ""}{${n.elems.map((e) => this.withPre(e)).join(", ")}}` : this.generic(n);
      case "Assign":
        return A(n)._orReturn ? this.orReturn(n) : this.generic(n);
      case "Catch":
        return this.catchStmt(n);
      case "Defer": {
        const free: { group: AllocGroup; keep: boolean } | undefined = A(n)._groupFree;
        if (!free) return this.generic(n);
        const first = free.group.members[0];
        const alloc = free.group.allocator ? `, ${this.emit(free.group.allocator)}` : "";
        if (free.keep) return `defer free(${first.count ? `raw_data(${first.name})` : first.name}${alloc})` + this.skipLines(n);
        return `/* ${joinTokens(n.toks.slice(n.stmt.start, n.stmt.end))}: freed together with ${first.name} */` + this.skipLines(n);
      }
      case "ErrDefer":
        this.fileUsesRuntime = this.usesRuntime = true;
        return `defer if ${RUNTIME_ALIAS}.failed(${A(n)._errName}) { ${this.emit(n.stmt)} }`;
      case "ProcLit":
        return A(n)._ifaceMethod ? this.methodGroup(n, A(n)._ifaceMethod) : this.procLit(n);
      case "Labeled":
        return n.stmt.k === "RangeFor" && A(n.stmt)._pool ? this.poolFor(n.stmt, n.label) : this.generic(n);
      case "Branch":
        return this.branchText.get(n) ?? this.generic(n);
      case "RangeFor": {
        if (A(n)._pool) return this.poolFor(n, null);
        const syms: LocalSym[] = A(n)._syms ?? [];
        const shadowed = syms.filter((s) => s.refCaptured);
        if (shadowed.length) this.prologue.set(n.body, shadowed.map(addressable));
        return this.generic(n);
      }
      case "Call": {
        const spec: { sym: GlobalSym; key: string } | undefined = A(n)._spec;
        if (spec) return this.qualify(spec.sym, `${spec.sym.odinName}__${spec.key}`, `call '${spec.sym.name}'`) + this.generic(n, n.fn.end);
        if (A(n)._pool) return this.qualify(A(n)._pool, poolName(A(n)._pool));
        if (A(n)._poolOp) return this.poolOp(n);
        const conv: GlobalSym | undefined = A(n)._ifaceConv;
        if (conv && n.args.length === 1 && A(n.args[0])._upcast) return this.emit(n.args[0]);
        if (conv) return `${this.qualify(conv, fromName(conv))}(${n.args.map((a) => this.emit(a)).join(", ")})`;
        if (A(n)._closure) return this.closureCall(n);
        return (this.an.optimize && this.fmtCall(n)) || this.generic(n);
      }
      case "InterfaceType":
        return this.interfaceType(n);
      case "Binary": {
        const cmp: { iface: GlobalSym; value: Expr } | undefined = A(n)._ifaceNil;
        // an interface value is nil when it has no vtable
        if (cmp) return `${this.emit(cmp.value)}.__vtable ${n.op} nil`;
        return this.generic(n);
      }
      case "ImplBlock":
        for (const info of (A(n)._impls as ImplInfo[] | undefined) ?? []) this.implHelpers(info);
        return this.generic(n, n.start, n.end, []);
      case "ClosureType":
        return this.closureType(n.sig);
      default:
        return this.generic(n);
    }
  }

  private inline(b: Block): string {
    return b.stmts.map((s) => this.withPre(s)).join("; ");
  }

  // ---- macro expansions ----

  /** Runs `f` emitting code a macro produced for `n`; lines it adds are attributed to `n`'s line. */
  private inPretty<T>(n: Node, f: () => T): T {
    if (this.pretty) return f();
    const first = n.toks[n.start].pos;
    this.pretty = { line: first.line, file: first.file, from: first.line, to: n.toks[n.end - 1].pos.line };
    try {
      return f();
    } finally {
      this.pretty = null;
    }
  }

  /** Source line breaks inside `n`, which the code replacing it leaves out. */
  private skipLines(n: Node): string {
    if (n.toks !== this.file.toks) return "";
    let lines = 0;
    for (let i = n.start + 1; i < n.end; i++) lines += n.toks[i].pre.split("\n").length - 1;
    return SKIP_LINE.repeat(lines);
  }

  /** The source line a line starting with `n` maps to: its own for code written in the file, else the macro call's. */
  private lineOf(n: Node): number {
    const pos = n.toks[n.start]?.pos;
    const p = this.pretty;
    if (!p) return pos.line;
    if (pos && pos.file === p.file && pos.line >= p.from && pos.line <= p.to) return pos.line;
    return -p.line;
  }

  /** Records a comment naming a macro call written in this file, put on its own line before the statement. */
  private note(call: Extract<Expr, { k: "MacroCall" }>): void {
    const pos = call.toks[call.start].pos;
    const p = this.pretty;
    const written = call.toks === this.file.toks || (p && pos.file === p.file && pos.line >= p.from && pos.line <= p.to);
    if (!written) return;
    const name = `${call.path.join(".")}!`;
    let bang = call.start;
    while (!(call.toks[bang].kind === "op" && call.toks[bang].text === "!")) bang++;
    const after = (end: number) => {
      const rest = joinTokens(call.toks.slice(bang + 1, end));
      return rest.startsWith("(") ? rest : rest && ` ${rest}`;
    };
    let text = name + after(call.end);
    if (call.blockArg && (text.length > 60 || call.toks[call.end - 1].pos.line !== pos.line)) {
      text = name + after(call.toks.indexOf(call.args[call.args.length - 1][0], call.start)) + " { ... }";
    }
    if (text.length > 60) text = `${name}(...)`;
    this.notes.push(`// ${text} — ${posix.basename(pos.file)}:${pos.line}`);
  }

  private indentOf(n: Node): string {
    const pre = n.toks[n.start].pre;
    if (pre.includes("\n")) return pre.slice(pre.lastIndexOf("\n") + 1) + this.deeper;
    // a statement after others on its line: lines it adds go one level in
    return (this.indents.get(n.toks[n.start].pos.line) ?? "") + this.deeper + "\t";
  }

  /**
   * A statement of a statement list. The comments for its macro calls and the statements macros
   * hoisted in front of it each go on their own line before it.
   */
  private listStmt(s: Stmt, indent: string): string {
    const outer = { notes: this.notes, indent: this.indent, listed: this.listed };
    this.notes = [];
    this.indent = indent;
    this.listed = s;
    try {
      const hoisted: Stmt[] = A(s)._pre ?? [];
      const before = hoisted.length ? this.inPretty(s, () => hoisted.map((h): [number, string] => [this.lineOf(h), this.hoisted(h)])) : [];
      const body = this.emit(s);
      const lines: [number, string][] = [...this.notes.map((c) => [-Math.abs(this.lineOf(s)), c] as [number, string]), ...before];
      if (!lines.length) return body;
      const head = lines.map(([, text], i) => (i ? nl(lines[i][0]) + indent : "") + text).join("");
      return body ? head + nl(this.lineOf(s)) + indent + body : head;
    } finally {
      ({ notes: this.notes, indent: this.indent, listed: this.listed } = outer);
    }
  }

  private hoisted(s: Stmt): string {
    if (!A(s)._compact) return this.emit(s);
    this.compact = true;
    try {
      return this.emit(s);
    } finally {
      this.compact = false;
    }
  }

  /** Statements on lines of their own, the first one where the output already is. */
  private stmtLines(stmts: Stmt[], indent: string, lead: boolean): string {
    let out = "";
    const line = (s: Stmt, text: string) => (out += (lead || out !== "" ? nl(this.lineOf(s)) + indent : "") + text);
    for (const s of stmts) {
      if (s.k === "Block" && s.inline) {
        out += this.stmtLines(s.stmts, indent, lead || out !== "");
        continue;
      }
      for (const c of s.toks[s.start].pre.match(/\/\/[^\n]*/g) ?? []) line(s, c);
      line(s, this.listStmt(s, indent));
    }
    return out;
  }

  /** What a statement macro expands to: one statement per line, in braces where only one statement fits. */
  private expansion(s: Stmt, exp: Block): string {
    const flat = (b: Block): Stmt[] => b.stmts.flatMap((x) => (x.k === "Block" && x.inline ? flat(x) : [x]));
    const stmts = flat(exp);
    if (this.listed === s) return this.stmtLines(stmts, this.indent, false);
    if (stmts.length === 1) return this.emit(stmts[0]);
    return this.braced(stmts, n0(exp));
  }

  private braced(stmts: Stmt[], close: number, extra: string[] = []): string {
    const outer = this.indent;
    const inner = outer + "\t";
    const prologue = extra.map((text) => nl(-Math.abs(close)) + inner + text).join("");
    const body = this.stmtLines(stmts, inner, true);
    if (!prologue && !body) return "{}";
    return "{" + prologue + body + nl(close) + outer + "}";
  }

  private prettyBlock(b: Block): string {
    const extra = this.prologue.get(b) ?? [];
    this.prologue.delete(b);
    const close = { ...b, start: b.end - 1 } as Block;
    return this.braced(b.stmts, this.lineOf(close), extra);
  }

  private prettySwitch(s: Extract<Stmt, { k: "Switch" }>): string {
    const first = s.cases[0]?.start ?? s.end - 1;
    let brace = first - 1;
    while (brace > s.start && this.tok(s.toks[brace]) !== "{") brace--;
    const head = this.generic(s, s.start, brace + 1, children(s).filter((c) => c.end <= brace));
    const outer = this.indent;
    let out = head;
    for (const c of s.cases) {
      let colon = c.start;
      while (colon < c.end && !(c.toks[colon].kind === "op" && c.toks[colon].text === ":")) colon++;
      out += nl(this.lineOf(c)) + outer + this.generic(c, c.start, colon + 1, c.exprs) + this.stmtLines(c.body, outer + "\t", true);
    }
    return out + nl(this.lineOf({ ...s, start: s.end - 1 } as Stmt)) + outer + "}";
  }

  private block(b: Block): string {
    const lines = this.prologue.get(b);
    if (!lines?.length) return this.generic(b);
    this.prologue.delete(b);
    const next = b.toks[b.start + 1];
    return this.tok(b.toks[b.start]) + " " + lines.join("; ") + ";" + (this.ws(next.pre) || " ") + this.generic(b, b.start + 1);
  }

  private symRef(sym: Sym): string {
    switch (sym.kind) {
      case "global": return sym.odinName;
      case "local": return sym.name;
      case "capture": return sym.byRef ? `__env.${sym.name}^` : `__env.${sym.name}`;
      case "pkg": return sym.name;
    }
  }

  // ---- error handling ----

  /** The left-hand names and the call, and the assignment to run after the error check. */
  private failHead(s: Stmt, call: string, errVar: string): { head: string; tail: string } {
    if (s.k === "ValueDecl") return { head: `${[...s.names.map((n) => n.name), errVar].join(", ")} := ${call}`, tail: "" };
    if (s.k === "Assign") {
      const temps = s.lhs.map((_, i) => `${errVar}_v${i}`);
      return { head: `${[...temps, errVar].join(", ")} := ${call}`, tail: `${s.lhs.map((l) => this.emit(l)).join(", ")} = ${temps.join(", ")}` };
    }
    const discard: number = A(s)._discard ?? 0;
    return { head: `${[...Array(discard).fill("_"), errVar].join(", ")} := ${call}`, tail: "" };
  }

  /** `x := f() or_return .E` -> `x, e := f(); if failed(e) do return {}, .E`; with named results, as Odin: `{ err = .E; return }` */
  private orReturn(s: Stmt): string {
    const info: { postfix: Extract<Expr, { k: "Postfix" }>; results: number; errVar: string; proc: ProcLit } = A(s)._orReturn;
    this.fileUsesRuntime = this.usesRuntime = true;
    const { head, tail } = this.failHead(s, this.emit(info.postfix.x), info.errVar);
    const value = this.emit(info.postfix.value!);
    const errName = this.errorResultName(info.proc.sig, A(info.proc)._nameResults);
    const exit = errName
      ? `{ ${errName} = ${value}; return }`
      : `do return ${[...Array(info.results - 1).fill("{}"), value].join(", ")}`;
    return `${head}; if ${RUNTIME_ALIAS}.failed(${info.errVar}) ${exit}${tail && `; ${tail}`}`;
  }

  private errorResultName(sig: ProcSig, synthesized: boolean): string | undefined {
    if (sig.resultsUnnamed) return synthesized ? "__err" : undefined;
    const last = sig.results[sig.results.length - 1];
    return last.names[last.names.length - 1].name;
  }

  /**
   * A declaration keeps its names in scope: `x, e := f()`, then the check on a line of its own.
   * An assignment or a bare call goes in a block of its own, which keeps the temporaries out of scope.
   */
  private catchStmt(s: Extract<Stmt, { k: "Catch" }>): string {
    this.fileUsesRuntime = this.usesRuntime = true;
    const errVar: string = A(s)._errVar;
    const { head, tail } = this.failHead(s.stmt, this.emit(A(s)._value), errVar);
    const check = `if ${RUNTIME_ALIAS}.failed(${errVar}) `;
    if (this.listed !== s || this.pretty || this.compact) return `${head}; ${check}${this.catchHandler(s, errVar, false)}${tail && `; ${tail}`}`;
    const gen = nl(-this.lineOf(s));
    if (s.stmt.k === "ValueDecl") {
      this.notes.push(this.catchNote(s));
      return head + gen + this.indent + check + this.catchHandler(s, errVar, true);
    }
    const outer = this.deeper;
    const inner = this.indent + "\t";
    this.deeper += "\t";
    try {
      const lines = [head, check + this.catchHandler(s, errVar, true), ...(tail ? [tail] : [])];
      return `{ ${this.catchNote(s)}` + lines.map((l) => gen + inner + l).join("") + gen + this.indent + "}";
    } finally {
      this.deeper = outer;
    }
  }

  private catchHandler(s: Extract<Stmt, { k: "Catch" }>, errVar: string, multiline: boolean): string {
    if (s.unreachable || !s.body) return multiline ? `do ${RUNTIME_ALIAS}.unexpected(${errVar})` : `{ ${RUNTIME_ALIAS}.unexpected(${errVar}) }`;
    const bind = s.errName ? [`${s.errName} := ${errVar}`] : [];
    const b = s.body;
    if (b.toks[b.start].text === "do") return `{ ${[...bind, ...b.stmts.map((x) => this.emit(x))].join("; ")} }`;
    const first = b.toks[b.start + 1].pre;
    if (multiline && bind.length && first.includes("\n")) {
      const indent = first.slice(first.lastIndexOf("\n") + 1) + this.deeper;
      return "{" + nl(-this.lineOf(s)) + indent + bind[0] + this.ws(first) + this.generic(b, b.start + 1);
    }
    if (bind.length) this.prologue.set(b, bind);
    return this.emit(b);
  }

  /** `// x := f() catch err { ... } — file.vidar:12` */
  private catchNote(s: Extract<Stmt, { k: "Catch" }>): string {
    const pos = s.toks[s.start].pos;
    const handler = !s.body ? " unreachable" : s.body.toks[s.body.start].text === "do" ? " do ..." : " { ... }";
    const text = `${joinTokens(s.toks.slice(s.stmt.start, s.stmt.end))} catch${s.errName ? ` ${s.errName}` : ""}${handler}`;
    return `// ${text} — ${posix.basename(pos.file)}:${pos.line}`;
  }

  /** `name` declared in `owner`'s package, as spelled from the file being emitted. */
  private qualify(owner: GlobalSym, name: string, what = `use interface '${owner.name}'`): string {
    if (owner.pkg.unit === this.unit) return name;
    const scope = this.pkg.fileScopes.get(this.file);
    for (const s of scope?.syms.values() ?? []) if (s.kind === "pkg" && s.target?.unit === owner.pkg.unit) return `${s.name}.${name}`;
    throw new CompileError(`to ${what} here, this file needs to import package '${owner.pkg.name}'`, posOf(this.file.stmts[0] ?? owner.decl));
  }

  // ---- declarations ----

  private valueDecl(s: Extract<Stmt, { k: "ValueDecl" }>): string {
    if (s.values.length && s.values.every((v) => v.k === "ProcLit" && v.comptime)) {
      const lit = s.values[0] as ProcLit;
      const pos = s.toks[s.start].pos;
      const head = joinTokens(s.toks.slice(s.start, lit.body!.start));
      return `// ${head} — comptime, ${posix.basename(pos.file)}:${pos.line}` + this.skipLines(s);
    }
    return this.generic(s);
  }

  // ---- anonymous struct literals ----

  /** `{ a = 1 }` -> `struct { a: type_of(__anon1_a) }{a = __anon1_a}`; the values were hoisted into temps. */
  private anonLit(n: Extract<Expr, { k: "CompoundLit" }>): string {
    return `${this.anonType(n)}${this.anonValue(n)}`;
  }

  private anonType(n: Extract<Expr, { k: "CompoundLit" }>): string {
    const fields: AnonField[] = A(n)._anon;
    return `struct { ${fields.map((f) => `${f.name}: ${f.nested ? this.anonType(f.nested) : `type_of(${f.temp})`}`).join(", ")} }`;
  }

  private anonValue(n: Extract<Expr, { k: "CompoundLit" }>): string {
    const fields: AnonField[] = A(n)._anon;
    return `{${fields.map((f) => `${f.name} = ${f.nested ? this.anonValue(f.nested) : f.temp}`).join(", ")}}`;
  }

  // ---- interfaces ----

  private paramList(sig: ProcSig): { decl: string; forward: string[] } {
    const decl: string[] = [];
    const forward: string[] = [];
    sig.params.forEach((p, gi) => {
      const t = p.type ? this.emit(p.type) : "";
      const variadic = p.type?.k === "Spread";
      if (sig.unnamed) {
        decl.push(`p${gi}: ${t}`);
        forward.push(variadic ? `..p${gi}` : `p${gi}`);
      } else {
        decl.push(`${p.names.map((n) => n.name).join(", ")}: ${t}`);
        for (const n of p.names) forward.push(variadic ? `..${n.name}` : n.name);
      }
    });
    return { decl: decl.join(", "), forward };
  }

  /** The interface value: a data pointer plus a vtable; each method is a dispatcher proc. */
  private interfaceType(t: InterfaceType): string {
    const sym: GlobalSym = A(t)._ifaceSym;
    const name = sym.odinName;
    const methods: IfaceMethod[] = A(t)._methods;
    const bases = this.an.basesOf(sym).map((b) => `\t${baseField(sym, b)}: ${this.qualify(b, `__${b.odinName}_VTable`)},\n`);
    const vtable = methods.map((m) => {
      const { decl } = this.paramList(m.rest);
      return `\t${m.name}: proc(self: ${name}${decl ? ", " + decl : ""})${this.results(m.rest)},\n`;
    });
    const upcasts = this.an.ancestorsOf(sym).map((a) => {
      const fields = [sym, ...this.an.basePath(sym, a)!].reduce<string[]>((acc, x, i, path) => (i ? [...acc, baseField(path[i - 1], x)] : acc), []);
      return `${upcastName(sym, a)} :: #force_inline proc(v: ${name}) -> ${this.qualify(a, a.odinName)} { return {data = v.data, __vtable = &v.__vtable.${fields.join(".")}} }`;
    });
    const dispatchers = methods.map((m) => {
      const { decl, forward } = this.paramList(m.lit.sig);
      const res = this.results(m.lit.sig);
      const indirect = `${res ? "return " : ""}${forward[0]}.__vtable.${m.name}(${forward.join(", ")})`;
      return this.dispatcher(dispatcherName(m), decl, res, forward[0], forward.slice(1), sym, m, indirect);
    });
    const inherited = this.an.allMethods(sym).filter((m) => this.inheritors(m).includes(sym)).map((m) => {
      const { decl, forward } = this.paramList(m.rest);
      const res = this.results(m.rest);
      const path = [sym, ...this.an.basePath(sym, m.iface)!];
      const fields = path.slice(1).map((b, i) => "." + baseField(path[i], b)).join("");
      const indirect = `${res ? "return " : ""}self.__vtable${fields}.${m.name}(${[`${upcastName(sym, m.iface)}(self)`, ...forward].join(", ")})`;
      return this.dispatcher(derivedDispatcherName(sym, m), `self: ${name}${decl ? ", " + decl : ""}`, res, "self", forward, sym, m, indirect);
    });
    const impls = this.an.impls.filter((i) => i.iface === sym);
    const overloads = [...impls.map((i) => `__${name}_from_${i.key}`), `__${name}_identity`];
    this.helpers.push(
      `__${name}_VTable :: struct {\n${bases.join("")}${vtable.join("")}}\n\n` +
        [...dispatchers, ...inherited, ...upcasts].map((x) => x + "\n\n").join("") +
        `__${name}_identity :: #force_inline proc(v: ${name}) -> ${name} { return v }\n\n` +
        `${fromName(sym)} :: proc{${overloads.join(", ")}}` +
        (this.an.pooled.has(sym) ? "\n\n" + this.poolHelpers(sym).trimEnd() : ""),
    );
    return keepLines(t, `struct { data: rawptr, __vtable: ^__${name}_VTable }`);
  }

  /** `Pool(I)`: a dynamic array per implementation, so a loop over it runs over each type's values in turn. */
  private poolHelpers(sym: GlobalSym): string {
    const name = poolName(sym);
    const bins = this.an.variants(sym).map((i) => i.key);
    return (
      `${name} :: struct {\n${this.an.variants(sym).map((i) => `\t${i.key}: [dynamic]${this.implTarget(i)},\n`).join("")}}\n\n` +
      `${name}_len :: #force_inline proc(p: ${name}) -> int { return ${bins.map((b) => `len(p.${b})`).join(" + ")} }\n\n` +
      `${name}_clear :: proc(p: ^${name}) { ${bins.map((b) => `clear(&p.${b})`).join("; ")} }\n\n` +
      `${name}_delete :: proc(p: ${name}) { ${bins.map((b) => `delete(p.${b})`).join("; ")} }\n\n`
    );
  }

  private poolOp(c: Call): string {
    const { op, iface, bins }: { op: string; iface: GlobalSym; bins?: ImplInfo[] } = A(c)._poolOp;
    const pool = c.args[0];
    if (op !== "append") {
      const ptr = this.an.normalize(this.an.typeOf(pool, A(pool)._scope ?? this.an.global))?.t === "ptr";
      const arg = this.emit(pool);
      const fn = this.qualify(iface, `${poolName(iface)}_${op}`);
      if (op === "clear") return `${fn}(${ptr ? arg : `&${arg}`})`;
      return `${fn}(${ptr ? `${arg}^` : arg})`;
    }
    const base = pool.k === "Unary" && pool.op === "&" ? this.emit(pool.x) : this.emit(pool);
    const groups: { key: string; args: string[] }[] = [];
    bins!.forEach((info, i) => {
      const value = this.emit(c.args[i + 1]);
      const last = groups[groups.length - 1];
      if (last?.key === info.key) last.args.push(value);
      else groups.push({ key: info.key, args: [value] });
    });
    return groups.map((g) => `append(&${base}.${g.key}, ${g.args.join(", ")})`).join("; ");
  }

  /**
   * `for x in pool { body }`: the body once per type, `x` a pointer to the element, so method calls
   * resolve statically. A `break` leaves every copy through a labeled block around them.
   */
  private poolFor(s: Extract<Stmt, { k: "RangeFor" }>, label: string | null): string {
    const iface: GlobalSym = A(s)._pool;
    const variants = this.an.variants(iface);
    const v = s.vals[0].name;
    const { breaks, continues } = loopExits(s.body, label);
    const many = variants.length > 1;
    const id = this.poolLoops++;
    const hoist = many && !repeatable(s.x);
    const pool = hoist ? `__pool${id}` : this.emit(s.x);
    const blockLabel = many && breaks.length ? (label ?? `__pool${id}`) : null;
    const line = s.toks[s.start].pos.line;
    const copies = variants.map((info, k) => {
      if (many) for (const b of breaks) this.branchText.set(b, `break ${blockLabel}`);
      if (many) for (const c of continues) this.branchText.set(c, `continue ${label}__${info.key}`);
      const loopLabel = !label ? "" : !many ? `${label}: ` : continues.length ? `${label}__${info.key}: ` : "";
      this.prologue.set(s.body, [`${v} := &__${v}`]);
      const text = `${loopLabel}for &__${v} in ${pool}.${info.key} ${this.emit(s.body)}`;
      return k ? nl(-line) + (this.indents.get(line) ?? "") + this.deeper + relocate(text, line) : text;
    });
    for (const b of [...breaks, ...continues]) this.branchText.delete(b);
    const open = `${blockLabel ? `${blockLabel}: ` : ""}{ ${hoist ? `${pool} := ${this.emit(s.x)}; ` : ""}`;
    return hoist || blockLabel ? `${open}${copies.join("")} }` : copies.join("");
  }

  /** The type an impl is for, as spelled from the file being emitted. */
  private implTarget(info: ImplInfo): string {
    const sym: Sym | undefined = A(info.node.target)._sym ?? A(info.node.target)._pkgMember;
    return sym?.kind === "global" ? this.qualify(sym, sym.odinName, `name '${sym.name}'`) : nodeText(info.node.target);
  }

  /** Interfaces in `m`'s unit that inherit it; each gets its own dispatcher in `m`'s proc group. */
  private inheritors(m: IfaceMethod): GlobalSym[] {
    return this.an.ifaceSyms.filter((d) => d !== m.iface && d.pkg.unit === m.iface.pkg.unit && this.an.basePath(d, m.iface));
  }

  /** Calls the bound proc directly for each known vtable, else `indirect`. */
  private dispatcher(name: string, params: string, res: string, self: string, rest: string[], iface: GlobalSym, m: IfaceMethod, indirect: string): string {
    const call = (f: string, args: string[]) => (res ? `return ${f}(${args.join(", ")})` : `${f}(${args.join(", ")}); return`);
    const guards = [...this.devirtualTargets(iface, m)].map(
      ([proc, vtables]) => `\tif ${vtables.map((v) => `${self}.__vtable == ${v}`).join(" || ")} { ${call(proc, [`auto_cast ${self}.data`, ...rest])} }\n`,
    );
    if (!guards.length) return `${name} :: proc(${params})${res} { ${indirect} }`;
    return `${name} :: proc(${params})${res} {\n${guards.join("")}\t${indirect}\n}`;
  }

  /**
   * Impls must live in the interface's unit, so its dispatchers can test for each of their vtables
   * (and the copies nested in extending interfaces' vtables) and call the bound proc directly.
   */
  private devirtualTargets(iface: GlobalSym, m: IfaceMethod): Map<string, string[]> {
    const targets = new Map<string, string[]>();
    for (const info of this.an.impls) {
      if (info.iface.pkg.unit !== iface.pkg.unit) continue;
      for (const path of this.an.basePaths(info.iface, iface)) {
        const fields = path.map((b, i) => "." + baseField(i ? path[i - 1] : info.iface, b)).join("");
        const proc = info.methods.get(m.name)!.odinName;
        targets.set(proc, [...(targets.get(proc) ?? []), `&__${info.iface.odinName}_vtable_${info.key}${fields}`]);
      }
    }
    const tests = [...targets.values()].reduce((n, v) => n + v.length, 0);
    return tests > MAX_DEVIRTUAL ? new Map() : targets;
  }

  /** `m :: proc(x: I, ...) ---` -> `m :: proc{dispatcher, every bound impl proc}` */
  private methodGroup(lit: ProcLit, m: IfaceMethod): string {
    const procs = this.an.impls.filter((i) => i.iface === m.iface).map((i) => i.methods.get(m.name)!.odinName);
    return keepLines(lit, `proc{${[dispatcherName(m), ...this.inheritors(m).map((d) => derivedDispatcherName(d, m)), ...procs].join(", ")}}`);
  }

  private implHelpers(info: ImplInfo): void {
    const name = info.iface.odinName;
    const T = this.emit(info.node.target);
    const vtable = (iface: GlobalSym, indent: string): string => {
      const self = this.qualify(iface, iface.odinName);
      const bases = this.an.basesOf(iface).map((b) => `${indent}\t${baseField(iface, b)} = {\n${vtable(b, indent + "\t")}${indent}\t},\n`);
      const thunks = ((A(this.an.ifaceNode(iface))._methods as IfaceMethod[] | undefined) ?? []).map((m) => {
        const { decl, forward } = this.paramList(m.rest);
        const res = this.results(m.rest);
        const call = `${info.methods.get(m.name)!.odinName}((^${T})(self.data)${forward.map((f) => ", " + f).join("")})`;
        return `${indent}\t${m.name} = proc(self: ${self}${decl ? ", " + decl : ""})${res} { ${res ? "return " : ""}${call} },\n`;
      });
      return bases.join("") + thunks.join("");
    };
    const vt = `__${name}_vtable_${info.key}`;
    this.helpers.push(
      `@(rodata)\n${vt} := __${name}_VTable{\n${vtable(info.iface, "")}}\n\n` +
        `__${name}_from_${info.key} :: proc(p: ^${T}) -> ${name} { return {data = p, __vtable = &${vt}} }`,
    );
  }

  // ---- @(specialize) and @(table) ----

  /** A copy of a @(specialize) proc where the parameters calls pass constants to are compile-time (`$x`). */
  private specClone(sym: GlobalSym, info: SpecInfo, key: string, consts: string[]): string {
    const value = sym.decl.values[sym.index];
    const p = info.lit;
    let open = p.start;
    while (!(p.toks[open].kind === "op" && p.toks[open].text === "(")) open++;
    let close = open;
    for (let depth = 0; close < p.end; close++) {
      const t = p.toks[close].text;
      if (t === "(") depth++;
      else if (t === ")" && --depth === 0) break;
    }
    const params = p.sig.params.flatMap((g) =>
      g.names.map((n) => `${n.prefix ?? ""}${consts.includes(n.name) ? "$" : ""}${n.name}${g.type ? `: ${this.emit(g.type)}` : " :"}${g.value ? `${g.type ? " " : ""}= ${this.emit(g.value)}` : ""}`),
    );
    const ps: LocalSym[] = A(p)._params ?? [];
    const shadowed = ps.filter((x) => x.refCaptured).map(addressable);
    if (shadowed.length) this.prologue.set(p.body!, shadowed);
    const before = value !== p ? this.generic(value, value.start, p.start) + " " : "";
    const after = this.generic(p, close + 1, p.body!.start);
    const head = `${before}${this.generic(p, p.start, open)}(${params.join(", ")})${after ? " " + after : ""}`;
    return `// ${sym.name} with ${consts.join(", ")} known at compile time\n${sym.odinName}__${key} :: ${head.trimEnd()} ${this.emit(p.body!)}`;
  }

  /** @(table): the proc becomes a lookup; the table is a literal, or filled at startup from the original body. */
  private tableDecl(s: Extract<Stmt, { k: "ValueDecl" }>, sym: GlobalSym, t: TableInfo): string {
    this.fileUsesRuntime = this.usesRuntime = true;
    const name = sym.odinName;
    const T = this.emit(t.type);
    const R = this.emit(t.result);
    const table = `__${name}_table`;
    const index = { enum: t.param, u8: t.param, bool: `1 if ${t.param} else 0`, i8: `int(${t.param}) + 128` }[t.domain];
    const size = t.domain === "enum" ? `[${T}]` : t.domain === "bool" ? "[2]" : "[256]";
    if (t.values) {
      const rows = t.values.map((v, i) => `${i % 8 ? " " : "\n\t"}${v},`).join("");
      this.helpers.push(`// ${sym.name}(x) for every x, computed by vidar\n@(rodata)\n${table} := ${size}${R}{${rows}\n}`);
    } else {
      const compute = `__${name}_compute`;
      const fill = {
        enum: `for x in ${T} do ${table}[x] = ${compute}(x)`,
        bool: `${table}[0] = ${compute}(false); ${table}[1] = ${compute}(true)`,
        u8: `for i in 0..<256 do ${table}[i] = ${compute}(${T}(i))`,
        i8: `for i in 0..<256 do ${table}[i] = ${compute}(${T}(i - 128))`,
      }[t.domain];
      this.helpers.push(
        `${table}: ${size}${R}\n\n${compute} :: ${this.emit(t.lit)}\n\n` +
          `// ${sym.name}(x) for every x, computed once at startup\n@(init)\n__${name}_fill :: proc "contextless" () {\n\tcontext = ${RUNTIME_ALIAS}.default_context()\n\t${fill}\n}`,
      );
    }
    const head = this.generic(s, s.start, s.values[0].start).trimEnd() + " ";
    return keepLines(s, `${head}#force_inline proc(${t.param}: ${T}) -> ${R} { return ${table}[${index}] }`);
  }

  // ---- -opt: allocations freed together ----

  /** `xs := make([]int, n); ys := make([]f32, n)` -> `xs, ys := make_group2(int, f32, n, n)`: one block, sliced up. */
  private allocGroup(g: AllocGroup): string {
    this.fileUsesRuntime = this.usesRuntime = true;
    const names = g.members.map((m) => (m.count ? m.name : `__${m.name}`));
    const args = [...g.members.map((m) => this.emit(m.elem)), ...g.members.map((m) => (m.count ? this.emit(m.count) : "1")), ...(g.allocator ? [this.emit(g.allocator)] : [])];
    const ptrs = g.members.filter((m) => !m.count).map((m) => `; ${m.name} := &__${m.name}[0]`);
    return `${names.join(", ")} := ${RUNTIME_ALIAS}.make_group${g.members.length}(${args.join(", ")})${ptrs.join("")}`;
  }

  // ---- -opt: fmt calls with a literal format ----

  /**
   * `fmt.sbprintf(b, "hp %d/%d", hp, max)` -> `__fmt_0(b, hp, max)`, a proc that writes "hp ", hp,
   * "/" and max directly: no format parsing at run time, no `any` boxing, no type switch.
   */
  private fmtCall(c: Call): string | undefined {
    const entry = fmtEntry(c);
    if (!entry) return undefined;
    const fn = c.fn as Extract<Expr, { k: "Selector" }>;
    if (c.args.some((a) => a.k === "FieldValue" || a.k === "Spread")) return undefined;
    const lead = c.args.slice(0, entry.lead);
    const values = c.args.slice(entry.lead + (entry.format ? 1 : 0));
    const scope = A(c)._scope ?? this.an.global;
    const single = (v: Expr) => this.an.isSingleValue(v, scope) || (v.k === "Call" && !!fmtEntry(v));
    if (lead.length < entry.lead || values.some((v) => (v.k === "Ident" && v.name === "nil") || !single(v))) return undefined;
    let pieces: FmtPiece[] | undefined;
    if (entry.format) {
      const f = c.args[entry.lead];
      const text = f?.k === "Lit" && f.kind === "string" ? decodeString(this.tok(f.toks[f.start])) : undefined;
      pieces = text === undefined ? undefined : parseFormat(text);
      if (!pieces || pieces.filter((p) => p.k === "arg").length !== values.length) return undefined;
    } else pieces = values.flatMap((_, i): FmtPiece[] => [...(i ? [{ k: "text" as const, text: " " }] : []), { k: "arg", verb: "v", spec: "%v" }]);
    if (entry.newline) pieces.push({ k: "text", text: "\n" });

    const kept: Expr[] = [];
    const writes: string[] = [];
    let pending = "";
    const sink = entry.kind === "sb" ? "b" : entry.kind === "t" || entry.kind === "a" ? "&b" : "w";
    const write = (what: string, x: string, extra = "") =>
      writes.push(`\t${sink === "w" ? "n += __vidar.w_" : "__vidar.sb_"}${what}(${sink}, ${x}${extra})\n`);
    const flush = () => pending && (write("str", encodeString(pending)), (pending = ""));
    let vi = 0;
    for (const p of pieces) {
      if (p.k === "text") {
        pending += p.text;
        continue;
      }
      const v = values[vi++];
      const inline = literalText(v, p.spec, (t) => this.tok(t));
      if (inline !== undefined) {
        pending += inline;
        continue;
      }
      flush();
      const arg = `a${kept.length}`;
      kept.push(v);
      if (FAST_VERBS.has(p.verb) && p.spec === "%" + p.verb) write(p.verb, arg);
      else write("spec", arg, `, ${encodeString(p.spec)}`);
    }
    flush();

    const params = kept.map((_, i) => `a${i}: $T${i}`);
    const key = `${entry.kind}\0${writes.join("")}`;
    let name = this.fmtProcs.get(key);
    if (!name) {
      name = `__fmt_${this.fmtProcs.size}`;
      this.fmtProcs.set(key, name);
      const origin = `// fmt.${fn.name}${entry.format ? " " + this.tok(c.args[entry.lead].toks[c.args[entry.lead].start]) : ""}\n`;
      const body = writes.join("");
      const head = (extra: string[], res: string) => `${origin}${name} :: proc(${[...extra, ...params].join(", ")})${res} {\n`;
      switch (entry.kind) {
        case "sb":
          this.helpers.push(`${head(["b: ^__vidar.Builder"], " -> string")}${body}\treturn __vidar.sb_to_string(b)\n}`);
          break;
        case "t":
        case "a":
          this.helpers.push(`${head([], " -> string")}\tb := __vidar.builder(context.${entry.kind === "t" ? "temp_allocator" : "allocator"})\n${body}\treturn __vidar.sb_to_string(&b)\n}`);
          break;
        case "w":
          this.helpers.push(`${head(["w: __vidar.Writer"], " -> (n: int)")}${body}\t__vidar.w_flush(w)\n\treturn\n}`);
          break;
        default:
          this.helpers.push(
            `${head([], " -> (n: int)")}\tbuf: [1024]byte\n\tbw: __vidar.File_Writer\n\tw := __vidar.std_writer(&bw, buf[:], ${entry.kind === "err"})\n${body}\t__vidar.w_flush(w)\n\treturn\n}`,
          );
      }
      this.fileUsesRuntime = this.usesRuntime = true;
    }
    const args = [...lead, ...kept];
    let lines = 0;
    if (c.toks === this.file.toks) {
      for (let i = c.start + 1; i < c.end; i++) if (!args.some((a) => i > a.start && i < a.end)) lines += c.toks[i].pre.split("\n").length - 1;
    }
    return `${name}(${args.map((a) => this.emit(a)).join(", ")})` + SKIP_LINE.repeat(lines);
  }

  // ---- closures ----

  private closureType(sig: ProcSig): string {
    this.usesRuntime = true;
    const params = sig.params.flatMap((p) => {
      if (!p.type) throw new CompileError("closure parameters need explicit types", p.names[0] ? undefined : undefined);
      const t = this.emit(p.type);
      return sig.unnamed ? [t] : p.names.map(() => t);
    });
    this.fileUsesRuntime = true;
    return `${RUNTIME_ALIAS}.Closure(proc(rawptr${params.map((t) => ", " + t).join("")})${this.results(sig)})`;
  }

  private results(sig: ProcSig): string {
    const types = sig.results.flatMap((r) => {
      const t = r.type ? this.emitNode(r.type) : "";
      return sig.resultsUnnamed ? [t] : r.names.map(() => t);
    });
    if (!types.length) return "";
    return types.length === 1 ? ` -> ${types[0]}` : ` -> (${types.join(", ")})`;
  }

  /** Gives unnamed results names so `errdefer` can look at the error result after `return`. */
  private nameResults(p: ProcLit): void {
    const rs = p.sig.results;
    rs.forEach((r, i) => {
      if (!r.type) return;
      const name = i === rs.length - 1 ? "__err" : `__r${i}`;
      const bare = rs.length === 1 && p.toks[r.type.start - 1]?.text === "->";
      A(r.type)._fix = bare ? { prefix: `(${name}: `, suffix: ")" } : { prefix: `${name}: `, suffix: "" };
    });
  }

  private procLit(p: ProcLit): string {
    if (A(p)._nameResults) this.nameResults(p);
    if (this.an.optimize && p.body && !A(p)._optimized) {
      A(p)._optimized = true;
      optimizeProc(p.body);
    }
    const params: LocalSym[] = A(p)._params ?? [];
    const shadowedParams = params.filter((s) => s.refCaptured).map(addressable);
    if (!p.captures) {
      if (p.body && shadowedParams.length) this.prologue.set(p.body, shadowedParams);
      return this.generic(p);
    }
    if (!p.body) throw new CompileError("closure literal needs a body", posOf(p));
    const caps: CaptureSym[] = A(p)._captures;
    const sigText = this.closureType(p.sig);
    let paren = p.start;
    while (!(p.toks[paren].kind === "op" && p.toks[paren].text === "]")) paren++;
    paren++;
    const signature = this.generic(p, paren, p.body.start);
    const withEnv = /^\(\s*\)/.test(signature)
      ? signature.replace(/^\(\s*\)/, "(__env_raw: rawptr)")
      : signature.replace(/^\(/, "(__env_raw: rawptr, ");
    this.prologue.set(p.body, [...(caps.length ? ["__env := cast(^__Env)__env_raw"] : []), ...shadowedParams]);
    const body = this.emit(p.body);
    const procText = `proc${withEnv} ${body}`;
    if (!caps.length) return `${sigText}{call = ${procText}, env = nil}`;

    const id = this.closureCount++;
    const helper = `__closure_${id}`;
    this.helpers.push(
      `${helper} :: proc(${caps.map((c, i) => `__c${i}: $T${i}`).join(", ")}) -> ${sigText} {\n` +
        `\t__Env :: struct {\n${caps.map((c, i) => `\t\t${c.name}: T${i},\n`).join("")}\t}\n` +
        `\treturn ${sigText}{\n\t\tcall = ${procText},\n` +
        `\t\tenv = new_clone(__Env{${caps.map((_, i) => `__c${i}`).join(", ")}}),\n\t}\n}`,
    );
    return `${helper}(${caps.map((c) => this.captureArg(c)).join(", ")})` + this.skipLines(p);
  }

  /** The value handed to a closure constructor for one capture, as seen at the creation site. */
  private captureArg(c: CaptureSym): string {
    const t = c.target;
    if (t.kind === "local") return c.byRef ? `&${t.name}` : t.name;
    if (c.byRef) return t.byRef ? `__env.${t.name}` : `&__env.${t.name}`;
    return t.byRef ? `__env.${t.name}^` : `__env.${t.name}`;
  }

  private isSimple(e: Expr): boolean {
    switch (e.k) {
      case "Ident": return true;
      case "Selector": return this.isSimple(e.x);
      case "Paren": return this.isSimple(e.x);
      case "Index": return !e.slice && this.isSimple(e.x) && e.indices.every((i) => i && (i.k === "Lit" || i.k === "Ident"));
      default: return false;
    }
  }

  private closureCall(c: Call): string {
    const ty: Extract<Ty, { t: "sig" }> = A(c)._closure;
    const callee = this.emit(c.fn);
    const args = c.args.map((a) => this.emit(a));
    if (this.isSimple(c.fn)) return `${callee}.call(${[`${callee}.env`, ...args].join(", ")})`;
    const sig = this.closureType(ty.sig);
    let name = this.callHelpers.has(sig) ? undefined : `__call_closure_${this.callHelperCount++}`;
    if (name) {
      const params = ty.sig.params.flatMap((p) => (ty.sig.unnamed ? [p.type!] : p.names.map(() => p.type!))).map((t) => this.emit(t));
      const res = this.results(ty.sig);
      this.callHelpers.set(sig,
        `${name} :: #force_inline proc(c: ${sig}${params.map((t, i) => `, p${i}: ${t}`).join("")})${res} {\n` +
          `\t${res ? "return " : ""}c.call(c.env${params.map((_, i) => `, p${i}`).join("")})\n}`);
    } else name = /^(\S+) ::/.exec(this.callHelpers.get(sig)!)![1];
    return `${name}(${[callee, ...args].join(", ")})`;
  }
}

/** fmt procs -opt specializes: where they write, and how many arguments come before the format */
const FMT_ENTRIES = new Map<string, { kind: "out" | "err" | "t" | "a" | "sb" | "w"; lead: number; format: boolean; newline: boolean }>(
  (
    [["", "out", 0], ["e", "err", 0], ["t", "t", 0], ["a", "a", 0], ["sb", "sb", 1], ["w", "w", 1]] as const
  ).flatMap(([prefix, kind, lead]) => [
    [`${prefix}printf`, { kind, lead, format: true, newline: false }],
    [`${prefix}printfln`, { kind, lead, format: true, newline: true }],
    [`${prefix}print`, { kind, lead, format: false, newline: false }],
    [`${prefix}println`, { kind, lead, format: false, newline: true }],
  ]),
);

/** `fmt.<name>(...)` for one of the procs -opt specializes */
function fmtEntry(c: Call) {
  const fn = c.fn;
  if (fn.k !== "Selector" || fn.x.k !== "Ident") return undefined;
  const pkg: Sym | undefined = A(fn.x)._sym;
  return pkg?.kind === "pkg" && pkg.path === "core:fmt" ? FMT_ENTRIES.get(fn.name) : undefined;
}

/** verbs the runtime writes directly for basic types (see fmtRuntime) */
const FAST_VERBS = new Set(["v", "d", "s", "x", "t", "c"]);

/** A literal argument printed as `spec` gives fixed text, which goes into the format proc. */
function literalText(v: Expr, spec: string, text: (t: Token) => string): string | undefined {
  if (v.k !== "Lit") return undefined;
  const t = text(v.toks[v.start]);
  if (v.kind === "string" && (spec === "%v" || spec === "%s")) return decodeString(t);
  if (v.kind === "int" && (spec === "%v" || spec === "%d") && /^\d+$/.test(t)) return BigInt(t).toString();
  return undefined;
}

// Odin params and loop values are not addressable
function addressable(sym: LocalSym): string {
  return `${sym.name} := ${sym.name}`;
}

function poolName(iface: GlobalSym): string {
  return `__${iface.odinName}_Pool`;
}

/**
 * The `break`s and `continue`s in a loop body that leave or restart that loop: unlabeled breaks
 * outside nested loops and switches, and branches naming the loop's label.
 */
function loopExits(body: Block, label: string | null): { breaks: Node[]; continues: Node[] } {
  const breaks: Node[] = [];
  const continues: Node[] = [];
  const visit = (n: Node, nested: boolean) => {
    if (n.k === "ProcLit") return;
    if (n.k === "Branch") {
      const named = n.end - n.start > 1 ? n.toks[n.start + 1].text : null;
      if (n.op === "break" && (named ? named === label : !nested)) breaks.push(n);
      if (n.op === "continue" && named && named === label) continues.push(n);
      return;
    }
    const inner = nested || n.k === "For" || n.k === "RangeFor" || n.k === "Switch";
    const kids = [...children(n), ...((A(n)._pre as Node[] | undefined) ?? [])];
    const exp: Node | undefined = A(n)._expansion;
    if (exp) kids.push(exp);
    for (const c of kids) visit(c, inner);
  };
  for (const s of body.stmts) visit(s, false);
  return { breaks, continues };
}

/** Generated code repeating source lines: its line breaks map back to those lines instead of advancing past them. */
function relocate(text: string, line: number): string {
  let out = "";
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (c === "\n") out += nl(++line);
    else if (c === SKIP_LINE) line++;
    else if (c === GEN_NL) {
      const end = text.indexOf(GEN_NL_END, i);
      out += text.slice(i, end + 1);
      i = end;
    } else out += c;
  }
  return out;
}

function fromName(iface: GlobalSym): string {
  return `__${iface.odinName}_from`;
}

/** `iface`'s name as seen from `from`'s package, for generated names */
function baseKey(from: GlobalSym, iface: GlobalSym): string {
  return iface.pkg.unit === from.pkg.unit ? iface.odinName : `${iface.pkg.name}_${iface.odinName}`;
}

function baseField(iface: GlobalSym, base: GlobalSym): string {
  return `__${baseKey(iface, base)}`;
}

function upcastName(from: GlobalSym, to: GlobalSym): string {
  return `__${from.odinName}_as_${baseKey(from, to)}`;
}

function dispatcherName(m: IfaceMethod): string {
  return `__${m.iface.odinName}_${m.name}`;
}

/** `m` inherited by `iface`, dispatched on an `iface` value */
function derivedDispatcherName(iface: GlobalSym, m: IfaceMethod): string {
  return `__${iface.odinName}_${m.name}`;
}

const BARE_PARENTS = new Set(["Call", "ValueDecl", "Assign", "Return", "CompoundLit", "FieldValue", "Paren"]);

/** Statement lists, where a statement may become several lines. */
function isList(n: Node): boolean {
  return n.k === "Case" || (n.k === "Block" && !n.inline && (n.start === 0 || n.toks[n.start].text === "{"));
}

function n0(b: Block): number {
  return -(b.toks[b.start]?.pos.line ?? 0);
}

/** Whitespace between tokens of generated code: kept to one line (line comments become block comments). */
function squash(pre: string): string {
  if (!pre.includes("\n")) return pre;
  const comments = pre.match(/\/\/[^\n]*|\/\*[\s\S]*?\*\//g) ?? [];
  const inline = comments.map((c) => (c.startsWith("//") ? `/*${c.slice(2)} */` : c.replace(/\s*\n\s*/g, " ")));
  return inline.length ? ` ${inline.join(" ")} ` : " ";
}

/** Turns the line markers into line breaks and returns the source line of each output line. */
function resolveLines(marked: string): EmittedFile {
  const lines = [1];
  let src = 1;
  let text = "";
  for (let i = 0; i < marked.length; i++) {
    const c = marked[i];
    if (c === "\n") {
      lines.push(++src);
      text += c;
    } else if (c === GEN_NL) {
      const end = marked.indexOf(GEN_NL_END, i);
      lines.push(Number(marked.slice(i + 1, end)));
      text += "\n";
      i = end;
    } else if (c === SKIP_LINE) src++;
    else text += c;
  }
  return { text, lines };
}

function relImport(fromDir: string, toDir: string): string {
  return posix.relative(fromDir || ".", toDir || ".") || ".";
}

/** Pads generated code to the line count of the code it replaces, so later line numbers still match. */
function keepLines(n: Node, text: string): string {
  let lines = 0;
  for (let i = n.start + 1; i < n.end; i++) lines += n.toks[i].pre.split("\n").length - 1;
  const have = text.split("\n").length - 1;
  return have < lines ? text + "\n".repeat(lines - have) : text;
}
