const { test } = require("node:test");
const assert = require("node:assert/strict");
const { mkdtempSync, writeFileSync } = require("node:fs");
const { tmpdir } = require("node:os");
const { join } = require("node:path");
const { DapMap } = require("../../dist/dap/translate.js");
const { MessageReader, frame } = require("../../dist/dap/wire.js");

const dir = mkdtempSync(join(tmpdir(), "vidar-unit-"));
writeFileSync(join(dir, "main.odin"), "package main\n\nmain :: proc() {\n\tx := 1\n}\n\n// ---- generated by vidar ----\n\nhelper :: proc() {}\n");
const map = new DapMap(dir, { version: 1, files: { "main.odin": { source: "/src/main.vidar", lines: [1, 2, 3, 4, 5, 0, 0, 0, 0] } } });

test("messages survive being split across chunks", () => {
  const got = [];
  const reader = new MessageReader((m) => got.push(m));
  const bytes = Buffer.concat([frame({ seq: 1, type: "event", event: "a" }), frame({ seq: 2, type: "event", event: "b", body: { text: "é" } })]);
  for (let i = 0; i < bytes.length; i += 7) reader.push(bytes.subarray(i, i + 7));
  assert.deepEqual(got.map((m) => m.event), ["a", "b"]);
  assert.equal(got[1].body.text, "é");
});

test("breakpoints on .vidar lines go to the generated file, and come back on the lines asked for", () => {
  const { args, pending } = map.setBreakpoints({ source: { path: "/src/main.vidar" }, breakpoints: [{ line: 4 }, { line: 99 }] });
  assert.equal(args.source.path, join(dir, "main.odin"));
  assert.deepEqual(args.breakpoints.map((b) => b.line), [4]);
  const body = map.breakpointsResponse(pending, { breakpoints: [{ verified: true, line: 4, source: { path: join(dir, "main.odin") } }] });
  assert.equal(body.breakpoints.length, 2);
  assert.deepEqual([body.breakpoints[0].verified, body.breakpoints[0].line, body.breakpoints[0].source.path], [true, 4, "/src/main.vidar"]);
  assert.deepEqual([body.breakpoints[1].verified, body.breakpoints[1].line], [false, 99]);
});

test("breakpoints in other files pass through", () => {
  const args = { source: { path: "/elsewhere/x.odin" }, breakpoints: [{ line: 3 }] };
  assert.equal(map.setBreakpoints(args).args, args);
});

test("frames in generated code move to .vidar lines; helper frames are dimmed", () => {
  const gen = join(dir, "main.odin");
  const [a, b, c] = map.frames([{ id: 1, line: 4, source: { path: gen } }, { id: 2, line: 9, source: { path: gen } }, { id: 3, line: 7, source: { path: "/odin/core/fmt.odin" } }]);
  assert.deepEqual([a.source.path, a.line], ["/src/main.vidar", 4]);
  assert.equal(b.presentationHint, "subtle");
  assert.equal(b.source.path, gen);
  assert.equal(c.source.path, "/odin/core/fmt.odin");
});
