package main; import __vidar "vidar_runtime"

import "core:fmt"
import "core:strconv"
import "core:strings"

// `vidar test examples/testing` runs the @(test) procs in tests.vidar with `odin test`.
// A failing `testing.expect`, a failed `assert` or a panic is reported at its .vidar line.

Error :: enum { None, Empty, Bad_Number, Unknown_Op }

Token :: union { int, rune }

// Splits "1 2 +" into tokens, calling `emit` for each one.
tokenize :: proc(text: string, emit: __vidar.Closure(proc(__vidar.Env, Token))) -> Error { __emit_call := emit.call;
	for word in strings.fields(text, context.temp_allocator) {
		if strings.contains_any(word[:1], "0123456789") {
			n, __err1 := strconv.parse_int(word); if __vidar.failed(__err1) do return .Bad_Number
			__emit_call(emit.env, n)
		} else {
			__emit_call(emit.env, rune(word[0]))
		}
	}
	return .None
}

// Evaluates a reverse Polish expression such as "2 3 4 * +".
eval :: proc(text: string) -> (result: int, err: Error) {
	stack: [dynamic]int
	defer delete(stack)
	bad := false
	tokenize(text, __closure_0(&stack, &bad)) or_return
	if bad do return 0, .Unknown_Op
	if len(stack) != 1 do return 0, .Empty
	return stack[0], .None
}

main :: proc() {
	for text in ([]string{"2 3 4 * +", "10 4 -", "1 +", "7 x"}) {
		// n := eval(text) catch err { ... } — main.vidar:57
		n, __err2 := eval(text)
		if __vidar.failed(__err2) {
			err := __err2
			fmt.printf("%q: %v\n", text, err)
			continue
		}
		fmt.printf("%q = %d\n", text, n)
	}
}

// ---- generated by vidar ----

__closure_0 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(__vidar.Env, Token)) {
	__Caps :: struct {
		stack: T0,
		bad: T1,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at main.vidar:32: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, Token)){
		call = proc(__env_raw: __vidar.Env, t: Token) { __env := transmute(__Env)__env_raw;
		switch v in t {
		case int:
			append(&__env.stack^, v)
		case rune:
			if len(__env.stack^) < 2 {
				__env.bad^ = true
				return
			}
			b, a := pop(&__env.stack^), pop(&__env.stack^)
			switch v {
			case '+': append(&__env.stack^, a + b)
			case '-': append(&__env.stack^, a - b)
			case '*': append(&__env.stack^, a * b)
			case: __env.bad^ = true
			}
		}
	},
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1}},
	}
}
