package main; import __vidar "vidar_runtime"

import "core:testing"

// Run with `vidar test examples/testing`, or one test with `--run eval_errors`.

@(test)
eval_arithmetic :: proc(t: ^testing.T) {
	cases := []struct { text: string, want: int }{
		{"2 3 4 * +", 14},
		{"10 4 -", 6},
		{"5", 5},
	}
	for c in cases {
		// got := eval(c.text) catch err { ... } — tests.vidar:15
		got, __err3 := eval(c.text)
		if __vidar.failed(__err3) {
			err := __err3
			testing.expectf(t, false, "%q failed: %v", c.text, err)
			continue
		}
		testing.expect_value(t, got, c.want)
	}
}

@(test)
eval_errors :: proc(t: ^testing.T) {
	_, err := eval("1 +")
	testing.expect_value(t, err, Error.Unknown_Op)
	_, err = eval("7 x")
	testing.expect_value(t, err, Error.Unknown_Op)
	_, err = eval("1 2")
	testing.expect_value(t, err, Error.Empty)
	_, err = eval("1 2x +")
	testing.expect_value(t, err, Error.Bad_Number)
}

@(test)
tokenize_counts :: proc(t: ^testing.T) {
	ints, ops := 0, 0
	err := tokenize("1 2 + 3 *", __closure_1(&ints, &ops))
	testing.expect_value(t, err, Error.None)
	testing.expect_value(t, ints, 3)
	testing.expect_value(t, ops, 2)
}

// ---- generated by vidar ----

__closure_1 :: proc(__c0: $T0, __c1: $T1) -> __vidar.Closure(proc(__vidar.Env, Token)) {
	__Caps :: struct {
		ints: T0,
		ops: T1,
	}
	#assert(size_of(__Caps) <= __vidar.CLOSURE_ENV, "closure at tests.vidar:38: its captures don't fit in VIDAR_CLOSURE_ENV bytes; capture a pointer, or build with -define:VIDAR_CLOSURE_ENV=<bytes>")
	__Env :: struct { using __caps: __Caps, __pad: [__vidar.CLOSURE_ENV - size_of(__Caps)]byte }
	return __vidar.Closure(proc(__vidar.Env, Token)){
		call = proc(__env_raw: __vidar.Env, tok: Token) { __env := transmute(__Env)__env_raw;
		switch _ in tok {
		case int:  __env.ints^ += 1
		case rune: __env.ops^ += 1
		}
	},
		env = transmute(__vidar.Env)__Env{__caps = {__c0, __c1}},
	}
}
