package main; import __vidar "vidar_runtime"

import "core:fmt"

Error :: enum { None, Empty, Negative }

parse :: proc(n: int) -> (int, Error) {
	if n == 0 do return 0, .Empty
	if n < 0 do return 0, .Negative
	return n * 10, .None
}

// or_return X: the failure branch is hinted cold under -opt
scaled :: proc(n: int) -> (int, Error) {
	v, __err1 := parse(n); if __vidar.expect(__vidar.failed(__err1), false) do return {}, .Negative
	return v + 1, .None
}

// errdefer: so is the check that the proc is failing
build :: proc(n: int) -> (out: [dynamic]int, err: Error) {
	append(&out, n)
	defer if __vidar.expect(__vidar.failed(err), false) { {
		__fmt_0(n, err)
		delete(out)
	} }
	v, __err2 := scaled(n); if __vidar.expect(__vidar.failed(__err2), false) { err = .Empty; return }
	append(&out, v)
	return
}

assign :: proc(n: int) -> int {
	total := 0
	{ // total = parse(n) catch { ... } — input.vidar:33
		__err3_v0, __err3 := parse(n)
		if __vidar.expect(__vidar.failed(__err3), false) { return -1 }
		total = __err3_v0
	}
	return total
}

// plain Odin or_return: -opt writes it out and hints the failure branch cold too
plain_decl :: proc(n: int) -> (int, Error) {
	return checked(n)
}

checked :: proc(n: int) -> (v: int, err: Error) {
	v = 2
	w, __err4 := parse(n); if __vidar.expect(__vidar.failed(__err4), false) { err = __err4; return }
	return v + w, .None
}

only_err :: proc(n: int) -> Error {
	_, __err5 := parse(n); if __vidar.expect(__vidar.failed(__err5), false) do return __err5
	return .None
}

plain_named :: proc(n: int) -> (total: int, err: Error) {
	total = 100
	__err6_v0, __err6 := parse(n); if __vidar.expect(__vidar.failed(__err6), false) { err = __err6; return }; total = __err6_v0
	_, __err7 := parse(n + 1); if __vidar.expect(__vidar.failed(__err7), false) { err = __err7; return }
	total += 1
	return
}

lookup :: proc(n: int) -> (int, bool) {
	return n * 2, n > 0
}

plain_ok :: proc(n: int) -> (s: string, ok: bool) {
	v, __err8 := lookup(n); if __vidar.expect(__vidar.failed(__err8), false) { ok = __err8; return }
	return __fmt_1(v), true
}

main :: proc() {
	for n in ([]int{3, 0, -2}) {
		v, err := scaled(n)
		__fmt_2(n, v, err)
	}

	for n in ([]int{4, -1}) {
		b, err := build(n)
		__fmt_3(n, len(b), err)
		if err == .None do delete(b)
	}

	for n in ([]int{5, 0}) {
		// v := parse(n) catch err { ... } — input.vidar:83
		v, __err9 := parse(n)
		if __vidar.expect(__vidar.failed(__err9), false) {
			err := __err9
			__fmt_4(n, err)
			continue
		}
		__fmt_5(n, v)
	}

	{ // parse(-7) catch e { ... } — input.vidar:90
		_, __err10 := parse(-7)
		if __vidar.expect(__vidar.failed(__err10), false) { e := __err10; __fmt_6(e) }
	}
	{ // parse(2) catch e { ... } — input.vidar:91
		_, __err11 := parse(2)
		if __vidar.expect(__vidar.failed(__err11), false) { e := __err11; __fmt_6(e) }
	}
	__fmt_7(assign(-7), assign(2))

	// sure := parse(9) catch unreachable — input.vidar:94
	sure, __err12 := parse(9)
	if __vidar.expect(__vidar.failed(__err12), false) do __vidar.unexpected(__err12)
	__fmt_8(sure)

	for n in ([]int{1, 0, -1}) {
		a, e1 := plain_decl(n)
		b, e2 := plain_named(n)
		c, ok := plain_ok(n)
		__fmt_9(n, a, e1, b, e2, c, ok, only_err(n))
	}
}

// ---- generated by vidar ----

// fmt.println
__fmt_0 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "  errdefer ran for ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	when T1 == Error { n += __print_main_Error(w, a1) } else { n += __vidar.w_spec(w, a1, "%v") }
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.tprint
__fmt_1 :: proc(a0: $T0) -> string {
	b := __vidar.builder(context.temp_allocator)
	__vidar.sb_v(&b, a0)
	return __vidar.sb_to_string(&b)
}

// fmt.println
__fmt_2 :: proc(a0: $T0, a1: $T1, a2: $T2) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "scaled ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " -> ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, " ")
	when T2 == Error { n += __print_main_Error(w, a2) } else { n += __vidar.w_spec(w, a2, "%v") }
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_3 :: proc(a0: $T0, a1: $T1, a2: $T2) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "build ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " -> ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, " ")
	when T2 == Error { n += __print_main_Error(w, a2) } else { n += __vidar.w_spec(w, a2, "%v") }
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_4 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "catch ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " failed: ")
	when T1 == Error { n += __print_main_Error(w, a1) } else { n += __vidar.w_spec(w, a1, "%v") }
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_5 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "catch ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ok: ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_6 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "bare catch failed: ")
	when T0 == Error { n += __print_main_Error(w, a0) } else { n += __vidar.w_spec(w, a0, "%v") }
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_7 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "assigned: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_8 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "unreachable not hit: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_9 :: proc(a0: $T0, a1: $T1, a2: $T2, a3: $T3, a4: $T4, a5: $T5, a6: $T6, a7: $T7) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "plain ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " -> ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, " ")
	when T2 == Error { n += __print_main_Error(w, a2) } else { n += __vidar.w_spec(w, a2, "%v") }
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a3)
	n += __vidar.w_str(w, " ")
	when T4 == Error { n += __print_main_Error(w, a4) } else { n += __vidar.w_spec(w, a4, "%v") }
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a5)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a6)
	n += __vidar.w_str(w, " ")
	when T7 == Error { n += __print_main_Error(w, a7) } else { n += __vidar.w_spec(w, a7, "%v") }
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt's %v for the types printed here, written out
@(private="file")
__print_main_Error :: proc(w: __vidar.Writer, x: Error) -> (n: int) {
	switch x {
	case .None: n += __vidar.w_str(w, "None")
	case .Empty: n += __vidar.w_str(w, "Empty")
	case .Negative: n += __vidar.w_str(w, "Negative")
	case: n += __vidar.w_spec(w, x, "%v")
	}
	return
}
