package main; import __vidar "vidar_runtime"

import "core:fmt"

Error :: enum { None, Empty, Negative }

parse :: proc(n: int) -> (int, Error) {
	if n == 0 do return 0, .Empty
	if n < 0 do return 0, .Negative
	return n * 10, .None
}

// or_return X: the failure branch is hinted cold under -opt
scaled :: proc(n: int) -> (int, Error) {
	v, __err1 := parse(n); if __vidar.expect(__vidar.failed(__err1), false) do return {}, .Negative
	return v + 1, .None
}

// errdefer: so is the check that the proc is failing
build :: proc(n: int) -> (out: [dynamic]int, err: Error) {
	append(&out, n)
	defer if __vidar.expect(__vidar.failed(err), false) { {
		__fmt_0(n, err)
		delete(out)
	} }
	v, __err2 := scaled(n); if __vidar.expect(__vidar.failed(__err2), false) { err = .Empty; return }
	append(&out, v)
	return
}

assign :: proc(n: int) -> int {
	total := 0
	{ // total = parse(n) catch { ... } — input.vidar:33
		__err3_v0, __err3 := parse(n)
		if __vidar.expect(__vidar.failed(__err3), false) { return -1 }
		total = __err3_v0
	}
	return total
}

main :: proc() {
	for n in ([]int{3, 0, -2}) {
		v, err := scaled(n)
		__fmt_1(n, v, err)
	}

	for n in ([]int{4, -1}) {
		b, err := build(n)
		__fmt_2(n, len(b), err)
		if err == .None do delete(b)
	}

	for n in ([]int{5, 0}) {
		// v := parse(n) catch err { ... } — input.vidar:50
		v, __err4 := parse(n)
		if __vidar.expect(__vidar.failed(__err4), false) {
			err := __err4
			__fmt_3(n, err)
			continue
		}
		__fmt_4(n, v)
	}

	{ // parse(-7) catch e { ... } — input.vidar:57
		_, __err5 := parse(-7)
		if __vidar.expect(__vidar.failed(__err5), false) { e := __err5; __fmt_5(e) }
	}
	{ // parse(2) catch e { ... } — input.vidar:58
		_, __err6 := parse(2)
		if __vidar.expect(__vidar.failed(__err6), false) { e := __err6; __fmt_5(e) }
	}
	__fmt_6(assign(-7), assign(2))

	// sure := parse(9) catch unreachable — input.vidar:61
	sure, __err7 := parse(9)
	if __vidar.expect(__vidar.failed(__err7), false) do __vidar.unexpected(__err7)
	__fmt_7(sure)
}

// ---- generated by vidar ----

// fmt.println
__fmt_0 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "  errdefer ran for ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_1 :: proc(a0: $T0, a1: $T1, a2: $T2) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "scaled ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " -> ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a2)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_2 :: proc(a0: $T0, a1: $T1, a2: $T2) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "build ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " -> ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a2)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_3 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "catch ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " failed: ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_4 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "catch ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ok: ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_5 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "bare catch failed: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_6 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "assigned: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_7 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "unreachable not hit: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}
