package iter; import __vidar "../vidar_runtime"

import "core:fmt"
import str "core:strings"

Stats :: struct { calls: int }

// called with closure literals from another package
each :: proc(xs: []int, f: __vidar.Closure(proc(__vidar.Env, int))) {
	for x in xs do f.call(f.env, x)
}

// uses its file's imports, a type and a proc of its package
sum_by :: proc(xs: []int, s: ^Stats, f: __vidar.Closure(proc(__vidar.Env, int) -> int)) -> int {
	total := 0
	for x in xs {
		total += f.call(f.env, x)
		bump(s)
	}
	if str.has_prefix("iter", "it") do __fmt_0(len(xs))
	return total
}

bump :: proc(s: ^Stats) { s.calls += 1 }

@(private)
hidden :: proc(x: int) -> int { return x + 1 }

// uses a package-private helper: no copy outside this package
shifted :: proc(xs: []int, f: __vidar.Closure(proc(__vidar.Env, int))) {
	for x in xs do f.call(f.env, hidden(x))
}

@(private = "file")
secret :: proc(x: int) -> int { return x * 2 }

// uses a file-private helper: no copy outside this file
doubled :: proc(xs: []int, f: __vidar.Closure(proc(__vidar.Env, int))) {
	for x in xs do f.call(f.env, secret(x))
}

// ---- generated by vidar ----

// fmt.println
__fmt_0 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_str(w, "sum_by: ")
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, " values\n")
	__vidar.w_flush(w)
	return
}
