package main; import __vidar "vidar_runtime"

import "core:fmt"

Grid :: struct { cells: []int }

squares :: proc(n: int) -> [dynamic]int {
	// reserved: one append per iteration of 0..<n
	xs: [dynamic]int
	reserve(&xs, len(xs) + n)
	for i in 0..<n {
		append(&xs, i * i)
	}
	return xs
}

pairs :: proc(lo, hi: i32) -> [dynamic]i32 {
	// reserved: two values per iteration of lo..=hi, an i32 range
	xs := make([dynamic]i32, 0, 1)
	reserve(&xs, len(xs) + 2 * (int(hi) - int(lo) + 1))
	for i in lo..=hi {
		append(&xs, i, -i)
	}
	return xs
}

copy_all :: proc(src: []int, g: Grid, out: ^[dynamic]int) {
	// reserved: by length, appending through a pointer
	reserve(out, len(out^) + len(src))
	for x in src do append(out, x)
	reserve(out, len(out^) + len(g.cells))
	for c in g.cells {
		append(out, c * 10)
	}
	ys: [dynamic]int
	defer delete(ys)
	reserve(&ys, len(ys) + (len(src) + 2) - 2)
	reserve(out, len(out^) + (len(src) + 2) - 2)
	outer: for i := 2; i < len(src) + 2; i += 1 {
		append(&ys, i)
		append(out, len(ys))
	}
}

Big :: struct { a, b, c: int }

evens :: proc(n: int) -> (xs: [dynamic]int, bigs: [dynamic]Big) {
	// reserved: at most one append per iteration, an upper bound
	reserve(&xs, len(xs) + n)
	for i in 0..<n {
		if i % 2 == 0 do append(&xs, i)
	}
	// reserved: the larger branch appends two values
	reserve(&xs, len(xs) + 2 * n)
	for i in 0..<n {
		if i < 2 {
			append(&xs, -i)
		} else if i == 3 {
			append(&xs, i, i)
		} else {
			append(&xs, 0)
		}
	}
	// not reserved: conditional, and Big is 24 bytes
	for i in 0..<n {
		if i == 1 do append(&bigs, Big{a = i})
	}
	return
}

letters :: proc(s: string) -> [dynamic]rune {
	// reserved: len(s) bytes, at least the rune count
	rs: [dynamic]rune
	reserve(&rs, len(rs) + len(s))
	for r in s do append(&rs, r)
	return rs
}

skipped :: proc(n: int) -> int {
	a, b, c, d, e, f, g: [dynamic]int
	defer { delete(a); delete(b); delete(c); delete(d); delete(e); delete(f); delete(g) }
	// not reserved: the append is under an if, and the bound comes from the array
	for i := 0; i < len(a) + n; i += 1 {
		if i % 2 == 0 do append(&a, i)
	}
	// not reserved: break can end the loop early
	for i in 0..<n {
		append(&b, i)
		if i == 3 do break
	}
	// not reserved: the array is cleared in the loop
	for i in 0..<n {
		append(&c, i)
		if len(c) > 4 do clear(&c)
	}
	// not reserved: the bound changes in the loop
	m := n
	for i := 0; i < m; i += 1 {
		append(&d, i)
		if i == 0 do m -= 1
	}
	// not reserved: the trip count reads the array itself
	append(&e, 1)
	for i := 0; i < min(len(e), 3); i += 1 {
		append(&e, i)
	}
	// not reserved: a spread appends an unknown number of values
	for i in 0..<n {
		append(&f, ..e[:])
	}
	// not reserved: its address escapes in the loop
	for i in 0..<n {
		append(&g, i)
		p := &g
		_ = p
	}
	return len(a) + len(b) + len(c) + len(d) + len(e) + len(f) + len(g)
}

main :: proc() {
	sq := squares(5)
	defer delete(sq)
	__fmt_0(sq[:], cap(sq) >= 5)
	ps := pairs(1, 3)
	defer delete(ps)
	__fmt_1(ps[:])
	out: [dynamic]int
	defer delete(out)
	cells := []int{7, 8}
	copy_all([]int{1, 2, 3}, Grid{cells}, &out)
	__fmt_2(out[:])
	rs := letters("héllo")
	defer delete(rs)
	__fmt_3(len(rs))
	ev, bigs := evens(6)
	defer delete(ev)
	defer delete(bigs)
	__fmt_4(ev[:], cap(ev) >= 9, len(bigs))
	__fmt_3(skipped(6))
}

// ---- generated by vidar ----

// fmt.println
__fmt_0 :: proc(a0: $T0, a1: $T1) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	when T0 == [dynamic]int { n += __print_dyn_int(w, a0) } else { n += __vidar.w_spec(w, a0, "%v") }
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_1 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	when T0 == [dynamic]i32 { n += __print_dyn_i32(w, a0) } else { n += __vidar.w_spec(w, a0, "%v") }
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_2 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	when T0 == [dynamic]int { n += __print_dyn_int(w, a0) } else { n += __vidar.w_spec(w, a0, "%v") }
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_3 :: proc(a0: $T0) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	n += __vidar.w_v(w, a0)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt.println
__fmt_4 :: proc(a0: $T0, a1: $T1, a2: $T2) -> (n: int) {
	buf: [1024]byte
	bw: __vidar.File_Writer
	w := __vidar.std_writer(&bw, buf[:], false)
	when T0 == [dynamic]int { n += __print_dyn_int(w, a0) } else { n += __vidar.w_spec(w, a0, "%v") }
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a1)
	n += __vidar.w_str(w, " ")
	n += __vidar.w_v(w, a2)
	n += __vidar.w_str(w, "\n")
	__vidar.w_flush(w)
	return
}

// fmt's %v for the types printed here, written out
@(private="file")
__print_dyn_int :: proc(w: __vidar.Writer, x: [dynamic]int) -> (n: int) {
	if raw_data(x) == nil && len(x) > 0 {
		__vidar.w_str(w, "nil")
		return
	}
	n += __vidar.w_str(w, "[")
	for e, i in x {
		if i > 0 do n += __vidar.w_str(w, ", ")
		n += __vidar.w_v(w, e)
	}
	n += __vidar.w_str(w, "]")
	return
}

@(private="file")
__print_dyn_i32 :: proc(w: __vidar.Writer, x: [dynamic]i32) -> (n: int) {
	if raw_data(x) == nil && len(x) > 0 {
		__vidar.w_str(w, "nil")
		return
	}
	n += __vidar.w_str(w, "[")
	for e, i in x {
		if i > 0 do n += __vidar.w_str(w, ", ")
		n += __vidar.w_v(w, e)
	}
	n += __vidar.w_str(w, "]")
	return
}
